### PR TITLE
Correct path for docs

### PR DESCRIPTION
**Pull request by MrRawes**
from https://sources.debian.org/patches/yt-dlp/2022.04.08-1/0001-Correct-path-for-docs.patch/
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code (although the patch is licensed under [GPL-2.0-or-later](https://metadata.ftp-master.debian.org/changelogs//main/y/yt-dlp/yt-dlp_2022.04.08-1_copyright) it is [not copyrightable](https://www.gnu.org/prep/maintain/maintain.html#Legally-Significant))

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

change yt_dlp to yt-dlp for the docs directory in setup.py for uniformity with other file paths

### CODE REVIEW

**Comment by pukkandan** [comment]
Atleast explain why a change is being made...

**Comment by MrRawes** [comment]
> This has been like this for almost a decade [a5741a3](https://github.com/yt-dlp/yt-dlp/commit/a5741a3f5e8f2f92951d3d32f0a1badb3028c32f)
> 
> Atleast explain why a change is being made...

the reason is uniformity

**Comment by pukkandan** [comment]
> the reason is uniformity with other file paths

Not a sufficient reason to make this change. Can be re-opened if you can point me to any specs justify this

**Comment by pukkandan** [comment]
setup.py is not primarily designed for building a debian package, but for the PiP package

**Pull request closed without merging**
