### PR TITLE
Update regex for extractor in CrtvgIE extractor

### PR DESCRIPTION
**Pull request by Xpl0itU**
### Description of your *pull request* and other information

This fixes an issue with url formats being different

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by bashonly** [comment]
Please share an example URL of the new format, and add it as a test

We need to try to keep the video IDs the same as they were before for `--download-archive` compat

**Comment by Xpl0itU** [comment]
> We need to try to keep the video IDs the same as they were before for `--download-archive` compat

This is the new URL format: https://www.crtvg.es/tvg/a-carta/a-parabolica-love-story

It's impossible to keep the old video IDs since the new/alternative format doesn't specify the video ID in either the URL or the page contents

**Comment by bashonly** [comment]
>  add it as a test

**Comment by bashonly** [comment]
and we could do this
```diff
+        if mobj := re.fullmatch(r'[^/#?]+-(?P<old_id>\d{7})', video_id):
+            old_video_id = [make_archive_id(self, mobj.group('old_id'))]
+        else:
+            old_video_id = None

         return {
             'id': video_id,
+            '_old_archive_ids': old_video_id,
```

**Review by bashonly — APPROVED** [review]

**Pull request merged**
