### PR TITLE
Add `--retry-sleep`

### PR DESCRIPTION
**Pull request by pukkandan**
Adds option `--retry-sleep [TYPE:]EXPR` to sleep b/w retries.

TYPE is one of `http` (default), `fragment`, `file_access` and EXPR is an equation with `n` representing the retry counter

Closes https://github.com/yt-dlp/yt-dlp/pull/2852 (superseeds)
~~`--exponential-backoff X` => `--retry-sleep "fragment: min(X * (1.5**n), 60)"`~~
`--exponential-backoff X` => `--retry-sleep "fragment:exp=X:60:1.5"`

### TODO

- [ ] Documentation
- [ ] ~~The list of allowed math functions could be expanded~~
- [ ] ~~The option name, types and function names are not finalized~~
- [ ] Allow type=`extractor`. Would be better to do after https://github.com/yt-dlp/yt-dlp/pull/1649

### CODE REVIEW

**Comment by pukkandan** [comment]
@cdown @Jules-A

**Comment by Jules-A** [comment]
Hmm... I think allowing full math equations is taking it a bit too far... I think maybe just excepting multiple parameters instead would be better like --retry-sleep [TYPE:]MATHTYPE, INITIAL, INCREMENT, MAX ?
So something like: --retry-sleep "fragment;http: linear, 0.3, 0.2, 10" or  --retry-sleep "fragment;http: exponential, 0.25, 1.5, 60" like what @cdown wanted.

**Comment by cdown** [comment]
This seems like overkill for my taste, since even just having any exponential backoff at all is likely to fix the problem. Having it be user configurable to this level of detail seems unnecessary. That said, I'm in favour of anything that will get merged which solves the problem, so if this is how you'd prefer it to be I have no problem with it.

**Comment by Jules-A** [comment]
> Why is it too far? For your approach, I'd have to maintain and document a list of supported "mathtypes" and their params, while being intrinsically more limited.
> 
> It does not allow arbitrary code. There is a list of whitelisted functions/operators that can be used. The only risk is that user can input a math expression so complex that it hangs. But this issue exists just for implementing just exponential backoff too - because of how fast exp increases

Well, mainly just adding a bunch of math functions ect. that might not get used elsewhere just seems a bit much to me. 
I don't think there would ever be a need for anything other than linear and exponential increases and the params would be the same for both so you wouldn't need to document them more than once.

**Comment by Jules-A** [comment]
> I can see why you'd consider allowing full math expressions as overkill, but isn't `--retry-sleep 2*(1.5**n)` a better UX than `--retry-sleep exponential,2,1.5` ?

I'm also concerned it would make it difficult for people not experienced with the program or people not great at maths.

**Comment by cdown** [comment]
Hey folks, any thoughts on how to progress here? I'm happy for either this or #2852, but it would be great to know what the way forwards is :-)

**Comment by pukkandan** [comment]
I have simplified the syntax for now according to you guys' suggestions. (I still don't like this, but Ive implemented this in such a way that it's easy to expand the syntax in future if needed)

Documentation is pending. If someone can help with that, this can be merged asap

**Comment by Jules-A** [comment]
I can't seem to get this to work? (I only tried fragmented downloads so far). I also I can't seem to use this for multiple retry types (I tried many separators without luck). Also, an "all" option would be very handy.

**Pull request closed without merging**
