### PR TITLE
Use shadow copy to extract cookies when chrome is open

### LINKED ISSUE #7271: `--cookies-from-browser` "Permission denied" errors when Chrome/chromium-based browser is open in Windows
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

cannot extract cookies from chrome when the chrome browser is open
and after closing all the windows of chrome, it can run correctly
i have no idea what is going wrong

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Mechrevo>yt-dlp.exe -vU --newline -R 30 --proxy socks5://127.0.0.1:7890 -i -o "Z:\YouTube\%(upload_date)s %(title)s.%(ext)s" --ignore-config --hls-prefer-native --add-metadata --embed-thumbnail --sub-langs all,-live_chat,-danmaku,-jpn-JP --embed-subs --merge-output-format mp4 --live-from-start --cookies-from-browser chrome "https://www.youtube.com/watch?v=3DiKrPSmO5c"
[debug] Command-line config: ['-vU', '--newline', '-R', '30', '--proxy', 'socks5://127.0.0.1:7890', '-i', '-o', 'Z:\\YouTube\\%(upload_date)s %(title)s.%(ext)s', '--ignore-config', '--hls-prefer-native', '--add-metadata', '--embed-thumbnail', '--sub-langs', 'all,-live_chat,-danmaku,-jpn-JP', '--embed-subs', '--merge-output-format', 'mp4', '--live-from-start', '--cookies-from-browser', 'chrome', 'https://www.youtube.com/watch?v=3DiKrPSmO5c']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Mechrevo\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Mechrevo\AppData\Local\Google\Chrome\User Data\Local State"                                           Traceback (most recent call last):
File "yt_dlp\__main__.py", line 17, in <module>
File "yt_dlp\__init__.py", line 967, in main
File "yt_dlp\__init__.py", line 927, in _real_main
File "yt_dlp\YoutubeDL.py", line 652, in __init__
File "yt_dlp\YoutubeDL.py", line 3827, in print_debug_header
File "yt_dlp\YoutubeDL.py", line 3871, in _setup_opener
File "yt_dlp\cookies.py", line 99, in load_cookies
File "yt_dlp\cookies.py", line 120, in extract_cookies_from_browser
File "yt_dlp\cookies.py", line 289, in _extract_chrome_cookies
File "yt_dlp\cookies.py", line 952, in _open_database_copy
File "shutil.py", line 418, in copy
File "shutil.py", line 264, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Mechrevo\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'
[25380] Failed to execute script '__main__' due to unhandled exception!
C:\Users\Mechrevo>
```

### PR DESCRIPTION
**Pull request by csm10495**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

On Windows, they lock the cookies database from regular IO access. We can work around it (if admin) by creating a shadow copy of the underlying volume and copying the file from that shadow, then cleaning up the shadow.

ADD DESCRIPTION HERE

Fixes #7271

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x ] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [ x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ x] Core bug fix/improvement
- [ x] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🍪🖥️🐛

Added a feature to extract cookies from browsers on Windows using WMI and a new exception class `CookiesFromBrowserUnavailableError`. Improved logging and error handling for the cookie extraction functions in `yt_dlp/cookies.py` and `yt_dlp/utils/_utils.py`.

> _To get cookies from browsers on Windows_
> _We use WMI and some clever hints_
> _But if something goes wrong_
> _We raise a new exception_
> _And log the `CookiesFromBrowserUnavailableError` events_

### Walkthrough
*  Add `CookiesFromBrowserUnavailableError` exception class to handle permission and other errors when extracting or copying cookies from browsers ([link](https://github.com/yt-dlp/yt-dlp/pull/7290/files?diff=unified&w=0#diff-c042473d560a04c6fd504c3cb3ae2c9a56a27e42458132a265a3ffda0d60a5c7R50), [link](https://github.com/yt-dlp/yt-dlp/pull/7290/files?diff=unified&w=0#diff-feda8f56946dc048e754111850baaef0eec4b9f8bbc2d3f04b1a785626ea5c0eL1271-R1276))
*  Import `textwrap` module to format error messages for the new exception class ([link](https://github.com/yt-dlp/yt-dlp/pull/7290/files?diff=unified&w=0#diff-c042473d560a04c6fd504c3cb3ae2c9a56a27e42458132a265a3ffda0d60a5c7R15))
*  Import and check `wmi` module to use Windows Management Instrumentation (WMI) API for creating and deleting shadow copies of cookies database files on Windows systems ([link](https://github.com/yt-dlp/yt-dlp/pull/7290/files?diff=unified&w=0#diff-c042473d560a04c6fd504c3cb3ae2c9a56a27e42458132a265a3ffda0d60a5c7R22-R27), [link](https://github.com/yt-dlp/yt-dlp/pull/7290/files?diff=unified&w=0#diff-c042473d560a04c6fd504c3cb3ae2c9a56a27e42458132a265a3ffda0d60a5c7L26-R33))
*  Modify `_open_database_copy` function in `yt_dlp/cookies.py` to accept and pass `logger` argument for logging debug messages about shadow copy process ([link](https://github.com/yt-dlp/yt-dlp/pull/7290/files?diff=unified&w=0#diff-c042473d560a04c6fd504c3cb3ae2c9a56a27e42458132a265a3ffda0d60a5c7L168-R176), [link](https://github.com/yt-dlp/yt-dlp/pull/7290/files?diff=unified&w=0#diff-c042473d560a04c6fd504c3cb3ae2c9a56a27e42458132a265a3ffda0d60a5c7L296-R304))
*  Modify `_open_database_copy` function in `yt_dlp/cookies.py` to handle `PermissionError` exception by trying to create and delete a temporary shadow copy of the volume and copy the file from there, or raise `CookiesFromBrowserUnavailableError` exception with a message recommending to run yt-dlp as administrator ([link](https://github.com/yt-dlp/yt-dlp/pull/7290/files?diff=unified&w=0#diff-c042473d560a04c6fd504c3cb3ae2c9a56a27e42458132a265a3ffda0d60a5c7L1054-R1096))

</details>

### CODE REVIEW

**Comment by csm10495** [comment]
If we'd like a couple unit tests (via patching since I don't think having a test that needs admin makes sense), I'd be happy to add that too.

**Comment by gamer191** [comment]
did you accidentally remove certifi when you were editing requirements.txt?

**Comment by pukkandan** [comment]
Do we really need the additional dependency? Can't we directly access `VssAPI.dll` instead? If the dependency is unavoidable, put it in `yt_dlp/dependencies` and document in readme.

**Comment by csm10495** [comment]
I don't think we can do that. I'm not quite sure. The API is COM and C++ instead of C.

We could shell out to PowerShell and call wmi via that instead if you'd prefer. Though I think the better way is via the wmi module as it is here.

What do you prefer?

**Comment by pukkandan** [comment]
Powershell isn't necesarily available on all systems. But with some investigation, it seems we can use `wmic shadowcopy`.

```cmd
❯ wmic shadowcopy call create Volume="D:\"
Executing (Win32_ShadowCopy)->create()
Method execution successful.
Out Parameters:
instance of __PARAMETERS
{
        ReturnValue = 0;
        ShadowID = "{53A5CE39-D041-4F42-AC12-98F682FF5F1C}";
};

❯ wmic shadowcopy where ID="{53A5CE39-D041-4F42-AC12-98F682FF5F1C}"
Caption  ClientAccessible  Count  Description  DeviceObject                                     Differential  ExposedLocally  ExposedName  ExposedPath  ExposedRemotely  HardwareAssisted  ID
                         Imported  InstallDate                Name  NoAutoRelease  NotSurfaced  NoWriters  OriginatingMachine  Persistent  Plex   ProviderID                              ServiceMachine   SetID                                   State  Status  Transportable  VolumeName
         TRUE              1                   \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy7  TRUE          FALSE                                     FALSE            FALSE             {53A5CE39-D041-4F42-AC12-98F682FF5F1C}  FALSE     20230613021202.613354+330        TRUE           FALSE        TRUE       DESKTOP-KGSH6Q9     TRUE        FALSE  {B5946137-7B9F-4925-AF80-51ABD60B20D5}  DESKTOP-KGSH6Q9  {196BCC2D-E07C-4B4F-8048-95BDEC997AF5}  12             FALSE          \\?\Volume{7ab88b45-44c2-4622-90ec-06b00b524bb0}\

❯ type "\\?\Volume{7ab88b45-44c2-4622-90ec-06b00b524bb0}\TRASH\test.txt"
test file

❯ wmic shadowcopy where ID="{53A5CE39-D041-4F42-AC12-98F682FF5F1C}" delete
Deleting instance \\DESKTOP-KGSH6Q9\ROOT\CIMV2:Win32_ShadowCopy.ID="{53A5CE39-D041-4F42-AC12-98F682FF5F1C}"
Instance deletion successful.
```

**Comment by csm10495** [comment]
wmic is deprecated: https://learn.microsoft.com/en-us/windows/whats-new/deprecated-features

**Comment by csm10495** [comment]
When would powershell not be installed? 
Per https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell?view=powershell-7.3:

```
Windows PowerShell comes installed by default in every Windows, starting with Windows 7 SP1 and Windows Server 2008 R2 SP1.
```

**Comment by pukkandan** [comment]
Deprecated as in no longer being developed, not that it's being removed. It's available in all versions and variants from XP-11 afaik

**Comment by csm10495** [comment]
It's already started being removed in the dev channel for win11: https://www.bleepingcomputer.com/news/microsoft/microsoft-starts-killing-off-wmic-in-windows-will-thwart-attacks/

**Comment by pukkandan** [comment]
hm.. You can stick to the library. Pls make the other changes

**Comment by csm10495** [comment]
@pukkandan i've updated the PR and CI is passing. Mind taking a look again? Thanks!

**Comment by csm10495** [comment]
@pukkandan any chance for a merge? - its been a few weeks now.

**Comment by csm10495** [comment]
I'm closing this out. It seems like its not getting merged. I've moved the shadowcopy logic to its own lib: https://github.com/csm10495/shadowcopy.. so if we want to merge this functionality in, please use that library instead.

**Comment by pukkandan** [comment]
We are still interested in merging this, but I can only review PRs as time allows.

**Comment by csm10495** [comment]
That's fine though I would do it using [csm10495](https://pypi.org/project/shadowcopy/) instead of doing it within the code in yt-dlp itself. Is that ok?

(I want only only one place to worry about maintaining this logic long term). 

So that would be a dependency on shadowcopy instead of wmi.

**Pull request closed without merging**
