### PR TITLE
Remove mutable default from keyword arguments of function definition

### PR DESCRIPTION
**Pull request by sulyi**
### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [ ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

### Description of your *pull request* and other information

> Do not use mutable default arguments in Python, unless you have a REALLY good reason to do so.
> Why? Because it can lead to all sorts of nasty and horrible bugs, give you headaches and waste everyone's time.
> Instead, default to None and assign the mutable value inside the function.

I can't bother to copy-paste the [whole](https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/) thing, so above is the tl;dr; part.

If you wish to discuss this further, there's an issue #1021 for it. Please keep this strictly about the change.

### TODO
- [x] find and change all dictionarys
- [x] find and change all lists 
- [x] find and change all sets (there's probably none, since it's much finicky to create an empty set)
- [x] do all the above for non-empty ones

### CODE REVIEW

**Comment by pukkandan** [comment]
@fstirlitz could u explain the reasoning behind the 👎

**Comment by fstirlitz** [comment]
I don’t see the point. The point of the rule proscribing mutable default arguments is to avoid *actually* mutating them, and as far as I know, we already don’t. If there had been an instance where a default argument is mutated, this change would have just made it mutate a temporary instad, sweeping the bug under the rug. This patch fails to protect against a danger that hasn’t even been shown to exist.

Also, this will slightly degrade performance, as now substituting an empty dict for a non-passed argument is performed in (interpreted) user code logic, as opposed to doing it in the (native-code) interpreter logic, and the empty dict is instantiated per each call, instead of once at definition time.

If anything, it would make more sense to replace `={}` with `=EmptyMap()` (and `=[]` with `=()`), where

```python
import collections.abc


class EmptyMap(collections.abc.Mapping):
	def __new__(cls):
		try:
			return cls.__instance
		except AttributeError:
			cls.__instance = object.__new__(cls)
			return cls.__instance
	__slots__ = ()
	__empty_set = frozenset(())
	def keys(self):
		return self.__empty_set
	def values(self):
		return self.__empty_set
	def items(self):
		return self.__empty_set
	def get(self, key, default=None):
		return default
	def __getitem__(self, key):
		raise KeyError(key)
	def __eq__(self, other):
		return True
	def __contains__(self):
		return False
	def __len__(self):
		return 0
	def __bool__(self):
		return False
	def __iter__(self):
		return
		yield
```

because that may actually protect against inadvertent mutations, as those would then throw `TypeError`s and/or `AttributeError`s. But I’m not sure even that is worth it.

**Comment by sulyi** [comment]
I've already update the description with explanation. Like I said I'll.

I don't know where the intrusive <h2> todo went, but it was there for a reason.

**Comment by pukkandan** [comment]
> I don’t see the point. The point of the rule proscribing mutable default arguments is to avoid actually mutating them, and as far as I know, we already don’t. If there had been an instance where a default argument is mutated, this change would have just made it mutate a temporary instad, sweeping the bug under the rug. This patch fails to protect against a danger that hasn’t even been shown to exist.

There have been issues with this in the past #727
I also don't know any more instances of the issue occurring. However, the problem is that once the argument passes through a few function calls, it is difficult to know if the dict is being mutated anywhere.

> Also, this will slightly degrade performance, as now substituting an empty dict for a non-passed argument is performed in (interpreted) user code logic, as opposed to doing it in the (native-code) interpreter logic, and the empty dict is instantiated per each call, instead of once at definition time.

I also don't agree with this. The performance impact of this will be miniscule in comparison to the normal operation times of yt-dlp

> If anything, it would make more sense to replace ={} with =EmptyMap() (and =[] with =()), where

This does make sense. Actually, I was just checking if there is a `FrozenDict` similar to the one for set. But it appears not. I'm not sure building our own version of it is worth it

**Comment by sulyi** [comment]
FrozenDict is rejected PEP 416

**Comment by sulyi** [comment]
Could you, @fstirlitz, move your comment to issue, it's not related to code.

I'm open to discuss it just not here.

**Comment by sulyi** [comment]
Deemed not useful.

**Pull request closed without merging**
