### PR TITLE
[nebula] Support authentication via tokens from cookie jar

### PR DESCRIPTION
**Pull request by hheimbuerger**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Improvement

---

### Description of your *pull request* and other information

Main conversation on issue: https://github.com/yt-dlp/yt-dlp/issues/496

* Support authentication from cookie jar.
* Token from cookie is preferred, if no cookie present or expired, credentials auth is run against login endpoint (with credentials required in `.netrc` or supplied on command line).
* Token retrieved from login endpoint is stored in cookie jar, if available.
* [tentative] If token is rejected by Nebula backend, reauthentication with credentials is attempted.

### CODE REVIEW

**Comment by hheimbuerger** [comment]
Somehow, the merge commit broke the diff. I'll fix and re-push.

**Comment by pukkandan** [comment]
>  I am the original author of this code and I am willing to release it under Unlicense

@TpmKranz is a co-author, correct?

---

> Somehow, the merge commit broke the diff

The line endings seems to have been forcibly changed. I've fixed it

**Comment by TpmKranz** [comment]
> > I am the original author of this code and I am willing to release it under Unlicense
> 
> @TpmKranz is a co-author, correct?

Yes, but my contribution is negligible, imo. But just in case:

**I am the original author of parts of this code and I am willing to release it under Unlicense**

**Comment by pukkandan** [comment]
> [tentative] If token is rejected by Nebula backend, reauthentication with credentials is attempted.

Not really necessary (unless the website frequently invalidates the token), but since you wrote it, I see no harm in keeping it

**Pull request merged**
