### PR TITLE
[extractor/pornhub] Remove fetch of /video/get_media for formats

### PR DESCRIPTION
**Pull request by scrat5h**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

Previously URLs that contained `/video/get_media` returned JSON with available formats.

Some time ago Pornhub seem to removed this endpoint and has started to return `HTTP Error 403: Forbidden`, see #4298.

Nowadays it seem to serve originally requested html page which, of course, cannot be parsed with JSON parser. yt-dlp produced WARNING:

```
Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0).
```

Since we are already getting format of the video by other means (`mpd` or `m3u8`) this change removes fetching of URLs that don't provide value to us anymore.

Fixes: #5615

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by bashonly** [comment]
> Some time ago Pornhub seem to removed this endpoint and has started to return HTTP Error 403: Forbidden

The endpoint was still working (intermittently) as recently as this month, see: https://github.com/yt-dlp/yt-dlp/issues/4627#issuecomment-1304927609

There is evidence to suggest that TLS/browser fingerprinting is the cause of PH serving bogus html instead of JSON. If you examine the contents of the HTML (use `--write-pages`) you'll see PH is trolling users who are trying to access this endpoint without a browser -- it is a redirect to a video about corn cobs (yes, actual corn)

I don't believe this code should be removed, since it has the potential to work again if changes are made to yt-dlp's networking, and since the JSON is the only source of direct mp4 URLs. I think instead it's better to use pukkandan's suggestion of adding `errnote=False` to the `self._download_json` call (and maybe adding a `self.write_debug` so we can still see the result in verbose logs?)

**Comment by dirkf** [comment]
Currently in the UK the cornhub page is being given to yt-dl but just JSON `[]` in a browser.

**Comment by scrat5h** [comment]
I have found why people get different results. It is the cookie `platform` :

- if it is set to `pc` - a html page is returned
- if it is set to `mac` or `tv` - a valid json is returned
- if it is not set an empty json list `[]` is returned 

That cookie doesn't need to be set every time - apparently it is stored on server's side and paired with session cookie(s).

With this info it looks like `errnote=False` might be really best approach here.

> I don't believe this code should be removed, since it has the potential to work again if changes are made to yt-dlp's networking (e.g. #2861, #3668), and since the JSON is the only source of direct mp4 URLs. I think instead it's better to use pukkandan's suggestion of adding `errnote=False` to the `self._download_json` call (and maybe adding a `self.write_debug` so we can still see the result in verbose logs?)

@bashonly I'm not sure how you meant to use that `self.write_debug` . From what I understand extractor doesn't have access to parameters to test if verbose is set and if `_download_json` is not fatal I don't seem to have a way to catch that warning. Well, I might override `report_warning` but that sounds overkill and I'm not sure what else that would break.

**Comment by bashonly** [comment]
> From what I understand extractor doesn't have access to parameters to test if verbose is set

not necessary, `write_debug` is already verbose-only output

I meant something like this:
```py
            if '/video/get_media' in video_url:
                medias = self._download_json(video_url, video_id, fatal=False, errnote=False)
                if medias is None:
                    self.write_debug(f'{video_id}: get_media endpoint returned HTML')
                elif isinstance(medias, list):
                    if not medias:
                        self.write_debug(f'{video_id}: get_media endpoint returned empty list')
                    for media in medias:
                        if not isinstance(media, dict):
                            continue
                        video_url = url_or_none(media.get('videoUrl'))
                        if not video_url:
                            continue
                        height = int_or_none(media.get('quality'))
                        add_format(video_url, height)
                continue
```

**Comment by dirkf** [comment]
1. Once instantiated, an extractor has a `_downloader` attribute whose value is the `YoutubeDL` object that invoked the extractor.

So you can get any (in theory, public) attributes of the invoking object, including the parameter `dict` where the `verbose` setting is found. Compared with yt-dl, yt-dlp pulls some methods and properties into the extractor class, internally forwarding to its `_downloader`, such as `write_debug()`.

2. Testing with yt-dl

With the `platform` cookie set to `tv` or `mac`, or cleared (shouldn't there be `InfoExtractor._clear_cookie()`?), yt-dl gets these results for the purported JSON using the Lego video:
* Py 2.7: OK
* Py 3.5: OK
* Py 3.9: cornhub (yt-dlp too)

For `pc`, it's always cornhub.

Better than that, yt-dl with Py3.9 gets the cornhub video (180k views) as the `webpage` (versus the Lego video with 210k views), but yt-dlp doesn't. Setting a vanilla UA gives the same result. Other things that don't help: visiting the home page first, setting `Referer`, different values of `platform` or none.

Presumably whatever the difference is between yt-dlp's request for the `pc` webpage and its request for the media JSON needs to be reversed and applied to yt-dl's webpage request.

3. AOB

* For Py 2.7/3.5 (hence yt-dl, but same code), the `view_count` extraction fails because the target element `<span class="count" ...` contains `208K` instead of (say) 208,000. A view_count with the value 207951 (when tested!) is extracted from the ld+json block, which is merged into the returned info_dict. A `[kKmM]?` should be added to the count REs in case such values are to be extracted and if so the counts should be merged after the ld+json.
* For safety any `url` should be popped before merging the extracted ld+json.
* At l.487, `.strip()` is already done by `clean_html()`:
```diff
-                return [clean_html(x).strip() for x in re.findall(r'(?s)<a[^>]+\bhref=[^>]+>.+?</a>', div)]
+                return [clean_html(x) for x in re.findall(r'(?s)<a[^>]+\bhref=[^>]+>.+?</a>', div)]
```
* The `add_video()` local function should be moved up, given an optional `height` argument, and used wherever `video_urls`/`video_urls_set` are updated.

**Comment by scrat5h** [comment]
Since the semantic of the fix changed I have opened new PR that replaces this one: #5636 .

**Pull request closed without merging**
