### PR TITLE
mp4 files were not faststart in some cases

### PR DESCRIPTION
**Pull request by megapro17**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

Better handling of mp4 based files

### CODE REVIEW

**Comment by Anuskuss** [comment]
Doesn't work for me:
### DASH
```
$ yt-dlp -o video.mp4 https://v.redd.it/8rj8b6c18ki51
[generic] 8rj8b6c18ki51: Requesting header
[redirect] Following redirect to https://www.reddit.com/r/nextfuckinglevel/comments/ieiwpj/demonstrating_the_danger_of_storm_surge_through/
[Reddit] ieiwpj: Downloading JSON metadata
[Reddit] ieiwpj: Downloading m3u8 information
[Reddit] ieiwpj: Downloading MPD manifest
[info] 8rj8b6c18ki51: Downloading 1 format(s): dash-video_4770588+dash-audio_0_131736
[download] Destination: video.fdash-video_4770588.mp4
[download] 100% of 44.13MiB in 00:09
[download] Destination: video.fdash-audio_0_131736.m4a
[download] 100% of 1.22MiB in 00:00
[Merger] Merging formats into "video.mp4"
Deleting original file video.fdash-audio_0_131736.m4a (pass -k to keep)
Deleting original file video.fdash-video_4770588.mp4 (pass -k to keep)
```
```
$ mediainfo -f video.mp4 | grep IsStreamable
IsStreamable                             : No
```

### HLS
```
$ yt-dlp -o video.mp4 https://v.redd.it/16cqbkev2ci51
[generic] 16cqbkev2ci51: Requesting header
[redirect] Following redirect to https://www.reddit.com/r/Product_Hub/comments/iduchl/see_through_whirlpool_facet/
[Reddit] iduchl: Downloading JSON metadata
[Reddit] iduchl: Downloading m3u8 information
[Reddit] iduchl: Downloading MPD manifest
[info] 16cqbkev2ci51: Downloading 1 format(s): hls-1352
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
[download] Destination: video.mp4
[download] 100% of 1.98MiB in 00:00
[FixupM3u8] Fixing MPEG-TS in MP4 container of "video.mp4"
```
```
$ mediainfo -f video.mp4 | grep IsStreamable
IsStreamable                             : No

```

**Comment by pukkandan** [comment]
It is not necessary that all downloaded videos need to be faststart. There is no reason the DASH case should be faststart since we are downloading it as-is and are not making any changes to it (If you download with ffmpeg, it will be?). In the m3u8 case, since we are doing fixup, we might as well make it faststart

**Comment by Anuskuss** [comment]
True, most videos served online should (hopefully) already be `faststart`. In the case of the container/M3U8 fixup, the `faststart` shouldn't hurt. Can't say if it's any useful otherwise but it's definitely not that expensive. Don't know if yt-dlp has anything akin to ffmpeg's `qt-faststart` but that would be the way if you'd want to avoid a separate `ffmpeg` step.

**Comment by Vangelis66** [comment]
@Anuskuss 

Not sure whether you can regard this as a solution to your "problem", but in your MPEG-DASH example above you can create streamable MP4 files by using ` --ppa "Merger:-movflags +faststart"`:
```
yt-dlp -o video.mp4 "https://v.redd.it/8rj8b6c18ki51" --ppa "Merger:-movflags +faststart" -v => 

[debug] Command-line config: ['--ffmpeg-location', '..', '--downloader-args', 'ffmpeg:-v 8 -stats', '-o', 'video.mp4', 'https://v.redd.it/8rj8b6c18ki51', '--ppa', 'Merger:-movflags +faststart', '-v']
[debug] Encodings: locale cp1253, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1253
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.7.9 (CPython 32bit) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://v.redd.it/8rj8b6c18ki51
[generic] 8rj8b6c18ki51: Requesting header
[redirect] Following redirect to https://www.reddit.com/r/nextfuckinglevel/comments/ieiwpj/demonstrating_the_danger_of_storm_surge_through/
[debug] [Reddit] Extracting URL: https://www.reddit.com/r/nextfuckinglevel/comments/ieiwpj/demonstrating_the_danger_of_storm_surge_through/
[Reddit] ieiwpj: Downloading JSON metadata
[Reddit] ieiwpj: Downloading m3u8 information
[Reddit] ieiwpj: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7),vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext,aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 8rj8b6c18ki51: Downloading 1 format(s): dash-video_4770588+dash-audio_0_131736
[debug] Invoking downloader on "https://v.redd.it/8rj8b6c18ki51/DASH_1080.mp4"
[download] Destination: video.fdash-video_4770588.mp4
[download] 100% of 44.13MiB in 00:51
[debug] Invoking downloader on "https://v.redd.it/8rj8b6c18ki51/DASH_audio.mp4"
[download] Destination: video.fdash-audio_0_131736.m4a
[download] 100% of 1.22MiB in 00:01
[Merger] Merging formats into "video.mp4"
[debug] ffmpeg command line: "..\ffmpeg" -y -loglevel "repeat+info" -i "file:video.fdash-video_4770588.mp4" -i "file:video.fdash-audio_0_131736.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:video.temp.mp4"
Deleting original file video.fdash-audio_0_131736.m4a (pass -k to keep)
Deleting original file video.fdash-video_4770588.mp4 (pass -k to keep)

mediainfo --version
MediaInfo Command line,
MediaInfoLib - v21.09

mediainfo -f video.mp4 | FindStr IsStreamable
IsStreamable                             : Yes
```
Likewise, your HLS example can create streamable MP4 file via `--ppa "FixupM3u8:-movflags +faststart"`: 
```
yt-dlp -o video1.mp4 "https://v.redd.it/16cqbkev2ci51" --ppa "FixupM3u8:-movflags +faststart" -v => 

[debug] Command-line config: ['--ffmpeg-location', '..', '--downloader-args', 'ffmpeg:-v 8 -stats', '-o', 'video1.mp4', 'https://v.redd.it/16cqbkev2ci51', '--ppa', 'FixupM3u8:-movflags +faststart', '-v']
[debug] Encodings: locale cp1253, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1253
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.7.9 (CPython 32bit) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://v.redd.it/16cqbkev2ci51
[generic] 16cqbkev2ci51: Requesting header
[redirect] Following redirect to https://www.reddit.com/r/Product_Hub/comments/iduchl/see_through_whirlpool_facet/
[debug] [Reddit] Extracting URL: https://www.reddit.com/r/Product_Hub/comments/iduchl/see_through_whirlpool_facet/
[Reddit] iduchl: Downloading JSON metadata
[Reddit] iduchl: Downloading m3u8 information
[Reddit] iduchl: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7),vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext,aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 16cqbkev2ci51: Downloading 1 format(s): hls-1352
[debug] Invoking downloader on "https://v.redd.it/16cqbkev2ci51/HLS_540.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
[download] Destination: video1.mp4
[download] 100% of 1.98MiB in 00:03
[debug] ffprobe command line: "..\ffprobe" -hide_banner -show_format -show_streams -print_format json "file:video1.mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "video1.mp4"
[debug] ffmpeg command line: "..\ffmpeg" -y -loglevel "repeat+info" -i "file:video1.mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:video1.temp.mp4"

mediainfo -f video1.mp4 | FindStr IsStreamable
IsStreamable                             : Yes
```
In both cases, the relocation of the `moov` atom is done in the same `ffmpeg` invocation that creates the MP4 file... 
However, how to tell in advance which postprocessor is going to be used (Merger | FixupM3u8) is something I haven't figured out yet... Supplying **both options at the same time**, to get you covered for either case, doesn't seem to hurt for your **reddit** downloads and always yields streamable MP4 files: 
```
yt-dlp -o video.mp4 "https://v.redd.it/8rj8b6c18ki51" --ppa "Merger:-movflags +faststart" --ppa "FixupM3u8:-movflags +faststart"

yt-dlp -o video1.mp4 "https://v.redd.it/16cqbkev2ci51" --ppa "Merger:-movflags +faststart" --ppa "FixupM3u8:-movflags +faststart"
```
Hope I've helped 😄

**Comment by pukkandan** [comment]
Oh, I did not notice it was going through the merger. We can add faststart to the MergerPP by default. I was thinking that it was a single dash format that was being downloaded

In essence, what I meant in my above comment was that we shouldn't run a PP just to make a video faststart. But in all existing PPs, we can add the faststart when it is safe (ie, when we know it will result in mp4)

**Comment by megapro17** [comment]
> In essence, what I meant in my above comment was that we shouldn't run a PP just to make a video faststart. But in all existing PPs, we can add the faststart when it is safe (ie, when we know it will result in mp4)

ffmpeg doesn't care, it ignores faststart if it's not available, we can add it by default for all files

**Comment by Anuskuss** [comment]
@Vangelis66 Thanks for the tip, I've totally missed `postprocessor-args` while reading the documentation.
Most of the time it's doing an `ffmpeg` step anyway, so adding it as a `postprocessor-args` is better than doing an additional `exec` step:
```
yt-dlp -o video.mp4 https://v.redd.it/8rj8b6c18ki51 --ppa "ffmpeg:-movflags +faststart"
```
This will work regardless of whether the devs decide to always apply `faststart` (on FixupM3u8, MP4 merge, etc.) because `ffmpeg` would just ignore the second `faststart`. The only downside being that it wouldn't work when you download an MP4 as is, so here's hoping that the content providers did their homework (like is the case when you download the DASH MP4 from that Reddit link).

> In essence, what I meant in my above comment was that we shouldn't run a PP just to make a video faststart. But in all existing PPs, we can add the faststart

This is the way.

**Comment by Vangelis66** [comment]
Something's slightly amiss in my log from 

`yt-dlp -o video1.mp4 "https://v.redd.it/16cqbkev2ci51" --ppa "FixupM3u8:-movflags +faststart" -v`
(or 
`yt-dlp -o video1.mp4 "https://v.redd.it/16cqbkev2ci51" --ppa "ffmpeg:-movflags +faststart" -v` if you will...): 

```
[download] Destination: video1.mp4
[download] 100% of 1.98MiB in 00:03
[debug] ffprobe command line: "..\ffprobe" -hide_banner -show_format -show_streams -print_format json "file:video1.mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "video1.mp4"
[debug] ffmpeg command line: "..\ffmpeg" -y -loglevel "repeat+info" -i "file:video1.mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:video1.temp.mp4"
```
"We" are `ffprobe`-ing the initially downloaded file, it's a VIDEO-ONLY stream inside the MPEG-TS media container, 
```js
"..\ffprobe" -hide_banner -show_format -show_streams -print_format json "file:video1.mp4" => 

{
Input #0, mpegts, from 'file:video1.mp4':
  Duration: 00:00:12.30, start: 1.400000, bitrate: 1351 kb/s
  Program 1
  Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progr
essive), 640x640 [SAR 1:1 DAR 1:1], 30 fps, 30 tbr, 90k tbn, 60 tbc
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "Main",
            "codec_type": "video",
            "codec_tag_string": "[27][0][0][0]",
            "codec_tag": "0x001b",
            "width": 640,
            "height": 640,
            "coded_width": 640,
            "coded_height": 640,
            "closed_captions": 0,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "1:1",
            "pix_fmt": "yuv420p",
            "level": 31,
            "chroma_location": "left",
            "field_order": "progressive",
            "refs": 1,
            "is_avc": "false",
            "nal_length_size": "0",
            "id": "0x100",
            "r_frame_rate": "30/1",
            "avg_frame_rate": "30/1",
            "time_base": "1/90000",
            "start_pts": 126000,
            "start_time": "1.400000",
            "duration_ts": 1107000,
            "duration": "12.300000",
            "bits_per_raw_sample": "8",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        }
    ],
    "format": {
        "filename": "file:video1.mp4",
        "nb_streams": 1,
        "nb_programs": 1,
        "format_name": "mpegts",
        "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
        "start_time": "1.400000",
        "duration": "12.300000",
        "size": "2078152",
        "bit_rate": "1351643",
        "probe_score": 50
    }
}
```
... however, the **FixupM3u8** PP is still issuing the AUDIO bitstream filter flag, `-bsf:a aac_adtstoasc`, to ffmpeg...
While in itself it _doesn't break the lossless remux to the MP4 container_, **why is it there in the first place, for a video-only elementary stream** ???

**Comment by pukkandan** [comment]
Afaik, having `-bsf:a aac_adtstoasc` doesn't hurt anyway. So whoever added that code (it may have been me, honestly dont remember 🤷) must have thought there is no point in checking for audio stream. If there is any issues with adding it unconditionally, let me know and we can adjust it accordingly

**Comment by pukkandan** [comment]
@megapro17 Some PPs are still missing it (eg: merger)

**Comment by megapro17** [comment]
here? https://github.com/yt-dlp/yt-dlp/blob/9bdd99cf39974bf19badc0dfc9ee7172ff198e98/yt_dlp/postprocessor/ffmpeg.py#L818

**Comment by pukkandan** [comment]
I'm pretty sure it should be based on `ext` and not `vcodec`, but u'll have to check to be sure

**Comment by megapro17** [comment]
ffmpeg will ignore this option if it doesn't exist, so we always can pass it

**Comment by pukkandan** [comment]
Even when writing audio subs etc? Also, can you confirm this is true for older ffmpeg as well? I'd like to keep compatibility with atleast 3.0 and above.

If both these are fine, we can add the option directly to `real_run_ffmpeg` instead of adding to each PP

**Comment by megapro17** [comment]
Ok, i'll check

**Comment by megapro17** [comment]
i tried multiple options and it's working fine

[test.txt](https://github.com/yt-dlp/yt-dlp/files/7742222/test.txt)

**Comment by Anuskuss** [comment]
Can confirm that it works for DASH (Merger), but HLS broke (it's not "fixing" the MPEG-TS container anymore).
As a note, since this only applies to downloads which need to be post-processed by ffmpeg, this won't make MP4s "streamable". But as a user, this is the intended behaviour, because I would've expected to get my MP4 untouched anyway.

**Comment by pukkandan** [comment]
> but HLS broke (it's not "fixing" the MPEG-TS container anymore)

log?

**Comment by Anuskuss** [comment]
@pukkandan Just run the [HLS command above](https://github.com/yt-dlp/yt-dlp/pull/1491#issuecomment-981205167):
```
[debug] Command-line config: ['-o', 'video.mp4', 'https://v.redd.it/16cqbkev2ci51', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.7.3 (CPython 32bit) - Linux-5.10.63-v7l+-armv7l-with-debian-10.11
[debug] exe versions: ffmpeg 4.3.git (fdk), ffprobe 4.3.git
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://v.redd.it/16cqbkev2ci51
[generic] 16cqbkev2ci51: Requesting header
[redirect] Following redirect to https://www.reddit.com/r/Product_Hub/comments/iduchl/see_through_whirlpool_facet/
[debug] [Reddit] Extracting URL: https://www.reddit.com/r/Product_Hub/comments/iduchl/see_through_whirlpool_facet/
[Reddit] iduchl: Downloading JSON metadata
[Reddit] iduchl: Downloading m3u8 information
[Reddit] iduchl: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 16cqbkev2ci51: Downloading 1 format(s): hls-1352
[debug] Invoking downloader on "https://v.redd.it/16cqbkev2ci51/HLS_540.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
[download] Destination: video.mp4
[download] 100% of 1.98MiB in 00:00
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json file:video.mp4
```

Notice how it's missing
```
[FixupM3u8] Fixing MPEG-TS in MP4 container of "video.mp4"
```

**Comment by pukkandan** [comment]
Because it is not an `mpeg-ts` video, but is already a valid `mpeg4`. Try running ffprobe on it

**Comment by Anuskuss** [comment]
`mediainfo` says MPEG-TS though and `ffprobe` errors out:
```
$ ffprobe -hide_banner video.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x254e9b0] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x254e9b0] moov atom not found
video.mp4: Invalid data found when processing input
```

**Comment by pukkandan** [comment]
Can't reproduce
```
➤ yt-dlp -v https://v.redd.it/16cqbkev2ci51 --exec ffprobe
[debug] Command-line config: ['-v', 'https://v.redd.it/16cqbkev2ci51', '--exec', 'ffprobe']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071af6] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 4273cc776
[debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-103892-g71f2a9a2e5-20210927 (setts,fdk), ffprobe N-103892-g71f2a9a2e5-20210927, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://v.redd.it/16cqbkev2ci51
[generic] 16cqbkev2ci51: Requesting header
[redirect] Following redirect to https://www.reddit.com/r/Product_Hub/comments/iduchl/see_through_whirlpool_facet/
[debug] [Reddit] Extracting URL: https://www.reddit.com/r/Product_Hub/comments/iduchl/see_through_whirlpool_facet/
[Reddit] iduchl: Downloading JSON metadata
[Reddit] iduchl: Downloading m3u8 information
[Reddit] iduchl: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 16cqbkev2ci51: Downloading 1 format(s): hls-1352
[debug] Invoking downloader on "https://v.redd.it/16cqbkev2ci51/HLS_540.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
[download] Destination: See through Whirlpool Facet [16cqbkev2ci51].mp4
[download] 100% of 1.98MiB in 00:00
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:See through Whirlpool Facet [16cqbkev2ci51].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "See through Whirlpool Facet [16cqbkev2ci51].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:See through Whirlpool Facet [16cqbkev2ci51].mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:See through Whirlpool Facet [16cqbkev2ci51].temp.mp4"
[Exec] Executing command: ffprobe "D:\Programs\Source\yt-dlp\yt-dlp\See through Whirlpool Facet [16cqbkev2ci51].mp4"
ffprobe version N-103892-g71f2a9a2e5-20210927 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20210408
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-nonfree --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --enable-vulkan --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --enable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libglslang --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20210927
  libavutil      57.  7.100 / 57.  7.100
  libavcodec     59.  9.101 / 59.  9.101
  libavformat    59.  5.100 / 59.  5.100
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8.  9.100 /  8.  9.100
  libswscale      6.  1.100 /  6.  1.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\Programs\Source\yt-dlp\yt-dlp\See through Whirlpool Facet [16cqbkev2ci51].mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.5.100
  Duration: 00:00:12.30, start: 0.000000, bitrate: 1319 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 640x640 [SAR 1:1 DAR 1:1], 1317 kb/s, 30 fps, 30 tbr, 90k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
```

**Comment by Anuskuss** [comment]
Literally only running
```
$ git clone https://github.com/yt-dlp/yt-dlp && cd yt-dlp && make yt-dlp && ./yt-dlp -v https://v.redd.it/16cqbkev2ci51 --exec "ffprobe -hide_banner"
Cloning into 'yt-dlp'...
remote: Enumerating objects: 103111, done.
remote: Counting objects: 100% (169/169), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 103111 (delta 97), reused 136 (delta 79), pack-reused 102942
Receiving objects: 100% (103111/103111), 31.33 MiB | 10.36 MiB/s, done.
Resolving deltas: 100% (79902/79902), done.
mkdir -p zip
for d in yt_dlp yt_dlp/downloader yt_dlp/extractor yt_dlp/postprocessor ; do \
  mkdir -p zip/$d ;\
  cp -pPR $d/*.py zip/$d/ ;\
done
touch -t 200001010101 zip/yt_dlp/*.py zip/yt_dlp/*/*.py
mv zip/yt_dlp/__main__.py zip/
cd zip ; zip -q ../yt-dlp yt_dlp/*.py yt_dlp/*/*.py __main__.py
rm -rf zip
echo '#!/usr/bin/env python3' > yt-dlp
cat yt-dlp.zip >> yt-dlp
rm yt-dlp.zip
chmod a+x yt-dlp
[debug] Command-line config: ['-v', 'https://v.redd.it/16cqbkev2ci51', '--exec', 'ffprobe -hide_banner']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.7.3 (CPython 32bit) - Linux-5.10.63-v7l+-armv7l-with-debian-10.11
[debug] exe versions: ffmpeg 4.3.git (fdk), ffprobe 4.3.git
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://v.redd.it/16cqbkev2ci51
[generic] 16cqbkev2ci51: Requesting header
[redirect] Following redirect to https://www.reddit.com/r/Product_Hub/comments/iduchl/see_through_whirlpool_facet/
[debug] [Reddit] Extracting URL: https://www.reddit.com/r/Product_Hub/comments/iduchl/see_through_whirlpool_facet/
[Reddit] iduchl: Downloading JSON metadata
[Reddit] iduchl: Downloading m3u8 information
[Reddit] iduchl: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 16cqbkev2ci51: Downloading 1 format(s): hls-1352
[debug] Invoking downloader on "https://v.redd.it/16cqbkev2ci51/HLS_540.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
[download] Destination: See through Whirlpool Facet [16cqbkev2ci51].mp4
[download] 100% of 1.98MiB in 00:00
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:See through Whirlpool Facet [16cqbkev2ci51].mp4'
[Exec] Executing command: ffprobe -hide_banner '/home/pi/yt-dlp/See through Whirlpool Facet [16cqbkev2ci51].mp4'
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1f1a9b0] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1f1a9b0] moov atom not found
/home/pi/yt-dlp/See through Whirlpool Facet [16cqbkev2ci51].mp4: Invalid data found when processing input
ERROR: Postprocessing: Command returned error code 1
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3053, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3228, in post_process
    info = self.run_pp(pp, info)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3167, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "./yt-dlp/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "./yt-dlp/yt_dlp/postprocessor/exec.py", line 37, in run
    raise PostProcessingError('Command returned error code %d' % retCode)
yt_dlp.utils.PostProcessingError: Command returned error code 1
```

> `➤ yt-dlp -v https://v.redd.it/16cqbkev2ci51 --exec ffprobe`

Dumb question, but are you sure that you're actually running against `master`?

**Comment by pukkandan** [comment]
> [debug] Git HEAD: 4273cc776

But let me check again

**Comment by megapro17** [comment]
Exec is running before fixup?

**Comment by Anuskuss** [comment]
I still don't know what's exactly going on here but since neither of you can reproduce, it's likely my fault.
If I hide my `ffprobe`, I finally see the "Fixup" line, but it still doesn't work:
```
 $ ./yt-dlp https://v.redd.it/16cqbkev2ci51 -o video.mp4
[generic] 16cqbkev2ci51: Requesting header
[redirect] Following redirect to https://www.reddit.com/r/Product_Hub/comments/iduchl/see_through_whirlpool_facet/
[Reddit] iduchl: Downloading JSON metadata
[Reddit] iduchl: Downloading m3u8 information
[Reddit] iduchl: Downloading MPD manifest
[info] 16cqbkev2ci51: Downloading 1 format(s): hls-1352
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
[download] Destination: video.mp4
[download] 100% of 1.98MiB in 00:00
WARNING: Unable to extract metadata: ffprobe not found. Please install or provide the path using --ffmpeg-location
[FixupM3u8] Fixing MPEG-TS in MP4 container of "video.mp4"
ERROR: Postprocessing: file:video.mp4: Invalid data found when processing input
```
I don't know what's wrong with my `ffprobe` (I have compiled it myself ages ago), but I'll figure it out when I have more time.
Please disregard.

**Pull request closed without merging**
