### PR TITLE
[crunchyroll] Fix thumbnail

### PR DESCRIPTION
**Pull request by funniray**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

The thumbnail for crunchyroll can no longer be taken from the XML api of Crunchyroll, however, the fallback for the thumbnail was pointed at media.metadata.thumbnail, however the thumbnail is just at media.metadata

### CODE REVIEW

**Comment by funniray** [comment]
The thumbnail from the metadata tag is very low quality (360p). For my needs, I need a high quality thumbnail, so I'm currently attempting to get the higher quality thumbnail from the script tag which is a JSON descriptor on the page.

**Comment by pukkandan** [comment]
Since there are multiple thumbnails, try to return `thumbnails` with `width` and `height` as well if possible

**Comment by funniray** [comment]
Crunchyroll doesn't directly show what resolution the thumbnails are, but I could assume what they are. I've also noticed that the names of the different resolution thumbnails are able to be procedurally generated as followed  

https://img1.ak.crunchyroll.com/i/spire4-tmb/<uuid>_<res_enum>.jpg

For the enum, it's these resolutions (from my understanding)

- `main` - `1920x1080`
- `full` - `640x360`
- `fwide` - `640x360`
- `large` - `200x112`
- `thumb` - `160x90`
- `medium` - `100x56`
- `small` - `50x28`

I have went back to a show from 2014 on crunchyroll and the thumbnails still seem to use the same format with the same resolutions. Should I try to generate the thumbnail urls using this format, even though they aren't linked on the page directly?

**Comment by funniray** [comment]
I made it return both thumbnails that were on the page itself. I hardcoded the width and height because from all testing I've done, they seem to be the right resolution and it's not on the webpage anywhere.

**Comment by pukkandan** [comment]
You can hardcode the urls if they are guaranteed to exist. Even if they are not, we could hardcode the URLs and then test them (like we do for youtube), but not really needed since we already have the best thumbnail

**Pull request merged**
