### PR TITLE
Query completion locations via pkg-config

### PR DESCRIPTION
**Pull request by hseg**
### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Queries the completion locations via `pkg-config`.
To do this properly, added autoconf support.
Build process is now:
```
autoreconf --install
./configure --prefix=$PREFIX
make man
python setup.py build
python setup.py install
```

Closes: #108, #110

### CODE REVIEW

**Comment by hseg** [comment]
A pointer that was useful to me in writing these is <https://stackoverflow.com/a/26832773>. Note in particular the distinction raised there between the packager, dev and release workflows.

**Comment by pukkandan** [comment]
1. Simply cloning the repo and running `make` should continue to work as before as long as we don't care about completions. Especially, `yt-dlp doc test ot clean` shouldn't be affected. This can probably be achieved by committing the generated `makefile` into the repo
2. Necessary changes (if any) must be made to `build.yml` and `README.md`

**Comment by hseg** [comment]
1. Could commit a makefile with the defaults and have builds overwrite it. Indeed, could hide the `autoreconf --install` voodoo behind a `make devenv` target and make sure `make distclean` restores that default. Unsure that it is recommended. Judging by SO link, recommended practice instead is to have `make tar` bundle in the generated `configure` and `Makefile.in` files, and have devs run `autoreconf --install` to generate them. Though even GNU don't follow that latter recommendation, instead having a `bootstrap` script.
2. Didn't know about `build.yml`. Looking at `README.md`, it needed updating anyway, as it still refers to `make youtube_dlc`.

BTW, noticed that you edited this to say this closes #110 -- it doesn't, unless we're going down the "have completions shipped by makefile" route.

**Comment by hseg** [comment]
Also, judging by `automake` documentation, `make tar` should be renamed `make dist`. Can just alias for backwards compatibility.

**Comment by samoht0** [comment]
I've tested the changes in setup.py. Working well, so far. Thanks for the work. I've got two suggestions:
Is .bash-completion ending really still common? Or remove it? Never seen it on Fedora, at least.
Should there be a warning, when "if pkgconfig.exists" fails?

**Comment by hseg** [comment]
... actually, writing out a directive to restore the default is a) difficult and b) pointless considering the existence of `git restore`. Fixing the rest right now, though

**Comment by pukkandan** [comment]
> Unsure that it is recommended. Judging by SO link, recommended practice instead is to have make tar bundle in the generated configure and Makefile.in files, and have devs run autoreconf --install to generate them. Though even GNU don't follow that latter recommendation, instead having a bootstrap script.

It makes sense for projects that have milestone based releases where the users are only expected to use the release version and never the master. However, we have releases primarily as a convinience for end-users and there are many people who build themselves from master branch. I don't want to add autotools and related packages as a necessary dependancy. There is also build.yml which depends on makefile to run (although in this case, I assume we can edit it to use autotools)

> Looking at README.md, it needed updating anyway, as it still refers to make youtube_dlc.

Has been already updated in 127d07595538ebc108712d5fdb06ee927743c637

> Also, judging by automake documentation, make tar should be renamed make dist. Can just alias for backwards compatibility.

Alias, dont rename

> Indeed, could hide the autoreconf --install voodoo behind a make devenv target and make sure make distclean restores that default. 

You can do it, but I doubt it is actually necessary. You can just `git restore` after building

**Comment by pukkandan** [comment]
btw, autoreconfig isnt working for me on WSL. Do you know which repo to add to get the latest version of autoconfig?

```bash
$ sudo apt-get install autoconf
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf is already the newest version (2.69-11.1).
0 upgraded, 0 newly installed, 0 to remove and 80 not upgraded.

$ autoreconf --install
configure.ac:1: error: Autoconf version 2.71 or higher is required
configure.ac:1: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: error: echo failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
```

**Comment by pukkandan** [comment]
> BTW, noticed that you edited this to say this closes #110 -- it doesn't, unless we're going down the "have completions shipped by makefile" route.

Like I said before, I am inexperienced with packaging unix distributions. Whichever solution you are able to implement, I will go with it assuming it doesn't break any existing functionality

**Comment by hseg** [comment]
Hrm, thought I had rebased on top of that.
In re dependency load of autotools, hadn't fully internalized how much it'd cost end users.
E.g. from your error messages, I see I should've at least made an attempt at using the minimum version possible.

**Comment by hseg** [comment]
> Like I said before, I am inexperienced with packaging unix distributions. Whichever solution you are able to implement, I will go with it assuming it doesn't break any existing functionality

Unfortunately, it's a blind leading the blind scenario. Am perhaps a little more familiar, but not to the extent I'm comfortable making judgement calls.

**Comment by hseg** [comment]
Though autotools are afaict a common dependency for people building their own packages. e.g. Arch Linux presumes it's installed for custom packagers

**Comment by pukkandan** [comment]
> Unfortunately, it's a blind leading the blind scenario. Am perhaps a little more familiar, but not to the extent I'm comfortable making judgement calls.

I will try to get someone who knows more about this to help

**Comment by hseg** [comment]
In summary, we're unsure about the dependency burden of using autotools for such a small callout to pkg-config, using it requires devs to autoconf their systems before being able to build, which changes the build process.

If we do go through with this, the necessary additional edits are:
* Package the generated `configure` and `Makefile.in` into the tarball
* Alias `make dist = make tar`
* Update `build.yml`, `README.md` to suit the new build process

**Comment by hseg** [comment]
Side note: `doc/Makefile` errors out if sphinx isn't installed. Will want to look into making it an optional component dependent on if sphinx is installed, but again will need judgement call re autotools

**Comment by pukkandan** [comment]
> doc/Makefile errors out if sphinx isn't installed. Will want to look into making it an optional component dependent on if sphinx is installed, but again will need judgement call re autotools

`doc/Makefile` is only run in order to make the sphinx docs, so the dependency makes sense. It is not invoked by the main `makefile`

**Comment by hseg** [comment]
It is in the generated makefile for things like `make distclean`

**Comment by hseg** [comment]
:facepalm: never mind, I misread the manual and added it unnecessarily

**Comment by pukkandan** [comment]
btw, have you tried discussing this matter with the youtube-dl devs?

Related issues: https://github.com/ytdl-org/youtube-dl/pull/22355 https://github.com/ytdl-org/youtube-dl/issues/22521 https://github.com/ytdl-org/youtube-dl/issues/16512

**Comment by hseg** [comment]
No, thanks for reminding me.

**Comment by hseg** [comment]
OK, so checking the PR you linked, it's probably a much better idea to go with that approach and just fix the paths. Adding all the flexibility of `pkg-config` is probably overkill anyway.

**Comment by hseg** [comment]
As noted there, will need to place completions in a subdirectory for `pip` to be able to install them.

**Comment by pukkandan** [comment]
Closing this since #114 is sufficient for now. If need for this PR ever arises, I will re-open

**Pull request closed without merging**
