### PR TITLE
[extractor/twitter] Improve unauthenticated extraction

### PR DESCRIPTION
**Pull request by bashonly**
Found a much better way to get tweets without auth (graphql == all metadata/videos/error info).

For unauthenticated users, the GraphQL endpoint has a rate-limit of 50 queries per ??? minutes/hours/days?? But it's irrelevant because we can just request a new guest token for each download.

Things to consider/experiment with:
 1. will this still work in a few days?
 2. does the syndication endpoint currently used by yt-dlp have a rate-limit based on IP?
 3. does the guest token endpoint have a rate-limit based on IP?

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🐦🚀🔊

Improve Twitter extractor by using GraphQL API and adding guest tokens and Spaces support. This enables more reliable and comprehensive extraction of tweets and audio streams from Twitter. The file `yt_dlp/extractor/twitter.py` is modified to implement these changes.

> _Oh we're the jolly coders of the Twitter extractor_
> _We fetch the guest tokens and we use the GraphQL_
> _We handle more tweets and we avoid the errors_
> _And we check the login for the Twitter Spaces all_

### Walkthrough
*  Add and use a new method `_fetch_guest_token` to handle guest token requests and extraction for the Twitter API ([link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103R154-R162), [link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103L181-R190), [link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103L283-R304))
*  Modify the `_call_api` method to conditionally set the headers for authenticated or unauthenticated requests to the Twitter API ([link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103L283-R304))
*  Modify the `_graphql_to_legacy` method to handle different GraphQL queries and responses depending on the login status, and to raise appropriate exceptions for inaccessible tweets ([link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103L1028-R1042), [link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103R1048-R1052))
*  Modify the `_build_graphql_query` method to return different queries with different variables, features, and fieldToggles for the `TweetResultByRestId` query when not logged in ([link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103R1103-R1133))
*  Modify the `_real_extract` method of the `TwitterIE` class to use the GraphQL API instead of the syndication JSON when not logged in, and to pass the `twid` argument to the `_graphql_to_legacy` method ([link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103L1092-R1140))
*  Remove unnecessary workarounds and fallbacks from the `extract_from_video_info` and `extract_from_card_info` functions in the `_real_extract` method of the `TwitterIE` class, which are no longer needed since the GraphQL API provides the `media_id` and the `extended_entities` in the tweet result ([link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103L1132-L1136), [link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103L1161-R1196), [link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103L1246-R1281), [link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103L1253-R1287))
*  Add a check to the `_real_extract` method of the `TwitterSpacesIE` class, which raises a `LoginRequired` exception if the user is not logged in, since the Twitter Spaces API requires authentication ([link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103R1477-R1478))
*  Remove an unused import of `urllib.error` from the `yt_dlp/extractor/twitter.py` module ([link](https://github.com/yt-dlp/yt-dlp/pull/7516/files?diff=unified&w=0#diff-8b22c3c3c6185164ce8c3e82541f91c728397dec66456eef7e05f664d5729103L3))

</details>

### CODE REVIEW

**Comment by pukkandan** [comment]
We should merge this in two commits, like this https://github.com/yt-dlp/yt-dlp/compare/master...pukkandan:yt-dlp-dev:pr/7516

**Comment by bashonly** [comment]
Came up with another version that also adds back legacy API support, which could be useful as a fallback in case twitter breaks more stuff: https://github.com/yt-dlp/yt-dlp/compare/master...bashonly:yt-dlp:fix/twitter-gql-again

**Comment by pukkandan** [comment]
LGTM, but don't merge it rn. I want to merge this between the two upcoming releases so there's a version with the new method.

**Comment by pukkandan** [comment]
Can merge now

**Comment by Renew231** [comment]
Super

**Pull request merged**
