### PR TITLE
Import extractors plugins if using Bundle App

### PR DESCRIPTION
**Pull request by oleksis**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [ ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Add support for use plugins extractr fro BundleApp (binaries)

Feel free the make changes!

### CODE REVIEW

**Comment by oleksis** [comment]
See one use case [Picta-DL](https://t.me/picta_dl/157)

**Comment by pukkandan** [comment]
I don't understand. Plugins are already loaded for binaries. That is the whole point of being a "plugin" after all.

Could you explain what the exact issue that this solves is?

**Comment by pukkandan** [comment]
```
$ dir /b /s
D:\AKJ\Progs\mpv\yt-dlp\yt-dlp.exe
D:\AKJ\Progs\mpv\yt-dlp\ytdlp_plugins
D:\AKJ\Progs\mpv\yt-dlp\ytdlp_plugins\extractor
D:\AKJ\Progs\mpv\yt-dlp\ytdlp_plugins\extractor\sample.py
D:\AKJ\Progs\mpv\yt-dlp\ytdlp_plugins\extractor\__init__.py

$ yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.05.11 (exe)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.8.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: none
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```

**Comment by pukkandan** [comment]
```
$ dir /b /s
<REDACTED>\yt-dlp\yt-dlp.exe
<REDACTED>\yt-dlp\ytdlp_plugins
<REDACTED>\yt-dlp\ytdlp_plugins\extractor
<REDACTED>\yt-dlp\ytdlp_plugins\extractor\sample.py
<REDACTED>\yt-dlp\ytdlp_plugins\extractor\__init__.py

$ yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.05.11 (exe)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.8.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: none
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```

**Comment by oleksis** [comment]
@pukkandan The case of use is when you run YT-DLP from another process, for example using the yt-dlg GUI, the relative import error occurs. That is why I add that directory to the path of the Python import system and don’t use relative imports. 

In the event of an import error, send the output to the Errors stream, since by default yt-dlp ignores the error if the Plugin cannot be imported.

Try using the plugin system from YT-DLG

**Comment by pukkandan** [comment]
I downloaded `yt-dlg` and copied `ytdlp_plugins` with the sample plugin to `%appdata%\yt-dlg` (where yt-dlg downloads the yt-dlp executable). Then I added `-v` to yt-dlg CLI options and ran on URL `sampleplugin:test`. The log generated clearly shows that the plugin was sucessfully loaded.

```

2021-05-18 21:34:56,622-DEBUG-Worker_1-[debug] Command-line config: ['--newline', '-i', '-o', '<REDACTED>\\%(title)s.%(ext)s', '--ignore-config', '--hls-prefer-native', '-v', 'sampleplugin:test']
2021-05-18 21:34:56,622-DEBUG-Worker_1-[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
2021-05-18 21:34:56,622-DEBUG-Worker_1-[debug] yt-dlp version 2021.05.11 (exe)
2021-05-18 21:34:56,622-DEBUG-Worker_1-[debug] Plugin Extractors: ['SamplePlugin']
2021-05-18 21:34:56,622-DEBUG-Worker_1-[debug] Python version 3.8.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
2021-05-18 21:34:56,622-DEBUG-Worker_1-[debug] exe versions: none
2021-05-18 21:34:56,622-DEBUG-Worker_1-[debug] Proxy map: {}
2021-05-18 21:34:56,632-DEBUG-Worker_1-WARNING: The program functionality for this site has been marked as broken, and will probably not work.
2021-05-18 21:34:56,632-DEBUG-Worker_1-ERROR: 'NoneType' object has no attribute 'get'
2021-05-18 21:34:56,632-DEBUG-Worker_1-Traceback (most recent call last):
2021-05-18 21:34:56,632-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 1117, in wrapper
2021-05-18 21:34:56,632-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 1138, in __extract_info
2021-05-18 21:34:56,632-DEBUG-Worker_1-  File "yt_dlp\extractor\common.py", line 560, in extract
2021-05-18 21:34:56,632-DEBUG-Worker_1-AttributeError: 'NoneType' object has no attribute 'get'
2021-05-18 21:34:56,632-DEBUG-Worker_1-Child process exited with non-zero code: 1
```

**Comment by oleksis** [comment]
> I downloaded `yt-dlg` and copied `ytdlp_plugins` with the sample plugin to `%appdata%\yt-dlg` (where yt-dlg downloads the yt-dlp executable). Then I added `-v` to yt-dlg CLI options and ran on URL `sampleplugin:test`. The log generated clearly shows that the plugin was sucessfully loaded.
> 

Ok verified, Excuse me and thank you for your time.  In some tests I had to add the import.  The important thing is that Plugin 🔌 (extractor) does not use relative import and use yt_dlp as namespace.

**Comment by pukkandan** [comment]
> The important thing is that Plugin 🔌 (extractor) does not use relative import and use yt_dlp as namespace.

Yes, and this is specifically documented in `sample.py`

**Pull request closed without merging**
