### PR TITLE
[JioCinema] Add extractor

### LINKED ISSUE #5563: Jio cinema Extractor
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

_No response_

### Example URLs

Watch Bose: Dead/Alive now on ALTBalaji

https://www.altbalaji.com/show/171

https://www.jiocinema.com/watch/movies/run-for-life-bhaag/0/0/5399e0b02aa411ed9e2f7b23e76e919b/0/0

### Provide a description that is worded well enough to be understood

Please add ALTBalaji and Jio cinema Extractor. This site are not completely DRM. They offer free video also.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
❯ yt-dlp https://www.jiocinema.com/watch/movies/run-for-life-bhaag/0/0/5399e0b02aa411ed9e2f7b23e76e919b/0/0
[generic] 0: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 0: Extracting information
ERROR: Unsupported URL: https://www.jiocinema.com/watch/movies/run-for-life-bhaag/0/0/5399e0b02aa411ed9e2f7b23e76e919b/0/0
```

### PR DESCRIPTION
**Pull request by Rajeshwaran2001**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADD DESCRIPTION HERE

Fixes #5563 

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by bashonly** [comment]
Hm, a lot of this code [looks very familiar](https://github.com/bashonly/yt-dlp/commit/340fdc674ec762480297f9d4dc7e18131a81f257)

**Comment by Rajeshwaran2001** [comment]
> Hm, a lot of this code [looks very familiar](https://github.com/bashonly/yt-dlp/commit/340fdc674ec762480297f9d4dc7e18131a81f257)

yeah i got most of the code from your repo and added little tweaks

**Comment by pukkandan** [comment]
Avoid so much copy-paste. Derive the desired functionality from a baseclass

**Comment by shortthirdman** [comment]
@bashonly @pukkandan When is this PR going to be merged into release? Just waiting to use it for testing.

**Comment by Rajeshwaran2001** [comment]
> @bashonly @pukkandan When is this PR going to be merged into release? Just waiting to use it for testing.

you can get the build https://github.com/DRM-Media-Tool/yt-dlp/releases/tag/2024.03.09.093349

**Comment by shortthirdman** [comment]
> > @bashonly @pukkandan When is this PR going to be merged into release? Just waiting to use it for testing.
> 
> you can get the build https://github.com/DRM-Media-Tool/yt-dlp/releases/tag/2024.03.09.093349

@Rajeshwaran2001 Build is not stable. Tested with couple of free videos, both of them failed in the download stage throwing error as `ERROR: unable to download video data: HTTP Error 400: Bad Request`.

Full log below:

```
$PS> $jio = 'https://www.jiocinema.com/tv-shows/udaariyaan/1/tejo-loses-fateh/3523229'
$PS> .\yt.exe -f "hls-1328-1+ba" -P "$pwd" -o "S%(season_number)s E%(episode_number)s - %(upload_date>%#d %B %Y)s - %(episode)s.%(ext)s" $jio

[JioCinema] Extracting URL: https://www.jiocinema.com/tv-shows/udaariyaan/1/tejo-loses-fateh/3523229
[JioCinema] Downloading guest token
[JioCinema] Fetching Metadata
[JioCinema] 3523229: Downloading playback JSON
[JioCinema] 3523229: Downloading MPD manifest
[JioCinema] 3523229: Downloading m3u8 information
[info] 3523229: Downloading 1 format(s): hls-1328-1+hls-A64-aac
[info] There are no subtitles for the requested languages
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: D:\Entertainment - TV Shows\NEXT\S1 E341 - 5 April 2022 - Tejo loses Fateh!.jpg
[info] Writing video metadata as JSON to: D:\Entertainment - TV Shows\NEXT\S1 E341 - 5 April 2022 - Tejo loses Fateh!.info.json
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 217
[download] Destination: D:\Entertainment - TV Shows\NEXT\S1 E341 - 5 April 2022 - Tejo loses Fateh!.fhls-1328-1.mp4
[download]   0.2% of ~ 315.69MiB at  194.33KiB/s ETA 37:08 (frag 1/217)ERROR: unable to download video data: HTTP Error 400: Bad Request
```

Did you test it out yourself first before the PR?

**Comment by Rajeshwaran2001** [comment]
> > > @bashonly @pukkandan When is this PR going to be merged into release? Just waiting to use it for testing.
> > 
> > 
> > you can get the build https://github.com/DRM-Media-Tool/yt-dlp/releases/tag/2024.03.09.093349
> 
> @Rajeshwaran2001 Build is not stable. Tested with couple of free videos, both of them failed in the download stage throwing error as `ERROR: unable to download video data: HTTP Error 400: Bad Request`.
> 
> Full log below:
> 
> ```
> $PS> $jio = 'https://www.jiocinema.com/tv-shows/udaariyaan/1/tejo-loses-fateh/3523229'
> $PS> .\yt.exe -f "hls-1328-1+ba" -P "$pwd" -o "S%(season_number)s E%(episode_number)s - %(upload_date>%#d %B %Y)s - %(episode)s.%(ext)s" $jio
> 
> [JioCinema] Extracting URL: https://www.jiocinema.com/tv-shows/udaariyaan/1/tejo-loses-fateh/3523229
> [JioCinema] Downloading guest token
> [JioCinema] Fetching Metadata
> [JioCinema] 3523229: Downloading playback JSON
> [JioCinema] 3523229: Downloading MPD manifest
> [JioCinema] 3523229: Downloading m3u8 information
> [info] 3523229: Downloading 1 format(s): hls-1328-1+hls-A64-aac
> [info] There are no subtitles for the requested languages
> [info] Downloading video thumbnail 0 ...
> [info] Writing video thumbnail 0 to: D:\Entertainment - TV Shows\NEXT\S1 E341 - 5 April 2022 - Tejo loses Fateh!.jpg
> [info] Writing video metadata as JSON to: D:\Entertainment - TV Shows\NEXT\S1 E341 - 5 April 2022 - Tejo loses Fateh!.info.json
> [hlsnative] Downloading m3u8 manifest
> [hlsnative] Total fragments: 217
> [download] Destination: D:\Entertainment - TV Shows\NEXT\S1 E341 - 5 April 2022 - Tejo loses Fateh!.fhls-1328-1.mp4
> [download]   0.2% of ~ 315.69MiB at  194.33KiB/s ETA 37:08 (frag 1/217)ERROR: unable to download video data: HTTP Error 400: Bad Request
> ```
> 
> Did you test it out yourself first before the PR?

I had tested it before making the PR. I am aware of this and this has nothing to do with the extractor it only gets the mpd or m3u8 link and sends it to the downloading engine. The issue is most of the m3u8 formats will not download I faced this issue with most of the free content and only tried the formats that used the HTTPS  protocol. If you need any help in decryption messages in [Discord ]([discord.gg/QpEHdyst5b](https://discord.gg/QpEHdyst5b))I will help you.

```
D:\>yt -f 16+ba https://www.jiocinema.com/tv-shows/udaariyaan/1/tejo-loses-fateh/3523229
[debug] Command-line config: ['-f', '16+ba', 'https://www.jiocinema.com/tv-shows/udaariyaan/1/tejo-loses-fateh/3523229']
[debug] Portable config "C:\tools\yt-dlp.conf": ['--cookies-from-browser', 'firefox', '--write-sub', '--write-info-json', '--allow-u', '--write-thumbnail', '--embed-chapters', '--split-chapters', '-v']
WARNING: You have asked for UNPLAYABLE formats to be listed/downloaded. This is a developer option intended for debugging.
         If you experience any issues while using this option, DO NOT open a bug report
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.09.093349 from DRM-Media-Tool/yt-dlp [1ebfa7b6e] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.26058-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\rajes\AppData\Roaming\Mozilla\Firefox\Profiles\maqnt34q.default-release\cookies.sqlite"
Extracted 1223 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets
WARNING: --embed-chapters is ignored since --allow-unplayable-formats was given
WARNING: --embed-subs is ignored since --allow-unplayable-formats was given
[debug] Loaded 1805 extractors
[JioCinema] Extracting URL: https://www.jiocinema.com/tv-shows/udaariyaan/1/tejo-loses-fateh/3523229
[JioCinema] Downloading guest token
[JioCinema] Fetching Metadata
[JioCinema] 3523229: Downloading playback JSON
[JioCinema] 3523229: Downloading MPD manifest
[JioCinema] 3523229: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 3523229: Downloading 1 format(s): 16+1
[info] There are no subtitles for the requested languages
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: Udaariyaan [3523229].jpg
[info] Writing video metadata as JSON to: Udaariyaan [3523229].info.json
WARNING: You have requested merging of multiple formats while also allowing unplayable formats to be downloaded. The formats won't be merged to prevent data corruption.
[debug] Invoking http downloader on "https://jc-ak-dashstreaming.jiocinema.com/content/entry/wvdata/90/84/452253e0b4e911ecb5255352398d9ee1_2492_v_1662370449384.mp4?hdntl=exp=1710526434~acl=/*~id=3ecf03882f6e40ea8f3f9d7365289b72~data=hdntl~hmac=aa751eff325793785eaa4f0bab116a4f8d518d79fb2903b25efdba7c0d2c9bbb"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Udaariyaan [3523229].f16.mp4
[download] 100% of  356.18MiB in 00:00:17 at 20.05MiB/s
[debug] Invoking http downloader on "https://jc-ak-dashstreaming.jiocinema.com/content/entry/wvdata/90/84/452253e0b4e911ecb5255352398d9ee1_stereo_64_a_1662370449384.mp4?hdntl=exp=1710526434~acl=/*~id=3ecf03882f6e40ea8f3f9d7365289b72~data=hdntl~hmac=aa751eff325793785eaa4f0bab116a4f8d518d79fb2903b25efdba7c0d2c9bbb"
[download] Destination: Udaariyaan [3523229].f1.m4a
[download] 100% of   10.61MiB in 00:00:00 at 17.81MiB/s
[SplitChapters] Chapter information is unavailable
```

**Pull request closed without merging**
