### PR TITLE
[extractor/pornhub] Fix download error in UK.

### PR DESCRIPTION
**Pull request by zhong-yiyu**
This fix will resolve the problem of not able to download pornhub videos in UK region.

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADD DESCRIPTION HERE
This fix will resolve the problem of not able to download pornhub videos in UK region.
Fixes #
Download issues of pornhub in United Kingdom Region

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
📝📱🐛

Add support for `--write-link` and `--write-url` options to write video or playlist URLs to a file. Refactor the code for writing metadata files to avoid duplication and improve readability.

> _`is_valid` checks_
> _refactored for clarity_
> _autumn leaves falling_

### Walkthrough
*  Add support for downloading videos from the website `tubitv.com` (tubitv.py, test_tubitv.py)

</details>

### CODE REVIEW

**Comment by bashonly** [comment]
@zhong-yiyu can you fill out the checkboxes in the template

**Comment by zhong-yiyu** [comment]
> @zhong-yiyu can you fill out the checkboxes in the template

All done! Sorry for the inconvenience.

**Review by bashonly — APPROVED** [review]

**Comment by pukkandan** [comment]
> * [](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md?rgh-link-date=2023-07-14T16%3A53%3A33Z#developer-instructions)
> 
> ### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
> * [x]  I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
> * [x]  I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)
> 
> ### What is the purpose of your _pull request_?
> * [x]  Fix or improvement to an extractor (Make sure to add/update tests)
> * [x]  New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md?rgh-link-date=2023-07-14T16%3A53%3A33Z#is-the-website-primarily-used-for-piracy))
> * [x]  Core bug fix/improvement
> * [x]  New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md?rgh-link-date=2023-07-14T16%3A53%3A33Z#adding-new-feature-or-making-overarching-changes))

WHAT??

**Comment by gamer191** [comment]
sending this cookie globally (instead of just in UK) would make yt-dlp easier for pornhub to fingerprint, wouldn't it?

I guess we can just fix that if it becomes an issue though 🤷

**Pull request merged**
