### PR TITLE
Optimize string concat in mpd parser

### PR DESCRIPTION
**Pull request by FlxB2**
### Description of your *pull request* and other information

</details>

I'm in the process of building a dynamic analysis tool for python. I ran the tool on this repository and found an opportunity to improve the parsing of MPD files. Right now string concatenations to parse initialization templates are done using `+=`. However, according to [PEP-008](https://peps.python.org/pep-0008/#programming-recommendations) the proposed change is encouraged and faster on most interpreters other than CPython.

I ran the dynamic analysis by executing the tests, therefore the proposed changes should already be covered by the following test cases: [float_duration](https://github.com/yt-dlp/yt-dlp/blob/master/test/test_InfoExtractor.py#L1050) and [subtitles](https://github.com/yt-dlp/yt-dlp/blob/master/test/test_InfoExtractor.py#L1262)

Fixes -

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
Does this really matter? I am not interested in making millisecond optimizations

**Comment by FlxB2** [comment]
I think it would make a difference, initialization and media can get quite long, e.g. in this [example](https://cloudflarestream.com/31c9291ab41fac05471db4e73aa11717/manifest/video.mpd). Every time `+=` is called the interpreter has to create a new string and copy the values over, the execution time differs quite a bit. You can find more information to that [here](https://python.plainenglish.io/concatenating-strings-efficiently-in-python-9bfc8e8d6f6e).

But if you are not interested in those kind of changes I can run the tool directly on youtube-dl as well and see if the change makes sense there.

**Comment by pukkandan** [comment]
You didn't think to actually try timing it before "optimizing"? Here, I'll do it for you. The example manifest you gave is actually quite small, and not a suitable candidate for testing. So I took the best of 5 with the gigantic manifest in https://github.com/yt-dlp/yt-dlp/issues/3390 instead

master
```
❯ yt-dlp -s https://www.youtube.com/watch?v=mivcDoTjpQE
[youtube] mivcDoTjpQE: Downloading webpage
[youtube] mivcDoTjpQE: Downloading android player API JSON
[youtube] mivcDoTjpQE: Downloading MPD manifest
Function _parse_mpd_formats_and_subtitles Took 1.1475 seconds
[youtube] mivcDoTjpQE: Downloading MPD manifest
Function _parse_mpd_formats_and_subtitles Took 2.4663 seconds
[info] mivcDoTjpQE: Downloading 1 format(s): 18
```
PR
```
❯ yt-dlp -s https://www.youtube.com/watch?v=mivcDoTjpQE
[youtube] mivcDoTjpQE: Downloading webpage
[youtube] mivcDoTjpQE: Downloading android player API JSON
[youtube] mivcDoTjpQE: Downloading MPD manifest
Function _parse_mpd_formats_and_subtitles Took 1.1729 seconds
[youtube] mivcDoTjpQE: Downloading MPD manifest
Function _parse_mpd_formats_and_subtitles Took 2.9814 seconds
[info] mivcDoTjpQE: Downloading 1 format(s): 18
```

Your code actually ends up being marginally slower, though the difference is actually below statistical significance

Please don't waste maintainers' time with pointless PRs. If you really wanted to help improve performance, there are many places using sub-optimal code (Eg: https://github.com/yt-dlp/yt-dlp/pull/3234). But to identify and improve them, you'd have to actually put in some effort

**Comment by FlxB2** [comment]
Unfortunately I could not reproduce the results for your example. Seems like the inline `prepare_template` method does not get executed as far as I can tell. 

But I did execute some tests as well, unfortunately a significant difference can only be achieved for pretty long strings. 
Here is the tests I ran if your interested:

```python 
import timeit
import random
import string
import functools

# setup
d = ''.join(random.choice(string.ascii_uppercase + string.digits + string.punctuation) for _ in range(10000))

def a(tmpl):
    in_template = False
    t = ''
    for c in tmpl:
        t += c
        if c == '$':
            in_template = not in_template
        elif c == '%' and not in_template:
            t += c

def b(tmpl):
    t_list = []
    in_template = False

    for c in tmpl:
        t_list.append(c)
        if c == '$':
            in_template = not in_template
        elif c == '%' and not in_template:
            t_list.append(c)
    t = ''.join(t_list)

t_a = timeit.Timer(functools.partial(a, d))
t_b = timeit.Timer(functools.partial(b, d))
print(t_a.timeit(100))
print(t_b.timeit(100))
```
Results:
```bash
> python3 yt-dlp-test.py 
0.1256352269999752
0.11093434099996102
> pypy3 yt-dlp-test.py 
0.2907702929999232
0.06776938899997731
```

I searched for mpd files with long initialization / media attributes, but none of them were longer than 500 chars. Therefore I agree that this change does not really make sense.

**Pull request closed without merging**
