### PR TITLE
[nebula] Convert repo copy of python source file from CRLF to LF

### PR DESCRIPTION
**Pull request by glenn-slayden**
Fix: the repo copy of the file `extractor\nebula.py` is stored with CRLF instead of LF.

This PR converts the line endings for `extractor\nebula.py` from CRLF to LF in the github repo.

There is no change to the substance of the file.

### CODE REVIEW

**Comment by glenn-slayden** [comment]
p.s.  This is the only file in the **yt-dlp** repo stored with incorrect line endings.

**Comment by glenn-slayden** [comment]
@pukkandan  Is there an option in the linter to validate/ensure “LF only” so that incorrect line endings can’t make it into the repo again?

**Comment by pukkandan** [comment]
I was thinking along the same lines, but I dont know of any such settings right now. We will need to investigate. If you find anything, let me know

**Comment by pukkandan** [comment]
I just noticed that `.gitattrbutes` is not set to convert py files to `LF`. While that setting can still be overwritten, it will prevent accidentally pushing windows endings

**Comment by glenn-slayden** [comment]
I noticed that too last month. But are you brave enough to propose adding that setting? 

I wasn’t. There’s a huge amount of subtlety in how all the EOL settings interact, local vs. remote configs, auto=true vs. false vs. “input” (!), text=…, whether “auto” detects round-trippability or reversibility and/or bothers testing for it, binary corruption for wrong guesses, all permutations of mixed CR/CRLF/LF, precedence of where ‘clone’ gets an initial config setting from, etc…

I got scared, but actually it’s probably fine    :)

**Comment by pukkandan** [comment]
.gitattributes is the recommended way to ensure consistent endings for a project. The other settings can be changed by each contributor as needed based on how they want the local endings to be. See [this guide by github](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings)

**Comment by hheimbuerger** [comment]
@glenn-slayden For the record: my apologies for causing this (I'm the original committer of these CRLFs... 😳) and my gratitude for fixing it.

I was actually planning to finally change this in the repo a few weeks ago, but couldn't figure it out and ultimately gave up. Turns out that was because you had already fixed it and that's why I couldn't find these CRLFs anymore! 😁

So anyway, sorry and thank you.

**Pull request merged**
