### PR TITLE
[youtube] Use localized title & description

### LINKED ISSUE #387: [Site Request] Support translated/localized YouTube titles and descriptions
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.06.08**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

An official feature of YouTube is allowing uploaders to provide translated titles/descriptions for their videos. Which title displays depends upon the language you have YouTube set to display in. When writing the infojson file or the description file youtube-dl and its forks only have the title/description in the original language and has no mentions of other languages. This feature should be included for the sake of those who use this program for archiving purposes. A solution would be to turn "title" in the infojson into a tree instead of a string, or to not break compatibility have a separate tree named "title_translated" or similar and use the language identifier (en_US, ja_JP, etc) as the key for objects in the tree.

### PR DESCRIPTION
**Pull request by mjsir911**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [x] Improvement

---

### Description of your *pull request* and other information

Pulled from - ytdl-org/youtube-dl#28538

Get the localized version of title, description (channel name is already translated ^.^)

- Prioritize microformat title & description over basic title & description

Related:
- ytdl-org/youtube-dl#27371
- ytdl-org/youtube-dl#13811 Related, alternative feedback. Embed original title somewhere?

Fixes:
- Fixes #387
- Fixes ytdl-org/youtube-dl#28421 
- Fixes ytdl-org/youtube-dl#27738
- Fixes ytdl-org/youtube-dl#27499
- Fixes ytdl-org/youtube-dl#10758
- Fixes ytdl-org/youtube-dl#27075 (why is this closed?)
- Fixes mpv-player/mpv#8676

### CODE REVIEW

**Comment by pukkandan** [comment]
See discussion on https://github.com/yt-dlp/yt-dlp/issues/387 and related issues

**Comment by mjsir911** [comment]
> See discussion on #387 and related issues

Yuup and I don't really have the bandwidth to deal with a PR more complicated, just putting this here for posterity. 

This PR *is* desired by users & doesn't break any existing tests, and the fact of the matter is similar localization is already being done for the `channel` key (and maybe others, I haven't checked).

see [this comment](https://github.com/ytdl-org/youtube-dl/pull/28538#issuecomment-826151492) for the workaround/explanation as to how to change the languages of the returned metadata using this PR

Additionally, the inconsistencies outlined in mpv-player/mpv#8676 still exist where the playlist's returned title is translated, but the video's metadata on download is untranslated.

**Comment by coletdjnz** [comment]
To add on, unfortunately I don't think PR will really work as intended with yt-dlp atm anyways :confused:. Recently we made a change that enforces English regardless of user provided cookies/lang header (mentioned in #387).

**Comment by mjsir911** [comment]
> To add on, unfortunately I don't think PR will really work as intended with yt-dlp atm anyways. Recently we made a change that enforces English regardless of user provided cookies/lang header

I appreciate the addition, testing this out I can confirm this behaviour:
```
$ yt-dlp --get-title UnIhRpIT7nc --add-header 'Accept-Language: en'
inabakumori - Lagtrain (Vo. Kaai Yuki) / 稲葉曇『ラグトレイン』Vo. 歌愛ユキ
$ yt-dlp --get-title UnIhRpIT7nc --add-header 'Accept-Language: es'
inabakumori - Lagtrain (Vo. Kaai Yuki) / 稲葉曇『ラグトレイン』Vo. 歌愛ユキ
```

Additionally with the (existing) channel metadata: 
```
$ yt-dlp -j UnIhRpIT7nc --add-header 'Accept-Language: en' | jq -S .channel
"inabakumori"
$ yt-dlp -j UnIhRpIT7nc --add-header 'Accept-Language: es' | jq -S .channel
"inabakumori"
```

**Pull request closed without merging**
