### PR TITLE
[extractor/niconico] Add support for like history

### PR DESCRIPTION
**Pull request by Matumo**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

This adds support for [like history](https://www.nicovideo.jp/my/history/like).

Like history URLs have the same prefix as watch history URLs.  Therefore, I fixed the regular expression of NiconicoHistoryIE (watch history extractor).  Specifically, URLs with `like` after `history/` are excluded.

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Review by pukkandan — CHANGES_REQUESTED** [review]
The whole extractor is redundant and could be easily merged into NiconicoHistoryIE. Alternately, create a base class to subclass both from

**Comment by Matumo** [comment]
Thank you.  I created a base class.

**Comment by pukkandan** [comment]
Though I suggested subclassing as an option, it's clear looking at final code that there is no point in it being a new class

**Comment by pukkandan** [comment]
pls test and let me know

**Comment by Matumo** [comment]
I agree with you.  I added IE only for checking the regular expression's correctness using the URL match test.
I tested it using my account.  The code works correctly.

**Pull request merged**
