### PR TITLE
[Porntrex] Add extractor

### LINKED ISSUE #2281: Porntrex.com videos with formats > 720p are not available to download.
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Kenya

### Example URLs

1. https://www.porntrex.com/video/1751385/african-women
2. https://www.porntrex.com/video/1793703/brija-monet-boob-bangin-brija2

### Description

Porntrex.com is being detected by the generic logger - however it is not able to get any video higher than 720p which sometimes exist. Anything below and including 720p is detected correctly.

e.g. 

### 1. https://www.porntrex.com/video/1751385/african-women has up to 1080p
```cmd
$ yt-dlp -Uv https://www.porntrex.com/video/1751385/african-women -Fj
[debug] Command-line config: ['-Uv', 'https://www.porntrex.com/video/1751385/african-women', '-Fj']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 2021-12-02-git-4a6aece703-full_build-www.gyan.dev (setts), ffprobe 2021-12-02-git-4a6aece703-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://www.porntrex.com/video/1751385/african-women
[generic] african-women: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] african-women: Downloading webpage
[generic] african-women: Extracting information
[debug] Looking for video embeds
[debug] Identified a KWS Player
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 1751385:
ID      EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
─────────────────────────────────────────────────
360p    mp4 unknown    │ https │ unknown unknown
480p    mp4 unknown    │ https │ unknown unknown
720p_HD mp4 unknown    │ https │ unknown unknown
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1751385: Downloading 1 format(s): 720p_HD
{"id": "1751385", "display_id": "african-women", "title": "African Women", "thumbnail": "https://statics.cdntrex.com/contents/videos_screenshots/1751000/1751385/preview.jpg", "formats": [{"url": "https://www.porntrex.com/get_file/4/700506bd36c65dda0673e7c63f08255ca5a8e124f0/1751000/1751385/1751385_360p.mp4/", "format_id": "360p", "ext": "mp4", "quality": 1, "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format": "360p - unknown", "resolution": null, "dynamic_range": "SDR", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Language": "en-us,en;q=0.5", "Cookie": "PHPSESSID=1d3j1mer5qr383mmt6npqep6gj; kt_ips=105.160.72.231"}}, {"url": "https://www.porntrex.com/get_file/4/00cca71401b57db7f525cb5e7267a1e569606e1355/1751000/1751385/1751385.mp4/", "format_id": "480p", "ext": "mp4", "quality": 1, "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format": "480p - unknown", "resolution": null, "dynamic_range": "SDR", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Language": "en-us,en;q=0.5", "Cookie": "PHPSESSID=1d3j1mer5qr383mmt6npqep6gj; kt_ips=105.160.72.231"}}, {"url": "https://www.porntrex.com/get_file/4/81fb45410e613565327677ac458f92c156572f4703/1751000/1751385/1751385_720p.mp4/", "format_id": "720p_HD", "ext": "mp4", "quality": 1, "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format": "720p_HD - unknown", "resolution": null, "dynamic_range": "SDR", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Language": "en-us,en;q=0.5", "Cookie": "PHPSESSID=1d3j1mer5qr383mmt6npqep6gj; kt_ips=105.160.72.231"}}], "webpage_url": "https://www.porntrex.com/video/1751385/african-women", "original_url": "https://www.porntrex.com/video/1751385/african-women", "webpage_url_basename": "african-women", "webpage_url_domain": "porntrex.com", "extractor": "generic", "extractor_key": "Generic", "playlist": null, "playlist_index": null, "thumbnails": [{"url": "https://statics.cdntrex.com/contents/videos_screenshots/1751000/1751385/preview.jpg", "id": "0"}], "requested_subtitles": null, "__has_drm": false, "url": "https://www.porntrex.com/get_file/4/81fb45410e613565327677ac458f92c156572f4703/1751000/1751385/1751385_720p.mp4/", "format_id": "720p_HD", "ext": "mp4", "quality": 1, "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format": "720p_HD - unknown", "resolution": null, "dynamic_range": "SDR", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Language": "en-us,en;q=0.5", "Cookie": "PHPSESSID=1d3j1mer5qr383mmt6npqep6gj; kt_ips=105.160.72.231"}, "fulltitle": "African Women", "epoch": 1641748263, "_filename": "African Women [1751385].mp4", "filename": "African Women [1751385].mp4", "urls": "https://www.porntrex.com/get_file/4/81fb45410e613565327677ac458f92c156572f4703/1751000/1751385/1751385_720p.mp4/"}
```
Cleaned up json

```json
{
  "id": "1751385",
  "display_id": "african-women",
  "title": "African Women",
  "thumbnail": "https://statics.cdntrex.com/contents/videos_screenshots/1751000/1751385/preview.jpg",
  "formats": [
    {
      "url": "https://www.porntrex.com/get_file/4/700506bd36c65dda0673e7c63f08255ca5a8e124f0/1751000/1751385/1751385_360p.mp4/",
      "format_id": "360p",
      "ext": "mp4",
      "quality": 1,
      "protocol": "https",
      "video_ext": "mp4",
      "audio_ext": "none",
      "format": "360p - unknown",
      "resolution": null,
      "dynamic_range": "SDR",
      "http_headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-us,en;q=0.5",
        "Cookie": "PHPSESSID=1d3j1mer5qr383mmt6npqep6gj; kt_ips=105.160.72.231"
      }
    },
    {
      "url": "https://www.porntrex.com/get_file/4/00cca71401b57db7f525cb5e7267a1e569606e1355/1751000/1751385/1751385.mp4/",
      "format_id": "480p",
      "ext": "mp4",
      "quality": 1,
      "protocol": "https",
      "video_ext": "mp4",
      "audio_ext": "none",
      "format": "480p - unknown",
      "resolution": null,
      "dynamic_range": "SDR",
      "http_headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-us,en;q=0.5",
        "Cookie": "PHPSESSID=1d3j1mer5qr383mmt6npqep6gj; kt_ips=105.160.72.231"
      }
    },
    {
      "url": "https://www.porntrex.com/get_file/4/81fb45410e613565327677ac458f92c156572f4703/1751000/1751385/1751385_720p.mp4/",
      "format_id": "720p_HD",
      "ext": "mp4",
      "quality": 1,
      "protocol": "https",
      "video_ext": "mp4",
      "audio_ext": "none",
      "format": "720p_HD - unknown",
      "resolution": null,
      "dynamic_range": "SDR",
      "http_headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-us,en;q=0.5",
        "Cookie": "PHPSESSID=1d3j1mer5qr383mmt6npqep6gj; kt_ips=105.160.72.231"
      }
    }
  ],
  "webpage_url": "https://www.porntrex.com/video/1751385/african-women",
  "original_url": "https://www.porntrex.com/video/1751385/african-women",
  "webpage_url_basename": "african-women",
  "webpage_url_domain": "porntrex.com",
  "extractor": "generic",
  "extractor_key": "Generic",
  "playlist": null,
  "playlist_index": null,
  "thumbnails": [
    {
      "url": "https://statics.cdntrex.com/contents/videos_screenshots/1751000/1751385/preview.jpg",
      "id": "0"
    }
  ],
  "requested_subtitles": null,
  "__has_drm": false,
  "url": "https://www.porntrex.com/get_file/4/81fb45410e613565327677ac458f92c156572f4703/1751000/1751385/1751385_720p.mp4/",
  "format_id": "720p_HD",
  "ext": "mp4",
  "quality": 1,
  "protocol": "https",
  "video_ext": "mp4",
  "audio_ext": "none",
  "format": "720p_HD - unknown",
  "resolution": null,
  "dynamic_range": "SDR",
  "http_headers": {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "en-us,en;q=0.5",
    "Cookie": "PHPSESSID=1d3j1mer5qr383mmt6npqep6gj; kt_ips=105.160.72.231"
  },
  "fulltitle": "African Women",
  "epoch": 1641748263,
  "_filename": "African Women [1751385].mp4",
  "filename": "African Women [1751385].mp4",
  "urls": "https://www.porntrex.com/get_file/4/81fb45410e613565327677ac458f92c156572f4703/1751000/1751385/1751385_720p.mp4/"
}
```

### 2. https://www.porntrex.com/video/1793703/brija-monet-boob-bangin-brija2 has up to 2160p

```cmd
$ yt-dlp -Uv https://www.porntrex.com/video/1276932/hot-babe-oily-teasing -Fj
[debug] Command-line config: ['-Uv', 'https://www.porntrex.com/video/1276932/hot-babe-oily-teasing', '-Fj']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 2021-12-02-git-4a6aece703-full_build-www.gyan.dev (setts), ffprobe 2021-12-02-git-4a6aece703-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://www.porntrex.com/video/1276932/hot-babe-oily-teasing
[generic] hot-babe-oily-teasing: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] hot-babe-oily-teasing: Downloading webpage
[generic] hot-babe-oily-teasing: Extracting information
[debug] Looking for video embeds
[debug] Identified a KWS Player
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 1276932:
ID      EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
─────────────────────────────────────────────────
360p    mp4 unknown    │ https │ unknown unknown
480p    mp4 unknown    │ https │ unknown unknown
720p_HD mp4 unknown    │ https │ unknown unknown
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1276932: Downloading 1 format(s): 720p_HD
{"id": "1276932", "display_id": "hot-babe-oily-teasing", "title": "Hot Babe Oily Teasing", "thumbnail": "https://statics.cdntrex.com/contents/videos_screenshots/1276000/1276932/preview.jpg", "formats": [{"url": "https://www.porntrex.com/get_file/6/dc89caaff64c97309d9b840bdd6f85d43d71ad7333/1276000/1276932/1276932_360p.mp4/", "format_id": "360p", "ext": "mp4", "quality": 1, "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format": "360p - unknown", "resolution": null, "dynamic_range": "SDR", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Language": "en-us,en;q=0.5", "Cookie": "PHPSESSID=t4kob4vovlpnm27i6qe99pa730; kt_ips=105.160.72.231"}}, {"url": "https://www.porntrex.com/get_file/6/4523c828cab3cdb71d7f690419dbb72e204e65756b/1276000/1276932/1276932.mp4/", "format_id": "480p", "ext": "mp4", "quality": 1, "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format": "480p - unknown", "resolution": null, "dynamic_range": "SDR", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Language": "en-us,en;q=0.5", "Cookie": "PHPSESSID=t4kob4vovlpnm27i6qe99pa730; kt_ips=105.160.72.231"}}, {"url": "https://www.porntrex.com/get_file/6/41101b5bc52b11e9d64554ea52ad3131f960d30df9/1276000/1276932/1276932_720p.mp4/", "format_id": "720p_HD", "ext": "mp4", "quality": 1, "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format": "720p_HD - unknown", "resolution": null, "dynamic_range": "SDR", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Language": "en-us,en;q=0.5", "Cookie": "PHPSESSID=t4kob4vovlpnm27i6qe99pa730; kt_ips=105.160.72.231"}}], "webpage_url": "https://www.porntrex.com/video/1276932/hot-babe-oily-teasing", "original_url": "https://www.porntrex.com/video/1276932/hot-babe-oily-teasing", "webpage_url_basename": "hot-babe-oily-teasing", "webpage_url_domain": "porntrex.com", "extractor": "generic", "extractor_key": "Generic", "playlist": null, "playlist_index": null, "thumbnails": [{"url": "https://statics.cdntrex.com/contents/videos_screenshots/1276000/1276932/preview.jpg", "id": "0"}], "requested_subtitles": null, "__has_drm": false, "url": "https://www.porntrex.com/get_file/6/41101b5bc52b11e9d64554ea52ad3131f960d30df9/1276000/1276932/1276932_720p.mp4/", "format_id": "720p_HD", "ext": "mp4", "quality": 1, "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format": "720p_HD - unknown", "resolution": null, "dynamic_range": "SDR", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Language": "en-us,en;q=0.5", "Cookie": "PHPSESSID=t4kob4vovlpnm27i6qe99pa730; kt_ips=105.160.72.231"}, "fulltitle": "Hot Babe Oily Teasing", "epoch": 1641748588, "_filename": "Hot Babe Oily Teasing [1276932].mp4", "filename": "Hot Babe Oily Teasing [1276932].mp4", "urls": "https://www.porntrex.com/get_file/6/41101b5bc52b11e9d64554ea52ad3131f960d30df9/1276000/1276932/1276932_720p.mp4/"}
```

cleaned up json

```json
{
  "id": "1276932",
  "display_id": "hot-babe-oily-teasing",
  "title": "Hot Babe Oily Teasing",
  "thumbnail": "https://statics.cdntrex.com/contents/videos_screenshots/1276000/1276932/preview.jpg",
  "formats": [
    {
      "url": "https://www.porntrex.com/get_file/6/dc89caaff64c97309d9b840bdd6f85d43d71ad7333/1276000/1276932/1276932_360p.mp4/",
      "format_id": "360p",
      "ext": "mp4",
      "quality": 1,
      "protocol": "https",
      "video_ext": "mp4",
      "audio_ext": "none",
      "format": "360p - unknown",
      "resolution": null,
      "dynamic_range": "SDR",
      "http_headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-us,en;q=0.5",
        "Cookie": "PHPSESSID=t4kob4vovlpnm27i6qe99pa730; kt_ips=105.160.72.231"
      }
    },
    {
      "url": "https://www.porntrex.com/get_file/6/4523c828cab3cdb71d7f690419dbb72e204e65756b/1276000/1276932/1276932.mp4/",
      "format_id": "480p",
      "ext": "mp4",
      "quality": 1,
      "protocol": "https",
      "video_ext": "mp4",
      "audio_ext": "none",
      "format": "480p - unknown",
      "resolution": null,
      "dynamic_range": "SDR",
      "http_headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-us,en;q=0.5",
        "Cookie": "PHPSESSID=t4kob4vovlpnm27i6qe99pa730; kt_ips=105.160.72.231"
      }
    },
    {
      "url": "https://www.porntrex.com/get_file/6/41101b5bc52b11e9d64554ea52ad3131f960d30df9/1276000/1276932/1276932_720p.mp4/",
      "format_id": "720p_HD",
      "ext": "mp4",
      "quality": 1,
      "protocol": "https",
      "video_ext": "mp4",
      "audio_ext": "none",
      "format": "720p_HD - unknown",
      "resolution": null,
      "dynamic_range": "SDR",
      "http_headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-us,en;q=0.5",
        "Cookie": "PHPSESSID=t4kob4vovlpnm27i6qe99pa730; kt_ips=105.160.72.231"
      }
    }
  ],
  "webpage_url": "https://www.porntrex.com/video/1276932/hot-babe-oily-teasing",
  "original_url": "https://www.porntrex.com/video/1276932/hot-babe-oily-teasing",
  "webpage_url_basename": "hot-babe-oily-teasing",
  "webpage_url_domain": "porntrex.com",
  "extractor": "generic",
  "extractor_key": "Generic",
  "playlist": null,
  "playlist_index": null,
  "thumbnails": [
    {
      "url": "https://statics.cdntrex.com/contents/videos_screenshots/1276000/1276932/preview.jpg",
      "id": "0"
    }
  ],
  "requested_subtitles": null,
  "__has_drm": false,
  "url": "https://www.porntrex.com/get_file/6/41101b5bc52b11e9d64554ea52ad3131f960d30df9/1276000/1276932/1276932_720p.mp4/",
  "format_id": "720p_HD",
  "ext": "mp4",
  "quality": 1,
  "protocol": "https",
  "video_ext": "mp4",
  "audio_ext": "none",
  "format": "720p_HD - unknown",
  "resolution": null,
  "dynamic_range": "SDR",
  "http_headers": {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "en-us,en;q=0.5",
    "Cookie": "PHPSESSID=t4kob4vovlpnm27i6qe99pa730; kt_ips=105.160.72.231"
  },
  "fulltitle": "Hot Babe Oily Teasing",
  "epoch": 1641748588,
  "_filename": "Hot Babe Oily Teasing [1276932].mp4",
  "filename": "Hot Babe Oily Teasing [1276932].mp4",
  "urls": "https://www.porntrex.com/get_file/6/41101b5bc52b11e9d64554ea52ad3131f960d30df9/1276000/1276932/1276932_720p.mp4/"
}
```

### Verbose log

```shell
$ yt-dlp -Uv https://www.porntrex.com/video/1751385/african-women
[debug] Command-line config: ['-Uv', 'https://www.porntrex.com/video/1751385/african-women']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 2021-12-02-git-4a6aece703-full_build-www.gyan.dev (setts), ffprobe 2021-12-02-git-4a6aece703-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://www.porntrex.com/video/1751385/african-women
[generic] african-women: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] african-women: Downloading webpage
[generic] african-women: Extracting information
[debug] Looking for video embeds
[debug] Identified a KWS Player
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1751385: Downloading 1 format(s): 720p_HD
[debug] Invoking downloader on "https://www.porntrex.com/get_file/4/81fb45410e613565327677ac458f92c156572f4703/1751000/1751385/1751385_720p.mp4/"
[download] Destination: African Women [1751385].mp4
[download]   0.0% of 1.01GiB at 110.59KiB/s ETA 02:39:47
ERROR: Interrupted by user


[debug] Command-line config: ['-Uv', 'https://www.porntrex.com/video/1276932/hot-babe-oily-teasing']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 2021-12-02-git-4a6aece703-full_build-www.gyan.dev (setts), ffprobe 2021-12-02-git-4a6aece703-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://www.porntrex.com/video/1276932/hot-babe-oily-teasing
[generic] hot-babe-oily-teasing: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] hot-babe-oily-teasing: Downloading webpage
[generic] hot-babe-oily-teasing: Extracting information
[debug] Looking for video embeds
[debug] Identified a KWS Player
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1276932: Downloading 1 format(s): 720p_HD
[debug] Invoking downloader on "https://www.porntrex.com/get_file/6/41101b5bc52b11e9d64554ea52ad3131f960d30df9/1276000/1276932/1276932_720p.mp4/"
[download] Destination: Hot Babe Oily Teasing [1276932].mp4
[download]   1.5% of 66.06MiB at 892.14KiB/s ETA 01:14
ERROR: Interrupted by user
```

### PR DESCRIPTION
**Pull request by trassshhub**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Add extractor for porntrex.com (closes #2281)

### CODE REVIEW

**Comment by nindogo** [comment]
1. Thanks
2. Why a whole new extractor? My suspicion is that the generic one could be changed and be able to download videos with resolution more than 720p. This solution may help other sites that are not yet supported ....

**Comment by trassshhub** [comment]
After looking into the generic extractor code, I believe you are right. I was reinventing the wheel. I will try to fix the generic extractor and do another PR.

**Comment by trassshhub** [comment]
I am going to close this PR and focus on fixing the generic extractor as mine is much inferior.

**Comment by pukkandan** [comment]
If you are modifying the generic extractor, the code should have generic use in other websites. Otherwise, keep the new extractor

**Comment by trassshhub** [comment]
My code was doing the same thing (extracting Kvs player data) as the generic extractor, and I can see at least 1 issue in there causing it not to extract all videos.

I will be make sure it will still pass the existing tests before submitting the PR. Otherwise, I will re-submit this one.

**Comment by pukkandan** [comment]
FYI: The test requirements were made stricter recently, so some of the existing tests may complain about missing metadata fields

**Comment by trassshhub** [comment]
not sure if I should continue the discussion here or not, but here are my findings:

https://github.com/yt-dlp/yt-dlp/blob/e9a6a65a555b3c7234bd10f16a8df96dfc2d923a/yt_dlp/extractor/generic.py#L3778
Current code hardcoded to look for the first 3 formats only, causing #2281

https://github.com/yt-dlp/yt-dlp/blob/e9a6a65a555b3c7234bd10f16a8df96dfc2d923a/yt_dlp/extractor/generic.py#L3785

From a few Tests urls, I found that all video urls ends with “.mp4/“. Current regexp fails to extract height when there is no parameter after the slash.
I.e. correct regexp should be r'%s_(\d+)p\.mp4/(?:[?].*)?$'
or for better compatibility r'%s_(\d+)p\.mp4/?(?:[?].*)?$'

**Pull request closed without merging**
