### PR TITLE
[Niconico] Added Nico Search Extractor

### PR DESCRIPTION
**Pull request by animelover1984**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This PR adds a search extractor and search URL extractor for niconico.

### CODE REVIEW

**Comment by animelover1984** [comment]
For context, Niconico doesn't expose search results beyond 50 pages, so I need to recursively divide the search range until I find spans that don't have 50 pages (the max number of pages).
I attempted to fetch pages on-demand with a generator, and I think I succeeded. Suggestions are welcome!

**Comment by dirkf** [comment]
Can anyone explain how the test for `NicovideoSearchDateIE` ends up with 1610 videos (only) when the same thing in the site page (ie `https://www.nicovideo.jp/search/a?start=2007-01-01&end=2021-12-06&sort=f&order=d`) shows `Found 922,877 videos containing a`?

I'd like to get that working in my yt-dl back-port but am stumped as to the break criteria (the other extractors appear to be working). Currently it looks like it wants to show all ~1M videos promised on the browser page.

I couldn't see anything in the yt-dlp `SearchInfoExtractor` that might be different.  Obviously the significant thing I've had to change in this extractor are the multiple levels of `yield from` in the search extractors.

**Comment by pukkandan** [comment]
@dirkf This is the commit responsible for making sure tests exit early 6911e11edd581392ca1f0688b78787716ec235e9. Though this may/maynot depend on other changes I have made to the core program - honestly can't remember

**Comment by dirkf** [comment]
Completely sorted the problem, many thanks; also, a good mod in itself.

**Pull request merged**
