### PR TITLE
Check OSError when importing cryptodome

### PR DESCRIPTION
**Pull request by DUOLabs333**
(The module may exist, but the so files might not).

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by coletdjnz** [comment]
> (The module may exist, but the so files might not).

Do you know why this happens? This sounds like an issue with your installation? :confused:

**Comment by DUOLabs333** [comment]
No, I intentionally did that (I want to avoid C dependencies when possible. So, I want to set up a venv with yt-dlp without any non-Python dependencies).

**Comment by pukkandan** [comment]
Why would you intentionally install a dependency improperly and expect us to handle that case? If you don't want the dependency, just don't install it at all

**Comment by DUOLabs333** [comment]
Or, there you can offer Cryptodome, mutagen, etc., as optional dependencies, which can be installed as `yt_dlp[full]`.

**Comment by pukkandan** [comment]
Most people would prefer to have these dependencies when just doing `pip install yt-dlp`. If https://github.com/pypa/setuptools/issues/1139 was a thing, I would have put them behind extras. But unfortunately, pip does not currently provide a way to setup recommended/default dependencies.

Since yt-dlp has no mandatory dependencies at all, putting everything behind an extra only makes it harder for newbies with no real benefit. You can simply use `--no-deps` instead

**Pull request closed without merging**
