### PR TITLE
Warn of less data also, for --flat-playlist

### PR DESCRIPTION
**Pull request by jidanni**
Must mention side effects.

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADD DESCRIPTION HERE

Fixes #
Users assume the same data is fetched with --flat-playlist.
Only the .webm etc. aren't fetched.

Now we alert the users that this is not the case!

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by jidanni** [comment]
Or say "less metadata is fetched".

**Comment by pukkandan** [comment]
1. This is autogenerated from options.py
2. Didn't you already open an issue for this before?
3. This is what "don't extract" already means.

**Comment by jidanni** [comment]
1. OK, I wish there was a warning. I assumed that I was editing the source, not the destination. We see `<!-- ...` but that should also say 'do not edit.'
2. I can't find that other issue either today. Anyway, that issue is just a side effect of this issue.
3. >  "Don't extract video metadata from playlists" to clarify what "extract" means? Would that be satisfactory?

I want to have the man page communicate:
- don't fetch videos themselves
- don't fetch the metadata that comes with those videos

Saying "extract" seems like "we fetched it, but didn't extract it from what we fetched."

**Comment by Grub4K** [comment]
I think this is a common misconception of how yt-dl works. A job of the so called extractors is to "extract" data from a webpage into the info dictionary. This is the definition of extract. We have however not communicated this clearly in the readme, and should probably clarify the terminoligy and how the project works in general

**Comment by pukkandan** [comment]
@Grub4K Do you have any concrete suggestions on how to improve this?

**Comment by jidanni** [comment]
Hmm at the top of the man page / readme, you could have a section called 'let's get some definitions straight'..

Or, skip trying to establish definitions and just keep with common English each time. Especially as people will be reading things out of context and will still encounter the funny word usage.
So instead of saying "extract"  say the longer version...

**Comment by bashonly** [comment]
```diff
diff --git a/yt_dlp/options.py b/yt_dlp/options.py
index 6c6a0b3f9..930d9d4be 100644
--- a/yt_dlp/options.py
+++ b/yt_dlp/options.py
@@ -419,7 +419,9 @@ def _alias_callback(option, opt_str, value, parser, opts, nargs):
     general.add_option(
         '--flat-playlist',
         action='store_const', dest='extract_flat', const='in_playlist', default=False,
-        help='Do not extract the videos of a playlist, only list them')
+        help=(
+            'Do not extract a playlist\'s URL result entries; '
+            'some entry metadata may be missing and downloading may be bypassed'))
     general.add_option(
         '--no-flat-playlist',
         action='store_false', dest='extract_flat',
```

**Pull request closed without merging**
