### PR TITLE
disable --mtime by default

### PR DESCRIPTION
**Pull request by flisk**
the mtime of a file normally reflects the last modification time of the file on disk rather than what the contents of the file represent. yt-dlp goes against this convention by default, which can cause issues when users don't know about yt-dlp's special mtime behavior, e.g. premature deletion of files by cleanup scripts or time-based file searches.

instead of behaving in this unconventional way by default, yt-dlp should not modify the mtime of its output files unless the user specifically asks for that.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by flisk** [comment]
ah, my bad. i was under the assumption that youtube-dl was superseded by this project. in that case, i'll direct the patch at upstream.

**Comment by pukkandan** [comment]
I don't think they will change it either. Both projects try their best to maintain backward compatibility

**Comment by dirkf** [comment]
I don't think this default that has been in place "forever" can be changed.

Perhaps it is the case that there is a subset of users who care and want `--no-mtime` to be the default, and everyone else would be pleasantly surprised by the change, if they noticed at all. I doubt it.

Historically, yt-dl seems to have followed _wget_ in its CLI design. As was pointed out in https://github.com/ytdl-org/youtube-dl/issues/1709, _wget_ has a similar option:
```
       --no-use-server-timestamps
           Don't set the local file's timestamp by the one on the server.

           By default, when a file is downloaded, its timestamps are set to
           match those from the remote file. This allows the use of
           --timestamping on subsequent invocations of wget. However, it is
           sometimes useful to base the local file's timestamp on when it was
           actually downloaded; for that purpose, the
           --no-use-server-timestamps option has been provided.
```
But we don't seem to have added the `--timestamping` function.

**Comment by dirkf** [comment]
And yt-dlp already has the `--mtime` option that I intend to add to yt-dl.

**Pull request closed without merging**
