### PR TITLE
Termux and pycryptodomex

### PR DESCRIPTION
**Pull request by rofrol**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature
- [x] Documentation

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by nyuszika7h** [comment]
Technically, the Play Store version of Termux warns you that it's outdated, so it's not really our job to tell users to install from F-Droid IMO.

**Comment by rofrol** [comment]
> Technically, the Play Store version of Termux warns you that it's outdated, so it's not really our job to tell users to install from F-Droid IMO.

What if some user has outdated Termux from Google Play? I saw some people have problems with `pkg update` https://stackoverflow.com/questions/67647518/i-want-to-ask-how-to-fix-this-termux-repository/68881710#68881710

**Comment by pukkandan** [comment]
I am not going to add instructions on how to update your environment. Should I also teach users how to install python? While we are at it, why not also add instructions on how to install and update windows

**Comment by rofrol** [comment]
So why there are false instruction about pycryptodomex?

Do you want me to modify this PR?

**Pull request closed without merging**
