### PR TITLE
[extractor/rutube] Add extraction of chapters from description

### PR DESCRIPTION
**Pull request by mushbite**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

This allows to extract chapters (timecodes) from a video description. Youtube parser is reused for the extraction.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x]  At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x]  [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x]  Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x]  I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by pukkandan** [comment]
Give example URL. Does the site itself mark chapters?

**Comment by mushbite** [comment]
> Give example URL. Does the site itself mark chapters?

I tested it like this:
./yt-dlp.sh -f worst --add-metadata https://rutube.ru/video/c65b465ad0c98c89f3b25cb03dcc87c6/

Yes, the website marks chapters on timeline. Timecodes in the description are clickable and allow to jump to a chapter.

Here is a video WITHOUT chapters. Absense of chapters doesn't cause any errors.
https://rutube.ru/video/492c8d83a560274fa309ebf1e5db2fa7/

**Comment by pukkandan** [comment]
Could you move _extract_chapters_from_description to common.py? Creating a YoutubeIE for it is not good impl.
Also, pls add a test

**Comment by mushbite** [comment]
Ok, I've moved it. Could you help me with the test? I made a full-text search for 'rutube' in the yt-dlp dir, but I couldn't find any test files to complement. I also tried to run the test as advised in the developer instructions:
> python3 test/test_download.py TestDownload.test_rutube
E
======================================================================
ERROR: test_rutube (unittest.loader._FailedTest)
>\----------------------------------------------------------------------
AttributeError: type object 'TestDownload' has no attribute 'test_rutube'

>\----------------------------------------------------------------------
Ran 1 test in 0.000s

>FAILED (errors=1)

Moreover, I get the same result for youtube:
> python3 test/test_download.py TestDownload.test_youtube

**Comment by bashonly** [comment]
IE name is case-sensitive:
```
python3 test/test_download.py TestDownload.test_Rutube
python3 test/test_download.py TestDownload.test_Rutube_1
...
python3 test/test_download.py TestDownload.test_Youtube
```

**Comment by mushbite** [comment]
Ok, the tests are in extractors files. I added my test (test_Rutube_2), but it causes this error:

> Unable to download f4m manifest: HTTP Error 404: Not Found

test_Rutube and test_Rutube_1 cause the same error.

**Comment by bashonly** [comment]
> Ok, the tests are in extractors files. I added my test (test_Rutube_2), but it causes this error:
>    `Unable to download f4m manifest: HTTP Error 404: Not Found`
> test_Rutube and test_Rutube_1 cause the same error.

`_extract_f4m_formats` is `fatal=False`, so you could add `'expected_warnings': ['Unable to download f4m']` to the tests so that they pass. Or you could investigate to see if f4m formats actually still exist for any videos

**Comment by mushbite** [comment]
Now it passes all tests.
I couldn't find a video with f4m format using yt-dlp -F ... It seems that all videos have uniform set of formats.

**Pull request merged**
