### PR TITLE
Updated README.md with a new output format example

### PR DESCRIPTION
**Pull request by iamdebajyoti**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Documentation update 
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Updated README.md with a new output format example.
This is basically a documentation update with a new output format template and an associated example.

### CODE REVIEW

**Comment by iamdebajyoti** [comment]
@pukkandan 
To answer your question - I had mentioned that as the comment ---
_Download YouTube playlist videos in separate directory without indexed by the video order of the playlist **but suffixed with the video id**_

Please reopen and merge it. I was on vacation - hence could not respond.

**Comment by iamdebajyoti** [comment]
@pukkandan
To answer your question - I had mentioned that as the comment ---

Download YouTube playlist videos in separate directory without indexed by the video order of the playlist but suffixed with the video id

None of existing examples cover this part.

Please reopen and merge it. I was on vacation - hence could not respond.
________________________________

**Comment by pukkandan** [comment]
> Download YouTube playlist videos in separate directory without indexed by the video order of the playlist but suffixed with the video id
None of existing examples cover this part.

Should I also add examples for all possible combinations of all the fields!? 😕

The current examples demonstrate everything you need to know to construct this

**Comment by Ashish0804** [comment]
True spirit of opensource is `If don't like it, you fork it`

**Pull request closed without merging**
