### PR TITLE
Lookup order of .netrc on windows

### LINKED ISSUE #792: yt-dlp ignores my %HOME% variable and insist .netrc to be in my %USERPROFILE% folder
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

```

## Description

Today I've switched from youtube-dl to yt-dlp and some of my videos stopped working. After inspection I've realized that yt-dlp ignores my %HOME% variable and insist .netrc to be in my %USERPROFILE% folder. Please fix this.

### PR DESCRIPTION
**Pull request by sulyi**
### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Due to changes introduced in python 3.8, it no longer uses "%HOME%". 
For required compatibility first existence of "%HOME%\.netrc" is checked.

No upstream solution.

This is untested!

closes #792

### CODE REVIEW

**Comment by letmeindude** [comment]
Could you make yt-dlp look for .netrc in its own folder like it already looks for yt-dlp.conf?
This would be really great for portability. Thank you.

**Comment by sulyi** [comment]
Help, test is needed,

neither `test_netrc test_options test_verbose_output` nor any test case in `test_download` hits this code.

**Comment by sulyi** [comment]
Lookup order should be [`yt-dlp.conf` location, `%HOME%`, `%HOMEDRIVE%\%HOMEPOROFILE%`]

Following snippet can be used to trigger changed code:
```py
from test.helper import FakeYDL
from yt_dlp.extractor.common import InfoExtractor


class DummyIE(InfoExtractor):
    pass


DummyIE(FakeYDL({'usenetrc': True}))._get_netrc_login_info('github.com')

```

Please, report whether it works or not.

**Comment by pukkandan** [comment]
#792 has been fixed by https://github.com/yt-dlp/yt-dlp/commit/c589c1d3956cb9a8655e8555f2e02f14fbca8a2e, https://github.com/yt-dlp/yt-dlp/commit/0001fcb586c3ab297cd48c77ddd6f5d40546dac4

**Pull request closed without merging**
