### PR TITLE
GNU-style release SHA512 sums

### PR DESCRIPTION
**Pull request by nihil-admirari**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
SHA256 provided with the release cannot be verified using standard Linux tools:
```bash
$ sha256sum -c SHA2-256SUMS
sha256sum: SHA2-256SUMS: no properly formatted SHA256 checksum lines found
```

The reason is two-fold:
1. `file:hash` is not a standard checksum syntax, `coreutils` understands only GNU `hash  file` or BSD `SHA256(file) = hash` styles.
2. For some reason, `SHA2-256SUMS` has Windows line endings, not Unix ones.

Version line is immaterial and will simply generate a warning:
```
sha256sum: WARNING: 1 line is improperly formatted
```

P.S. Consider signing releases with GPG, just like the original fork does: https://github.com/ytdl-org/youtube-dl/releases/download/2021.06.06/youtube-dl.sig.

### CODE REVIEW

**Comment by pukkandan** [comment]
The updater depends on this format. To apply your PR, first the updater has to be modified to handle this new format (while also keeping support for the old format), hope most people update in a reasonable amount of time and then change the GHA. It would be much easier to just add another file with this new style instead.

As for the new lines, the SHA file was being built by windows machine previously. I only recently split it into a separate action and made it `ubuntu-latest` while removing py2. So the sed replace should not be necessary

> Consider signing releases with GPG, just like the original fork does

I am not sure how to sign in github actions, but I'll look into it.

**Comment by fstirlitz** [comment]
I guess you’ll have to commit an encrypted private key, then store the passphrase as a repository secret and use it to unlock the key when signing. (The passphrase should be a long random string, but I think you already know that.) And keep a key revocation certificate at the ready, just in case something happens.

**Comment by pukkandan** [comment]
> I guess you’ll have to commit an encrypted private key, then store the passphrase as a repository secret and use it to unlock the key when signing. (The passphrase should be a long random string, but I think you already know that.) 

Why not add the private key itself as the secret?

**Comment by fstirlitz** [comment]
Actually, this could work too. I guess I’m just used to the model where repository secrets can only store one line of text, but GitHub allows multiline secrets as well.

**Comment by nihil-admirari** [comment]
> It would be much easier to just add another file with this new style instead.
Ok. Switched to creating a parallel `SHA2-512SUMS` instead.

**Comment by pukkandan** [comment]
Sorry for the force push. I first merged the branch with my local tip instead of origin/master

**Comment by nihil-admirari** [comment]
> To apply your PR, first the updater has to be modified to handle this new format (while also keeping support for the old format), hope most people update in a reasonable amount of time and then change the GHA.

Looks like no one will have much trouble updating even a very old version:
```py
hashes = list(map(lambda x: x.split(':'), hash_data.splitlines()))
return next((i[1] for i in hashes if i[0] == 'yt-dlp%s' % label), None)
```
will always return `None` for GNU-style hash without crashing: hash lines have no colons, so `i[0]` test will simply never succeed. When a hash cannot be found, `exe` update [issues a warning](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/update.py#L181), while `zip`-file update [doesn't even warn](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/update.py#L223)!

Looks like the `version:` line is not used by the updater (and even if it needs a version, it's always available in GitHub's JSON). `sha256sum` would warn on that line too. So I decided to use `version:` as a format differentiator: if it's present—colon format is assumed, if it's absent—GNU style is assumed. Currently colon branch is always taken.

May I suggest that in the future, when a substantial number of people have updated their `yt-dlp`s (even if they didn't, the maximum they'll get is a warning), the format of `SHA2-256SUMS` be changed to a proper GNU style, which validates cleanly without a warning (i.e. has no `version:` line). Of course, if you don't like that suggestion, you may simply avoid cherry-picking the last commit in this branch.

**Comment by pukkandan** [comment]
> Looks like no one will have much trouble updating even a very old version:
> will always return None for GNU-style hash without crashing: hash lines have no colons, so i[0] test will simply never succeed.

great

> while zip-file update doesn't even warn!

fixed

> Looks like the version: line is not used by the updater

Correct

> sha256sum would warn on that line too. So I decided to use version: as a format differentiator: if it's present—colon format is assumed, if it's absent—GNU style is assumed. Currently colon branch is always taken.

This is good

> May I suggest that in the future, when a substantial number of people have updated their `yt-dlp`s (even if they didn't, the maximum they'll get is a warning), the format of `SHA2-256SUMS` be changed to a proper GNU style, which validates cleanly without a warning (i.e. has no `version:` line)

Yes, of course. The current hashfile structure is due to youtube-dlc. I don't mind changing it eventually to stay compliant to the UNIX standards. My only concern was the updater. But now that it is a non-issue, I have no reservations in changing it. But, I'd rather not have everyone updating get hit by the warning right away. So we wont make the change right now.

If I forget to get back to this in a month or so, feel free to remind me again

---

I have pushed some changes. Let me know what you think of them. I am going to sleep rn. If there are no more changes needed, I can merge it tomorrow

**Comment by nihil-admirari** [comment]
> I have pushed some changes. Let me know what you think of them.

I'm totally fine with your changes.

> If I forget to get back to this in a month or so, feel free to remind me again

Let's create an issue to track it: https://github.com/yt-dlp/yt-dlp/issues/385.

**Pull request merged**
