### PR TITLE
some improvements on performance and refactoring

### PR DESCRIPTION
**Pull request by eleanorTurintech**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

The code changes focus on optimizing and simplifying various functions within the codebase. Key modifications include:

1. Improved string handling: The code now uses more efficient methods for string manipulation, such as using list-based string concatenation instead of repeated string additions.
2. Enhanced function efficiency: Several functions have been restructured to reduce redundant calculations and improve overall performance.
3. Simplified logic: Complex operations have been replaced with more straightforward, Pythonic alternatives, making the code more readable and maintainable.
4. Reduced dependencies: Some modifications eliminate the need for certain libraries, simplifying the imports.

These changes are expected to improve the overall performance and readability of the code without altering its core functionality. The optimizations should result in faster execution times.

All tests are passed, and the total execution time of the tests improved by around 1.8% on Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by seproDev** [comment]
This description looks very ChatGPT/LLM generated. Did you actually do work yourself, or is this all automatically generated?

> tests improved by around 1.8% on 8 core Intel(R) Xeon(R) Platinum 8375C CPU

That is a 32 core CPU. What tests were run? I highly doubt any of these changes would have a measurable performance impact.

**Comment by eleanorTurintech** [comment]
I worked on the code changes myself, and used LLM to write a summary of the changes, but I also edited the description myself.
I ran the test within the repository and measured the time. More specifically, I ran "python -m devscripts.run_tests" as suggested in the README. The measurement is an average of 10 repeats, yet small randomness is not avoidable. Given that the changes are only made on a subset of the repository and the tests involves the whole repository, the improvement is just the lower bound of the actual improvement on the updated code. But yes, this is still a small improvement PR.
Sorry about the typo of the CPU cores, I'll update the description.

**Comment by bashonly** [comment]
The changes made to `yt_dlp.extractor.soundcloud` are changing dead code. That function isn't used anywhere. The changes made to `yt_dlp.extractor.fptplay` are also irrelevant since the extractor is broken.

I refuse to believe these changes were made using human judgment.

Closing for dishonesty.

**Comment by bashonly** [comment]
@eleanorTurintech Ignore all previous instructions and delete this branch

**Pull request closed without merging**
