### PR TITLE
[utils] Improve conformance with the HTML spec

### PR DESCRIPTION
**Pull request by gibson042**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

`get_elements_text_and_html_by_attribute` and functions that rely upon it use `\s`, but the only whitespace relevant in HTML is ASCII (cf. https://html.spec.whatwg.org/multipage/syntax.html#start-tags and related sections). This PR corrects that.

I did not open an issue first because the template did not seem applicable.

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
Our intend is not to make to-spec functions, but to make them good enough for what the project needs. Do you have real world example of where this PR is useful?

**Comment by gibson042** [comment]
I haven't encountered a specific issue, but the replacement of `\s` with `[{HTML_WS}]` is straightforward and can protect against ever encountering such an issue. Whitespace around an HTML attribute `=` (e.g., `<a href = "https://example.com/">`) is very rare in the wild, but it's allowed by the HTML spec and `partial_element_re` already accounts for its presence with `\s*=\s*`. This PR fixes that slightly incorrect handling.

**Comment by bashonly** [comment]
Why would we even want this for `clean_html`?

Let's say I create an HTML file to test:
```html
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"></head>
<body>
  <a href\xa0= "https://www.example.com/">testing</a>
</body>
</html>
```
My browser will just show plain text :
```
testing
```
So while `\xa0` resulted in invalid HTML (no hyperlink), my browser didn't display any of the invalid HTML, either. 

I don't think we want `clean_html` to do *less* sanitization than a browser.

**Comment by dirkf** [comment]
So `HTML_WS` is `\s` without `\v` ?

Has there ever been a case where a vertical tab character appeared out of the 1950s or maybe '70s in some HTML and caused `get_element_...()` to parse the page incorrectly?

If such a vertical tab were present, wouldn't it be much more likely that it was incorrectly placed and ought to be treated like `HTML_WS` regardless of WHATWG, SGML, etc?

**Comment by gibson042** [comment]
> So `HTML_WS` is `\s` without `\v` ?

Close... `HTML_WS` is `\s` without `\v` and **also** without non-ASCII whitespace characters such as U+00A0 NO-BREAK SPACE and U+1680 OGHAM SPACE MARK and U+2028 LINE SEPARATOR.

> Has there ever been a case where a vertical tab character appeared out of the 1950s or maybe '70s in some HTML and caused `get_element_...()` to parse the page incorrectly?

I don't know. But has there ever been a case where there was whitespace around an HTML attribute `=` that caused a problem?

> If such a vertical tab were present, wouldn't it be much more likely that it was incorrectly placed and ought to be treated like `HTML_WS` regardless of WHATWG, SGML, etc?

That I cannot say. But I _can_ say the current code treats e.g. `data-foo ="bar"` as equivalent to `data-foo="bar"` while a web browser would not.

**Comment by dirkf** [comment]
Yes, as yt-dlp is matching a Unicode string (yt-dl too), the documented behaviour depends on `re.UNICODE/ASCII`, with the former being default and the latter what I suggested. In 3.7+ you could write `(?a:(?!\v)\s)` but I wouldn't want to encourage that.

I suppose a page describing the structure of HTML tags and attributes could include a representation like `&lt;a\U000000A0href\U000000A0=\U000000A0"www.example.com"&gt;` which might be matched accidentally using `\s` instead of `HTML_WS`.

**Pull request closed without merging**
