### PR TITLE
Bugfix for 104a7b5a46dc1805157fb4cc11c05876934d37c1

### PR DESCRIPTION
**Pull request by bashonly**
104a7b5a46dc1805157fb4cc11c05876934d37c1 added a check for the existence of both the deprecated singular info dict fields and the new pluralized info dict fields, and outputs a deprecation warning if both are found.

This is a problem for `--load-info-json`, since when we `--write-info-json` (or `--dump-json` etc), we are writing the new plural fields **and** the old singular fields to the info json, and then when we load it back we get deprecation errors:
```shell
ERROR: Do not return 'artist' when 'artists' is present; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: Do not return 'creator' when 'creators' is present; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

This is kind of a hack-y fix; any better ideas are welcome.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Core bug fix/improvement

</details>

### CODE REVIEW

**Comment by bashonly** [comment]
alternative impl: https://github.com/bashonly/yt-dlp/commit/d4cd86525051aa52265c00ee80e0c04a4c6ba6e3

**Comment by Grub4K** [comment]
I think the hack workaround makes more sense for now. We will have to have people move away from the singluar fields anyways

**Review by Grub4K — APPROVED** [review]
Pure hate but whatever

**Comment by pukkandan** [comment]
> alternative impl: [bashonly@ffa23bf](https://github.com/bashonly/yt-dlp/commit/ffa23bf8e0c864aafae9fd846715251d1b345155)

This is problematic. It would have to be done in `sanitize_info` if we go that route. But current soln is good enough imo

**Pull request merged**
