### PR TITLE
[extractor/vimeo] Fix #6149 vimeo playerConfig extraction - patch by @bashonly

### LINKED ISSUE #6149: [vimeo] Unable to extract info section
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello, I am getting increasingly more 'unable to extract info section' errors. The urls are from vimeo. On the same url, sometimes, this error appears and sometimes it doesn't.  at times,can get same error on same url for 6-10 consecutive time.  I'm go through big input text file and it is important for me to avoid as it breaks my operation.  

Using windows exe . Anything to avoid this would be appreciated.  Thank you.

 yt-dlp --get-title https://player.vimeo.com/video/786646692 -vU

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--get-title', 'https://player.vimeo.com/video/786646692', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-01-30-git-2d202985b7-full_build-www.gyan.dev (setts), ffprobe 2023-01-30-git-2d202985b7-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[vimeo] Extracting URL: https://player.vimeo.com/video/786646692
[vimeo] 786646692: Downloading webpage
ERROR: [vimeo] 786646692: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\vimeo.py", line 837, in _real_extract
  File "yt_dlp\extractor\common.py", line 1228, in _search_regex
```

### PR DESCRIPTION
**Pull request by LeoniePhiline**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

The vimeo extractor did not yet use the common `def _search_json()`, failing with its regex when some vimeo players left out the semicolon `;` after the `playerConfig` JSON.

This PR, containing a patch authored by @bashonly, fixes this issue by using the more reliable `_search_json()`.

Fixes #6149

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) 

_`python3 test/test_download.py TestDownload.test_Vimeo_all` failed with `AssertionError: 'b3e7f4d2cbb53bd7dc3bb6ff4ed5cfbd' != '619b811a4417aa4abe78dc653becf511'`, but that **looks like the test, not the code is broken.**_

Test output:

```
❯ python3 test/test_download.py TestDownload.test_Vimeo_all      
Skipping Vimeo: No longer available
Skipped test_Vimeo
[debug] Loaded 1766 extractors
[vimeo] Extracting URL: http://player.vimeo.com/video/54469442
[vimeo] 54469442: Downloading webpage
[vimeo] 54469442: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 54469442: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 54469442: Downloading fastly_skyfire m3u8 information
[vimeo] 54469442: Downloading fastly_skyfire m3u8 information
[vimeo] 54469442: Downloading akfire_interconnect_quic MPD information
[vimeo] 54469442: Downloading akfire_interconnect_quic MPD information
[vimeo] 54469442: Downloading fastly_skyfire MPD information
[vimeo] 54469442: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] 54469442: Downloading 1 format(s): http-1080p
[info] Writing video metadata as JSON to: test_Vimeo_1_54469442.info.json
[debug] Invoking http downloader on "https://vod-progressive.akamaized.net/exp=1676046833~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F893%2F2%2F54469442%2F150773109.mp4~hmac=ea7f5232b97ce427391c3e7ee68fd9d0ab388b4d66e370deb01f3aa689037066/vimeo-prod-skyfire-std-us/01/893/2/54469442/150773109.mp4"
[download] Destination: test_Vimeo_1_54469442.mp4
[download] 100% of   10.00KiB in 00:00:00 at 148.42KiB/s
F
======================================================================
FAIL: test_Vimeo_all (__main__.TestDownload):
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leonie/Projekte/yt-dlp-wip/test/test_download.py", line 281, in test_template
    getattr(self, test_name)()
  File "/home/leonie/Projekte/yt-dlp-wip/test/test_download.py", line 235, in test_template
    self.assertEqual(tc['md5'], md5_for_file)
AssertionError: 'b3e7f4d2cbb53bd7dc3bb6ff4ed5cfbd' != '619b811a4417aa4abe78dc653becf511'
- b3e7f4d2cbb53bd7dc3bb6ff4ed5cfbd
+ 619b811a4417aa4abe78dc653becf511


----------------------------------------------------------------------
Ran 1 test in 1.704s

FAILED (failures=1)
```

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/) 
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

_Please ask @bashonly_ - I only brought in the PR to get this fixed.

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by farcaller** [comment]
I verified this, and it works as intended (and I find it hilarious how I stumbled on this problem exactly 35 minutes ago and it took me about 6 minutes to exhaust my debugging and get to GH where I saw this PR).

**Comment by pukkandan** [comment]
> * [](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md?rgh-link-date=2023-02-10T12%3A35%3A39Z#developer-instructions)
> 
> _`python3 test/test_download.py TestDownload.test_Vimeo_all` failed with `AssertionError: 'b3e7f4d2cbb53bd7dc3bb6ff4ed5cfbd' != '619b811a4417aa4abe78dc653becf511'`, but that **looks like the test, not the code is broken.**_

You an update the test definition

**Comment by LeoniePhiline** [comment]
@pukkandan  Thanks, I got further with updating a few hashes, and one 960px URL to 1280px.

However, how do I need to fix the subtitle fixtures of the following:

```
[debug] Loaded 1766 extractors
[vimeo] Extracting URL: http://vimeo.com/76979871
[vimeo] 76979871: Downloading webpage
[vimeo] 76979871: Downloading JSON metadata
[vimeo] 76979871: Downloading JSON metadata
[vimeo] 76979871: Checking Original video URL
[vimeo] 76979871: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 76979871: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 76979871: Downloading fastly_skyfire m3u8 information
[vimeo] 76979871: Downloading fastly_skyfire m3u8 information
[vimeo] 76979871: Downloading akfire_interconnect_quic MPD information
[vimeo] 76979871: Downloading akfire_interconnect_quic MPD information
[vimeo] 76979871: Downloading fastly_skyfire MPD information
[vimeo] 76979871: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] 76979871: Downloading 1 format(s): Original
[info] Writing video metadata as JSON to: test_Vimeo_4_76979871.info.json
[debug] Invoking http downloader on "https://player.vimeo.com/progressive_redirect/download/76979871/container/ccfaa6de-0af0-44cb-a61a-8ecebadb6ad1/67ae7aaa/the_new_vimeo_player_%28you_know,_for_videos%29%20%28Original%29.mov?expires=1676036752&loc=external&signature=c72e776dff806fc8a666e8ae4b643af3bc5ee35a89f3ef535663d8f4d8904a72"
[download] Destination: test_Vimeo_4_76979871.mov
[download] 100% of   10.00KiB in 00:00:00 at 31.77KiB/s
F
======================================================================
FAIL: test_Vimeo_all (__main__.TestDownload):
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leonie/Projekte/yt-dlp-wip/test/test_download.py", line 281, in test_template
    getattr(self, test_name)()
  File "/home/leonie/Projekte/yt-dlp-wip/test/test_download.py", line 215, in test_template
    expect_info_dict(self, tc_res_dict, tc.get('info_dict', {}))
  File "/home/leonie/Projekte/yt-dlp-wip/test/helper.py", line 233, in expect_info_dict
    expect_dict(self, got_dict, expected_dict)
  File "/home/leonie/Projekte/yt-dlp-wip/test/helper.py", line 186, in expect_dict
    expect_value(self, got, expected, info_field)
  File "/home/leonie/Projekte/yt-dlp-wip/test/helper.py", line 137, in expect_value
    expect_dict(self, got, expected)
  File "/home/leonie/Projekte/yt-dlp-wip/test/helper.py", line 186, in expect_dict
    expect_value(self, got, expected, info_field)
  File "/home/leonie/Projekte/yt-dlp-wip/test/helper.py", line 139, in expect_value
    self.assertEqual(
AssertionError: 1 != 5 : Expect a list of length 1, but got a list of length 5 for field de

----------------------------------------------------------------------
Ran 1 test in 15.988s

FAILED (failures=1)
```

Also, should these fixes really be part of this PR? Apparently nobody is running these tests - not even CI. The failing tests have nothing to do with this PR.

**Comment by pukkandan** [comment]
> Apparently nobody is running these tests - not even CI.

Download tests are only expected to be run by devs when editing the IE. It's appreciated if you can fix the tests assuming the failures are only due to changing test definitions. But I'll merge the PR even if you don't

**Comment by LeoniePhiline** [comment]
@pukkandan I fixed some tests, see https://github.com/yt-dlp/yt-dlp/pull/6203/commits/a3048b1e2f09bb49ea79a014c30e0d98df6e4c98

To fix more I don't have enough knowledge about the test suite. See my previous comment.

**Comment by LeoniePhiline** [comment]
🎉

**Comment by mrzenwiz** [comment]
This is wonderful news. Any estimate on when a new release will be forthcoming?

**Comment by farcaller** [comment]
I have a temporary build in place for nix that includes this patch, so if you happen to have nix (the package manager, not the os), then you can grab it with `nix profile install github:farcaller/nixpkgs/yt-dlp#yt-dlp`

**Comment by EmmaWebGH** [comment]
Ah great, I was searching for problems with Vimeo downloading, looks like I just need to wait a few days and update YTDLP. 
Thanks

**Comment by mrzenwiz** [comment]
I installed nix:

sudo mkdir /nix
sudo chown admar:users /nix
sudo apt install nix-bin
:
21:14 ***@***.***:~/Downloads] $ nix profile install
github:farcaller/nixpkgs/yt-dlp#yt-dlp
error: experimental Nix feature 'nix-command' is disabled; use
'--extra-experimental-features nix-command' to override
21:14 ***@***.***:~/Downloads] $ nix profile install
github:farcaller/nixpkgs/yt-dlp#yt-dlp --extra-experimental-features
nix-command
error: could not set permissions on '/nix/var/nix/profiles/per-user' to
755: Operation not permitted
21:14 ***@***.***:~/Downloads] $ ll -d /nix
drwxr-xr-x 4 admar users 4096 Feb 11 21:10 /nix/
21:14 ***@***.***:~/Downloads] $

No joy on the install...

Mark

**Comment by farcaller** [comment]
> I installed nix

I'm not sure how the deb-based installs work tbh, but I think that the general linux installation path is this: https://nix.dev/tutorials/install-nix (I used it for macOS and it worked just fine).

**Pull request merged**
