### PR TITLE
[ie/youtube] Add `player_use_pp` extractor arg

### PR DESCRIPTION
**Pull request by coletdjnz**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADD DESCRIPTION HERE

Allows user to pass custom player params to be used

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [X] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🆕🎬🔓

Add an option to use custom player params for YouTube videos in `yt_dlp/extractor/youtube.py` and document it in `README.md`. This can help with some videos that have playback or download issues.

> _Sing, O Muse, of the cunning code that unlocked the secrets of YouTube_
> _The code that gave the user a choice, to use the `player_use_pp` option_
> _And thus to overcome the barriers that the video platform had set_
> _Such as the fearsome age-restriction, or the dread region-lock that vexed_

### Walkthrough
*  Add `player_use_pp` option to `youtube` extractor ([link](https://github.com/yt-dlp/yt-dlp/pull/7458/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1805), [link](https://github.com/yt-dlp/yt-dlp/pull/7458/files?diff=unified&w=0#diff-b7b9f6790de4427214b61939432e667d95b929d07fd918b9da1a36d7996cc506L4063-R4074))
*  Use smuggled `player_params` to override default `_PLAYER_PARAMS` in `_extract_player_response` function ([link](https://github.com/yt-dlp/yt-dlp/pull/7458/files?diff=unified&w=0#diff-b7b9f6790de4427214b61939432e667d95b929d07fd918b9da1a36d7996cc506L3615-R3620))

</details>

### CODE REVIEW

**Comment by pukkandan** [comment]
Why is this useful?

**Comment by pukkandan** [comment]
> Why not use `player_params` as the extractor-arg?

this, but otherwise LGTM

**Comment by coletdjnz** [comment]
> Why not use `player_params` as the extractor-arg?

since youtube already has a standard way of specifying them via the url

**Comment by coletdjnz** [comment]
gonna rewrite this to use an extractor arg

**Pull request closed without merging**
