### PR TITLE
Add Spectrum Adobe MSO - Credit to Kevinoconnor7

### PR DESCRIPTION
**Pull request by ohmybahgosh**
Added Spectrum AP-mso, credit to Kevinoconnor7:  
https://github.com/ytdl-org/youtube-dl/pull/26792

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Spectrum Seems to have updated their AP-MSO, as it's been broken for quite sometime now.  Thanks to Kevinoconnor7's PR over at ytdl-org, this fixes the issue and once again allows users to login via their Spectrum account.

### CODE REVIEW

**Comment by pukkandan** [comment]
Since I have no way of testing this myself, please confirm that this has been tested to work

**Comment by ohmybahgosh** [comment]
> Since I have no way of testing this myself, please confirm that this has been tested to work
> 
> Edit: and fix the linter

I can PM you a login if you want, as you're way more experienced with YT-DLP than I.  Just let me know, and I'll send em over to whatever email you want. 

I'll also post some of my own logs, of it working.

**Comment by ohmybahgosh** [comment]
``` bash
✦ ❯ yt-dlp --verbose --simulate https://www.usanetwork.com/law-and-order-special-victims-unit/video/guardians-and-gladiators/4261777                                [debug] User config file: /root/yt-dlp.conf
[debug] User config: ['--ap-mso', 'Spectrum', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-N50', '-f', 'bv+ba/b', '--downloader-args', 'aria2c:-x 16 -s 16 -j 16 -k 5M']
[debug] Command-line config: ['--verbose', '--simulate', 'https://www.usanetwork.com/law-and-order-special-victims-unit/video/guardians-and-gladiators/4261777']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.06.23 (zip)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-kali9-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, phantomjs 1.9.7, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [USANetwork] Extracting URL: https://www.usanetwork.com/law-and-order-special-victims-unit/video/guardians-and-gladiators/4261777
[USANetwork] 4261777: Downloading JSON metadata
[USANetwork] 4261777: Downloading JSON metadata
[USANetwork] 4261777: Downloading Provider Redirect Page
[USANetwork] 4261777: Downloading Provider Login Page
[USANetwork] 4261777: Downloading SAML Response
[USANetwork] 4261777: Confirming Login
[USANetwork] 4261777: Retrieving Session
[USANetwork] 4261777: Retrieving Authorization Token
[USANetwork] 4261777: Retrieving Media Token
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/NnzsPC/media/guid/***REDACTED_PRIVATE_AUTH_DATA***/
[ThePlatform] 4261777: Downloading SMIL data
[ThePlatform] 4261777: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] 4261777: Downloading JSON metadata
[info] 4261777: Downloading 1 format(s): hls-4178
```

**Comment by pukkandan** [comment]
> Verbose Log - Successfull Authentication For Spectrum:

Thats all that needed to be tested 👍

**Comment by ohmybahgosh** [comment]
> Since I have no way of testing this myself, please confirm that this has been tested to work
> 
> Edit: and fix the linter

Linter fixed, whitespace removed

**Pull request merged**
