### PR TITLE
Updated fujitv.py on extracting 1080P stream from tv_android m3u8

### PR DESCRIPTION
**Pull request by YuenSzeHong**
getting high resolution from android tv stream

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [x] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

fixes for fuji FOD and updated that it can extract 1080 stream from that

### CODE REVIEW

**Review by Ashish0804 — APPROVED** [review]

**Comment by pukkandan** [comment]
Are you sure android_tv works for all videos? Or perhaps we should add fallbacks?

**Comment by YuenSzeHong** [comment]
works on free videos, tested

**Comment by pukkandan** [comment]
I assume the valid_url change u pushed to #1927 is actually meant for this PR?

**Comment by YuenSzeHong** [comment]
wrong commit, ment to commit on my pr on fuji extractor

**Comment by YuenSzeHong** [comment]
but the valid url has changed for ages, the older ones doesn't work anymore

**Comment by YuenSzeHong** [comment]
do I need to provide tests for this PR? waiting for this to be merged to new release

**Comment by pukkandan** [comment]
Yes. Please add a test

**Comment by YuenSzeHong** [comment]
not easy, free videos lasts only a week, so the tests not always work

**Comment by pukkandan** [comment]
That is ok. Just add a test that works right now. Then add `'skip': 'Expired'` to the test definition

**Comment by YuenSzeHong** [comment]
put that in the test folder at root dir?

**Pull request merged**
