### PR TITLE
[extractor/reddit] add vcodec to fallback format

### PR DESCRIPTION
**Pull request by chengzhicn**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

Current fallback format is missing "vcodec" attribute which is used by other program(eg: mpv), this PR add that "vcodec" attribute so that script relies on "vcodec" can continue to work.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
`mp4` is not the codec though

**Comment by chengzhicn** [comment]
You're right. It's unfortunate reddit didn't provide codec info for the fallback and judging from the few samples I have, they all encoded by h264, so I changed the vcodec to h264 and hope for other videos also encoded in h264

**Comment by pukkandan** [comment]
> which is used by other program(eg: mpv),

Out of curiosity, why does mpv need vcodec to work? There are plenty of sites where yt-dlp cannot extract the codec information. The script should ideally be updated to account for this. If needed, mpv can use ffprobe to check the codec once yt-dlp gives the URL

**Comment by pukkandan** [comment]
Merged this, but if we ever find videos in another codec, I will revert it

**Pull request merged**
