### PR TITLE
[extractor/tiktok] TikTokBaseIE update api hostname

### LINKED ISSUE #5688: TikTok Parsing Feed Breaking Update Dec 1, 2022 (non-watermark version missing)
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

Requesting the list of formats returns JSON feed error, which resorts to downloading webpage which now only shows one video (with watermark) ... which his not helpful.

yt-dlp -F https://www.tiktok.com/@repurposeio/video/7158191036513127685

[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] 7158191036513127685: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7158191036513127685: Downloading webpage
[info] Available formats for 7158191036513127685:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 576x1024   │ https │ unknown unknown

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
root@new-proc-ubuntu-2gb-nyc1-01-processing-01-1495731460959-8gb-nyc1:~/hani# /root/smpnode/yt-dlp-master/yt_dlp/__main__.py --proxy https://196.51.251.236:8800 --add-header 'user-agent:Mozilla/5.0' "https://www.tiktok.com/@repurposeio/video/7158191036513127685" -vU
[debug] Command-line config: ['--proxy', 'https://196.51.251.236:8800', '--add-header', 'user-agent:Mozilla/5.0', 'https://www.tiktok.com/@repurposeio/video/7158191036513127685', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b]
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.8.9 (CPython x86_64 64bit) - Linux-4.15.0-173-generic-x86_64-with-glibc2.17 (OpenSSL 1.0.2n  7 Dec 2017, glibc 2.27)
[debug] exe versions: ffmpeg 5.0.1-static (setts), ffprobe 5.0.1-static, rtmpdump 2.4
[debug] Optional libraries: certifi-2018.01.18, sqlite3-2.6.0
[debug] Proxy map: {'http': 'https://196.51.251.236:8800', 'https': 'https://196.51.251.236:8800'}
[debug] Loaded 1731 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@repurposeio/video/7158191036513127685
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] 7158191036513127685: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7158191036513127685: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7158191036513127685: Downloading 1 format(s): 0
```

### PR DESCRIPTION
**Pull request by redraskal**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

Modified the api hostname for TikTok. Looks like TikTok only shut down or changed the previous API hostname and did not start requiring additional signatures.

Cannot run tests for some reason due to a RecursionError :), so I manually ran some of the tests.

Fixes #5688 

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
> Cannot run tests for some reason due to a RecursionError :),

Pls explain

**Comment by redraskal** [comment]
> > Cannot run tests for some reason due to a RecursionError :),
> 
> Pls explain

test/test_download.py throws the following error for any extractor:
```
WARNING: Falling back to normal extractor since lazy extractor CrunchyrollIE does not have attribute real_class; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "F:\GitHub\yt-dlp\test\test_download.py", line 269, in <module>
    inject_tests(normal_test_cases)
  File "F:\GitHub\yt-dlp\test\test_download.py", line 258, in inject_tests
    for test_case in test_cases:
  File "F:\GitHub\yt-dlp\test\helper.py", line 91, in gettestcases
    for ie in yt_dlp.extractor.gen_extractors():
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\GitHub\yt-dlp\yt_dlp\extractor\__init__.py", line 20, in gen_extractors
    return [klass() for klass in gen_extractor_classes()]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\GitHub\yt-dlp\yt_dlp\extractor\__init__.py", line 20, in <listcomp>
    return [klass() for klass in gen_extractor_classes()]
            ^^^^^^^
  File "F:\GitHub\yt-dlp\yt_dlp\extractor\lazy_extractors.py", line 36, in __new__
    instance = cls.real_class.__new__(cls.real_class)
               ^^^^^^^^^^^^^^
  File "F:\GitHub\yt-dlp\yt_dlp\extractor\lazy_extractors.py", line 25, in __getattr__
    return getattr(cls.real_class, name)
                   ^^^^^^^^^^^^^^
  File "F:\GitHub\yt-dlp\yt_dlp\extractor\lazy_extractors.py", line 25, in __getattr__
    return getattr(cls.real_class, name)
                   ^^^^^^^^^^^^^^
  File "F:\GitHub\yt-dlp\yt_dlp\extractor\lazy_extractors.py", line 25, in __getattr__
    return getattr(cls.real_class, name)
                   ^^^^^^^^^^^^^^
  [Previous line repeated 985 more times]
  File "F:\GitHub\yt-dlp\yt_dlp\utils.py", line 5881, in __get__
    return self.func(cls)
           ^^^^^^^^^^^^^^
  File "F:\GitHub\yt-dlp\yt_dlp\extractor\lazy_extractors.py", line 32, in real_class
    cls._real_class = getattr(importlib.import_module(cls._module), cls.__name__)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1203, in _gcd_import
RecursionError: maximum recursion depth exceeded
```
I'm guessing it's something on my end because I do not see other issues for this and recently reinstalled Windows and swapped files around.

**Comment by redraskal** [comment]
I pulled video urls from the tests in tiktok.py and from the issue to test this change- works on my device

**Comment by bashonly** [comment]
`TikTokIE` tests pass for me.

**Comment by pukkandan** [comment]
Your lazy extractors are somehow broken. Rebuild/remove it

**Comment by guodong2019** [comment]
It seems still not work.

**url**=https://api16-normal-c-useast1a.tiktokv.com/aweme/v1/feed/?aweme_id=7121336502398782747&version_name=26.1.3&version_code=260103&build_number=26.1.3&manifest_version_code=260103&update_version_code=260103&openudid=39e7cfc7f9023de1&uuid=1450823614373125&_rticket=1669974438356&ts=1669974438&device_brand=Google&device_type=Pixel+4&device_platform=android&resolution=1080%2A1920&dpi=420&os_version=10&os_api=29&carrier_region=US&sys_region=US&region=US&app_name=trill&app_language=en&language=en&timezone_name=America%2FNew_York&timezone_offset=-14400&channel=googleplay&ac=wifi&mcc_mnc=310260&is_my_cn=0&aid=1180&ssmix=a&as=a1qwert123&cp=cbfhckdckkde1

**headers**={'User-Agent': 'com.ss.android.ugc.trill/260103 (Linux; U; Android 10; en_US; Pixel 4; Build/QQ3A.200805.001; Cronet/58.0.2991.0)', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate'}, cookies={'odin_tt': '6f1dcfd0f0eb63399678b4fe18bf40b3be311bb0e1891a09df06fe65d4419662cc40351a8d7f918487930ab3152dc291809846f9f07e8c1bda91febe2059b42a127f38f63e1bc5b4fbeff1452a6051fc'}

response **status**=200, **text**=, **content**=b''

**Comment by bashonly** [comment]
@guodong2019 can you show a verbose yt-dlp log of it not working? and what region are located in, if you don't mind sharing?

**Comment by guodong2019** [comment]
sorry, it worked now. I just called the aweme/detail/ endpoint.

**Pull request merged**
