### PR TITLE
Support for flat --extract-single-video that allows single video download

### PR DESCRIPTION
**Pull request by SVyatoslavG**
### Description of your *pull request* and other information

</details>

I have been running into problems when yt-dlp follows links on the youtube page, twitter post or facebook posts and tries to download videos from pages post links to. This is great but I want to have the option to download ONLY the specified URL and do not follow any links. 

I found in yt_dlp/YoutubeDL.py line 1615
```
 if ((extract_flat == 'in_playlist' and 'playlist' in extra_info)
                    or extract_flat is True):
```
but here is not way to extract_flat to True.
I added the option to set extract_flat to True and avoid following links.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
Example: https://www.funimation.com/shows/attack-on-titan-junior-high/broadcast-dub-preview

**Comment by SVyatoslavG** [comment]
Thank you for your response.
`--ies` seems to be a workable solution, however, I encounter the issue when tweet links to youtube video.
```
yt_dlp "https://twitter.com/Google/status/1582487357487427584" -s --dump-single-json --no-warnings --use-extractors "twitter" --trim-file-names=40
```
failes with
```
ERROR: No suitable extractor found for URL https://www.youtube.com/embed/IoXiXlCNoXg?list=PL590L5WQmH8dsxxz7ooJAgmijwOz0lh2
```
That tween links to a youtube video but I need to get information if the tweet contains video (embedded video on platform and not going to youtube, vimeo etc).
Is there a way to do so?

**Comment by pukkandan** [comment]
> That tweet links to a youtube video but I need to get information if the tweet contains video (embedded video on platform and not going to youtube, vimeo etc).
> Is there a way to do so?

If it contains embedded video, it will not give error

**Comment by SVyatoslavG** [comment]
Is there a workaround/parameter to check if the page has an embedded video?
Basically, I have an automated tool that downloads videos from tweets or Facebook posts. Occasionally, I get errors from yt-dlp because I cannot automatically determine if the post contains a video or not.

**Pull request closed without merging**
