### PR TITLE
Science channel update

### PR DESCRIPTION
**Pull request by Sipherdrakon**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [X] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Sciencechannel.com updated their site to be more like discoveryplus.com. So I went and added it to the dplay extractor so it functions just like downloading from Discoveryplus.com.

### CODE REVIEW

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/pull/29643, fixes https://github.com/ytdl-org/youtube-dl/issues/29634

**Comment by Mr-Jake** [comment]
It looks like Animal Planet was also recently updated like Science Channel. Would it be possible to fix Animal Planet site support using the same Science Channel extractor fix.

**Comment by Sipherdrakon** [comment]
Pull request initiated at #1050

**Comment by Mr-Jake** [comment]
@Sipherdrakon

Thank you!

**Pull request merged**
