### PR TITLE
apply `shellcheck` fixes to run_tests.sh and added `set -eu` to yt-dlp.sh

### PR DESCRIPTION
**Pull request by MrRawes**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

[Double quote to prevent globbing and word splitting](https://www.shellcheck.net/wiki/SC2086)

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
Why though?

**Comment by MrRawes** [comment]
> Why though?

IMO linting code is a good idea (`shellcheck` is a linter)

**Comment by pukkandan** [comment]
This is a Python project. shellcheck is not a linter I have any interest in adhering to. That said, while this PR is useless, it's also harmless. So I don't mind merging this. However, I don't encourage PRs like this in the future

**Comment by MrRawes** [comment]
the changes i made to yt-dlp.sh are that i added `set -eu`
`set -eu` sets values
-e sets "Exit immediately if a command exits with a non-zero status"
-u sets "Treat unset variables as an error when substituting"

**Comment by Lesmiscore** [comment]
I don't see the point in setting `set -eu` in `yt-dlp.sh` since it literally references no variables (aside from `$@`) and the first command is `exec` (and the last, too)

**Pull request closed without merging**
