### PR TITLE
[DigitalConcertHall] remove username/password login and add token support

### LINKED ISSUE #11404: [DigitalConcertHall] all attempts fail with Unable to login: HTTP Error 400: Bad Request (new CAPTCHA?)
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

All attempts to download from https://www.digitalconcerthall.com/ fail at the login stage (using known-good credentials) with "Unable to login: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)"

I've tried several different URLs and they all fail in the same way. Loading the same URLs into a browser works fine and the content can be played.

I last tried this about 6 weeks ago, with yt-dlp-2024.08.06, and it was working then. The only difference I can see is that the login page now mentions "FriendlyCaptcha".

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.digitalconcerthall.com/en/concert/23508']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.10.28.110905 from yt-dlp/yt-dlp-master-builds [f101e5d34] (zip)
[debug] Python 3.11.2 (CPython aarch64 64bit) - Linux-6.1.0-26-arm64-aarch64-with-glibc2.36 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2022.09.24, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.10.28.110905 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.10.28.110905 from yt-dlp/yt-dlp-master-builds)
[DigitalConcertHall] Obtaining token
[DigitalConcertHall] Logging in
ERROR: [DigitalConcertHall] 23508: Unable to login: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
  File "/home/dave/bin/yt-dlp/yt_dlp/extractor/common.py", line 739, in extract
    self.initialize()
  File "/home/dave/bin/yt-dlp/yt_dlp/extractor/common.py", line 645, in initialize
    self._perform_login(username, password)
  File "/home/dave/bin/yt-dlp/yt_dlp/extractor/digitalconcerthall.py", line 92, in _perform_login
    login_response = self._download_json(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/bin/yt-dlp/yt_dlp/extractor/common.py", line 1152, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/bin/yt-dlp/yt_dlp/extractor/common.py", line 1112, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/bin/yt-dlp/yt_dlp/extractor/common.py", line 962, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/bin/yt-dlp/yt_dlp/extractor/common.py", line 911, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/dave/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 398, in _send
    res = opener.open(urllib_req, timeout=self._calculate_timeout(request))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dave/bin/yt-dlp/yt_dlp/extractor/common.py", line 898, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4162, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/bin/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/bin/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/bin/yt-dlp/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dave/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 403, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request
```

### PR DESCRIPTION
**Pull request by uduman**
### Description of your *pull request* and other information

Removed login because of unavoidable captcha and added token support

Fixes #11404

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by B1ueH0r1z0n** [comment]
What EXACTLY is the complete example for downloading a best video/audio nowadays? I copied and used the example from the original 2022 pull for just an attempt: 
```
yt-dlp https://www.digitalconcerthall.com/en/concert/53201 --add-metadata --playlist-items 1 --netrc -f 'bestvideo+audio0-flac' --postprocessor-args '-strict -2'
``` 
and I got 
```
error: wrong --postprocessor-args formatting; No closing quotation
```
 can't figure out why since I'm just a rookie at these things, like command line and stuff.

**Comment by uduman** [comment]
`./yt-dlp.sh https://www.digitalconcerthall.com/en/concert/53201 --username token --password [your token] --add-metadata --playlist-items 1  -f 'bestvideo+hls-audio0-fLaC' --postprocessor-args '-strict -2'`

This worked for me. Basically just changed the format to `bestvideo+hls-audio0-fLaC` and used `access_token_production` from the browser's local storage to login. I'm not sure if you need a voucher because the account I used to test had one.

**Comment by B1ueH0r1z0n** [comment]
> `./yt-dlp.sh https://www.digitalconcerthall.com/en/concert/53201 --username token --password [your token] --add-metadata --playlist-items 1 -f 'bestvideo+hls-audio0-fLaC' --postprocessor-args '-strict -2'`
> 
> This worked for me. Basically just changed the format to `bestvideo+hls-audio0-fLaC` and used `access_token_production` from the browser's local storage to login. I'm not sure if you need a voucher because the account I used to test had one.

thx, so basiclly the first thing to do is login my account, but how? or did some of the field in this example just skip the acconut loging-in? btw what is a token and how do i get access to "my token"? and your example didn't seems to modify the format of the post-processor option, so how can I reverse the error i receive? 
```
yt-dlp: error: wrong --postprocessor-args formatting; No closing quotation
```

**Comment by CC75** [comment]
Is there missing in this command line : 

`yt-dlp --username [my email] --add-metadata https://www.digitalconcerthall.com/en/concert/23503`

Because I used the modified extractor file, and keep having the same issue after entering my password :  

`[DigitalConcertHall] Extracting URL: https://www.digitalconcerthall.com/en/concert/23503
[DigitalConcertHall] 23503: Downloading JSON metadata
ERROR: too many positional arguments`

I can't figure if I forgot something ?

**Comment by Lontananza** [comment]
Hi CC75, very rookie here. How do you exactly insert your password? When asked I can't type nor paste it, and nothing happens.

**Comment by Lontananza** [comment]
> 
> thx, so basiclly the first thing to do is login my account, but how? or did some of the field in this example just skip the acconut loging-in? btw what is a token and how do i get access to "my token"? and your example didn't seems to modify the format of the post-processor option, so how can I reverse the error i receive?
> 
> ```
> yt-dlp: error: wrong --postprocessor-args formatting; No closing quotation
> ```
Have still to figure out myself the login way. But for the "no closing quotation" problem, just write '-strict-2' instead of '-strict -2'
Don't ask me why, I have no idea, two hours ago I didn't even know of yt-dlp.

**Comment by CC75** [comment]
> Hi CC75, very rookie here. How do you exactly insert your password? When asked I can't type nor paste it, and nothing happens.
> 
> Edit: I have tried the .netrc file option, but I always get:
> 
> > [DigitalConcertHall] Obtaining token
> > [DigitalConcertHall] Logging in
> > ERROR: [DigitalConcertHall] 55634: Unable to login: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>

It's actually a very good question... I thought the fact that nothing shows when you enter the password was a kind of protection, almost like "•••••" on websites... so, yes, I don't even know if I entered my password...

**Comment by Lontananza** [comment]
> It's actually a very good question... I thought the fact that nothing shows when you enter the password was a kind of protection, almost like "•••••" on websites... so, yes, I don't even know if I entered my password...

Well looks like you did - since you get at least the "download JSON metadata" step. I tried typing, ctrl+v, shift+ins ... nothing!

**Comment by Lontananza** [comment]
> `./yt-dlp.sh https://www.digitalconcerthall.com/en/concert/53201 --username token --password [your token] --add-metadata --playlist-items 1 -f 'bestvideo+hls-audio0-fLaC' --postprocessor-args '-strict -2'`
> 
> This worked for me. Basically just changed the format to `bestvideo+hls-audio0-fLaC` and used `access_token_production` from the browser's local storage to login. I'm not sure if you need a voucher because the account I used to test had one.

Hi udoman, if I understand correctly using a token overrules username + password login which now doesn't work anymore. Is it possible on Windows 10 to use 'access_token_production', and how should it be done? Sorry for rookie question.

**Comment by Lontananza** [comment]
Hi Grub4K, thanks for your answer. As I said I'm a very old Windows 10 user with just a basic grasp of CMD prompt workings. I understand I should run the udoman Python script and check lines 70/71, shouln't I? I downloaded Python 3.12, but when I try to run the script it gives me 

`from .common import InfoExtractor
ImportError: attempted relative import with no known parent package`

Which I guess is one of the basic knowledge elements I haven't. Sorry. 
Maybe I'm asking for something simpler which doesn't exist?

**Comment by Grub4K** [comment]
Disregard previous instructions. Closing since issue is assigned to @bashonly

**Pull request closed without merging**
