### PR TITLE
[douyin] Add new extractor

### PR DESCRIPTION
**Pull request by pyx**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Adding new extractor for www.douyin.com.

Tiktok is the international version of Douyin (抖音). They have a proper website (finally, with video lists, user profile pages, video searching, etc.) last month.

### CODE REVIEW

**Comment by pyx** [comment]
@llacb47 PR created as you suggested there.

It's working now, all tests passed.

yt-dlp

**Comment by pukkandan** [comment]
The website doesn't load for me. Is there some geo-restriction?

**Comment by pyx** [comment]
> The website doesn't load for me. Is there some geo-restriction?

I've keeping an eye on that everyday, it work sometimes (for example, yesterday about 18 hours ago), since the website is kind of new, they probably is still optimizing the back-end, that might be the cause of zero length html response.

The other reason might be, as I was analyzing the output the day before yesterday, the website sometime responded with an html with javascript doing some challenge-response test similar to reCAPTCHA with slider, the triggering condition seems to be too many access in curtain short period, to avoid spamming or to prevent DOS, I guess. I am keeping record of that and see if I can figure out the exact condition, then I can either have a workaround if it's possible, or try to avoid that if it's not.

Thank you.

**Comment by pyx** [comment]
The underlying extractor logic is working if the html can be properly loaded.

**Comment by pyx** [comment]
@pukkandan  update on last two replies, for example, It's working right now. 10:35PM EST

**Pull request merged**
