### PR TITLE
[extractor/eurosport] Add extractor

### LINKED ISSUE #2487: support for eurosport.com
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

worldwide

### Example URLs

https://www.eurosport.com/tennis/australian-open/2022/nick-kyrgios-hits-kid-in-crowd-with-wild-shot-turns-his-tears-to-smiles-with-gift-at-australian-open_vid1614604/video.shtml

### Description

[Eurosport](https://en.wikipedia.org/wiki/Eurosport) is a pan-European television sports network and a subsidiary of Discovery.

### Verbose log

```shell
[debug] Command-line config: ['https://www.eurosport.com/tennis/australian-open/2022/nick-kyrgios-hits-kid-in-crowd-with-wild-shot-turns-his-tears-to-smiles-with-gift-at-australian-open_vid1614604/video.shtml', '--ignore-config', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-105208-gb24f0c82b3-20220108 (setts), ffprobe N-105208-gb24f0c82b3-20220108
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.eurosport.com/tennis/australian-open/2022/nick-kyrgios-hits-kid-in-crowd-with-wild-shot-turns-his-tears-to-smiles-with-gift-at-australian-open_vid1614604/video.shtml
[generic] video: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] video: Downloading webpage
[generic] video: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.eurosport.com/tennis/australian-open/2022/nick-kyrgios-hits-kid-in-crowd-with-wild-shot-turns-his-tears-to-smiles-with-gift-at-australian-open_vid1614604/video.shtml
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3966, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.eurosport.com/tennis/australian-open/2022/nick-kyrgios-hits-kid-in-crowd-with-wild-shot-turns-his-tears-to-smiles-with-gift-at-australian-open_vid1614604/video.shtml
```

### PR DESCRIPTION
**Pull request by HobbyistDev**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

ADD DESCRIPTION HERE
This PR add site support for www.eurosport.com. At the moment, this PR didn't include geo-block detection and not tested geo-blocked link. Any help to test geo-blocked video is appreciated.

Fixes #2487 

KNOWN ISSUE:
- ~Some link (eg: https://www.eurosport.com/tennis/roland-garros/2022/watch-the-top-five-shots-from-men-s-final-as-rafael-nadal-beats-casper-ruud-to-seal-14th-french-open_vid1694283/video.shtml) raise PostProcessorError, but it works when we input the url manually to ffmpeg~ fixed by setting `m3u8` at `protocol`
- ~Eurosport actually support video file in mss type. I didn't know how to extract this type, so this is unsupported at the moment~ already supported
TO DO:
- ~Set better error on geo-blocked url~ Not needed as now, the extractor will have geo-bypass mechanism

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
> Some link (eg: [eurosport.com/tennis/roland-garros/2022/watch-the-top-five-shots-from-men-s-final-as-rafael-nadal-beats-casper-ruud-to-seal-14th-french-open_vid1694283/video.shtml](https://www.eurosport.com/tennis/roland-garros/2022/watch-the-top-five-shots-from-men-s-final-as-rafael-nadal-beats-casper-ruud-to-seal-14th-french-open_vid1694283/video.shtml)) raise PostProcessorError, but it works when we input the url manually to ffmpeg

Pls show me full verbose log of the error

**Comment by HobbyistDev** [comment]
Here's the log:
```shell
(python_proj2) > python -m yt_dlp -v "https://www.eurosport.com/cycling/tour-de-france-femmes/2022/incredible-ride-marlen-reusser-storms-to-stage-4-win-at-tour-de-france-femmes_vid1722221/video.shtml" --test
[debug] Command-line config: ['-v', 'https://www.eurosport.com/cycling/tour-de-france-femmes/2022/incredible-ride-marlen-reusser-storms-to-stage-4-win-at-tour-de-france-femmes_vid1722221/video.shtml', '--test']
[debug] Portable config "~\yt-dlp.conf": ['--netrc-location', '~yt-dlp_netrc']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158f7] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: cd4df5ffa
[debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1-full_build-www.gyan.dev (setts), ffprobe 5.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Using fake IP 2.18.205.76 (EU) as X-Forwarded-For
[Eurosport] Trying to get token
[debug] [Eurosport] Extracting URL: https://www.eurosport.com/cycling/tour-de-france-femmes/2022/incredible-ride-marlen-reusser-storms-to-stage-4-win-at-tour-de-france-femmes_vid1722221/video.shtml
[Eurosport] vid1722221: Downloading webpage
[Eurosport] vid1722221: Downloading JSON metadata
[Eurosport] vid1722221: Downloading MPD manifest
[Eurosport] vid1722221: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), channels, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2582552: Downloading 1 format(s): 10004-1+audio_0-English-1
[debug] Invoking hlsnative downloader on "https://eurosport-vod.akamai.prod-live.h264.io/primary/3/47d772172bdd417a9b42875b64310d33/06f683030f9a485d9ce8ef187a6cc0de/hdntl=exp=1660169358~acl=/primary/3/47d772172bdd417a9b42875b64310d33/06f683030f9a485d9ce8ef187a6cc0de/*~data=hdntl~hmac=6415e04f7a840cf16f1e330a0438ee37e48d435c90aba65f956893ce45e2d94e/888b802aa23d4bc9b3111997063e3fa5/9884daa108e64d1188a945784d9f68c3/5d88433b697c4988beabc4839719c825/index_4.m3u8"
[download] ‘Incredible ride!’ - Marlen Reusser storms to Stage 4 win at Tour de France Femmes [2582552].f10004-1.mp4 has already been downloaded
[download] 100% of 5.83MiB
[debug] Invoking hlsnative downloader on "https://eurosport-vod.akamai.prod-live.h264.io/primary/3/47d772172bdd417a9b42875b64310d33/06f683030f9a485d9ce8ef187a6cc0de/hdntl=exp=1660169358~acl=/primary/3/47d772172bdd417a9b42875b64310d33/06f683030f9a485d9ce8ef187a6cc0de/*~data=hdntl~hmac=6415e04f7a840cf16f1e330a0438ee37e48d435c90aba65f956893ce45e2d94e/888b802aa23d4bc9b3111997063e3fa5/9884daa108e64d1188a945784d9f68c3/5d88433b697c4988beabc4839719c825/index_10_0.m3u8"
[download] ‘Incredible ride!’ - Marlen Reusser storms to Stage 4 win at Tour de France Femmes [2582552].faudio_0-English-1.mp4 has already been downloaded
[download] 100% of 93.92KiB
[debug] ffmpeg command line: ffprobe -show_streams "file:‘Incredible ride!’ - Marlen Reusser storms to Stage 4 win at Tour de France Femmes [2582552].faudio_0-English-1.mp4"
[Merger] Merging formats into "‘Incredible ride!’ - Marlen Reusser storms to Stage 4 win at Tour de France Femmes [2582552].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:‘Incredible ride!’ - Marlen Reusser storms to Stage 4 win at Tour de France Femmes [2582552].f10004-1.mp4" -i "file:‘Incredible ride!’ - Marlen Reusser storms to Stage 4 win at Tour de France Femmes [2582552].faudio_0-English-1.mp4" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:‘Incredible ride!’ - Marlen Reusser storms to Stage 4 win at Tour de France Femmes [2582552].temp.mp4"
[debug] ffmpeg version 5.1-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001f6e5224240] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001f6e5224240] moov atom not found
file:‘Incredible ride!’ - Marlen Reusser storms to Stage 4 win at Tour de France Femmes [2582552].f10004-1.mp4: Invalid data found when processing input

ERROR: Postprocessing: file:‘Incredible ride!’ - Marlen Reusser storms to Stage 4 win at Tour de France Femmes [2582552].f10004-1.mp4: Invalid data found when processing input
Traceback (most recent call last):
  File "~\yt_dlp\YoutubeDL.py", line 3245, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "~\yt_dlp\YoutubeDL.py", line 3415, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "~\yt_dlp\YoutubeDL.py", line 3397, in run_all_pps
    info = self.run_pp(pp, info)
  File "~\yt_dlp\YoutubeDL.py", line 3376, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "~\yt_dlp\postprocessor\common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "~\yt_dlp\postprocessor\common.py", line 125, in wrapper
    return func(self, info)
  File "~\yt_dlp\postprocessor\ffmpeg.py", line 823, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "~\yt_dlp\postprocessor\ffmpeg.py", line 318, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "~\yt_dlp\postprocessor\ffmpeg.py", line 356, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:‘Incredible ride!’ - Marlen Reusser storms to Stage 4 win at Tour de France Femmes [2582552].f10004-1.mp4: Invalid data found when processing input
```

**Comment by pukkandan** [comment]
Does it work with `--downloader ffmpeg`? If so, set `protocol=m3u8`

**Comment by pukkandan** [comment]
Also, even though there is error, does the downloaded file play?

**Comment by HobbyistDev** [comment]
It seems the error occured when there's `--test` argument. I didn't konw why that happen.

Here's log with `--test`:
```shell
(python_proj2) ~>python -m yt_dlp -v "https://www.eurosport.com/tennis/roland-garros/2022/watch-the-top-five-shots-from-men-s-final-as-rafael-nadal-beats-casper-ruud-to-seal-14th-french-open_vid1694283/video.shtml" --test
[debug] Command-line config: ['-v', 'https://www.eurosport.com/tennis/roland-garros/2022/watch-the-top-five-shots-from-men-s-final-as-rafael-nadal-beats-casper-ruud-to-seal-14th-french-open_vid1694283/video.shtml', '--test']
[debug] Portable config "~\yt-dlp.conf": ['--netrc-location', '~yt-dlp_netrc']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158f7] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: cd4df5ffa
[debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1-full_build-www.gyan.dev (setts), ffprobe 5.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Using fake IP 2.20.219.131 (EU) as X-Forwarded-For
[Eurosport] Trying to get token
[debug] [Eurosport] Extracting URL: https://www.eurosport.com/tennis/roland-garros/2022/watch-the-top-five-shots-from-men-s-final-as-rafael-nadal-beats-casper-ruud-to-seal-14th-french-open_vid1694283/video.shtml
[Eurosport] vid1694283: Downloading webpage
[Eurosport] vid1694283: Downloading JSON metadata
[Eurosport] vid1694283: Downloading MPD manifest
[Eurosport] vid1694283: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), channels, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2481254: Downloading 1 format(s): 7634-1+audio_0-Default-1
[debug] Invoking hlsnative downloader on "https://eurosport-vod.akamai.prod-live.h264.io/primary/3/2a5e6e52edbc463e866ab25906e5d613/06f683030f9a485d9ce8ef187a6cc0de/hdntl=exp=1660227819~acl=/primary/3/2a5e6e52edbc463e866ab25906e5d613/06f683030f9a485d9ce8ef187a6cc0de/*~data=hdntl~hmac=d7362e8269d6f99f3bde38de2f7f7e48e913a5eb621f6a4daa480f62c94a7695/888b802aa23d4bc9b3111997063e3fa5/2bf445ce214f4c0d9c1208a0a8ae2b2e/5d88433b697c4988beabc4839719c825/index_1.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 22
[download] Destination: Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].f7634-1.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of 2.97MiB in 00:03 at 887.71KiB/s
[debug] Invoking hlsnative downloader on "https://eurosport-vod.akamai.prod-live.h264.io/primary/3/2a5e6e52edbc463e866ab25906e5d613/06f683030f9a485d9ce8ef187a6cc0de/hdntl=exp=1660227819~acl=/primary/3/2a5e6e52edbc463e866ab25906e5d613/06f683030f9a485d9ce8ef187a6cc0de/*~data=hdntl~hmac=d7362e8269d6f99f3bde38de2f7f7e48e913a5eb621f6a4daa480f62c94a7695/888b802aa23d4bc9b3111997063e3fa5/2bf445ce214f4c0d9c1208a0a8ae2b2e/5d88433b697c4988beabc4839719c825/index_9_0.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 22
[download] Destination: Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].faudio_0-Default-1.mp4
[download] 100% of 94.28KiB in 00:00 at 200.72KiB/s
[debug] ffmpeg command line: ffprobe -show_streams "file:Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].faudio_0-Default-1.mp4"
[Merger] Merging formats into "Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].f7634-1.mp4" -i "file:Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].faudio_0-Default-1.mp4" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].temp.mp4"
[debug] ffmpeg version 5.1-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001b32b2f0500] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001b32b2f0500] moov atom not found
file:Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].f7634-1.mp4: Invalid data found when processing input

ERROR: Postprocessing: file:Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].f7634-1.mp4: Invalid data found when processing input
Traceback (most recent call last):
  File "~\yt_dlp\YoutubeDL.py", line 3245, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "~\yt_dlp\YoutubeDL.py", line 3415, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "~\yt_dlp\YoutubeDL.py", line 3397, in run_all_pps
    info = self.run_pp(pp, info)
  File "~\yt_dlp\YoutubeDL.py", line 3376, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "~\yt_dlp\postprocessor\common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "~\yt_dlp\postprocessor\common.py", line 125, in wrapper
    return func(self, info)
  File "~\yt_dlp\postprocessor\ffmpeg.py", line 823, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "~\yt_dlp\postprocessor\ffmpeg.py", line 318, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "~\yt_dlp\postprocessor\ffmpeg.py", line 356, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].f7634-1.mp4: Invalid data found when processing input
```

Here without `--test`:
```shell
(python_proj2) ~>python -m yt_dlp -v "https://www.eurosport.com/tennis/roland-garros/2022/watch-the-top-five-shots-from-men-s-final-as-rafael-nadal-beats-casper-ruud-to-seal-14th-french-open_vid1694283/video.shtml"
[debug] Command-line config: ['-v', 'https://www.eurosport.com/tennis/roland-garros/2022/watch-the-top-five-shots-from-men-s-final-as-rafael-nadal-beats-casper-ruud-to-seal-14th-french-open_vid1694283/video.shtml']
[debug] Portable config "~\yt-dlp.conf": ['--netrc-location', '~yt-dlp_netrc']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158f7] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: cd4df5ffa
[debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1-full_build-www.gyan.dev (setts), ffprobe 5.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Using fake IP 53.218.24.4 (DE) as X-Forwarded-For
[Eurosport] Trying to get token
[debug] [Eurosport] Extracting URL: https://www.eurosport.com/tennis/roland-garros/2022/watch-the-top-five-shots-from-men-s-final-as-rafael-nadal-beats-casper-ruud-to-seal-14th-french-open_vid1694283/video.shtml
[Eurosport] vid1694283: Downloading webpage
[Eurosport] vid1694283: Downloading JSON metadata
[Eurosport] vid1694283: Downloading MPD manifest
[Eurosport] vid1694283: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), channels, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2481254: Downloading 1 format(s): 7634-1+audio_0-Default-1
[debug] Invoking hlsnative downloader on "https://eurosport-vod.akamai.prod-live.h264.io/primary/3/2a5e6e52edbc463e866ab25906e5d613/06f683030f9a485d9ce8ef187a6cc0de/hdntl=exp=1660227623~acl=/primary/3/2a5e6e52edbc463e866ab25906e5d613/06f683030f9a485d9ce8ef187a6cc0de/*~data=hdntl~hmac=c8003cfb4a3b780db002f6234942fe6bcd63c41ad69d364ead0b6896fe8f2dee/888b802aa23d4bc9b3111997063e3fa5/2bf445ce214f4c0d9c1208a0a8ae2b2e/5d88433b697c4988beabc4839719c825/index_1.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 22
[download] Destination: Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].f7634-1.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of 103.72MiB in 01:16 at 1.36MiB/s
[debug] Invoking hlsnative downloader on "https://eurosport-vod.akamai.prod-live.h264.io/primary/3/2a5e6e52edbc463e866ab25906e5d613/06f683030f9a485d9ce8ef187a6cc0de/hdntl=exp=1660227623~acl=/primary/3/2a5e6e52edbc463e866ab25906e5d613/06f683030f9a485d9ce8ef187a6cc0de/*~data=hdntl~hmac=c8003cfb4a3b780db002f6234942fe6bcd63c41ad69d364ead0b6896fe8f2dee/888b802aa23d4bc9b3111997063e3fa5/2bf445ce214f4c0d9c1208a0a8ae2b2e/5d88433b697c4988beabc4839719c825/index_9_0.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 22
[download] Destination: Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].faudio_0-Default-1.mp4
[download] 100% of 2.00MiB in 00:09 at 223.25KiB/s
[debug] ffmpeg command line: ffprobe -show_streams "file:Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].faudio_0-Default-1.mp4"
[Merger] Merging formats into "Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].f7634-1.mp4" -i "file:Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].faudio_0-Default-1.mp4" -c copy -map "0:v:0" -map "1:a:0" "-bsf:a:0" aac_adtstoasc -movflags "+faststart" "file:Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].temp.mp4"
Deleting original file Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].faudio_0-Default-1.mp4 (pass -k to keep)
Deleting original file Watch the top five shots from men's final as Rafael Nadal beats Casper Ruud to seal 14th French Open title [2481254].f7634-1.mp4 (pass -k to keep)
```

**Comment by pukkandan** [comment]
Right, `--test` doesn't work with PPs. Use `--fixup never`

**Pull request merged**
