### PR TITLE
[youtube] Options for begin and end of recording live streams

### LINKED ISSUE #3451: [Youtube] --live-from-start support for sequence / range download
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi, 
I try to implement capability of youtube livestream download (--live-from-start), that we can determine from which sequence it starts downloads until live/current live, or range from sequence A to sequence B by changing some parts on `extractor/youtube`
In my case this is working well as expected, and super useful, and I want to know what you guys think.
Maybe if this is good enough I hope I can be push it upstream, or let this be just a feature request :)

commit: https://github.com/mxvin/yt-dlp/commit/ecf8b603c2f6e1356ab13c8912c9d29111ecc0dd

### Verbose log

_No response_

### PR DESCRIPTION
**Pull request by azatoth**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

Options for begin and end of recording live streams
    
Extend `--live-from-start` with two options `-live-from-start-begin`and `-live-from-start-end` which will limit the recording to between these values.
    
`--live-from-start-end` is optional and if omitted will continously record as normal.

While as generic as the existing `--live-from-start` option, it's limited to youtube for now.

Example:
```sh
yt-dlp https://www.youtube.com/watch?v=nbBeoReu12E --live-from-start --live-from-start-begin 2022-12-18T10:35:00+01:00 --live-from-start-end 2022-12-18T10:35:16+01:00
```

Fixes #3451

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [x] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
Don't add new switches. Instead, make the feature obey `--download-sections *start-end`. The downloader can access the timestamps at `section_start/end` keys in the info_dict

**Comment by azatoth** [comment]
> Don't add new switches. Instead, make the feature obey `--download-sections *start-end`. The downloader can access the timestamps at `section_start/end` keys in the info_dict

I was thinking about using that one but as it's explicitly prohibited to be used when live I thought it was better to not try to attempt that.

**Comment by pukkandan** [comment]
> it's explicitly prohibited to be used when live

This is because we don't have an implementation for it

**Comment by azatoth** [comment]
> > it's explicitly prohibited to be used when live
> 
> This is because we don't have an implementation for it

I assume you have a totally different implementation in mind as I can't see it possible to utilize `--download-sections` for this. neither to be able to specify sections (chapters), nor having multiple separate sections.

**Comment by azatoth** [comment]
> Don't add new switches. Instead, make the feature obey `--download-sections *start-end`. The downloader can access the timestamps at `section_start/end` keys in the info_dict

So I can see `--download-sections` to work if we add following restrictions when we are under a live stream:

1. make end optional
2. have it count backwards from time of start downloading
3. disallow specifying chapter(s)
4. disallow multiple ranges

imo making these stipulations makes a totally separate function than what we currently have.

**Comment by pukkandan** [comment]
> * make end optional

This is already the case

> * have it count backwards from time of start downloading

Is there no way around this? If we can determine the current length of the stream (or the start time), we can translate b/w the two systems. This will also allow to implement https://github.com/yt-dlp/yt-dlp/issues/4554 and https://github.com/yt-dlp/yt-dlp/issues/5608 in future

> * disallow specifying chapter(s)

Chapter to timestamp translation is done by core code. You don't need to be concerned about it. Besides, I believe live streams cannot have chapters anyway (maybe premiers can have it?)

> * disallow multiple ranges

This is a problem only if we cannot solve (2)

**Comment by azatoth** [comment]
> Is there no way around this? If we can determine the current length of the stream (or the start time), we can translate b/w the two systems. This will also allow to implement #4554 and #5608 in future

While it would be possible to count from start of live stream, I think that would be impractical for most usecases as it would require the user to know exactly when the live stream started.
Counting from the `MAX_DURATION` would make it practically impossible to use as the window would move.

I can think of two compromises:
* Allow specifying start/end as unixtime, i.e. `--download-sections "@1671698944-1671698964"`
* Allow negative values, i.e. `--download-sections *-start--end`

**Comment by pukkandan** [comment]
> * Allow negative values, i.e. `--download-sections *-start--end`

Allowing negative values is trivial and I can add it in core code. Just make the downloader handle +ive values, and make sure the extractor returns correct `timestamp`/`release_timestamp`

**Comment by azatoth** [comment]
> Allowing negative values is trivial and I can add it in core code. Just make the downloader handle +ive values, and make sure the extractor returns correct `timestamp`/`release_timestamp`

Can you explain what you mean by "+ive values"? 

I must confess I've problem navigate the code; And I'm not sure what you want me to accomplish :/

**Comment by kadamwhite** [comment]
Could "+ive" mean "positive"?

**Comment by SnowSquire** [comment]
i would like this feature merged

**Comment by halimselim** [comment]
https://github.com/halimselim/yt-dlp/releases/tag/2023.02.28.215904
I tested [azatoth](https://github.com/azatoth/yt-dlp)'s version and it works, and released it for Linux and Windows.

**Comment by mrienstra** [comment]
Working for me as well, installed using:

```
python3 -m pip install -U pip setuptools wheel
python3 -m pip install --force-reinstall https://github.com/azatoth/yt-dlp/archive/live_from_start_range.tar.gz
```

There seems to be a variable offset between the time requested and the time downloaded, I tried 3 different livestreams, each had a different offset (-0h32m15s, -3h12m16s, +2h52m53s). This offset may drift slowly as well, still testing.

The "Starting download from the last 120 hours of the live stream since YouTube does not have data before that" warning should probably be suppressed when using these flags. See [extractor/youtube.py#L2763-L2765](https://github.com/yt-dlp/yt-dlp/blob/9b7a48a/yt_dlp/extractor/youtube.py#L2763-L2765).

Would be nice to have an accurate `fragment_count` shown, right now it shows something like `(frag 406/222451)`.

It would be great to have the option to specify the start & end using either:
* Same offset as used by the `&t=` URL param, which is in seconds, though you can also pass it as `&t=38h20m03s`. Time elapsed since stream started.
* Same offset as used by clips, the initial HTML payload when loading a clip contains (in JS) `ytInitialPlayerResponse.clipConfig.startTimeMs` & `ytInitialPlayerResponse.clipConfig.endTimeMs`, these values are the same as `&t=` URL param except in milliseconds rather than seconds.

But more importantly, it would be great to get this "good enough" and merged. @pukkandan, what do you need to see addressed at this point?

**Comment by pukkandan** [comment]
The PR is on my radar, but so is so many others. I believe I have explained the changes needed in above comments (mainly https://github.com/yt-dlp/yt-dlp/pull/5822#issuecomment-1356814571). If OP (or anyone else) cannot address them, I plan to get around to make the changes myself eventually. But it will take time - like I said, so many stuff on my plate and only so much time I can spare. If you want to expedite the process, try and help with making the changes, or even spin up your own PR.

**Comment by mrienstra** [comment]
Thanks @pukkandan, appreciate the response!

@azatoth, any thoughts on how to proceed? I've started poking around to try to figure out how to proceed, but I'm new to this codebase.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/pull/6498 is a nicer implementation and superseeds this

**Comment by azatoth** [comment]
> #6498 is a nicer implementation and superseeds this

Fair enough, should I close this one?

**Comment by mrienstra** [comment]
@azatoth, if you close this, I'd appreciate it if you could delay deleting your branch until #6498 has been merged. Otherwise I'd be unable to return to using your branch after testing #6498 (assuming I do so again), which would mean no way to download stream segments!

... Well, I guess I can just download the archive -- done! -- but still, might be nice to have your work as a reference while #6498 is still in the oven.

**Comment by Grub4K** [comment]
Closed bc superseeded

**Pull request closed without merging**
