### PR TITLE
[dont-ignore-me] Fix allows clean

### PR DESCRIPTION
**Pull request by sulyi**
### Description of your *pull request* and other information

This allows removing artefacts in `test/` by running `git clean -f test`

Imho, 337e0c62f894722e9c268b14d02a85b84c96024d should be seriously reconsidered.
Ignored artefacts are starting to appear in root as well for me.

Originally this has to do something with #352, but tl;dr... sorry.

### Test

- [x] run `make clean-test`

### CODE REVIEW

**Comment by pukkandan** [comment]
The artifacts should not be committed, so they are ignored in gitignore. `make clean-test` is what is supposed to clean up the artifacts. If it is missing something, let me know

**Comment by sulyi** [comment]
If it works, don't fix it...

`make clean-test` also removes `test/testdata/player-*.js *.frag.aria2` and does `*.part*`

node of `make clean-test`, `make clean-dist` nor `make clean-cache` removes these:
`*.ogg cookies *.annotations.xml *.part *.m4v *.sbv *.conf *cookies.txt *.flac *.live_chat.json *.swp *.srt *.aria2 *.description` or `*.part-*` but last one is removed by above.

This was a head scratcher, for me to comprehend, but think this does make it easier to stage with git, right?

**Comment by pukkandan** [comment]
You can add these to clean-test (except cookies and conf). I have just been adding extensions to gitignore and clean-test as I encounter them. Sometimes I just forget to add it to one or the other

> but think this does make it easier to stage with git, right?

Yeah. I always have test artifacts lying around. git tracking them is annoying

PS: `.aria2` is no longer used

**Comment by sulyi** [comment]
Is `*.annotations.xml`  and `*.description` download artefact?

**Comment by pukkandan** [comment]
yes. .annotations are youtube annotations which dont exist anymore.
.description is generated when using `--write-description`

**Comment by sulyi** [comment]
Made them ordered alnum.

**Pull request merged**
