### PR TITLE
[ruutu] Add extractor for nelonen.fi

### PR DESCRIPTION
**Pull request by tpikonen**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] New extractor

---

### Description of your *pull request* and other information

Add extractor for video clips in nelonen.fi, which uses ruutu.fi for streaming.

### CODE REVIEW

**Comment by pukkandan** [comment]
Isn't it better to add a `_extract_urls` for `RuutuIE` and add it to generic?

**Comment by tpikonen** [comment]
> Isn't it better to add a _extract_urls for RuutuIE and add it to generic?

No idea, but I can modify this PR to do that if needed. Is there any documentation on _extract_urls, or should I just go by example from other extractors?

**Comment by pukkandan** [comment]
> Is there any documentation on _extract_urls

Actually no :( - because there is actually no standardized interface for it. Most extractors follow the pattern that I will explain below, but some (older) extractors deviate from it, making it tricky to standardize

In extractor:
```py
@classmethod
def _extract_urls(cls, webpage):
    ...
    yield url
```
In generic:
```py
ruutu_urls = RuutuIE._extract_urls(webpage)
if ruutu_urls:
    return self.playlist_from_matches(ruutu_urls, video_id, video_title, ie=RuutuIE)
```

OR

In extractor:
```py
@classmethod
def _extract_url(cls, webpage):
    ...
    return url
```
In generic:
```py
ruutu_url = RuutuIE._extract_url(webpage)
if ruutu_url:
    return self.url_result(ruutu_url, RuutuIE)
```

**Comment by tpikonen** [comment]
I'm not sure if I like this style of adding support to a site (no tests!), but here goes. Thanks for the explanation on _extract_url, @pukkandan.

**Comment by pukkandan** [comment]
tests can be added in generic extractor

**Comment by tpikonen** [comment]
> tests can be added in generic extractor

Thanks for the fixes. Should I add a testcase, or is this done?

**Comment by pukkandan** [comment]
I would be willing to merge this without a test, but best to add one

**Comment by tpikonen** [comment]
Ok, I added the test case from the first version of this PR.

**Pull request merged**
