### PR TITLE
[ie/imgur] Support new URL format

### PR DESCRIPTION
**Pull request by Deer-Spangle**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

This pull request adds support for the new format of imgur URLs which contain a title slug, for example:
https://imgur.com/mrw-gifv-is-up-running-without-any-bugs-A61SaA1
instead of simply:
https://imgur.com/A61SaA1

It doesn't seem a bug was raised for this, which seems surprising

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Review by seproDev — APPROVED** [review]

**Review by seproDev — CHANGES_REQUESTED** [review]
Actually, taking a second look, these tests are incomplete. Please run them, and fill them out properly.

**Review by bashonly — CHANGES_REQUESTED** [review]

**Comment by Deer-Spangle** [comment]
Apologies for the delay there, I've fixed those tests now. Let me know what else might be required

**Comment by seproDev** [comment]
Did you run the tests you added? They are still missing a bunch of info.

**Comment by Deer-Spangle** [comment]
> Did you run the tests you added? They are still missing a bunch of info.

Oh bloody heck, I see the problem.
I ran `hatch test ImgurIE ImgurGalleryIE ImgurAlbumIE` and assumed that ran all the tests for all 3 of those extractor classes. But it seems that only runs the first test case for each.
I guess I actually have to run `hatch test ImgurIE_all ImgurGalleryIE_all ImgurAlbumIE_all`? That seems quite an unintuitive interface. (Also, it then stops at the first failed test case, which is a bit weird if each one is considered a separate test. Not how most frameworks seem to work there)

I had assumed I didn't need to fill out every attribute of the info dicts, as that seemed like it would just be increasing the fragility imo. But yeah, it does complain about that once it's actually running them all, not just the first it finds...

Okay, should all be fixed now, unless there's another hatch command to try?

**Pull request merged**
