### PR TITLE
[cookies] Add `--cookies-from-browser` support for Whale

### PR DESCRIPTION
**Pull request by roeniss**
### Description of your *pull request* and other information

Currently, yt-dlp doens't support --cookies-from-browser Naver Whale browser because the browser uses its own directory in Windows, macOS, and Linux.

Luckily, Naver Whale is based on Chromium, so thanksfully I could just add a little bit of code.

Fixes https://github.com/yt-dlp/yt-dlp/issues/9307

- I didn't add a test because cookie-related tests seems that it doens't test each of browsers. But If it's needed, please tell me then I'll try my best.
- I did dog-fooding with macOS 14.2, Ubuntu Desktop 22.04, Windows 11. I failed on Windows because of https://github.com/yt-dlp/yt-dlp/issues/7271 but the user data directory is confirmed

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

edit: Add a mention for dog-fooding

### CODE REVIEW

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/2903

**Comment by bashonly** [comment]
@pukkandan see #9307. Whale uses a different keyring on linux and can't be supported as chromium/chrome

**Comment by pukkandan** [comment]
I see. Is this a common thing? Is https://github.com/yt-dlp/yt-dlp/issues/7805 similar issue? If so, it would be more beneficial to support passing keyring name in the CLI than adding just whale.

**Comment by bashonly** [comment]
> Is https://github.com/yt-dlp/yt-dlp/issues/7805 similar issue?

Looks like possibly yes, but really there's no way to tell from the limited info in that issue.

> If so, it would be more beneficial to support passing keyring name in the CLI than adding just whale.

Maybe? But cramming more into the `--cookies-from-browser` syntax would not be great IMO. Would the user even necessarily know what the keyring name is? I think it might be better to add proper support for these browsers, as the alternative is involuntarily maintaining some sort of knowledge bank of keyring names in our tracker that we direct users to every time we get a dupe issue opened about one

**Comment by pukkandan** [comment]
I am concerned the list will quickly grow too large, but I see your point. We can merge this for now and think of generalization if this keeps coming up

**Comment by roeniss** [comment]
Wait please, I'll review my PR within 24 hours from now. Some fix seems not merged.

**Comment by coletdjnz** [comment]
> > Is https://github.com/yt-dlp/yt-dlp/issues/7805 similar issue?
> 
> Looks like possibly yes, but really there's no way to tell from the limited info in that issue.
> 
> > If so, it would be more beneficial to support passing keyring name in the CLI than adding just whale.
> 
> Maybe? But cramming more into the `--cookies-from-browser` syntax would not be great IMO. Would the user even necessarily know what the keyring name is? I think it might be better to add proper support for these browsers, as the alternative is involuntarily maintaining some sort of knowledge bank of keyring names in our tracker that we direct users to every time we get a dupe issue opened about one

I think at this point we should support more browsers for convenience of the user..

Large list of supported browsers doesn't matter imo. You could throw the full list into a section of the README, with only the main few listed on the option help string

**Comment by roeniss** [comment]
code check is done. 

I think there must be serveral ways instead of adding one by one. We just temporarily need more browsers example to decide which way to go. This is one of them.

**Comment by roeniss** [comment]
Should I do something else to be merged?

**Comment by roeniss** [comment]
@pukkandan gentle ping

**Pull request merged**
