### PR TITLE
[ie/Dropbox] supported password,thumbnail

### PR DESCRIPTION
**Pull request by ndyanx**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information
This pull request adds support for Dropbox password and thumbnail extraction. 

**Changes:**
- Added functionality to handle password-protected Dropbox links.
- Implemented thumbnail extraction for Dropbox videos.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by bashonly** [comment]
I would like to review this soon since the patch looks basically merge-able, but what's going on here with the YandexDisk commit and the closing/re-opening?

**Comment by ndyanx** [comment]
I'm sorry for the mess caused, please: "learning"

**Comment by Grub4K** [comment]
Don't worry, take your time. We all are 😄

**Comment by bashonly** [comment]
@ndyanx I understand. If you want, I could help clean this up and push my code suggestions directly for you to test

**Pull request closed without merging**
