### PR TITLE
[youtube] fix for signature decode function detection

### PR DESCRIPTION
**Pull request by PSlava**
Signed-off-by: Slava <slash@i-slash.com>

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by pukkandan** [comment]
Provide example of a player where this is useful

**Comment by PSlava** [comment]
https://www.youtube.com/s/player/be9c9f3b/player_ias.vflset/en_US/base.js

**Comment by PSlava** [comment]
Anyway. There is a strange code for regexp. You are expecting for 2 char function. According to history YouTube uses 3 char functions.

**Comment by PSlava** [comment]
Sorry

> https://www.youtube.com/s/player/be9c9f3b/player_ias.vflset/en_US/base.js

It's not relevant link. Since my request YouTube have changed player url.
I have saved player content.

**Comment by PSlava** [comment]
I've found link in my history: https://www.youtube.com/s/player/850eb2bc/player_ias.vflset/en_US/base.js

**Pull request merged**
