### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by KPCOFGS**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Updated relative links to absolute links for PyPI documentation compatibilities

ADD DESCRIPTION HERE

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))
- [x] Documentation fixes

</details>

### CODE REVIEW

**Comment by bashonly** [comment]
This won't work, since multiple versions of the README exist on Github (e.g. `master` vs `2024.04.09` vs `8e15177b4113c355989881e4e030f695a9b59c3a` etc), but all links would point to the `master` version.

The proper approach would be to process the README via script before publishing to PyPI. See #6271 for more discussion

**Comment by KPCOFGS** [comment]
Hello! Thank you for your feedback! I see what the problem is. One way that can potentially fix this problem is to change the part of the url where it says `/master/` to a certain variable and then make a workflow that can automatically change that variable to the proper branch name. 

I just created a GitHub workflow and tested it on my fork and apparently it's working as expected. On my forked README.md file, I changed my previous absolute paths,`/master/` to `VARIABLE`, then the workflow changed `VARIABLE` back to the branch name

**Comment by KPCOFGS** [comment]
Edit: Changed `VARIABLE` to `THIS_VARIABLE` as the previous one resulted in conflicts

**Comment by pukkandan** [comment]
Only the PyPI description should be changed - not the readme that is committed into the repo

**Pull request closed without merging**
