### PR TITLE
[ie/stv] Add DRM account id

### PR DESCRIPTION
**Pull request by aarubui**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Adds correct Brightcove account ID for DRM protected videos. Previously rejected in #5834 for explicitly supporting protected content. Appealing the rejection as the codebase has many cases of only calling `report_drm()` without `--allow-unplayable-formats`.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by seproDev** [comment]
You already got your answer last time. We will not add additional code to yt-dlp to enable downloading of DRM protected media. Circumventing copy protection is illegal in most jurisdictions and making such additions would put the project at risk. This is non negotiable.

**Comment by aarubui** [comment]
@seproDev I see what you mean now. You really should have made it clear that your point was "**additional** code". That was not made clear last time (and not that clear this time either). But you're still kidding yourselves if you think "someone else wrote the code", "someone else merged the code" or "that was already there when I became a collaborator" are valid excuses.

**Comment by aarubui** [comment]
@seproDev Or maybe the real reason's something else. Maybe it's to do with how long ago the code was merged. Maybe you're deciding based on what country the site's from. Maybe it's as specific as not wanting the ID of a Brightcove account that only has protected videos hardcoded. You can have whatever policy you want and even believe it actually makes any difference _legally_. Just like how you can't state specifically what your policy is (or respond in any way) in case it makes a difference _legally_.

Just don't tell me "You already got your answer last time." I asked for why some cases are allowed and some cases aren't. And you don't allow youselves to give the reason.

**Comment by bashonly** [comment]
The `allow_unplayable_formats` parameter and most related code will be removed from the codebase soon.

**Comment by aarubui** [comment]
> The `allow_unplayable_formats` parameter and most related code will be removed from the codebase soon.

@bashonly That's great to hear. You've restored some respect for yourselves rather than having a willy-nilly policy on DRM that helps no one.

**Pull request closed without merging**
