### PR TITLE
Man page: Clarify behavior of `--check-formats`

### PR DESCRIPTION
**Pull request by danielyli**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement — documentation
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

It looks like `--check-formats` attempts to download the next best format if the server 503s on the best one. This PR clarifies this behavior in the manpage.

Related: [#3308](https://github.com/yt-dlp/yt-dlp/issues/3308#issuecomment-1088277324)

### CODE REVIEW

**Comment by pukkandan** [comment]
It doesn't help with just "best" selection, but also with `-f f1/f2/f3`. How about this:
```
Make sure formats are selected only from those that are actually downloadable
```

**Comment by danielyli** [comment]
I like that :) Updated.

**Comment by danielyli** [comment]
What’s remaining for this PR to be merged?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/commit/ebc7d3ff1f39a2f71ab7360ce25a37da744c8f3e

**Pull request closed without merging**
