### PR TITLE
Use "There are no" text in log output when attempting to download YouTube subtitles or thumbnails for a video without them

### PR DESCRIPTION
**Pull request by synthead**
Simple grammar fix in log output for YouTube when no subtitles exist for requested languages, and when attempting to download thumbnails when thumbnails aren't present.

Before:

```
[info] There's no subtitles for the requested languages
```

After:

```
[info] There are no subtitles for the requested languages
```

"There's" is a contraction for "there is," and "there is no subtitles" is not correct, as "is" is singular.

Fixes https://github.com/yt-dlp/yt-dlp/issues/6726

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by pukkandan** [comment]
Same for thumbnails

**Comment by synthead** [comment]
> Same for thumbnails

@pukkandan, are you suggesting to also fix possible grammar issues for thumbnails as a part of this PR?

**Comment by pukkandan** [comment]
Yes. The same sentence is used for thumbnails and description. For description, it makes sense since there is only one. Since you are fixing subs, fix thumbs too.

**Comment by synthead** [comment]
@pukkandan, I included a grammar fix for thumbnails and updated this PR's title and body to reflect the changes :+1:

**Comment by synthead** [comment]
Hi @pukkandan!  Are there any other changes you'd like me to add to this PR?  Thanks!

**Pull request closed without merging**
