### PR TITLE
Fix a few typos in README

### PR DESCRIPTION
**Pull request by ghost**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Fix a few typos in README.

### CODE REVIEW

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/pull/1404#issuecomment-950609743
Same is mentioned in contributing.md

**Comment by q1800** [comment]
Hello,

I did look through the CONTRIBUTING.md file, but I saw nothing specifically calling out anything on correcting typos or other documentation errors.

I am sorry to be a bother to you and for obviously wasting your time.

I will go ahead and close this pull request.

Again, my apologies.

**Comment by pukkandan** [comment]
I hope you can understand that it's annoying to deal with a lot of "fix typo" PRs/issues. I will apply these changes anyway, but as I said in the other PR, I don't want to encourage this unless it is a significant change

**Comment by gamer191** [comment]
Please ignore this comment. It is semi-automated and is intended to ensure PRs by @ghost get indexed by Github

**Pull request closed without merging**
