### PR TITLE
[generic] improve KVS player video extraction

### PR DESCRIPTION
**Pull request by trassshhub**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Current generic KVS player extractor does not work correctly on porntrex.com and issues were identified in #2281.
This is the follow up PR.

### CODE REVIEW

**Comment by trassshhub** [comment]
I am not very good with python yet so there is probably a better way to write the loop instead of using while True

**Comment by trassshhub** [comment]
I learnt a lot from your edit, just want to point out that the regexp
https://github.com/yt-dlp/yt-dlp/blob/77b28f000a2cbe6f974e642ffb154c4bee325126/yt_dlp/extractor/generic.py#L3778
should be r'video_url|video_alt_url\d*' as the second key is "video_alt_url" instead of "video_alt_url1"

**Comment by nindogo** [comment]
Thanks again @trassshhub also thanks to @pukkandan for review.

**Comment by nindogo** [comment]
> should be r'video_url|video_alt_url\d*' as the second key is "video_alt_url" instead of "video_alt_url1"

image

Yes it ignores the 480p now

image

**Pull request merged**
