### PR TITLE
Build mac os packages

### PR DESCRIPTION
**Pull request by smplayer-dev**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

As requested [here](https://github.com/yt-dlp/yt-dlp/issues/1075), this creates two packages for Mac OS with the Python3 runtime, one with one file only and the other with one directory. 

The option to create a universal2 application didn't work for me, so this creates a 64-bit application.

I modified pyinst.py so it can be use with macos as well, and had to add certifi to the list of modules, otherwise the links wouldn't load due to ssl errors.

### CODE REVIEW

**Comment by pukkandan** [comment]
There is also the issue of auto-updates. You MUST add a way to detect the mac bin apart from all the other variants to `update.detect_variant`. I believe, a combination of `frozen`, `_MEIPASS` and the `os_name` is sufficient for this.

As for the actual update mechanism, if you can make it work, that would be great. If not, add a message to `update._NON_UPDATEABLE_REASONS` like 
```py
'mac_bin': 'Auto-update is currently not supported for MacOS standalone binary; Re-download the latest release'
```

**Comment by pukkandan** [comment]
Test build: https://github.com/pukkandan/yt-dlp-dev/releases/tag/2021.10.20.

It's update URL has been adjusted to point to  https://github.com/pukkandan/yt-dlp-dev/releases/tag/2021.10.20.1 . Please confirm that it can be updated with `-U`

**Comment by pukkandan** [comment]
Oh, that's my mistake. Let me fix that and make another build

**Comment by pukkandan** [comment]
Fixed: https://github.com/pukkandan/yt-dlp-dev/releases/tag/2021.10.21

**Comment by pukkandan** [comment]
@smplayer-dev The mac build is failing https://github.com/yt-dlp/yt-dlp/actions/runs/1442166835. Can you have a look?

**Comment by smplayer-dev** [comment]
> @smplayer-dev The mac build is failing https://github.com/yt-dlp/yt-dlp/actions/runs/1442166835. Can you have a look?

Maybe a bug in pyinstaller 4.6?
Installing version 4.5.1 seems to fix it.

`/usr/bin/python3 -m pip install -U --user pip Pyinstaller==4.5.1 mutagen pycryptodomex websockets`

**Comment by jefft666** [comment]
Man what a bummer. I was hoping to switch to YT-DLP since YT-DL has so many unresolved bugs. Guess I'll just follow this bug report and grab it once it's building again for MacOS.

**Pull request merged**
