### PR TITLE
DiscoveryPlus: add auth

### LINKED ISSUE #2950: discovery italy gives error HTTPError 404: 'Not Found'
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Description

Hello, when trying to download file info from https://www.discoveryplus.com/it/video/fratelli-di-crozza/stagione-6-puntata-1-del-18-febbraio-2022 i got this annoying error, just at the -F

Unable to download JSON metadata: HTTP Error 404: Not Found

thanks in advance!!

### Verbose log

```shell
C:\Users\Fede\Desktop\youtube_dl>yt-dlp.exe --verbose -F "https://www.discoveryplus.com/it/video/fratelli-di-crozza/stagione-6-puntata-1-del-18-febbraio-2022"
[debug] Command-line config: ['--verbose', '-F', 'https://www.discoveryplus.com/it/video/fratelli-di-crozza/stagione-6-puntata-1-del-18-febbraio-2022']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.25 [87e0499] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-12-23-git-60ead5cd68-essentials_build-www.gyan.dev (setts), ffprobe 2021-12-23-git-60ead5cd68-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [DiscoveryPlusItaly] Extracting URL: https://www.discoveryplus.com/it/video/fratelli-di-crozza/stagione-6-puntata-1-del-18-febbraio-2022
[debug] [DPlay] Extracting URL: https://discoveryplus.it/video/fratelli-di-crozza/stagione-6-puntata-1-del-18-febbraio-2022
[debug] Using fake IP 79.48.245.10 (IT) as X-Forwarded-For
[DPlay] fratelli-di-crozza/stagione-6-puntata-1-del-18-febbraio-2022: Downloading token
[DPlay] fratelli-di-crozza/stagione-6-puntata-1-del-18-febbraio-2022: Downloading JSON metadata
ERROR: [DPlay] fratelli-di-crozza/stagione-6-puntata-1-del-18-febbraio-2022: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 717, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3456, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

### PR DESCRIPTION
**Pull request by timendum**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Add the cookie/auth part in class `DiscoveryPlusBaseIE`, so that all request will be authenticated (from cookie or with a anonymous token)

Fixes #2950, probably  #2361 (but it's geo restricted) and #2138

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)

### CODE REVIEW

**Comment by fedepr** [comment]
hello!
i have tried the following
yt-dlp.exe -Uv --cookies-from-browser firefox -f dash-video=798048 https://www.discoveryplus.com/it/video/uomini-di-pietra/stagione-2-cambio-al-vertice

i do not get 404 but i get 
HTTP Error 403: Forbidden. Retrying fragment 1

full log here
[debug] Command-line config: ['-Uv', '--cookies-from-browser', 'firefox', '-f', 'dash-video=798048', 'https://www.discoveryplus.com/it/video/uomini-di-pietra/stagione-2-cambio-al-vertice']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-12-23-git-60ead5cd68-essentials_build-www.gyan.dev (setts), ffprobe 2021-12-23-git-60ead5cd68-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "***"
[Cookies] Extracted 1609 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [DiscoveryPlusItaly] Extracting URL: https://www.discoveryplus.com/it/video/uomini-di-pietra/stagione-2-cambio-al-vertice
[debug] Using fake IP 79.25.72.20 (IT) as X-Forwarded-For
[DiscoveryPlusItaly] uomini-di-pietra/stagione-2-cambio-al-vertice: Downloading JSON metadata
[DiscoveryPlusItaly] 1059737: Downloading JSON metadata
[DiscoveryPlusItaly] uomini-di-pietra/stagione-2-cambio-al-vertice: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 1059737: Downloading 1 format(s): dash-video=798048
[debug] Invoking dashsegments downloader on "https://dplus-it-google-v2.prod-vod.h264.io/20e54809-c643-461c-a88e-ca1ade600ed7/993d665d-0c66-43c9-b02e-a075718b10d6/dash_clear_fmp4/x-goog-token=Expires=1664120411&KeyName=prod-sign-url-key-eu&Signature=533ch-y4_wuRyPa8fRT4mrjfO-g/master.mpd"
[dashsegments] Total fragments: 1491
[download] Destination: Cambio al vertice [1059737].mp4
[debug] File locking is not supported. Proceeding without locking
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
  File "yt_dlp\__main__.py", line 18, in <module>
  File "yt_dlp\__init__.py", line 962, in main
  File "yt_dlp\__init__.py", line 954, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3293, in download
  File "yt_dlp\YoutubeDL.py", line 3268, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1448, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1556, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1614, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2712, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3171, in process_info
  File "yt_dlp\YoutubeDL.py", line 2895, in dl
  File "yt_dlp\downloader\common.py", line 443, in download
  File "yt_dlp\downloader\dash.py", line 54, in real_download
  File "yt_dlp\downloader\fragment.py", line 373, in download_and_append_fragments_multiple
  File "yt_dlp\downloader\fragment.py", line 517, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 463, in download_fragment
  File "yt_dlp\utils.py", line 5794, in __iter__
  File "yt_dlp\downloader\fragment.py", line 460, in error_callback
  File "yt_dlp\downloader\common.py", line 388, in report_retry
  File "yt_dlp\utils.py", line 5801, in report_retry
  File "yt_dlp\downloader\common.py", line 391, in <lambda>
  File "yt_dlp\YoutubeDL.py", line 994, in report_error
  File "yt_dlp\YoutubeDL.py", line 923, in trouble

ERROR: fragment 1 not found, unable to continue
  File "yt_dlp\__main__.py", line 18, in <module>
  File "yt_dlp\__init__.py", line 962, in main
  File "yt_dlp\__init__.py", line 954, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3293, in download
  File "yt_dlp\YoutubeDL.py", line 3268, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1448, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1556, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1614, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2712, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3171, in process_info
  File "yt_dlp\YoutubeDL.py", line 2895, in dl
  File "yt_dlp\downloader\common.py", line 443, in download
  File "yt_dlp\downloader\dash.py", line 54, in real_download
  File "yt_dlp\downloader\fragment.py", line 373, in download_and_append_fragments_multiple
  File "yt_dlp\downloader\fragment.py", line 518, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 482, in append_fragment
  File "yt_dlp\YoutubeDL.py", line 994, in report_error
  File "yt_dlp\YoutubeDL.py", line 923, in trouble

how can i proceed?

**Comment by pukkandan** [comment]
@timendum Is this tested with all subclasses?

**Comment by timendum** [comment]
I'm unable to test with other extractors, because they are all geo-restricted.

But it only add functionality for un-authenticated users.

**Comment by pukkandan** [comment]
The change you are making affects all dplay extractors I cannot merge it without sufficient testing

**Pull request closed without merging**
