### PR TITLE
[ie/tvbanywherena] New extractor

### PR DESCRIPTION
**Pull request by aarubui**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Add support for https://www.tvbanywherena.com/

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by aarubui** [comment]
Ideally, I'd:
* use Brightcove's `custom_fields` for video info
* defer to `BrightcoveNewIE` with a `https://players.brightcove.net/.../index.html?playlistId=` URL for playlists

but I can't get either to work without touching `brightcove.py`.

**Comment by bashonly** [comment]
Sorry I haven't able to get around to reviewing this. I am a bit swamped right now, and there are really only 2 of us doing extractor PR reviews. If you want to reopen this (or open a new PR), I will try to get to it eventually. I do see all of the PRs that are opened and intend to get around to all of them. I apologize if you felt ignored or frustrated by the lack of review so far.

**Comment by aarubui** [comment]
@bashonly I didn't realise deleting the fork would close the PRs. I remember GitHub wasn't doing that in the past. Just as well, as no-one's opened as issue wanting this extractor, this would have the very lowest of priority so you won't get around to this ever and nor should you. Same as the #11207, which is nothing more than an aesthetic change.

I'm only a volunteer to help the maintainers (aka owners of the codebase) in their **personal** aim to support as many sites as possible and make the best software. You should never apologise to the contributers as you owe them nothing. If that's not the case and this project is supposed to be by the community, for the community, you should really open the project up to more maintainers, whatever the consequence it brings to the quality. Having it both ways is hypocrisy.

**Comment by denychen** [comment]
@aarubui, I'm interested in seeing support for this extractor. Do you want me to formally open an issue for the request before reopening/recreating this PR?

And thank you @bashonly for your work!

**Comment by aarubui** [comment]
@denychen Personally, I'd rather you didn't as I think this project already has too many extractors for the maintainers to manage. Just use it yourself by putting the code in your `yt_dlp_plugins` directory.

**Pull request closed without merging**
