### PR TITLE
[extractor/tubitv]

### PR DESCRIPTION
**Pull request by shloop**
- Adds correct series and episode names when downloading shows.
- Fixes series ID assignment.
- Reduces HTTP requests to a single call no matter what type of content is being downloaded.
  - A series/episode webpage contains JSON with information pertaining to every episode in the series, so the data is smuggled for individual episode downloads.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
* There is no need to smuggle, just use url_transparent
* Don't remove tests

**Comment by shloop** [comment]
Stopped working on this for a while due to major life events. Just updated the code as requested to restore the missing test cases, added some clarifying comments, and updated the pull request summary.

**Comment by Jules-A** [comment]
Seems to work okay still as far as I can tell after quickly testing it. It would be nice if "Dub/Dubbed/English Dubbed" could be removed from Seasons/Titles but that's not really the extractors fault ```Avenger (Dubbed) - S1E1 - Dome (Dub)``` lol... Either way so much better than not having the series name at all...

**Comment by shloop** [comment]
Closing this since it was never accepted and the most crucial changes are already implemented in https://github.com/yt-dlp/yt-dlp/pull/9975. I may make a new PR to add series names since that metadata is still missing in the current version.

**Pull request closed without merging**
