### PR TITLE
[youtube] add support for multiple subtitles with the same lang_code

### PR DESCRIPTION
**Pull request by nixxo**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Improvement
- [x] New feature

---

### Description of your *pull request* and other information

As title...

Taken from here: https://github.com/ytdl-org/youtube-dl/pull/26112

Some youtube videos have multiple subtitle for the same language. Right now yt-dl only takes one. This PR solves that.

It probably requires to add more tests and fix some to pass.

this one as an example: https://www.youtube.com/watch?v=wsQiKKfKxug

Before:

```
[youtube] wsQiKKfKxug: Downloading webpage
Available subtitles for wsQiKKfKxug:
Language formats
en       vtt, ttml, srv3, srv2, srv1, json3
```

After:
```
[youtube] wsQiKKfKxug: Downloading webpage
Available subtitles for wsQiKKfKxug:
Language name                           formats
en       English                        vtt, ttml, srv3, srv2, srv1, json3
en       English - French Speakers Only vtt, ttml, srv3, srv2, srv1, json3
```

### CODE REVIEW

**Comment by pukkandan** [comment]
Why though? Isn't https://github.com/pukkandan/yt-dlp-dev/commit/0162ae4e76d6278be9dea46ad60b744ecf123afb enough? 

```
$ yt-dlp --list-subs wsQiKKfKxug jc5DlOkOcU4
[youtube] wsQiKKfKxug: Downloading webpage
Available subtitles for wsQiKKfKxug:
Language       formats
en             vtt, ttml, srv3, srv2, srv1, json3
en-1JJtFDtHuZg vtt, ttml, srv3, srv2, srv1, json3
```

We could also add the `name` to `--list-subs` so that user can easily understand which is which. But other than that, I don't see the point of the other changes

**Comment by nixxo** [comment]
in the minimal approach you did the language code `en-1JJtf....` is an invalid language code that should be two letter. IMHO.
and I think it creates problem when you embed the subs in the video and the lang code is non-standard.

I think the info about the substitle name is useful especially when embedding the subs because it makes the sub more recognizable

Example in mediainfo and mpc:
x2scrap
x2scrap2

For all the code, I just took the code from the linked PR and adapted for the slightly different code of yt-dlp.
It has code for managing the added name to the subtitle, the multiple subs with the same lang code in ffmpeg embedding or converting and I added the fixed tests that failed.

**Comment by pukkandan** [comment]
The "language code" is not a standardized language code, but only an id for the subtitle.

```
    subtitles:      The available subtitles as a dictionary in the format
                    {tag: subformats}. "tag" is usually a language code, and
                    "subformats" is a list sorted from lower to higher
                    preference, each element is a dictionary with the "ext"
```
> "tag" is usually a language code

Many extractors don't write the 2-letter lang code as the tag. This tag is passed through `ISO639Utils.short2long` when embedding. So as long as the first 2 characters of the tag is the lang-code, the correct language code will be written to the video.   

---

> I think the info about the substitle name is useful especially when embedding the subs because it makes the sub more recognizable

I agree, hence why I said "We could also add the name to --list-subs"

**Comment by nixxo** [comment]
not only that... try --write-subs and see what happens with your minimal code. It downloads only one of the subs, not both.

yt-dlp does not support multiple subtitle with the same lang code ATM. the minimal code is a workaround to "list" them but it doesn't do anything else with it.

Hence the extra code written in the PR that fundamentally extends the subtitles handling by yt-dl.
At first, when I saw the code, I too was of the impression that it seemed a little bit excessive and my solution was very similar to yours. But then I realized, while testing it, that everything else besides listing the subtitles simply did't work. Downloading, embedding, converting etc...

Which is why the code is so much, it changes the way subtitles are handled by yt-dl.

**Comment by pukkandan** [comment]
> try --write-subs and see what happens with your minimal code. It downloads only one of the subs, not both.

That is the intended behavior. It should only write the "best" subs with the default options. If you want both subs, you need to specify so using `--sub-langs`. In this case, that would be `--sub-langs en,en-1JJtFDtHuZg` or even easier `--sub-langs en,en.+`

> yt-dlp does not support multiple subtitle with the same lang code ATM

If there are multiple subtitles with the same tag, the assumption is that they are the same subs in different formats

> everything else besides listing the subtitles simply did't work. Downloading, embedding, converting etc...

They all work as long as the user requests both subs

>  it changes the way subtitles are handled by yt-dl.

That is exactly why I am reluctant to merge it

**Comment by pukkandan** [comment]
I've added the name as well. https://github.com/pukkandan/yt-dlp-dev/commits/multi-sub
Let me know what you think

**Comment by pukkandan** [comment]
> I've added the name as well. https://github.com/pukkandan/yt-dlp-dev/commits/multi-sub
Let me know what you think

@nixxo 

I was simply asking whether you still think there is any benefit to this more complex approach than my implementations. I did not expect you to force push the entire PR to that branch. But since that is what you did, I assume you think my approach has no disadvantages over this? If so, I can merge those commits separately.

Pushing it to this PR serves no purpose other than simply making it impossible for anyone to follow this conversation in the future. So I have pushed it back to its original state

**Comment by nixxo** [comment]
both solutions solves the problem of recognizing all subtitles available.
To me is indifferent which one is implemented.

The solution in this PR assumed, and I did as well, that the lang_code needed to be a two-letter identifier and so having multiple variants with the same lang code required extra code.

But, has you pointed out, the lang code is just a generic identifier for the languare and so it's not necessary to create "variants" for the same lang code with all the extra code.

Your solution is simpler and cleaner and it will allow to be maintained easily I guess.

**Pull request closed without merging**
