### PR TITLE
[extractor/youtube] Update piped instances

### PR DESCRIPTION
**Pull request by Generator**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

Updated piped instances based on https://github.com/TeamPiped/Piped/wiki/Instances and https://piped-instances.kavin.rocks/

Similar PR #5286
<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
Does the generic redirect not work for these?

**Comment by Generator** [comment]
@pukkandan it doesn't

@Lesmiscore it works here! 

```
./yt-dlp -s https://piped.smnz.de/watch?v=c70T_a58owc
[youtube] c70T_a58owc: Downloading webpage                 [youtube] c70T_a58owc: Downloading android player API JSON
[youtube] c70T_a58owc: Downloading MPD manifest
[youtube] c70T_a58owc: Downloading MPD manifest
[info] c70T_a58owc: Downloading 1 format(s): 303+251
```

**Comment by pukkandan** [comment]
My bad - It's invidious that Generic can resolve, not piped.

Does Piped have anything similar to https://github.com/iv-org/invidious/pull/1730? If not, someone should probably bring it up to them

**Comment by Bnyro** [comment]
> My bad - It's invidious that Generic can resolve, not piped.
> 
> Does Piped have anything similar to [iv-org/invidious#1730](https://github.com/iv-org/invidious/pull/1730)? If not, someone should probably bring it up to them
>
We don't support it yet but it shouldn't be hard to add, I'll probably add support for it later! :)

**Pull request merged**
