### PR TITLE
describe lbry extractors as odysee

### PR DESCRIPTION
**Pull request by KBelmin**
https://odysee.com/ also working! Love it.

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

https://odysee.com/ working (full download & trimmed videos)

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x ] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by seproDev** [comment]
Thank you for wanting to contribute. However, this PR cannot be merged.
`supportedsites.md` is autogenerated. Odysee is covered by the lbry extractor, which is alraedy listed.

**Comment by bashonly** [comment]
`supportedsites.md` is automatically generated upon new releases of yt-dlp.

odyssey is currently listed under the name "lbry":

https://github.com/yt-dlp/yt-dlp/blob/40054cb4a7ebbea30d335d444e6f58b298a3baa0/supportedsites.md#L691-L693

if you want to add "odysee.com" to the supported sites list the correct way, you could set `IE_DESC` in the 3 extractors:

e.g. below these 2 lines:
https://github.com/yt-dlp/yt-dlp/blob/40054cb4a7ebbea30d335d444e6f58b298a3baa0/yt_dlp/extractor/lbry.py#L137-L138
you could add:
```py
    IE_DESC = 'odysee.com'
```

---

and here:
https://github.com/yt-dlp/yt-dlp/blob/40054cb4a7ebbea30d335d444e6f58b298a3baa0/yt_dlp/extractor/lbry.py#L365-L366
```py
    IE_DESC = 'odysee.com channels'
```

---

and finally:
https://github.com/yt-dlp/yt-dlp/blob/40054cb4a7ebbea30d335d444e6f58b298a3baa0/yt_dlp/extractor/lbry.py#L392-L393
```py
    IE_DESC = 'odysee.com playlists'
```

**Comment by KBelmin** [comment]
@bashonly hey! Thank you so much for the precise instructions. I have done as instructed. I hope this is fine.

1: https://github.com/yt-dlp/yt-dlp/compare/master...KBelmin:yt-dlp:patch-4
2: https://github.com/yt-dlp/yt-dlp/compare/master...KBelmin:yt-dlp:patch-3
3: https://github.com/yt-dlp/yt-dlp/compare/master...KBelmin:yt-dlp:patch-2

**Comment by Grub4K** [comment]
@KBelmin Those should probably go into a single PR

**Comment by KBelmin** [comment]
I'm sorry, I do not know how to do that, I would have to research it. Can I merge it or what should I do?

**Comment by bashonly** [comment]
I've taken care of it and this will be merged with #11328. You can leave it open; it will be closed automatically

**Pull request closed without merging**
