### PR TITLE
[core] Add brotli content encoding support

### PR DESCRIPTION
**Pull request by coletdjnz**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [X] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Adds support for [brotli](https://en.wikipedia.org/wiki/Brotli) content encoding alongside the existing gzip and deflate (`Content-Encoding: gzip, deflate, br`). This requires either the brotli or brotlicffi module to enable.

Used by most browsers today, and sites such as YouTube seem to prefer to use it if available.

I'm not sure if this would make much difference to yt-dlp, but it seems simple to add. Open for discussion.

I haven't added it to dependencies in setup.py or requirements.txt since it may break some existing automated builds.
brotli is preferred if you are using CPython, brotlicffi elsewhere <sup>[ref](https://pypi.org/project/brotlicffi/)</sup>

entries if we want to add them:
[requirements.txt](https://github.com/coletdjnz/yt-dlp-dev/blob/yt-dlp-go-brrr-prototype/requirements.txt#L5-L6), [setup.py](https://github.com/coletdjnz/yt-dlp-dev/blob/yt-dlp-go-brrr-prototype/setup.py#L26-L29)

### CODE REVIEW

**Comment by pukkandan** [comment]
Does this have any actual benefit, or adding it just because we can?

**Comment by coletdjnz** [comment]
> Does this have any actual benefit, or adding it just because we can?

I'm not sure, hence I am open for discussion. This is just part of modernizing the underlying network stack. 

From what I read, it is usually better than gzip/deflate, though I'm not sure if yt-dlp will see much of a difference. Maybe for slower connections?

Fingerprinting might be relevant here, since modern browsers (of the UA's we have) use br encoding.

**Comment by Zirro** [comment]
Brotli is particularly efficient for compressing web assets like HTML, CSS and JavaScript since it uses a dictionary with strings commonly found throughout these documents. While yt-dlp doesn't need the latter two, downloading HTML (and JSON in some cases) could theoretically benefit from using brotli.

However, in a few basic timing tests spent downloading pages from large YouTube channels - presumably the ideal case for this - I did not see any significant difference while on this branch. Still, it'd be great if someone else could measure the potential differences in times from their connection.

**Comment by pukkandan** [comment]
Note that this branch doesn't do anything unless u have the dependancy https://github.com/google/brotli

**Comment by coletdjnz** [comment]
I notice that on alpine, installing yt-dlp using pip will now require python3-dev (since that is required for brotli). 

Not sure if this might be an issue.

**Pull request merged**
