### PR TITLE
Add --fileopen-retries to retry on file access errors.

### LINKED ISSUE #517: ERROR: unable to download video data: [Errno 13] Permission denied:
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07 (exe)
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [generic] Extracting URL: _Link Redacted_
[generic] master: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: de, he, fr, es, en, ru, yi

```

## Description

when using native downloader a lot of times it fails with error "ERROR: unable to download video data: [Errno 13] Permission denied:" but if i retry it works, how do i make it retry automatically ? i tried --retries infinite but its not retrying

(i didnt checkbox latest version  **2021.07.07** because i am using version built today but also fails on latest "stable")

### PR DESCRIPTION
**Pull request by ehoogeveen-medweb**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Closes #517. I marked this as an improvement because the problem is arguably not a bug in yt-dlp itself. This is more of a workaround for the behavior of Python's `open()` function (which may itself not be the root cause - it would certainly be a very longstanding issue).

I wanted to add a new parameter (something like `--fileopen-retries`) but because `sanitize_open` is a generic utility function, every call site would have to be modified (and some of them don't look like they can easily access options themselves). Instead I just set the maximum number of attempts to 5 and set the number of milliseconds between attempts to 10. For the same reason I didn't make it print anything when a retry happens. I'd be happy to improve on those aspects with some guidance :)

On my laptop (which frequently experiences #517) even a single retry seems to be enough to work around the issue, but without understanding the root cause I can't say that it would never fail twice. The `time.sleep()` call is required - simply trying again right away fails with the same error.

### CODE REVIEW

**Comment by pukkandan** [comment]
I noticed `sanitize_open` is only used in `downloader`. So we can make a wrapper to it in the `FileDownloader` class that can be called as `self.sanitize_open`. That way, it will have access to the CLI params and the printing functions

**Comment by ehoogeveen-medweb** [comment]
Oh! Yes I see now, I didn't notice the inheritance structure. I'll work on making this configurable.

**Comment by ehoogeveen-medweb** [comment]
Alright, I'm much happier with this version.
* I added `--fileopen-retries` between `--retries` and `--fragment-retries` (it defaults to 10 like the others).
* I reverted the changes to `sanitize_open`.
* As suggested, I added a wrapper to `FileDownloader` which handles `errno.EACCES` errors with up to `fileopen_retries` retries.

The sleep time is still hardcoded to 10 milliseconds. I considered using `sleep_interval` but it seemed too unrelated, and adding another setting for the sleep time seemed like overkill.

**Comment by ehoogeveen-medweb** [comment]
Thanks!

**Pull request merged**
