### PR TITLE
Homebrew support

### PR DESCRIPTION
**Pull request by nao20010128nao**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This PR provides automated update for yt-dlp Homebrew formulae, and guide for installation in README.

For users using macOS, please try running `brew install yt-dlp/taps/yt-dlp` and let me know if it works. Thanks
**edit:** got report that installation on macOS was successful. thanks @gaato

~~@pukkandan Can you please create a new PAT and add it to secrets as `GH_TOKEN`? it is required to update `homebrew-taps` repository.
This PR is in draft state until PAT is ready.~~

### CODE REVIEW

**Comment by nao20010128nao** [comment]
@pukkandan ready for merge, script is working locally

**Comment by chenrui333** [comment]
It might be better to maintain the homebrew-core index instead.

Right now it can be installed via `brew install yt-dlp`.

**Comment by nao20010128nao** [comment]
@chenrui333 The .tar.gz file in Releases has a problem that it doesn't contain source code. So one in core does not work.

And also, homebrew-core requires PR to be merged, which cannot be automated. This PR is to aimed to automate version update for formulae.

**Comment by xxyzz** [comment]
You can send pull request to update homebrew formula automatically with GitHub Action, please check out https://github.com/dawidd6/action-homebrew-bump-formula and https://github.com/mislav/bump-homebrew-formula-action.

**Comment by pukkandan** [comment]
> You can send pull request to update homebrew formula automatically with GitHub Action, please check out dawidd6/action-homebrew-bump-formula and mislav/bump-homebrew-formula-action.

PRs for this is welcome as well

**Pull request merged**
