### PR TITLE
Fix yahoo extraction

### PR DESCRIPTION
**Pull request by llacb47**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

A quick and dirty fix for https://github.com/ytdl-org/youtube-dl/issues/28290.

This extractor could use more work, as many of the tests and logic are outdated, but this fixes the most pressing breakage for now.

Example videos fixed with this patch:
```
https://www.yahoo.com/entertainment/vin-diesel-the-rock-fast-and-furious-feud-143355696.html
https://au.news.yahoo.com/david-suzuki-rates-planets-chances-survival-060127745.html
https://www.yahoo.com/money/house-passes-biden-relief-package-including-stimulus-checks-070640949.html
```

### CODE REVIEW

**Comment by pukkandan** [comment]
Please don't skip the template

**Comment by llacb47** [comment]
Whoops, sorry. I'll go back and edit in a few

**Comment by llacb47** [comment]
Filled in the relevant checkboxes. I realized I probably shouldn't have removed the old code for backwards compat reasons. so I'll restore it ASAP.

**Comment by llacb47** [comment]
@pukkandan could you please review when you get a chance?

**Pull request merged**
