### PR TITLE
[pornhub] Add playlist extractor

### LINKED ISSUE #680: [Broken] Pornhub playlist only download first 36 videos
## Checklist

- [ ✅] I'm reporting a broken site support
- [ ✅] I've verified that I'm running yt-dlp version **2021.08.10**
- [ ✅] I've checked that all provided URLs are alive and playable in a browser
- [ ✅] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ✅] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp -v https://www.pornhub.com/playlist/95816161
[debug] Command-line config: ['-v', 'https://www.pornhub.com/playlist/95816161']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg N-102564-g2261cc6d8a, ffprobe N-102564-g2261cc6d8a
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [PornHubPagedVideoList] Extracting URL: https://www.pornhub.com/playlist/95816161
[download] Downloading playlist: playlist/95816161
[PornHubPagedVideoList] playlist/95816161: Downloading page 1
[PornHubPagedVideoList] playlist playlist/95816161: Downloading 36 videos
[download] Downloading video 1 of 36
[debug] [PornHub] Extracting URL: http://www.pornhub.com/view_video.php?viewkey=ph5c0a6ab9a71b1&pkey=95816161
[PornHub] ph5c0a6ab9a71b1: Downloading pc webpage
[PornHub] ph5c0a6ab9a71b1: Downloading JSON metadata
[PornHub] ph5c0a6ab9a71b1: Downloading m3u8 information
[PornHub] ph5c0a6ab9a71b1: Downloading m3u8 information
[PornHub] ph5c0a6ab9a71b1: Downloading m3u8 information
[PornHub] ph5c0a6ab9a71b1: Downloading m3u8 information
[PornHub] ph5c0a6ab9a71b1: Downloading m3u8 information
```

## Description

yt-dlp scrap only the first 36 videos from pornhub playlists, this issue on the youtube-dl as well, let's hope someone fix it on this fork.

Thanks

### PR DESCRIPTION
**Pull request by mzbaulhaque**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Current extractor that handle playlists is broken (only for playlists), i think a new one would be better rather than fixing current one because playlist pagination through url param (`?page=N`) no longer works.
Should fix #680.

### CODE REVIEW

**Comment by pukkandan** [comment]
Since we can pinpoint which page needs to be downloaded for each video, using a PagedList instead of a generator would be better. This will allow downloads with `--playlist-item 1000` for example, to download only the one page that is needed for that particular video

**Comment by mzbaulhaque** [comment]
Yeah i was thinking about that too but in this case the `page_size` is inconsistent (first page has 36 items, rest has 40). I'm not sure if this inconsistency can be tackled with a `PagedList`. Might need to implement another subclass but i don't think that's worth it.

If you know of any workaround let me know. Otherwise you can go ahead and merge it.

**Comment by pukkandan** [comment]
You are right. Neither of the existing subclasses seems to be able to handle this case

**Comment by Hrxn** [comment]
`%(playlist)s` gives the ID of a playlist, would be a nice improvement to also extract the title of a playlist in `playlist_title` or something?

**Comment by pukkandan** [comment]
@Hrxn Open a new site feature request

**Comment by Hrxn** [comment]
> I understand that I will be blocked if I intentionally remove or skip any mandatory* field *

I'm a bit scared now..

**Pull request merged**
