### PR TITLE
Use existing dropout session when found in cookies

### LINKED ISSUE #4035: [dropout] Problem with extractor login process when cookies imported
### Checklist

- [x] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

I had some difficulties pulling videos from dropout.tv but figured out what was wrong. 

The way that the extractor works is that it first goes to dropout.tv/login to extract an authentication token and store it in a variable and then logs in. Then the authentication token, now authorized, is used to request the video data.

The problem is that my default yt-dlp configuration is set to look for cookies in the firefox folder. The extractor doesn't know how to pull the authentication token from the firefox cookies, but the firefox cookies are applied when the extractor loads up the webpage. 

When the extractor goes to the login page, because the cookies are loaded, the user is already logged in and there is no authentication token available and there isn't an option to actually log in. 

There are a few ways to handle this that pop into mind

1. The cookies can be parsed to get the session ID and use that, bypassing the whole login process. I would suggest not logging out if this occurs so the cookies aren't invalidated.
2. If the authenticity_token is not found on the login page, try hitting the logout page and then reloading the login page. It'll likely be there now. This might invalidate the users existing browser based session though. 
3. Is there a way to scrape and interact with the login page without any loaded cookies being utilized? That would be the cleanest method, IMHO. 

Another problem: 
There is another report of people hitting authentication limitations. I think it might be related to how the extractor works, where it logs in to perform an action and then logs out. In fact, if you point yt-dlp at a URL representing a whole season, it logs out and logs back in for each video in the season. If the extractor can maintain the session for the whole download process, it'll seriously reduce the risk of being rate limited. 

### Verbose log

```shell
(not verbose, sorry)
adam@Storage /m/s/t/U/Season 06> yt-dlp --netrc "https://www.dropout.tv/um-actually/season:7/videos/porco-rosso-super-mario-odyssey-the-wonder-twins"
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 511 cookies from firefox
[Dropout] porco-rosso-super-mario-odyssey-the-wonder-twins: Getting authenticity token
[Dropout] porco-rosso-super-mario-odyssey-the-wonder-twins: Logging out
ERROR: [Dropout] porco-rosso-super-mario-odyssey-the-wonder-twins: Unable to extract authenticity_token; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

### PR DESCRIPTION
**Pull request by pingiun**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

(I'm not sure which tests are relevant)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

---

### Description of your *pull request* and other information

Fixes #4035 

Instead of logging in each time in the dropout extractor, check to see if a `_session` cookie exists and use it if possible. This causes a problem when the `_session` cookie refers to a logged out or unauthenticated session. However in that case the extractor tries to login again.

I also removed the logout after the video is extracted as I don't think this is needed and it speeds up the process if multiple video's are downloaded in a row.

### CODE REVIEW

**Comment by pingiun** [comment]
@DeftNerd could you try this fix?

**Comment by pukkandan** [comment]
> I also removed the logout after the video is extracted as I don't think this is needed and it speeds up the process if multiple video's are downloaded in a row.

This is why the logout code was added: https://github.com/yt-dlp/yt-dlp/pull/2045#discussion_r771891369

**Comment by pukkandan** [comment]
The `_real_exit` idea was abandoned because it was not needed at the time. Let me know if you think it would be useful and we can implement it

**Comment by pukkandan** [comment]
Confirm I haven't broken anything

**Comment by pingiun** [comment]
Can confirm this still works

**Pull request merged**
