### PR TITLE
[ABC] Add extractor for latest episode of an iView show

### PR DESCRIPTION
**Pull request by pabs3**
### Before submitting a *pull request* make sure you have:
 - [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests 
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Add extractor for latest episode of an ABC iView show.

This allows to download using only the show URL instead of
having to find out the latest episode URL manually.

### CODE REVIEW

**Comment by pukkandan** [comment]
When a show URL is passed, user's expectation is generally to download the whole show, not the latest episode

**Comment by pabs3** [comment]
As you can see in the name of the extracted JSON data, the ABC iView
show pages have what is called a "highlighted" episode (which might not
be the latest one), the extractor being added simply figures out which
episode is highlighted and then passes it to the episode extractor.

As far as I can tell there isn't an option in yt-dlp to select the
"highlighted" episode so that would need to be added before this
extractor could be added. I don't know if any other sites have this
concept of a "highlighted" episode so adding it might not be useful.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pukkandan** [comment]
The extractor can be made to return all episodes normally and the "highlighted" episode with `--no-playlist`

**Comment by pabs3** [comment]
How should the extractor return both the highlighted episode and the
playlist? Or how can the extractor know that a playlist wasn't wanted?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pukkandan** [comment]
```py
if self.get_param('noplaylist'):
    return url_result(...)

# extract playlist info here
return playlist_result(...)
```

**Comment by pabs3** [comment]
Thanks, implemented. Each show page only shows a single season of the
show, but by appending a series number to the URL one can select a
different season, added support for that in the URL matching too.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
I think this PR is now ready for review and merging.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by noaho** [comment]
> When a show URL is passed, user's expectation is generally to download the whole show, not the latest episode

What about this PR in the old youtube-dl repo? Could it be adapted and merged here? It would be great to have this functionality. 

https://github.com/ytdl-org/youtube-dl/pull/26318

**Comment by coffeebucket** [comment]
I've been testing out this PR and it appears to work as advertised.  After reviewing https://github.com/ytdl-org/youtube-dl/pull/26318 (nice find @noaho), there are a few changes that could be made to improve compatibility with the alternate use case of downloading all episodes for a show/series.

Firstly, the description of what this PR actually does should be clarified.  The `highlightVideo` key in `__INITIAL_STATE__` always points to the video tied to the play button when viewing a show through iView.  However the video's context changes based on the type and status of a show.  E.g.

* A show currently being screened on ABC TV in Australia with a series in progress will show "Watch Latest"
* A show with only one episode (e.g. a documentary or movie) could show "Watch"
* A show that has finished screening on ABC TV but still has episodes available on iView will show "Watch Episode 1", with the first episode being from either the first series of the show, or the oldest series still available to watch on iView.

There are likely more cases, but the point is the `highlightVideo` won't always be the latest for a show.  This PR allows downloading of the 'highlight' video for a show, even if iView does not make explicit use of that term in the UI.

As for the alternate use case of downloading all episodes for a show/series: the content of `__INITIAL_STATE__` should only be used in the case where the user specifies `--no-playlist` and only wants the `highlightVideo`.  The back end API should be used for all other multi-episode scenarios.  Specifically:

1. all available episodes for a show, i.e. `https://iview.abc.net.au/show/<showname>`
2. all episodes for a series (season) of a show, i.e. `https://iview.abc.net.au/show/<showname>/series/<seriesnumber>`

Thankfully both of these cases are neatly serviced by API calls to `https://api.iview.abc.net.au/v2/series/<showname>` and `https://api.iview.abc.net.au/v2/series/<showname>/<seriesnumber>` respectively.  youtube-dl/pull/26318 makes similar calls to an older API, but the newer `v2` endpoint provides much greater detail; particularly relating to series of episodes for a show.

`/v2/series/<showname>` returns an array of series objects whereas `/v2/series/<showname>/<seriesnumber>` returns a single series object. E.g. in the case of the [test video](https://github.com/yt-dlp/yt-dlp/blob/94a041c86a15ac898c3c27dad59d97617451318d/yt_dlp/extractor/abc.py#L266)

https://api.iview.abc.net.au/v2/series/upper-middle-bogan
https://api.iview.abc.net.au/v2/series/upper-middle-bogan/3

Perhaps the info extractors could be re-factored into

* `ABCIViewShowSeriesIE` - handles all episodes for a specific series, calling `ABCIViewIE` with individual video URLs
* `ABCIViewShowIE` - handles all episodes for a show, calling `ABCIViewShowSeriesIE` for each series

In both cases, conditional tests for `--no-playlist` could handle downloading only the `highlightVideo`.  These changes would be a huge improvement for the iView extractor.  Then there's the issue of getting accurate episode and  series numbers for shows that lump all the episodes together, but that's another matter.

**Comment by pukkandan** [comment]
I have merged this PR for now. The suggested improvements can be made in a new PR

**Pull request merged**
