### PR TITLE
[ie/hungama] Overhaul extractors

### LINKED ISSUE #7754: Support for un.hungama.com
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

_No response_

### Example URLs

Charts/Playlist: https://un.hungama.com/chart/bollywood-top-40/6532/
Album: https://un.hungama.com/album/what-jhumka-%3F-from-rocky-aur-rani-kii-prem-kahaani/103891805/
Song: https://un.hungama.com/song/tum-kya-mile-from-rocky-aur-rani-kii-prem-kahaani/103553672/
Artist: https://un.hungama.com/artist/justin-bieber/42221/

### Provide a description that is worded well enough to be understood

The original hungama.com website is revamped and its moved to un.hungama.com

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'cookies-un-hungama-com.txt', '-F', 'https://un.hungama.com/song/tum-kya-mile-from-rocky-aur-rani-kii-prem-kahaani/103553672']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.19.0-32-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: cookies-un-hungama-com.txt
ERROR: [generic] None: 'cookies-un-hungama-com.txt' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:cookies-un-hungama-com.txt" ) to search YouTube
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/generic.py", line 2403, in _real_extract
    raise ExtractorError(

[generic] Extracting URL: https://un.hungama.com/song/tum-kya-mile-from-rocky-aur-rani-kii-prem-kahaani/103553672
[generic] 103553672: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 103553672: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://un.hungama.com/song/tum-kya-mile-from-rocky-aur-rani-kii-prem-kahaani/103553672
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://un.hungama.com/song/tum-kya-mile-from-rocky-aur-rani-kii-prem-kahaani/103553672
```

### PR DESCRIPTION
**Pull request by Yalab7**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Added `un` subdomain to the extractor `hungama` by editing `_VALID_URL`

Fixes #7754 

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🎵🎬🛠️

Improved the Hungama extractor to handle a new subdomain for various media types. Modified a test case accordingly.

> _We are the rebels of the `un.` domain_
> _We break the chains of the Hungama extractor_
> _We play the songs of doom and despair_
> _We make the playlists of the damned_

### Walkthrough
*  Update the `_VALID_URL` patterns for the `HungamaIE`, `HungamaSongIE`, and `HungamaAlbumPlaylistIE` classes to support the `un.` subdomain ([link](https://github.com/yt-dlp/yt-dlp/pull/7757/files?diff=unified&w=0#diff-63a9fca1d957910fc25b03441bf6b809f2a9c90711095a30e17547dcd0b43e84L14-R14), [link](https://github.com/yt-dlp/yt-dlp/pull/7757/files?diff=unified&w=0#diff-63a9fca1d957910fc25b03441bf6b809f2a9c90711095a30e17547dcd0b43e84L74-R76), [link](https://github.com/yt-dlp/yt-dlp/pull/7757/files?diff=unified&w=0#diff-63a9fca1d957910fc25b03441bf6b809f2a9c90711095a30e17547dcd0b43e84L126-R128))
*  Change the test URL for the `HungamaIE` class to use the `un.` subdomain and match the updated pattern ([link](https://github.com/yt-dlp/yt-dlp/pull/7757/files?diff=unified&w=0#diff-63a9fca1d957910fc25b03441bf6b809f2a9c90711095a30e17547dcd0b43e84L22-R22))

</details>

### CODE REVIEW

**Comment by bashonly** [comment]
Don't replace the old tests, add new tests for the new subdomain

**Comment by Yalab7** [comment]
When I run the tests using `python test/test_download.py TestDownload.test_hungama` I get the following error
`AttributeError: type object 'TestDownload' has no attribute 'test_hungama'`

I tried rerunning the test multiple times as stated in [step 6](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-support-for-a-new-site) but the error is still unresolved.

Can you point me to the right direction on how to correctly run the tests?

**Comment by bashonly** [comment]
the test names are case sensitive
`python test/test_download.py TestDownload.test_Hungama`
`python test/test_download.py TestDownload.test_Hungama_1`
`python test/test_download.py TestDownload.test_HungamaSong`
`python test/test_download.py TestDownload.test_HungamaSong_all`
etc

**Comment by Yalab7** [comment]
I keep getting network errors when I try to test downloading, although the same URL is working in the release version that I'm using.

image

**Comment by apstheironheart** [comment]
If something helps:

The website is playing with a lower quality max streaming support upto 192kbps. Audio bitrates of 96,128kbps are also returned. If editing the URL and changing 192 to 320, then I can download the higher bitrate m3u8 file.

**Comment by bashonly** [comment]
The site changed something today and all of its extractors are now broken, even with updated `_VALID_URL`

**Comment by bashonly** [comment]
It turns out that it wasn't as simple as just updating the `_VALID_URL`. Added a baseclass so that `HungamaIE` and `HungamaPlaylistIE` could use a common method to call the site's metadata API, since the JSON LD blocks they were using previously are not available from `un.hungama.com` links

**Comment by apstheironheart** [comment]
is it resolved? I tried updating to nightly build and its only download a placeholder ad for all the songs from un.hungama?

**Comment by bashonly** [comment]
@apstheironheart Looks like song extraction is broken for both `www.hungama.com` and `un.hungama.com` song URLs. Can you open a new issue?

**Pull request merged**
