### PR TITLE
[Err] Add extractor

### PR DESCRIPTION
**Pull request by smarbaa**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Add support for [err.ee](https://www.err.ee) and its various subservices: 
- [etv.err.ee](https://etv.err.ee)
- [etv2.err.ee](https://etv2.err.ee)
- [etvpluss.err.ee](https://etvpluss.err.ee)
- [jupiter.err.ee](https://jupiter.err.ee)
- [jupiterpluss.err.ee](https://jupiterpluss.err.ee)
- [vikerraadio.err.ee](https://vikerraadio.err.ee)
- [klassikaraadio.err.ee](https://klassikaraadio.err.ee)
- [r2.err.ee](https://r2.err.ee)
- [r4.err.ee](https://r4.err.ee)
- [arhiiv.err.ee](https://arhiiv.err.ee)

ERR is Estonian Public Broadcasting service that offers video and audio material mostly in Estonian and Russian languages.

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🇪🇪📺🎙️

Add support for ERR extractors. Import the extractor classes from `yt_dlp/extractor/err.py` in `yt_dlp/extractor/_extractors.py`.

> _`ERR` videos_
> _extracted from many sites_
> _autumn harvest time_

### Walkthrough
* Add support for downloading videos and audio from ERR's various websites ([link](https://github.com/yt-dlp/yt-dlp/pull/8278/files?diff=unified&w=0#diff-780b22dc7eb280f5a7b2bbf79aff17826de88ddcbf2fc1116ba19901827aa4e3R581-R588))

</details>

### CODE REVIEW

**Comment by seproDev** [comment]
Hey, sorry for taking so long to reply here. First off, thank you for taking your time to write these extractors. Anyone spending their time to contribute to yt-dlp is greatly appreciated!

With that said, in its current state, this PR can not be merged. A number of things you do are already handled by yt-dlp core code or are not in line with the yt-dlp coding style. If you want to get this merged, please take another look at the [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md) and also at any recently written extractors.
To give some specific examples of what should be improved:
- Your JSON helper functions can be replaced with `traverse_obj` which you can find in `..utils.traversal`
- Instead of creating a dict and then assigning values one by one, you should assign values directly during dict creation
- You should not inherit from a concrete class, but instead move the relevant functions in to a base class


This will take some work to clean up, but if you want to work on this, I'd be happy to answer any questions that might come up and also give some more specific feedback and suggestions.

Of course, all this is only if you want the PR to be merged. If you prefer to keep your code the way it is, you could convert this to a [plugin](https://github.com/yt-dlp/yt-dlp#plugins) (and tag it with [yt-dlp-plugins](https://github.com/topics/yt-dlp-plugins) so that others can find it).
I hope you understand. Thank you.

**Comment by smarbaa** [comment]
Thanks a lot for comments!
I would surely like to have it merged, of course, but as you hinted, some time and effort will be needed to rework and fix it all. No problems. We shall see.

**Comment by glensc** [comment]
Note: There's similar attempt to add jupiter and jupiter+:
- https://github.com/yt-dlp/yt-dlp/pull/8549

So, maybe not worth starting to fix code style issues in this PR immediately, it's see how that goes.

I personally would add things incrementally, with smaller iterations and jupiter site I added is a start.

PS: This is impressive work done here over 3 years of commits!

**Comment by smarbaa** [comment]
I am sorry for not having done anything on this project for a while, been really busy. And it's not going to change for any time soon, I am afraid. So, I am starting to think that converting it to a plugin, as suggested by @seproDev, is actually an excellent idea. Will study that asap.
So, that's it. I am sorry. I give up. :-)

**Comment by glensc** [comment]
I'll be happy to extract things from this PR. Not sure how it affects contribution. Do we need your permission to say "yes". Or since you already contributed with this PR, your approval is implicit?

**Comment by smarbaa** [comment]
My approval was implicit, of course, or rather covered by GPL. But now that you ask me, I say 'yes' use it as best you can, I don't mind. I will package my code as a plugin anyway.

**Comment by seproDev** [comment]
@smarbaa Don't worry about it you are all good. Turning your existing code in to a plugin will be very straight forward. I think only the imports will need to be adjusted.

@glensc Commits can be authored by multiple people. Since smarbaa already agreed to having their code merged, you can create a new PR and base it on this code. Just make it clear that that is what you are doing, so it can properly attributed.

**Comment by bashonly** [comment]
> covered by GPL

?

> - [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

**Comment by smarbaa** [comment]
Ah sorry. At the time of writing I was looking at some yt-dlp plugin repositories, and one of them had GPL in it, so I falsely assumed, well, to cut the story short, of course, when I proposed my original pr, a couple of months ago, I implicitly  and explicitly accepted to Unlicence my marginal contributions. So, my apologies for the misunderstanding. One can never be too precise with software licenses. :-)

**Comment by bashonly** [comment]
@smarbaa All good, just wanted to make sure nobody was mistaken about the license

**Comment by smarbaa** [comment]
Consider this branch as discontinued. Converted my extractor to plugin format [yt-dlp-ugly-err](https://github.com/smarbaa/yt-dlp-ugly-err).

**Comment by glensc** [comment]
@smarbaa as an author you can close your PR's.

**Pull request closed without merging**
