### PR TITLE
Update to ytdl-commit-66ab08

### PR DESCRIPTION
**Pull request by coletdjnz**
Don't think there is anything we really need to merge this time.

Worth checking the following though:

https://github.com/ytdl-org/youtube-dl/commit/9112e668a5ea6376017718db9ff13b369d53ad7a

https://github.com/ytdl-org/youtube-dl/commit/d5ef405c5d533c85cebd205a5b7958614c7013f3

https://github.com/ytdl-org/youtube-dl/commit/1634b1d61efa36c31c86b8c64c88dc297a7af28a

https://github.com/ytdl-org/youtube-dl/commit/d9d07a95815a992bf5f876a62f25c831eb3f32ac

https://github.com/ytdl-org/youtube-dl/commit/1e8ccdd2eb77901e18feb8a9d48e62d11651cd1e

https://github.com/ytdl-org/youtube-dl/commit/b2741f2654e6ddfebc1771b5d5fadb5fd6fe3863

https://github.com/ytdl-org/youtube-dl/commit/b2ba24bb026904f3503db71f65d2b1627f08edf1

https://github.com/ytdl-org/youtube-dl/commit/44faa71b19c866b836e4433ddd3e4722ac6d282f

https://github.com/ytdl-org/youtube-dl/commit/2d2a4bc8324fc4bc5a235cbd1ee0b0769912bfd1

excluding:

https://github.com/ytdl-org/youtube-dl/commit/e7926ae9f4e5fa258696551a39295402819280c9
- no need for compress and long dead other x-gzip etc. 

https://github.com/ytdl-org/youtube-dl/commit/2efc8de4d2299e08e0c84d674d7fc7f3fa669487
- not much point adding compress content-encoding do not want to advertise it as makes yt-dlp easier to detect.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [X] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🔄🆙🛠️

Update youtube-dl commit hash in `README.md` to sync with upstream. This helps maintain yt-dlp's compatibility and functionality.

> _`yt-dlp` updates_
> _`youtube-dl` commit hash_
> _Autumn maintenance_

### Walkthrough
* Update the youtube-dl commit hash to keep yt-dlp compatible with upstream changes ([link](https://github.com/yt-dlp/yt-dlp/pull/8128/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L79-R79))

</details>

### CODE REVIEW

**Review by Grub4K — APPROVED** [review]
Agree that none seem of interest

**Review by bashonly — APPROVED** [review]

**Comment by pukkandan** [comment]
Just readme was updated?

**Comment by Grub4K** [comment]
Yes, the other changes were deemed unnecessary

**Comment by dirkf** [comment]
You might like this next time, from ytdl-org/youtube-dl@d9d07a9:
> add limited `!` evaluation [to `js_to_json()`] (eg, !!0 -> false, see tests)

The other stuff is plundered from here anyhow.

**Pull request merged**
