### PR TITLE
Added Support to ThisVid.com

### PR DESCRIPTION
**Pull request by FraFraFra-LongD**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Added ThisVid.com extractor, the website ThisVid.com **release public videos** so no copyright.
Im not the original author, [He is the author](https://github.com/blackjack4494). The code he written was forgotten in an old issue on YouTube-dl main repository, [this issue](https://github.com/ytdl-org/youtube-dl/pull/26060/files). This new extractor is requested also in [this issue](https://github.com/ytdl-org/youtube-dl/issues/17713), that is still open.
The code is working fine, with python 2.6, 2.7, and 3.2+; the extractor is also been tested with flake8

### CODE REVIEW

**Comment by MinePlayersPE** [comment]
Duplicate of https://github.com/yt-dlp/yt-dlp/pull/659?

**Comment by FraFraFra-LongD** [comment]
> Duplicate of #659?

that one is closed

**Comment by MinePlayersPE** [comment]
> that one is closed 
Because https://github.com/yt-dlp/yt-dlp/pull/549

**Comment by FraFraFra-LongD** [comment]
> > that one is closed
> 
> Because #549

so videos like the ones on ThisVid.com are handled as generic due to KVS Player?

**Comment by pukkandan** [comment]
1. What does this add that yt-dlp already doesn't extract?
2. If it adds anything, can't that be moved into the KWS code?
3. The downlead tests don't work
4. Fix test_no_duplicates

**Comment by afterdelight** [comment]
pls dont close and fix this

**Comment by FraFraFra-LongD** [comment]
> pls dont close and fix this

this is an useless code in yt-dlp, in fact it already supports a downloader for KVS, unlike YouTube-dl

**Comment by afterdelight** [comment]
> 1. What does this add that yt-dlp already doesn't extract?
> 
>     2. If it adds anything, can't that be moved into the KWS code?
> 
>     3. The downlead tests don't work
> 
>     4. Fix test_no_duplicates

you can make extractor folder thisvid with -o {extractor}

**Comment by afterdelight** [comment]
what about private videos?

**Comment by FraFraFra-LongD** [comment]
> what about private videos?

supported providing cookies

**Comment by afterdelight** [comment]
thats nice to know. why are you still trying to push merge commit on youtube-dl PR? is the generic kvs extractor not avilable in youtube-dl?

**Comment by pukkandan** [comment]
No, it was added in #549. Pls read the above comments

**Comment by afterdelight** [comment]
no, i was talking about hiss PR
https://github.com/ytdl-org/youtube-dl/pull/29187

**Comment by FraFraFra-LongD** [comment]
> why are you still trying to push merge commit on youtube-dl PR? is the generic kvs extractor not avilable in youtube-dl?

because the site is not supported on YouTube-dl

**Comment by pukkandan** [comment]
In fact, this PR was merged all the way back in https://github.com/blackjack4494/yt-dlc/pull/79 before being superseded by #549.

I don't get how people can open issues/PR without even trying if the issue actually exists!!

**Pull request closed without merging**
