### PR TITLE
[utils] random_user_agent: update with past stable release versions

### PR DESCRIPTION
**Pull request by tgurr**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

Replace the current list of random_user_agent CHROME_VERSIONS with the same amount of entries of the past stable versions.

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
The last time we updated the list, it caused so many issues. I'd rather keep it as-is for now unless there is any practical advantage

**Comment by gamer191** [comment]
As of Chrome 101, chrome user agents don't include minor versions (see https://www.chromium.org/updates/ua-reduction/#sample-ua-strings-phase-4). As such, the user agents in this PR are inaccurate. The list of user agents could be replaced with a random number generator between 106 and 116, which would achieve the same effect as this PR, but tbh if yt-dlp's user-agents ever do get updated, I think yt-dlp should just use one user agent, because it's much less of a fingerprinting surface than it used to be. If a site requests `Sec-CH-UA-Full-Version-List`, then yt-dlp should use a random user agent from that specific Chrome version

These are just my thoughts though, and as usual Pukkandan has the final say. This PR is unlikely to be merged any time soon though, and I kinda agree with Pukkandan that it's not a good idea to merge this until it becomes necessary

**Comment by tgurr** [comment]
> As of Chrome 101, chrome user agents don't include minor versions (see https://www.chromium.org/updates/ua-reduction/#sample-ua-strings-phase-4). As such, the user agents in this PR are inaccurate.

Thanks for the hint, I've at least updated the listed versions to be not incorrect. For the rest I completely agree, I just didn't want to abandon the MR and at least keep it updated for the time beeing until there might be a need. But of course also feel free to just close it.

**Comment by Grub4K** [comment]
I'll close. We should revisit this problem when the need for new UAs is pressing

**Pull request closed without merging**
