### PR TITLE
Add notes for external downloaders

### PR DESCRIPTION
**Pull request by CrendKing**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Start a documentation for external downloaders. See https://github.com/yt-dlp/yt-dlp/issues/8437.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
📝🚀🔧

Add `downloaders.md` to document external downloader usage and options. Explain how to use `--downloader-args` to customize downloader behavior.

> _`yt-dlp` forked_
> _adds `downloaders.md` file_
> _notes for winter speed_

### Walkthrough
* Add a new file `downloaders.md` with notes for external downloaders ([link](https://github.com/yt-dlp/yt-dlp/pull/8544/files?diff=unified&w=0#diff-642449688d9d04331332923a3f31f2ecc1e6ea97cb4528275ebd146fec219f6bR1-R29))

</details>

### CODE REVIEW

**Comment by bashonly** [comment]
Instead of a separate markdown file, an "external downloaders" section would be a good addition to the wiki, IMO

**Comment by CrendKing** [comment]
So should I create PR for https://github.com/yt-dlp/yt-dlp-wiki instead?

**Comment by bashonly** [comment]
> So should I create PR for https://github.com/yt-dlp/yt-dlp-wiki instead?

Yeah, that would be good; I think something this comprehensive belongs on the wiki.

And maybe keep this PR open in case we want to add something more concise to the README.

@Grub4K what do you think?

**Comment by CrendKing** [comment]
https://github.com/yt-dlp/yt-dlp-wiki/pull/29

**Comment by Grub4K** [comment]
I think keeping it in the wiki for now seems good. Maybe a link from the main README could go to the wiki, so its more accessible?

**Comment by CrendKing** [comment]
Updated the README.md. You already have the wiki PR.

**Comment by CrendKing** [comment]
@bashonly @Grub4K Are you guys still interested in that wiki update? https://github.com/yt-dlp/yt-dlp-wiki/pull/29

**Pull request closed without merging**
