### PR TITLE
[minor] Update _utils.py

### PR DESCRIPTION
**Pull request by Atlas48**
Fix grammar and formatting

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Code is a minor cosmetic grammar and formatting fix to the message that outputs when a download module fails.

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) (Errors will be upstream, this is a small cosmetic change)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)
- [X] Code is a minor change of a few characters, and cannot be copyrighted by the author.

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [X] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🐛📝🌐

Improved bug report message in `yt_dlp/utils/_utils.py`. Removed query string and fixed space issue in URL.

> _`yt-dlp` improves_
> _No query string, no space_
> _Clear URL in fall_

### Walkthrough
*  Removed the query string from the URL and fixed a space issue in the bug report message ([link](https://github.com/yt-dlp/yt-dlp/pull/7540/files?diff=unified&w=0#diff-feda8f56946dc048e754111850baaef0eec4b9f8bbc2d3f04b1a785626ea5c0eL1040-R1041)). This makes the URL more concise and readable, and avoids potential confusion or errors when copying and pasting the URL.

</details>

### CODE REVIEW

**Comment by pukkandan** [comment]
The extra spaces ae intentional

**Comment by Atlas48** [comment]
@pukkandan I don't understand why you need to keep them in?

**Comment by Constantin1489** [comment]
@Atlas48, the `?q= , '` part is for a string concatenation.
compare these two case below,

```python
print('Hello, '
'world')
```
Your version.
```python
print('Hello,'
'world')
```
result is
```text
Hello, world
Hello,world
```

**Comment by Atlas48** [comment]
Finally got around to producing the message, on my machine, it produces the following message:

```
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

That's two extra spaces, a typo, therefore, a bug.

**Comment by Grub4K** [comment]
As said they are intentional. Links, commands and similar in yt-dlp are denoted using surrounding spaces. Here I show the intention by enclosing them in `<>`:
```
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] unable to extract yt initial data; please report this issue on <https://github.com/yt-dlp/yt-dlp/issues?q=>, filling out the appropriate issue template. Confirm you are on the latest version using <yt-dlp -U>
```
So this is where the second space comes from. `on <https` => `on  https`

**Comment by Atlas48** [comment]
y tho

**Pull request closed without merging**
