### PR TITLE
[extractor/youtube] Support shorter relative time text format

### PR DESCRIPTION
**Pull request by coletdjnz**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADD DESCRIPTION HERE

See https://github.com/TeamNewPipe/NewPipeExtractor/issues/1067 https://github.com/FreeTubeApp/FreeTube/pull/3588

This adds support for the en-US and en-GB formats. We don't officially support en-GB but the additional changes required to support it was little so might as well.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [X] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🕒🆙🗣️

Improved relative time parsing for YouTube videos. Updated the regex in `yt_dlp/extractor/youtube.py` to handle more variations of time units.

> _`extract_relative_time`_
> _now matches more expressions_
> _autumn of YouTube_

### Walkthrough
*  Update the regex for relative time units to support more variations ([link](https://github.com/yt-dlp/yt-dlp/pull/7191/files?diff=unified&w=0#diff-b7b9f6790de4427214b61939432e667d95b929d07fd918b9da1a36d7996cc506L896-R898))
*  Fix a typo in the docstring of `extract_relative_time` ([link](https://github.com/yt-dlp/yt-dlp/pull/7191/files?diff=unified&w=0#diff-b7b9f6790de4427214b61939432e667d95b929d07fd918b9da1a36d7996cc506L896-R898))

</details>

### CODE REVIEW

**Comment by coletdjnz** [comment]
note that the regex unintentionally detects some other matches too, but unlikely to be an issue: `4 wees ago`, `9 ss ago`, `3 sond ago`, `9 yea ago`. 

(it's a feature, not a bug)

**Comment by pukkandan** [comment]
I would have hardcoded the allowed abbreviations to avoid false matches, but this is good enough.

**Comment by coletdjnz** [comment]
> I would have hardcoded the allowed abbreviations to avoid false matches, but this is good enough.

not sure why that didn't cross my mind. would be more clean 😅

**Comment by dirkf** [comment]
>`# XXX: this could be moved to a general function in utils.py`

Just extend `datetime_from_str()` ?

**Pull request merged**
