### PR TITLE
[Rumble] Extract description, view count

### LINKED ISSUE #2846: [Rumble] Extract description
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Description

When downloading Youtube videos the channel name, url, title and description are saved to the metadata. When downloading from Rumble the url and title are saved to metadata, but not the channel name or description.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://rumble.com/vv6cru-hurro.html']
[debug] User config "/Users/me/.config/yt-dlp/config": ['--cookies-from-browser', 'firefox', '--cache-dir', '/Users/me/.config/youtube-dl/', '--user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0', '--geo-bypass', '-u', 'PRIVATE', '-p', 'PRIVATE', '-i', '--no-mark-watched', '--no-warnings', '--retries', 'infinite', '--fragment-retries', 'infinite', '--download-archive', '/Users/me/.config/youtube-dl/downloads.txt', '-o', '/Users/me/Youtubes/%(uploader)s/%(playlist_title)s/%(upload_date)s - %(title)s.%(ext)s', '-f', 'bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a][abr<=192]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best', '--sub-format', 'srt', '--convert-subs', 'srt', '--write-subs', '--write-auto-subs', '--embed-subs', '--compat-options', 'no-keep-subs', '--sub-lang', 'en,ja', '--embed-thumbnail', '--embed-metadata', '--embed-chapters', '--xattrs', '--audio-format', 'm4a', '--recode-video', 'mp4']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/Users/me/Library/Application Support/Firefox/Profiles/xy4v0sei.default-release-1574345941647/cookies.sqlite"
[Cookies] Extracted 762 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Compatibility options: no-keep-subs
[debug] Python version 3.10.2 (CPython 64bit) - macOS-12.2-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file '/Users/me/.config/youtube-dl/downloads.txt'
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://rumble.com/vv6cru-hurro.html
[generic] vv6cru-hurro: Requesting header
[generic] vv6cru-hurro: Downloading webpage
[generic] vv6cru-hurro: Extracting information
[debug] Looking for video embeds
[debug] [RumbleEmbed] Extracting URL: https://rumble.com/embed/vsk6pm
[RumbleEmbed] vsk6pm: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] vsk6pm: Downloading 1 format(s): mp4-1080p
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: /Users/me/Youtubes/NA/NA/20220217 - Listen to this cat literally say 'hello' over and over again.jpg
[SubtitlesConvertor] There aren't any subtitles to convert
[debug] Invoking downloader on "https://sp.rmbl.ws/s8/2/Q/u/W/h/QuWhd.haa.mp4"
[download] Destination: /Users/me/Youtubes/NA/NA/20220217 - Listen to this cat literally say 'hello' over and over again.mp4
[download] 100% of 18.95MiB in 00:05
[VideoConvertor] Not converting media file "/Users/me/Youtubes/NA/NA/20220217 - Listen to this cat literally say 'hello' over and over again.mp4"; already is in target format mp4
[EmbedSubtitle] There aren't any subtitles to embed
[Metadata] Adding metadata to "/Users/me/Youtubes/NA/NA/20220217 - Listen to this cat literally say 'hello' over and over again.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Users/me/Youtubes/NA/NA/20220217 - Listen to this cat literally say '"'"'hello'"'"' over and over again.mp4' -map 0 -dn -ignore_unknown -c copy -metadata 'title=Listen to this cat literally say "hello" over and over again' -metadata date=20220217 -metadata purl=https://rumble.com/embed/vsk6pm -metadata comment=https://rumble.com/embed/vsk6pm -movflags +faststart 'file:/Users/me/Youtubes/NA/NA/20220217 - Listen to this cat literally say '"'"'hello'"'"' over and over again.temp.mp4'
[EmbedThumbnail] mutagen: Adding thumbnail to "/Users/me/Youtubes/NA/NA/20220217 - Listen to this cat literally say 'hello' over and over again.mp4"
Deleting original file /Users/me/Youtubes/NA/NA/20220217 - Listen to this cat literally say 'hello' over and over again.jpg (pass -k to keep)
[XAttrMetadata] Writing metadata to file's xattrs
[debug] Adding to archive: rumbleembed vsk6pm
```

### PR DESCRIPTION
**Pull request by mehq**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Extract description and view count, closes #2846.

### CODE REVIEW

**Comment by Ashish0804** [comment]
These are "useless" features and requires 2 webpage downloads 
IMO don't merge this.

**Comment by pukkandan** [comment]
It is clearly not useless as someone have requested it (#2846). It is a shame additional requests are needed for it, but it sometimes can't be helped

**Comment by johndpope** [comment]
useful - thanks

**Comment by zackees** [comment]
Found this bug when I was trying to get description on Rumble videos. It would be nice if this feature can be put behind a feature flag like `--include_description`.

Personally, I think this should be the default for `-J` because the amount of time necessary for the second page scrape is inconsequential in comparison to the time it takes to download the video file.

**Pull request closed without merging**
