### PR TITLE
[ie/youtube] Fix `n` function name extraction for player `3400486c`

### PR DESCRIPTION
**Pull request by bashonly**
This now:

```js
;a.D&&(b="nn"[+a.D],c=a.get(b))&&(c=rDa[0](c),a.set(b,c),rDa.length||rma(""))}};
```

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)

</details>

### CODE REVIEW

**Review by seproDev — APPROVED** [review]

**Review by Grub4K — APPROVED** [review]
Im not sure if we should make it generic like this, but its probably fine

**Comment by dirkf** [comment]
[I didn't think it was necessary](https://github.com/ytdl-org/youtube-dl/issues/32842#issuecomment-2247729123) to match the `a.D&&` etc, just some string of `n`s indexed by a variable or object access. Maybe just `\[[^]]+]` would do for the index part.

**Comment by illuminatibit** [comment]
After this update, the itag=18 (360p) format disappeared. Please bring back itag=18.

**Comment by bashonly** [comment]
@illuminatibit I did a quick spot check of a few URLs and I am still getting format 18. Share complete verbose output demonstrating this in a new issue.

**Pull request merged**
