### PR TITLE
[extractor/bilibili] Skip FLV+HEVC format sources

### PR DESCRIPTION
**Pull request by akiirui**
### Skip FLV+HEVC format sources on bilibili live

HEVC over FLV (and thus RTMP) is not defined nor supported.

These sources cannot be played, so skip these.

Ref: https://trac.ffmpeg.org/ticket/6389

Current version (and yt-dlp select source-7 by default):

``` 
yt-dlp -F https://live.bilibili.com/7777
[BiliLive] 7777: Downloading JSON metadata
[BiliLive] 7777: Downloading JSON metadata
[BiliLive] 7777: Downloading JSON metadata
[BiliLive] 7777: Downloading JSON metadata
[BiliLive] 7777: Downloading JSON metadata
[BiliLive] 7777: Downloading JSON metadata
[BiliLive] 7777: Downloading JSON metadata
[BiliLive] 7777: Downloading JSON metadata
[info] Available formats for 7777:
ID               EXT  RESOLUTION │ PROTO │ VCODEC ACODEC  MORE INFO
───────────────────────────────────────────────────────────────────
high_res-0       fmp4 unknown    │ m3u8  │ avc    unknown 高清
high_res-1       fmp4 unknown    │ m3u8  │ avc    unknown 高清
high_res-2       flv  unknown    │ https │ avc    unknown 高清
high_res-3       flv  unknown    │ https │ avc    unknown 高清
ultra_high_res-0 fmp4 unknown    │ m3u8  │ avc    unknown 超清
ultra_high_res-1 fmp4 unknown    │ m3u8  │ avc    unknown 超清
ultra_high_res-2 flv  unknown    │ https │ avc    unknown 超清
ultra_high_res-3 flv  unknown    │ https │ avc    unknown 超清
ultra_high_res-4 fmp4 unknown    │ m3u8  │ hevc   unknown 超清
ultra_high_res-5 fmp4 unknown    │ m3u8  │ hevc   unknown 超清
ultra_high_res-6 flv  unknown    │ https │ hevc   unknown 超清
ultra_high_res-7 flv  unknown    │ https │ hevc   unknown 超清
blue_ray-0       fmp4 unknown    │ m3u8  │ avc    unknown 蓝光
blue_ray-1       fmp4 unknown    │ m3u8  │ avc    unknown 蓝光
blue_ray-2       flv  unknown    │ https │ avc    unknown 蓝光
blue_ray-3       flv  unknown    │ https │ avc    unknown 蓝光
source-0         fmp4 unknown    │ m3u8  │ avc    unknown 原画
source-1         fmp4 unknown    │ m3u8  │ avc    unknown 原画
source-2         flv  unknown    │ https │ avc    unknown 原画
source-3         flv  unknown    │ https │ avc    unknown 原画
source-4         fmp4 unknown    │ m3u8  │ hevc   unknown 原画
source-5         fmp4 unknown    │ m3u8  │ hevc   unknown 原画
source-6         flv  unknown    │ https │ hevc   unknown 原画
source-7         flv  unknown    │ https │ hevc   unknown 原画
```
<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by skbeh** [comment]
Although there sources are not defined, it is still possible to download them and convert them to standard formats (e.g. mkv). So it would be better to automatically convert when possible, or add an option to let the users decide.

**Comment by akiirui** [comment]
> Although these format sources are not defined, it is still possible to download them and convert them to standard formats (e.g. mkv). So it would be better to automatically convert when possible, or add an option to let the users decide.

Sadly, ffmpeg cannot convert files such these.

**Comment by Lesmiscore** [comment]
Format ID 12 in FLV is indeed HEVC, which causes ffmpeg tons of errors as it's not supported

```
[flv @ 0x55c35417dec0] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[flv @ 0x55c35417dec0] Could not find codec parameters for stream 1 (Video: none ([12][0][0][0] / 0x000C), none, 2834 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, flv, from '德云色  快乐FPS！ [7777].flv':
  Metadata:
    fps             : 60
    profile         : 
    Rawdata         : 
    displayWidth    : 1920
    level           : 
    cdn_ip          : 192.168.254.4
    encoder         : Lavf58.29.100
    displayHeight   : 1080
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
  Stream #0:1: Video: none ([12][0][0][0] / 0x000C), none, 2834 kb/s, 60 fps, 60 tbr, 1k tbn
Unsupported codec with id 0 for input stream 1
```

While most of the casual-use people don't want to download such unplayable files <sub>(for "unplayable files" here, I don't mean they are encrypted; they just don't play because the container hasn't taken care of HEVC)</sub>, I'd suggest deprioritizing these formats to allow downloading one for anyone interested in.

ref. https://github.com/xqq/mpegts.js/blob/6bf10e8a5be96543aaf3fb4bb7dcfcf8e7a21f02/src/demux/flv-demuxer.js#L843

**Comment by akiirui** [comment]
@Lesmiscore Yep, it's a best way. But the default order of yt-dlp is 

```
lang,quality,res,fps,hdr:12,vcodec:vp9.2,channels,acodec,size,br,asr,proto,ext,hasaud,source,id
```

The `vcodec (vp9.2 > av01 > vp9.2 > vp9 > h265 > h264 > vp8 > h263 > theora > other)` is matched first and `ext (mp4 > mov > webm > flv > other)` is matched second.

So, `h265` and `flv` are selected here.

**Comment by Lesmiscore** [comment]
Let's do this: (I had to do this because GitHub doesn't allow reviews to unmodified regions)
```diff
diff --git a/yt_dlp/extractor/bilibili.py b/yt_dlp/extractor/bilibili.py
index bc0424194..4ee3133f4 100644
--- a/yt_dlp/extractor/bilibili.py
+++ b/yt_dlp/extractor/bilibili.py
@@ -1074,12 +1074,18 @@ def _parse_formats(self, qn, fmt):
         for codec in fmt.get('codec') or []:
             if codec.get('current_qn') != qn:
                 continue
+            preference = -1
+            if fmt.get('format_name') == 'flv' and codec.get('codec_name') in ('hevc', 'h265'):
+                # HEVC-over-FLV is out-of-spec from FLV's original spec
+                # ref. https://trac.ffmpeg.org/ticket/6389
+                preference = -10
             for url_info in codec['url_info']:
                 yield {
                     'url': f'{url_info["host"]}{codec["base_url"]}{url_info["extra"]}',
                     'ext': fmt.get('format_name'),
                     'vcodec': codec.get('codec_name'),
                     'quality': self._quality(qn),
+                    'source_preference': preference,
                     **self._FORMATS[qn],
                 }
 
@@ -1111,6 +1117,7 @@ def _real_extract(self, url):
             'thumbnail': room_data.get('user_cover'),
             'timestamp': stream_data.get('live_time'),
             'formats': formats,
+            '_format_sort_fields': ['source'],
             'http_headers': {
                 'Referer': url,
             },
```

And here's -F:
```
$ ./b -F https://live.bilibili.com/6
[BiliLive] Extracting URL: https://live.bilibili.com/6
[BiliLive] 6: Downloading JSON metadata
[BiliLive] 6: Downloading JSON metadata
[BiliLive] 6: Downloading JSON metadata
[BiliLive] 6: Downloading JSON metadata
[BiliLive] 6: Downloading JSON metadata
[BiliLive] 6: Downloading JSON metadata
[BiliLive] 6: Downloading JSON metadata
[BiliLive] 6: Downloading JSON metadata
[info] Available formats for 6:
ID               EXT RESOLUTION │ PROTO │ VCODEC ACODEC  MORE INFO
──────────────────────────────────────────────────────────────────
ultra_high_res-0 flv unknown    │ https │ hevc   unknown 超清
ultra_high_res-1 flv unknown    │ https │ hevc   unknown 超清
source-0         flv unknown    │ https │ hevc   unknown 原画
source-1         flv unknown    │ https │ hevc   unknown 原画
high_res-0       flv unknown    │ https │ avc    unknown 高清
high_res-1       flv unknown    │ https │ avc    unknown 高清
ultra_high_res-2 flv unknown    │ https │ avc    unknown 超清
ultra_high_res-3 flv unknown    │ https │ avc    unknown 超清
source-2         flv unknown    │ https │ avc    unknown 原画
source-3         flv unknown    │ https │ avc    unknown 原画
```

**Comment by akiirui** [comment]
@Lesmiscore 

Awesome, your method is good. I will close this PR and wait for your PR.

**Comment by pukkandan** [comment]
This looks like a situation where using `preference` instead of `source` seem justified

**Comment by pukkandan** [comment]
@Lesmiscore Feel free to directly push this change to master

**Pull request closed without merging**
