### PR TITLE
Add flag --breaking-match-filters

### PR DESCRIPTION
**Pull request by barcode**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Implement the `--break-on-reject-date` flag.

When downloading all videos a channel/playlist after some date  it can save a lot of time to use `--break-on-reject --lazy-playlist`.
This works fine, until you also want to use some `--match-filters`. Then you have to drop  `--break-on-reject` or the download will not work. The new flag solves this by only breaking, when a date filter (`--date`, `--datebefore`, `--dateafter`) is hit.

Example:
 
List:  https://www.youtube.com/playlist?list=UUYO_jab_esuFRV4b17AJtAw

Videos in date range:

* But what is a convolution?
* Researchers thought this was a bug (Borwein integrals)

Broken call using `--break-on-reject`

	python3 -m yt_dlp --break-on-reject --lazy-playlist --dateafter 20221101 --match-filters 'fulltitle!*="convolution"' 'https://www.youtube.com/playlist?list=UUYO_jab_esuFRV4b17AJtAw'

	[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=UUYO_jab_esuFRV4b17AJtAw
	[youtube:tab] UUYO_jab_esuFRV4b17AJtAw: Downloading webpage
	[youtube:tab] UUYO_jab_esuFRV4b17AJtAw: Redownloading playlist API JSON with unavailable videos
	[download] Downloading playlist: Uploads from 3Blue1Brown
	[youtube:tab] Playlist Uploads from 3Blue1Brown: Downloading N/A items of 127
	[download] Downloading item 1 of N/A
	[youtube] Extracting URL: https://www.youtube.com/watch?v=KuXjwB4LzSA
	[youtube] KuXjwB4LzSA: Downloading webpage
	[youtube] KuXjwB4LzSA: Downloading android player API JSON
	[download] But what is a convolution? does not pass filter (fulltitle!*="convolution"), skipping ..
	[info] Encountered a video that did not match filter, stopping due to --break-on-reject
	Aborting remaining downloads

-> no video was downloaded, since the first was filtered out

Call using `--break-on-reject-date`

	python3 -m yt_dlp --break-on-reject-date --lazy-playlist --dateafter 20221101 --match-filters 'fulltitle!*="convolution"' 'https://www.youtube.com/playlist?list=UUYO_jab_esuFRV4b17AJtAw'

	[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=UUYO_jab_esuFRV4b17AJtAw
	[youtube:tab] UUYO_jab_esuFRV4b17AJtAw: Downloading webpage
	[youtube:tab] UUYO_jab_esuFRV4b17AJtAw: Redownloading playlist API JSON with unavailable videos
	[download] Downloading playlist: Uploads from 3Blue1Brown
	[youtube:tab] Playlist Uploads from 3Blue1Brown: Downloading N/A items of 127
	[download] Downloading item 1 of N/A
	[youtube] Extracting URL: https://www.youtube.com/watch?v=KuXjwB4LzSA
	[youtube] KuXjwB4LzSA: Downloading webpage
	[youtube] KuXjwB4LzSA: Downloading android player API JSON
	[download] But what is a convolution? does not pass filter (fulltitle!*="convolution"), skipping ..
	[download] Downloading item 2 of N/A
	[youtube] Extracting URL: https://www.youtube.com/watch?v=851U557j6HE
	[youtube] 851U557j6HE: Downloading webpage
	[youtube] 851U557j6HE: Downloading android player API JSON
	[info] 851U557j6HE: Downloading 1 format(s): 313+251
	[download] Destination: Researchers thought this was a bug (Borwein integrals) [851U557j6HE].f313.webm
	[download] 100% of  334.38MiB in 00:00:17 at 19.42MiB/s
	[download] Destination: Researchers thought this was a bug (Borwein integrals) [851U557j6HE].f251.webm
	[download] 100% of   17.00MiB in 00:00:00 at 21.37MiB/s
	[Merger] Merging formats into "Researchers thought this was a bug (Borwein integrals) [851U557j6HE].webm"
	Deleting original file Researchers thought this was a bug (Borwein integrals) [851U557j6HE].f251.webm (pass -k to keep)
	Deleting original file Researchers thought this was a bug (Borwein integrals) [851U557j6HE].f313.webm (pass -k to keep)
	[download] Downloading item 3 of N/A
	[youtube] Extracting URL: https://www.youtube.com/watch?v=cDofhN-RJqg
	[youtube] cDofhN-RJqg: Downloading webpage
	[youtube] cDofhN-RJqg: Downloading android player API JSON
	[download] 2022-10-01 upload date is not in range 2022-11-01 - 9999-12-31
	[info] Encountered a video that did not match the allowed range of dates, stopping due to --break-on-reject-date
	Aborting remaining downloads

-> downloading the second video and stopping due to dateafter.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [x] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by pukkandan** [comment]
What happens when you want to break with filter, but not date? Or with date-after, but not date-before? This PR is adding a new switch to address just a special case of this underlying problem. I also want to eventually deprecate --date options once match-filter syntax is improved enough to handle all its usecases - which would become impossible once this is implemented. A more general solution is needed

**Comment by barcode** [comment]
I agree, a separate option for a different kind of filter would be better and more general. 
But i think it should be  `--breaking-match-filters`, since the default is non breaking. 

In this case the filters for `--breaking-match-filters` would always break and the filters for `--match-filters` only if `--break-on-reject` is set as well.

**Comment by pukkandan** [comment]
sounds good. It effectively deprecates `--breka-on-reject`, but that's okay

**Comment by barcode** [comment]
I cleaned up the code duplication

**Comment by barcode** [comment]
Anything i still need to do for this PR?

**Comment by pukkandan** [comment]
Sorry for the delay. I was planning to review, but ended up implementing this completely differently

**Pull request closed without merging**
