### PR TITLE
[ytdownload] Increased read timeout

### LINKED ISSUE #8468: [issue on youtube's end] YouTube 503 download problems
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Spain

### Provide a description that is worded well enough to be understood

As for Thursday, youtube gives problems when downloading an video.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[download] Downloading item 20 of 30
[youtube] Extracting URL: https://www.youtube.com/watch?v=oSPsr9m7OJo
[youtube] oSPsr9m7OJo: Downloading webpage
[youtube] oSPsr9m7OJo: Downloading android player API JSON
[youtube] oSPsr9m7OJo: Downloading ios player API JSON
[youtube] oSPsr9m7OJo: Downloading m3u8 information
[info] oSPsr9m7OJo: Downloading 1 format(s): 270+251
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 151
[download] Destination: Miss Tilly's Fun Time TV Minute Show 💖 ｜ Compilation ｜ Big City Greens ｜ Disney Channel [oSPsr9m7OJo].f270.mp4
[download]   4.8% of ~ 127.32MiB at    1.76MiB/s ETA 02:01 (frag 6/151)[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out.. Retrying (1/10)...
Sleeping 5.00 seconds ...
[download]  19.4% of ~ 127.15MiB at    2.08MiB/s ETA 00:36 (frag 28/151)[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out.. Retrying (1/10)...
Sleeping 5.00 seconds ...
[download]  19.4% of ~ 127.15MiB at  841.41KiB/s ETA 01:39 (frag 28/151)[download] Got error: 225540 bytes read. Retrying (2/10)...
Sleeping 5.00 seconds ...
[download]  19.4% of ~ 127.15MiB at    1.12MiB/s ETA 01:36 (frag 28/151)[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out.. Retrying (3/10)...
Sleeping 5.00 seconds ...
[download]  19.4% of ~ 127.15MiB at    1.20MiB/s ETA 01:01 (frag 28/151)[download] Got error: 225540 bytes read. Retrying (4/10)...
Sleeping 5.00 seconds ...
[download]  19.4% of ~ 127.15MiB at  986.35KiB/s ETA 01:13 (frag 28/151)[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out.. Retrying (5/10)...
Sleeping 5.00 seconds ...
[download]  19.4% of ~ 127.15MiB at    1.21MiB/s ETA 01:13 (frag 28/151)[download] Got error: 225540 bytes read. Retrying (6/10)...
Sleeping 5.00 seconds ...
[download]  23.9% of ~ 129.21MiB at    1.29MiB/s ETA 01:33 (frag 35/151)[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out.. Retrying (1/10)...
Sleeping 5.00 seconds ...
[download]  23.9% of ~ 129.21MiB at  655.61KiB/s ETA 01:37 (frag 35/151)[download] Got error: 180116 bytes read. Retrying (2/10)...
Sleeping 5.00 seconds ...
[download]  33.3% of ~ 130.45MiB at    1.33MiB/s ETA 00:30 (frag 51/151)[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out. (read timeout=20.0). Retrying (1/10)...
Sleeping 5.00 seconds ...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (2/10)...
Sleeping 5.00 seconds ...
[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out. (read timeout=20.0). Retrying (3/10)...
Sleeping 5.00 seconds ...
[download]  35.9% of ~ 132.52MiB at    1.25MiB/s ETA 01:16 (frag 55/151)
```

### PR DESCRIPTION
**Pull request by akashverma0786**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADD DESCRIPTION HERE

Fixes #8468 

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [ x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [ x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
:sparkles::truck::construction:

Add a new extractor module `ytdownload.py` for a website `yourextractor.com` and import it in `_extractors.py`. The new extractor class `ytdownloadIE` is still a work in progress and needs to be completed with the website-specific logic and data.

> _New `ytdownloadIE`_
> _Extracts from yourextractor_
> _Code is not finished_

### Walkthrough
* Create a new module `ytdownload.py` that defines a new extractor class for `yourextractor.com` ([link](https://github.com/yt-dlp/yt-dlp/pull/8472/files?diff=unified&w=0#diff-9fe0e05c08beee29596d701d0cde747643470055b81dc8a7ac032e7bcea00fbdL1-R34))
* Import and register the new extractor class in the main extractor module `_extractors.py` ([link](https://github.com/yt-dlp/yt-dlp/pull/8472/files?diff=unified&w=0#diff-780b22dc7eb280f5a7b2bbf79aff17826de88ddcbf2fc1116ba19901827aa4e3L2575-L2573))

</details>

### CODE REVIEW

**Comment by akashverma0786** [comment]
Please tell me what happened?

**Comment by akashverma0786** [comment]
@coletdjnz ?

**Comment by seproDev** [comment]
You opened a pull request, probably by accident, meaning you made a request to make changes to the yt-dlp code.
But the changes suggested here are nonsensical. That's why the PR was closed and marked as spam.

**Comment by akashverma0786** [comment]
@seproDev Thankyou for explaining
and sorry I am new in here, i thought that increasing timeout will resolve the issue but my bad.

**Comment by gamer191** [comment]
> and sorry I am new in here, i thought that increasing timeout will resolve the issue but my bad.

That's all good. The issue is that your PR literally does nothing except create a file called ytdownload.py
Perhaps you were trying to PR something different? Although tbh I don't think a PR to increase the read timeout would be merged anyway

**Pull request closed without merging**
