### PR TITLE
[extractor/ccc] Extract view_count

### PR DESCRIPTION
**Pull request by vkorablin**
Extract `view_count` for media.ccc.de

### CODE REVIEW

**Comment by pukkandan** [comment]
Do not remove the PR template!

**Comment by vkorablin** [comment]
> Do not remove the PR template!

Sorry, my bad. Just in case:

[x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

**Comment by gamer191** [comment]
NOTE: please ignore the failing commit test. It's due to an external bug (the external bug being that pytest is partially broken in python 3.11-dev)

**Comment by pukkandan** [comment]
@gamer191 You don't need to say this in each PR!

**Pull request merged**
