### PR TITLE
[extractor/tiktok] avoid for loop.

### PR DESCRIPTION
**Pull request by freezboltz**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

Avoid unnecessary looping .

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
If your objective is a code cleanup, pls do the same for all these

```py
yt_dlp • YoutubeDL.py:
  1071:         sep = ''.join([random.choice(ascii_letters) for _ in range(32)])

yt_dlp • extractor\adn.py:
  171:         self._K = ''.join([random.choice('0123456789abcdef') for _ in range(16)])

yt_dlp • extractor\discovery.py:
  81:                     'nonce': ''.join([random.choice(string.ascii_letters) for _ in range(32)]),

yt_dlp • extractor\funimation.py:
  213:                     'pinst_id': ''.join([random.choice(string.digits + string.ascii_letters) for _ in range(8)]),

yt_dlp • extractor\tencent.py:
  35:         guid = ''.join([random.choice(string.digits + string.ascii_lowercase) for _ in range(16)])
  58:             'flowid': ''.join(random.choice(string.digits + string.ascii_lowercase) for _ in range(32)),

yt_dlp • extractor\tiktok.py:
   52:         self._set_cookie(self._API_HOSTNAME, 'odin_tt', ''.join(random.choice('0123456789abcdef') for _ in range(160)))
   71:             'openudid': ''.join(random.choice('0123456789abcdef') for _ in range(16)),
   72:             'uuid': ''.join([random.choice(string.digits) for _ in range(16)]),
  641:             'device_id': ''.join(random.choice(string.digits) for _ in range(19)),  # Some endpoints don't like randomized device_id, so it isn't directly set in _call_api.

yt_dlp • extractor\videa.py:
  122:         random_seed = ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(8))

yt_dlp • extractor\viu.py:
  254:         rand = ''.join(random.choice('0123456789') for _ in range(10))

yt_dlp • extractor\vrv.py:
  33:             ('oauth_nonce', ''.join([random.choice(string.ascii_letters) for _ in range(32)])),

```

**Comment by freezboltz** [comment]
> If your objective is a code cleanup, pls do the same for all these
> 
> ```python
> yt_dlp • YoutubeDL.py:
>   1071:         sep = ''.join([random.choice(ascii_letters) for _ in range(32)])
> 
> yt_dlp • extractor\adn.py:
>   171:         self._K = ''.join([random.choice('0123456789abcdef') for _ in range(16)])
> 
> yt_dlp • extractor\discovery.py:
>   81:                     'nonce': ''.join([random.choice(string.ascii_letters) for _ in range(32)]),
> 
> yt_dlp • extractor\funimation.py:
>   213:                     'pinst_id': ''.join([random.choice(string.digits + string.ascii_letters) for _ in range(8)]),
> 
> yt_dlp • extractor\tencent.py:
>   35:         guid = ''.join([random.choice(string.digits + string.ascii_lowercase) for _ in range(16)])
>   58:             'flowid': ''.join(random.choice(string.digits + string.ascii_lowercase) for _ in range(32)),
> 
> yt_dlp • extractor\tiktok.py:
>    52:         self._set_cookie(self._API_HOSTNAME, 'odin_tt', ''.join(random.choice('0123456789abcdef') for _ in range(160)))
>    71:             'openudid': ''.join(random.choice('0123456789abcdef') for _ in range(16)),
>    72:             'uuid': ''.join([random.choice(string.digits) for _ in range(16)]),
>   641:             'device_id': ''.join(random.choice(string.digits) for _ in range(19)),  # Some endpoints don't like randomized device_id, so it isn't directly set in _call_api.
> 
> yt_dlp • extractor\videa.py:
>   122:         random_seed = ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(8))
> 
> yt_dlp • extractor\viu.py:
>   254:         rand = ''.join(random.choice('0123456789') for _ in range(10))
> 
> yt_dlp • extractor\vrv.py:
>   33:             ('oauth_nonce', ''.join([random.choice(string.ascii_letters) for _ in range(32)])),
> ```

on it.

**Comment by freezboltz** [comment]
> If your objective is a code cleanup, pls do the same for all these
> 
> ```python
> yt_dlp • YoutubeDL.py:
>   1071:         sep = ''.join([random.choice(ascii_letters) for _ in range(32)])
> 
> yt_dlp • extractor\adn.py:
>   171:         self._K = ''.join([random.choice('0123456789abcdef') for _ in range(16)])
> 
> yt_dlp • extractor\discovery.py:
>   81:                     'nonce': ''.join([random.choice(string.ascii_letters) for _ in range(32)]),
> 
> yt_dlp • extractor\funimation.py:
>   213:                     'pinst_id': ''.join([random.choice(string.digits + string.ascii_letters) for _ in range(8)]),
> 
> yt_dlp • extractor\tencent.py:
>   35:         guid = ''.join([random.choice(string.digits + string.ascii_lowercase) for _ in range(16)])
>   58:             'flowid': ''.join(random.choice(string.digits + string.ascii_lowercase) for _ in range(32)),
> 
> yt_dlp • extractor\tiktok.py:
>    52:         self._set_cookie(self._API_HOSTNAME, 'odin_tt', ''.join(random.choice('0123456789abcdef') for _ in range(160)))
>    71:             'openudid': ''.join(random.choice('0123456789abcdef') for _ in range(16)),
>    72:             'uuid': ''.join([random.choice(string.digits) for _ in range(16)]),
>   641:             'device_id': ''.join(random.choice(string.digits) for _ in range(19)),  # Some endpoints don't like randomized device_id, so it isn't directly set in _call_api.
>   689:             'device_id': ''.join(random.choice(string.digits) for i in range(19))
> 
> yt_dlp • extractor\videa.py:
>   122:         random_seed = ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(8))
> 
> yt_dlp • extractor\viu.py:
>   254:         rand = ''.join(random.choice('0123456789') for _ in range(10))
> 
> yt_dlp • extractor\vrv.py:
>   33:             ('oauth_nonce', ''.join([random.choice(string.ascii_letters) for _ in range(32)])),
> 
> yt_dlp • extractor\youku.py:
>   123:             random.choice(string.ascii_letters) for i in range(3)]))
> ```

fix #5800

**Comment by pukkandan** [comment]
You could have pushed it to same PR

**Pull request closed without merging**
