### PR TITLE
[youtube] Fix inconsistent date timezones (ensure result is in UTC)

### LINKED ISSUE #1881: Is the date value for the output based on the IP and if so is it possible to base it on the system date instead?
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

My system timezone is set to UTC and when I checked a newly uploaded video on youtube it matches the date on my system but when I downloaded it with `yt-dlp` the date is different. Is it possible to make the date value match my system date?

### PR DESCRIPTION
**Pull request by coletdjnz**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [X] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Fixes #1881 
Depends on #2069 

- Fixes upload_date for videos not being in UTC timezone (by parsing the `dateText` instead)
    - player response upload date is fixed to a timezone such as PT (US timezone). We will only use this as a fallback now.
    - this inadvertently fixes upload dates not being available on non-web clients (#1067)
    - For videos where there may be relative time, this would be restricted to <24 hours, so will still be accurate.
    - Livestreams, premieres and scheduled videos will continue to use microformat upload date, since in those cases the upload date is the true upload date. This changes to published date once the video is published.
~~- Fixes `datetime_from_str` using computer's timezone rather than UTC~~ already merged
   ~~- relative time text parsing actually returns a UNIX timestamp in UTC~~
~~- Enforce UTC timezone for all API/webpage calls in YouTube extractors, regardless of cookie setting.~~ already merged

TODO:
 - [X] Add some tests

### CODE REVIEW

**Comment by coletdjnz** [comment]
Couple things:
- should we have the bugs report message (or even the warning) if we can't extract the dateText upload date?
- for premieres that are scheduled, we get this behavior:
Using playerResponse upload_date:
```
$ yt-dlp --print upload_date JwvNn7JwIf0 --ignore-no-formats
WARNING: [youtube] Premieres in 2 days
WARNING: No video formats found!
WARNING: Requested format is not available
20220107
```
Using dateText from this PR:
```
$ yt-dlp --print upload_date JwvNn7JwIf0 --ignore-no-formats
WARNING: [youtube] Premieres in 2 days
WARNING: No video formats found!
WARNING: Requested format is not available
20220110
```
which is more or less the release date

**Comment by pukkandan** [comment]
> for premieres that are scheduled, we get this behavior:

hm.. that is a problem. afair, `upload_date` should be the date when the video was uploaded, and `release_date` when the premier starts

**Comment by coletdjnz** [comment]
> > for premieres that are scheduled, we get this behavior:
> 
> hm.. that is a problem. afair, `upload_date` should be the date when the video was uploaded, and `release_date` when the premier starts

TODO: I should check this for past streams/premieres and current/upcoming streams too.

I suppose we could always prefer playerResponse upload date source for scheduled premieres (and any other applicable)

Earlier I had also tested a video that had been published after being scheduled to release public after 2 weeks (normal video, not premiere) and the PR upload date was the same as the date it was made public/dateText).

**Comment by coletdjnz** [comment]
I observed what the player response was giving for the upload date for a scheduled stream, when it went live and finished. Going by the earlier observation I would assume this applies to premieres too.

dNkMG1Twjug:
**Before start (scheduled)**
```
"publishDate": "2022-01-04",
      "ownerChannelName": "Netflix Brasil",
      "liveBroadcastDetails": {
        "isLiveNow": false,
        "startTimestamp": "2022-01-10T00:00:00+00:00"
      },
      "uploadDate": "2022-01-04"
```
Note the upload date != stream start/release date

**When live**
```
"publishDate": "2022-01-04",
      "ownerChannelName": "Netflix Brasil",
      "liveBroadcastDetails": {
        "isLiveNow": true,
        "startTimestamp": "2022-01-10T00:00:06+00:00"
      },
      "uploadDate": "2022-01-04"
```

**When finished**

```
"publishDate": "2022-01-04",
      "ownerChannelName": "Netflix Brasil",
      "liveBroadcastDetails": {
        "isLiveNow": false,
        "startTimestamp": "2022-01-10T00:00:06+00:00",
        "endTimestamp": "2022-01-10T00:47:16+00:00"
      },
      "uploadDate": "2022-01-04"
```

**However**, not long after it finished, the upload date changed to the stream start date:

```
"publishDate": "2022-01-09",
      "ownerChannelName": "Netflix Brasil",
      "liveBroadcastDetails": {
        "isLiveNow": false,
        "startTimestamp": "2022-01-10T00:00:06+00:00",
        "endTimestamp": "2022-01-10T00:47:16+00:00"
      },
      "uploadDate": "2022-01-09"
```
This was a short stream though. Maybe it is possible YouTube can change the uploadDate during the livestream for longer ones?

**Comment by coletdjnz** [comment]
Going to merge the rest via https://github.com/yt-dlp/yt-dlp/pull/2402.

**Pull request merged**
