### PR TITLE
[SonyLiv]Fix key extraction and add series key.

### PR DESCRIPTION
**Pull request by Ashish0804**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

Previously it was appending the Series name and Episode title. 
Now title is episode title and series title is separate.

`title = metadata['episodeTitle']` this works for movies as well.

### CODE REVIEW

**Comment by pukkandan** [comment]
Please confirm that the title gets extracted correctly for all types of URLs
```
https://www.sonyliv.com/shows/bachelors-delight-1700000113/achaari-cheese-toast-1000022678?watch=true
https://www.sonyliv.com/movies/tahalka-1000050121?watch=true
https://www.sonyliv.com/clip/jigarbaaz-1000098925
https://www.sonyliv.com/trailer/sandwiched-forever-1000100286?watch=true
https://www.sonyliv.com/sports/india-tour-of-australia-2020-21-1700000286/cricket-hls-day-3-1st-test-aus-vs-ind-19-dec-2020-1000100959
https://www.sonyliv.com/music-videos/yeh-un-dinon-ki-baat-hai-1000018779
```

**Comment by Ashish0804** [comment]
> https://www.sonyliv.com/trailer/sandwiched-forever-1000100286?watch=true
> https://www.sonyliv.com/sports/india-tour-of-australia-2020-21-1700000286/cricket-hls-day-3-1st-test-aus-vs-ind-19-dec-2020-1000100959

It's working for all but these 2, not bcoz there's problem with edits i made, but with ytdlp or sony itself...maybe it's bcoz the match was live and now url changed and the trailer is removed as movies was released.
IMO my commit is okay to be merged but if you want me to test for trailer and sports then lemme know.

**Comment by pukkandan** [comment]
Those are just URLs from the test. You don't need to test for them specifically, but just any trailer and sports video

**Comment by Ashish0804** [comment]
> Those are just URLs from the test. You don't need to test for them specifically, but just any trailer and sports video

works for this
`https://www.sonyliv.com/sports/abu-dhabi-t10-league-2021-1700000666/cricket-hls-devils-vs-qalandars-29-jan-2021-1000106285?watch=true`

**Pull request merged**
