### PR TITLE
[networking] Remove `_CompatHTTPError`

### PR DESCRIPTION
**Pull request by coletdjnz**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

`_CompatHTTPError` was to help with transition to the networking framework. It is not used in yt-dlp, but was there in the rare case plugins or external scripts were catching it.

These days it should be safe to remove. It just bloats the logs we get from users.

Be sure to add a breaking change announcement on the release changelog.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [X] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Review by Grub4K — APPROVED** [review]

**Comment by pukkandan** [comment]
LGTM. But merge this for after the pending release imo

**Comment by pukkandan** [comment]
> These days it should be safe to remove. It just bloats the logs we get from users.

This is a very small change which nobody probably uses and so it's fine to remove.

But in general, I disagree. yt-dlp development moves very fast, but doesnt mean consumers of our API does the same. It's been only 3 months since deprecation, which is a tiny time window for more slow moving projects.

**Comment by pukkandan** [comment]
Shouldn't https://github.com/yt-dlp/yt-dlp/blob/225cf2b830a1de2c5eacd257edd2a01aed1e1114/yt_dlp/compat/_legacy.py#L73 also point to the new HTTPError?

**Comment by coletdjnz** [comment]
> > These days it should be safe to remove.
> 
> This is a very small change which nobody probably uses and so it's fine to remove.
> 
> But in general, I disagree. yt-dlp development moves very fast, but doesnt mean consumers of our API does the same. It's been only 3 months since deprecation, which is a tiny time window for more slow moving projects.

Yep, I agree too. Just in this particular case it should be fine as its unlikely to be used externally.

**Comment by pukkandan** [comment]
Missed https://github.com/yt-dlp/yt-dlp/blob/225cf2b830a1de2c5eacd257edd2a01aed1e1114/yt_dlp/compat/_legacy.py#L91

**Comment by coletdjnz** [comment]
> Missed https://github.com/yt-dlp/yt-dlp/blob/225cf2b830a1de2c5eacd257edd2a01aed1e1114/yt_dlp/compat/_legacy.py#L91

that says explicitly urllib though?

**Comment by pukkandan** [comment]
They are supposed to be the same thing and was added due to https://github.com/ytdl-org/youtube-dl/commit/249f2b631629471af5cfee2993e62de58c8f5990

**Pull request merged**
