### PR TITLE
Update supportedsites.md

### PR DESCRIPTION
**Pull request by demo308**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

myvrspot is a video hosting service for schools

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [√ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [√ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes)) **added to a list**

</details>

### CODE REVIEW

**Comment by bashonly** [comment]
Did you mean to open a [site support request](https://github.com/yt-dlp/yt-dlp/issues/new?assignees=&labels=triage%2Csite-request&projects=&template=2_site_support_request.yml) instead?

**Comment by demo308** [comment]
No. It's already supported but not in the list, I even tested it.

**Comment by Grub4K** [comment]
Sites may be supported through the generic extractor or similar. Does not mean support has been implemented by us explicitly

**Comment by demo308** [comment]
ok.

**Comment by grqz** [comment]
`supportedsites.md` is automatically generated by [`devscripts/make_supportedsites.py`](https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/make_supportedsites.py) every time when there is a release or whenever `make doc`/`make supportedsites` is run.
That's also why `generic: Generic downloader that works on some sites` is at the end of the file

**Comment by demo308** [comment]
Ok, thanks for the clarification.

**Pull request closed without merging**
