### PR TITLE
Add option `--no-break-on-existing`

### PR DESCRIPTION
**Pull request by bashonly**
<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Core bug fix/improvement

</details>

### CODE REVIEW

**Comment by Hrxn** [comment]
What is the purpose of this in comparison with `--no-download-archive`?

**Comment by Hrxn** [comment]
Ah, okay, so you can re-download videos already existing in the archive file..

Thank you for the explanation, appreciate it!

**Comment by bashonly** [comment]
@Hrxn no, it will not force downloading of already-recorded videos. 

Let's say you pass a playlist URL with 100 videos, and you have only the 50th video in the playlist already downloaded and recorded in the archive.

`--download-archive --break-on-existing` will download the first 49 videos, and then break upon reaching the 50th video since it is already recorded, and no further videos in the playlist will be downloaded.

`--download-archive --no-break-on-existing` wil ldownload the first 49 videos, skip the 50th video, and continue downloading the rest of the playlist

**Comment by Hrxn** [comment]
Ah, gotcha. Makes more sense.

Good that `--no-break-on-existing` is the default, I think this is more intuitive.

**Pull request merged**
