### PR TITLE
Add --color option with support 'always', 'never' and 'auto' values

### LINKED ISSUE #3643: Better color flags for terminal output
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Currently there only exists a `--no-colors` option. This only allows disabling color output, but there is no option to always enable color output. This is useful in my case, because I want to pipe it into grep, while also showing its output using tee.
That's why I propose the standardized way many applications (e.g. ls and grep) in the unix world already use:
```
--color=auto (default)
--color=always
--color=never
```

### Verbose log

_No response_

### PR DESCRIPTION
**Pull request by sulyi**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

---

### Description of your *pull request* and other information

Keeps existing `--no-color` option as an alias for backward compatibility.

closes #3643

### TODO:

- [x] add and document option
- [x] add documentation to `YoutubeDL`
- [x] add logic to set `_allow_colors`
- [x] add depreciated warning to `--no-color` (only in api)
- [x] add recommendation against `--no-color`
- [x] minor changes (remove British spelling variant of option, rename `use_color` parameter key to `color_mode`)
- [x] update readme

### Test

[test_never_color.py](https://gist.github.com/sulyi/ae3444902379f616273ead1262ab89f9)
- [x] `python test_never_color.py` no warning
- [x] `python -m test_never_color` has warning

**Please feel free to review and provide suggestions even when this is a draft :grinning:**

### CODE REVIEW

**Comment by pukkandan** [comment]
1. Nothing is actually implemented yes?
1. Document `--no-color` in https://github.com/yt-dlp/yt-dlp#not-recommended
2. The alias is unnecessary
3. Add stdout/stderr options to only colorize the specified stream

> add depreciated warning to --no-color?

In the CLI, make --no-color set `color_mode` instead. In API, show deprecation warning only if both `color_mode` and `no_color` are used simultaneously

**Comment by pukkandan** [comment]
> It' might require to rethink logic when setting _allow_colors, but that's ok.

I meant the colo**u**rs alias

**Comment by sulyi** [comment]
> I meant the colo**u**rs alias

Well, if you insist. I'll won't die defending it.

So `--no-color` alias of `--color never` can stay?

**Comment by pukkandan** [comment]
Yes

> In the CLI, make --no-color set color_mode instead. In API, show deprecation warning only if both color_mode and no_color are used simultaneously

**Comment by sulyi** [comment]
> Yes

Ok, renaming `use_color` to `color_mode` won't cause issue.

**Comment by UnlimitedCookies** [comment]
Good stuff! 
- I agree, the British spell alias is not necessary (the computing world has settled on American spelling)
-  Personally, I would prefer to just name it `color` in contrast to `color_mode`, because that's what other Unix programs already engraved into peoples heads  (but I'm not making the decision)
- Is both an equals sign and a space as separator between flag and value supported?
- The PR contains inconsistencies, sometimes the help message recommends `color='something'`, sometimes `color_mode='something'`

**Comment by sulyi** [comment]
>  name it `color` in contrast to `color_mode`

Tbc, `color_mode` is the names of the field in `params`, not the option. Option is named `--color` (or `--colour`, which is to be removed).
Since other fields in api that has cli equivalent are named the same as their option, this should be considered.

> Is both an equals sign and a space as separator between flag and value supported?

I'm not sure about `argparse`, but in `optparse` option value arguments are supported only with space between, afaik.

> The PR contains inconsistencies, sometimes the help message recommends `color='something'`, sometimes `color_mode='something'`

`color_mode='something'` is correct, but `color='something'` either needs to be `--color 'something'` or `color_mode='something'`. I'll look into it.

**Comment by UnlimitedCookies** [comment]
What's the status of this PR?

**Pull request closed without merging**
