### PR TITLE
Fix Pluto TV

### LINKED ISSUE #6639: PLUTO TV UPDATE?
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

SPAIN

### Provide a description that is worded well enough to be understood

Until no a lot ago i was downloading stuff from Pluto tv and the episode was downloaded perfect without ads.
Now every time i try this appear:
C:\Users\pc>C:\Users\pc\Downloads\Herramientas\VIDEOS\yt-dlp.exe https://pluto.tv/es/on-demand/series/teenage-mutant-ninja-turtles-es-ptv3/season/1/episode/el-ascenso-de-las-tortugas-parte-2-2011-1-102 -F
[PlutoTV] Extracting URL: https://pluto.tv/es/on-demand/series/teenage-mutant-ninja-turtles-es-ptv3/season/1/episode/el-asc...s-parte-2-2011-1-102
[PlutoTV] teenage-mutant-ninja-turtles-es-ptv3: Downloading JSON metadata
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 information
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 information
WARNING: [PlutoTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
WARNING: [PlutoTV] Unable to find ad-free formats
That warnings are new and i dont know if u can update it to bypass that or pluto tv its fucked now.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\pc>C:\Users\pc\Downloads\Herramientas\VIDEOS\yt-dlp.exe https://pluto.tv/es/on-demand/series/teenage-mutant-ninja-turtles-es-ptv3/season/1/episode/el-ascenso-de-las-tortugas-parte-2-2011-1-102 -F
[PlutoTV] Extracting URL: https://pluto.tv/es/on-demand/series/teenage-mutant-ninja-turtles-es-ptv3/season/1/episode/el-asc...s-parte-2-2011-1-102
[PlutoTV] teenage-mutant-ninja-turtles-es-ptv3: Downloading JSON metadata
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 information
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 information
WARNING: [PlutoTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
WARNING: [PlutoTV] Unable to find ad-free formats
```

### PR DESCRIPTION
**Pull request by joaquinito2070**
Fix 403 forbidden. See #6639.

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADD DESCRIPTION HERE

Fixes #6639 

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### Summary
🚫📺🚀

Improve Pluto TV extractor by filtering out ad segments from HLS and DASH playlists. This affects the file `yt_dlp/extractor/plutotv.py`.

> _`Pluto TV` extracts_
> _No more ad segments in `HLS`_
> _Winter stream is clear_

### Walkthrough
*  Filter out ad segments from HLS and DASH playlists by matching only specific URL prefixes ([link](https://github.com/yt-dlp/yt-dlp/pull/6679/files?diff=unified&w=0#diff-73930e95f920b842e4d951b4be62158257819351b2929b332eec8f01f9da0115L110-R110), [link](https://github.com/yt-dlp/yt-dlp/pull/6679/files?diff=unified&w=0#diff-73930e95f920b842e4d951b4be62158257819351b2929b332eec8f01f9da0115L117-R117)) in `yt_dlp/extractor/plutotv.py`

### CODE REVIEW

**Review by Lesmiscore — CHANGES_REQUESTED** [review]
:facepalm: I don't know about Pluto TV, but what to do with changing the domain **to change from?**

**Comment by joaquinito2070** [comment]
Please fix it, i don't know the code.

**Comment by bashonly** [comment]
@joaquinito2070 What was your intent with the change? The actual commit doesn't do anything useful, but if you can explain what you were trying to do, maybe that will get us somewhere

**Comment by gamer191** [comment]
@joaquinito2070 did you write that code?

**Comment by Ivoyko** [comment]
I am who said about that fail. I hope someone fix it. Thanks mates and good luck.

**Comment by heroku-miraheze** [comment]
Please with until i have ChatGPT Plus, and i Will fix the Code using AI.

**Comment by gamer191** [comment]
@heroku-miraheze are you and @joaquinito2070 the same person?
if yes, did you also write the initial code using chatgpt

**Pull request closed without merging**
