### PR TITLE
Add 'nyheter' and 'video-player/embed/' to the expressen regex

### PR DESCRIPTION
**Pull request by kylegustavo**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Add two more ways to represent video links to the expressen regex, nyheter and video-player

Fixes # https://github.com/yt-dlp/yt-dlp/issues/8141

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🆕🔗🎥

Update `expressen.py` extractor to handle more video URL formats. This allows the extractor to support more videos from the Expressen news website.

> _`video-?player`_
> _More ways to embed videos_
> _Autumn of changes_

### Walkthrough
* Update the regex for video URL extraction to handle more variations ([link](https://github.com/yt-dlp/yt-dlp/pull/8153/files?diff=unified&w=0#diff-3742a7379393063e080ff1520f21d58cb4c42b5833861f273f59358a9817c8d5L14-R15))

</details>

### CODE REVIEW

**Comment by bashonly** [comment]
Can you add tests for the new URL formats? You can use the URLs from the linked issue

**Comment by kylegustavo** [comment]
Ok, I added the new test cases and ran the test TestDownload.test_Expressen_all

**Review by bashonly — APPROVED** [review]

**Comment by kylegustavo** [comment]
Just checking, who will be in charge of merging this change?

**Comment by Grub4K** [comment]
I assume @bashonly will merge it soon

**Review by Grub4K — APPROVED** [review]

**Pull request merged**
