### PR TITLE
[Facebook] Fix tahoe request

### LINKED ISSUE #542: [Facebook] This video is only available for registered users
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.07.21**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
Downloading the video (works correctly):
```
[debug] Command-line config: ['-v', 'https://www.facebook.com/disguisedtoast/videos/333201981735004/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.07.21 (source)
[debug] Python version 3.7.11 (CPython 64bit) - Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004/
[facebook] 333201981735004: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: 333201981735004
[facebook] playlist 333201981735004: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 333201981735004: Downloading 1 format(s): hd
[debug] Invoking downloader on "https://scontent-ort2-2.xx.fbcdn.net/v/t66.36240-6/42652743_516468659568827_1724802297672679617_n.mp4?_nc_cat=109&ccb=1-3&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6MTAyNCwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=dUON7GG4L0oAX9ZhbhE&_nc_oc=AQmV6TGrIpTO-hDcQDoi0eRgkrpl_WnMh0lLSl2YHzl2iNAKnLY07HIWUnKhjOM74C4&rl=1500&vabr=259&_nc_ht=scontent-ort2-2.xx&oh=31e1df728d35eb0224b6f3db5fb66c26&oe=60FCD410"
[download] Destination: Facebook video #333201981735004 [333201981735004].mp4
[download] 100% of 3.86MiB in 00:16
[download] Finished downloading playlist: 333201981735004
```

Listing formats (does not work)
```
[debug] Command-line config: ['-v', '-F', 'https://www.facebook.com/disguisedtoast/videos/333201981735004/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.07.21 (source)
[debug] Python version 3.7.11 (CPython 64bit) - Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004/
[facebook] 333201981735004: Downloading webpage
ERROR: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1151, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1176, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/facebook.py", line 672, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/facebook.py", line 526, in _extract_from_url
    self.raise_login_required()
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 1042, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials

```

Retrieving JSON info (does not work):
```
[debug] Command-line config: ['-v', '-j', 'https://www.facebook.com/disguisedtoast/videos/333201981735004/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.07.21 (source)
[debug] Python version 3.7.11 (CPython 64bit) - Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004/
[facebook] 333201981735004: Downloading webpage
ERROR: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1151, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1176, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/facebook.py", line 672, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/facebook.py", line 526, in _extract_from_url
    self.raise_login_required()
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 1042, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials

```

## Description

**PLEASE NOTE:** I am aware that the error given clearly describes how to solve the problem (i.e., supplying a username and password), however, I am unfortunately unable to provide authentication for my use-case.

Somehow, yt-dlp (and youtube-dl) is able to download the video, but cannot supply any other information? Is this intended? I would assume that if the video can be downloaded, it should have enough information to return the JSON (or list formats).

> I've checked that all provided URLs are alive and playable in a browser

I have loaded the video (without being logged in - and in incognito mode) and it seems to be playable in the browser, however, the error raised implies that login information is required.

### PR DESCRIPTION
**Pull request by liamengland1**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Fix facebook API request ("tahoe") and bad patterns that erroneously called `raise_login_required` when there was any login form on the page. 

Should fix #542

### CODE REVIEW

**Comment by xenova** [comment]
Unfortunately the error persists:
```
[debug] Command-line config: ['-v', '-j', 'https://www.facebook.com/disguisedtoast/videos/333201981735004/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.07.21 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 2d231b0e0
[debug] Python version 3.7.11 (CPython 64bit) - Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004/
[facebook] 333201981735004: Downloading webpage
ERROR: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "/content/yt-dlp/yt_dlp/YoutubeDL.py", line 1152, in wrapper
    return func(self, *args, **kwargs)
  File "/content/yt-dlp/yt_dlp/YoutubeDL.py", line 1177, in __extract_info
    ie_result = ie.extract(url)
  File "/content/yt-dlp/yt_dlp/extractor/common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "/content/yt-dlp/yt_dlp/extractor/facebook.py", line 670, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/content/yt-dlp/yt_dlp/extractor/facebook.py", line 526, in _extract_from_url
    self.raise_login_required()
  File "/content/yt-dlp/yt_dlp/extractor/common.py", line 1042, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
```

(I am the author of the issue you mentioned)

**Comment by llacb47** [comment]
Thanks @xenova , I'll take another look later. Converted this PR to draft in the meantime.

**Comment by xenova** [comment]
> Thanks @xenova , I'll take another look later. Converted this PR to draft in the meantime.

Sweet! I'm also trying to figure it out on my end. Will post updates (if I have any)

**Comment by xenova** [comment]
These are the requests that are being made:
```
[DEBUG] https://www.facebook.com:443 "POST /video/tahoe/async/3629284013844544/?originalmediaid=3629284013844544&playerorigin=permalink&playersuborigin=tahoe&ispermalink=true&numcopyrightmatchedvideoplayedconsecutively=0&payloadtype=primary HTTP/1.1" 200 None
[DEBUG] https://www.facebook.com:443 "GET /video.php?v=3629284013844544 HTTP/1.1" 302 0
[DEBUG] https://www.facebook.com:443 "GET /login/?next=https%3A%2F%2Fwww.facebook.com%2Fvideo.php%3Fv%3D3629284013844544 HTTP/1.1" 200 None
```

As we can see, `/video.php?v=3629284013844544` returns a 302 redirection status. So, my guess is that the issue happens here instead of with `/video/tahoe/`?

**Comment by xenova** [comment]
https://github.com/yt-dlp/yt-dlp/issues/542#issuecomment-886241207

Mind taking a look at this? Thanks!

**Comment by llacb47** [comment]
Not a very resilient fix, closing.

**Pull request closed without merging**
