### PR TITLE
[extractor/prosiebensat1] fixed extraction (at least for videos)

### PR DESCRIPTION
**Pull request by Romern**
</details>

<details open><summary>I adjusted some of the regexes and removed the sim-technik API call, as the API does not seem to work with every video and is not needed anyway. Tested it with prosiebenmaxx and prosieben videos, e.g.:

https://www.prosiebenmaxx.de/anime/detektiv-conan/video/playlist-detektiv-conan

https://www.prosiebenmaxx.de/anime/detektiv-conan/videos/2448-die-detective-boys-auf-der-jagd-nach-dem-blauen-vogel-ganze-folge</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Review by bashonly — CHANGES_REQUESTED** [review]
> fixed extraction **(at least for videos)**

does this mean playlists are not working? do the tests pass?

**Comment by Romern** [comment]
Thank you for the feedback  @bashonly . I have checked the test videos too see if they are still working, and some additional videos. Most of the old test videos are not available anymore, so I've modified them a bit. What I have seen is, that the proMamsId is not up to date anymore and the ids associated with it wont return any data (with the _V4_BASE_URL API), and that the sites seem to use different credentials for the different sites. I added them for the test cases, so prosieben, prosiebenmaxx and voiceofgermany, but sat1 and sixx seem to work with the prosieben key, so I did not add them for now.

**Comment by Romern** [comment]
Playlists also work, but I only see them currently on prosiebenmaxx, as the other sites now have a similar model akin to streaming services, where no playlists are available anymore, but only seasons.

**Comment by bashonly** [comment]
The drastic changes made in 0f8cb1187be2b5c60ed2c1efb399be689d330029 to the BaseIE break the [puls4](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/puls4.py#L6) extractor and also introduce a new dependency on the dicts in the child class. I think a different approach will have to be taken.

**Comment by Grub4K** [comment]
I think it is fine to go this way, but I would split up the Extractor in smaller extractors, each having their own `_VALID_URL`, `_ACCESS_ID`, `_ENCRYPTION_KEY` and `_IV`. That would most likely be done by creating a new base extractor and subclassing that for each of the variants.

I can try to offer help with this as well.

How were these values extracted in the first place? Can they be generated somehow instead of hardcoded?

**Comment by Romern** [comment]
First, the config file for the website is retrieved, e.g.: 
https://config.player.p7s1.io/prosiebenmaxx-de.js
the `source-fetcher` contains the JWT credentials, which are XORed (webpack:///source-fetcher/src/decode-config.ts) with a secret, which is located in webpack:///source-fetcher/src/secret.ts.

**Comment by marieell** [comment]
The secret can be retrieved via the source map:
```
const map = JSON.parse(await get("https://oasis-player-prod.p7s1.io/web/15.5.1/bootstrap/bootstrap.js.map"))
return eval(map.sourcesContent[map.sources.indexOf("webpack:///../source-fetcher/src/secret.ts")].match(/(\[[^\]]+\]);/)[1])
```

**Comment by danielmarschall** [comment]
As of today (9 September 2023) this fix still works.

The only change I had to do to yt_dlp/extractor/prosiebensat1.py :

To `_CLIPID_REGEXES` add the following: `r'"video":\{"id":"([^"]+)"',`

It's a shame that this PR does not seem to be merged anytime soon :-(

**Comment by danielmarschall** [comment]
Update: After I downloaded the file, it turns out that the download actually didn't work.

The downloaded video file is just a black screen with the following text

Diese App wurde eingestellt.
Die Inhalte findest Du jetzt bei Joyn.
Bitte lade Dir die Joyn App im App-Store herunter.

(This app was discontinued. You will find the contents at Joyn.)

So the whole prosiebensat1 downloader seems to be obsolete??

**Comment by Romern** [comment]
I looked at the videos hosted at prosiebenmaxx and they seem to require an account now. This PR is obsolete now, so I will close it.

**Pull request closed without merging**
