### PR TITLE
[extractor/twitch] Update and add extractor-arg for `_CLIENT_ID`

### LINKED ISSUE #7058: [twitch] Cannot extract more than 100 VODs from a channel when providing cookies to yt-dlp
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

Scraping a Twitch channel's VODs only seems to yield up to 100 videos, even if the channel has more. I'm not sure how this would be fixed, but it does seem to yield more videos in browser, so it's possible an API endpoint isn't paginating properly or something.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--ignore-config', '--skip-download', 'https://www.twitch.tv/beyondthesummit/videos?filter=archives&sort=time', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-20-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.4.4 (fdk,setts), ffprobe 4.4.4
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2022.12.07, mutagen-1.45.1, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[TwitchVideos] Extracting URL: https://www.twitch.tv/beyondthesummit/videos?filter=archives&sort=time
[download] Downloading playlist: beyondthesummit - Past Broadcasts sorted by Date
[TwitchVideos] beyondthesummit: Downloading Videos GraphQL page 1
[TwitchVideos] beyondthesummit: Downloading Videos GraphQL page 2
[TwitchVideos] Playlist beyondthesummit - Past Broadcasts sorted by Date: Downloading 100 items of 100
[download] Downloading item 1 of 100
```

### LINKED ISSUE #7183: [twitch] ERROR: 'NoneType' object is not subscriptable
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

What I did:

Tried to download a Twitch stream like this:

```shell
yt-dlp 'https://twitch.tv/gamesdonequick'
```

What I expected to happen: It starts downloading

What happened instead:

```shell
ERROR: 'NoneType' object is not subscriptable
```

* I was successfully using `yt-dlp` with Twitch earlier today.
* The issue is not limited to my IP address AFAICT

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://twitch.tv/gamesdonequick']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.2.13-arch1-1-x86_64-with-glibc2.37 (OpenSSL 3.0.9 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotlicffi-1.0.9.2, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1842 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[twitch:stream] Extracting URL: https://twitch.tv/gamesdonequick
[twitch:stream] gamesdonequick: Downloading stream GraphQL
[twitch:stream] gamesdonequick: Downloading stream access token GraphQL
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1552, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1628, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 698, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/twitch.py", line 1025, in _real_extract
    token = access_token['value']
            ~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

### PR DESCRIPTION
**Pull request by bashonly**
Updates the `_CLIENT_ID` value to fix livestream extraction

Credit to [aeongdesu](https://github.com/aeongdesu) for [finding the ID value](https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/issues/94#issuecomment-1360683876) and to @Gregaras for sharing the info in our issue tracker

Also adds an extractor-arg to set the client ID, as I suspect the updated ID may not work for very long. Usage:
```
yt-dlp --extractor-arg "twitchstream:client_id=kimne78kx3ncx6brgo4mv6wki5h1ko" "URL"
```

Closes #7183, #7058
(for now)

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🛠️🔧🔄

Improved TwitchStreamIE extractor by using configurable Twitch API client ID instead of hard-coded value. Modified `yt_dlp/extractor/twitch.py` to implement this change.

> _Oh we're the crew of the TwitchStreamIE_
> _And we work with the code and the API_
> _We don't want no hard-coded client ID_
> _So we fetch it from the config or the fallback list_

### Walkthrough
* Remove hard-coded client ID for Twitch API and make it a property that can be dynamically obtained from configuration arguments ([link](https://github.com/yt-dlp/yt-dlp/pull/7200/files?diff=unified&w=0#diff-2804898417af0aad967097ad6fd96e53abe8cfb292fb4ab2928f5752b2e7eda0L44), [link](https://github.com/yt-dlp/yt-dlp/pull/7200/files?diff=unified&w=0#diff-2804898417af0aad967097ad6fd96e53abe8cfb292fb4ab2928f5752b2e7eda0R60-R64) in `yt_dlp/extractor/twitch.py`)

</details>

### CODE REVIEW

**Comment by pukkandan** [comment]
If there is no urgency anymore, I'd prefer we look into extracting the id instead of adding extractor-arg.

**Comment by pukkandan** [comment]
If merging this, make sure to document it in readme.

**Comment by gamer191** [comment]
> If there is no urgency anymore, I'd prefer we look into extracting the id instead of adding extractor-arg.

That would probably be difficult, given Twitch apparently blocks Firefox if `privacy.resistFingerprinting` is enabled https://github.com/yt-dlp/yt-dlp/issues/7183#issuecomment-1571077035. Then again, perhaps that's why they reverted the changes (I haven't tested using twitch with resist fingerprinting)

**Comment by bashonly** [comment]
> If merging this, make sure to document it in readme.

Thanks for the reminder, totally slipped my mind

> If there is no urgency anymore, I'd prefer we look into extracting the id instead of adding extractor-arg.

If I understand correctly, the `_CLIENT_ID` is hardcoded per client, e.g. `kimne78kx3ncx6brgo4mv6wki5h1ko` is the web/JS client ID, `ue6666qo983tsx6so1t0vnawi233wa` is the Nintendo Switch client ID, etc. So we would only be able to extract the old `kimne78kx3ncx6brgo4mv6wki5h1ko` ID from the webpage/JS anyways.

A more stable solution going forward would be figuring out how to extract the client integrity params, which are needed when Twitch restricts the client ID, but it's looking more and more like headless Chrome is necessary for that.

I do think this is worth merging, because while the web client ID is no longer restricted for livestreams, the Nintendo Switch client ID is *completely* unrestricted, so using it instead also fixes #7058 (which is still broken with the old ID)

**Pull request merged**
