### PR TITLE
[ie/afreecatv] Fix extractor

### LINKED ISSUE #4592: When downloading a VOD from afreecaTV, the upload_date would be changed to NA at the Concat
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The filename should start with the upload date, but ends up being NA. The upload date is correct right before the Concat.

URL used for testing: https://vod.afreecatv.com/player/90100147

As a side note, the folder I used is called youtube-dl, but the .exe inside is yt-dlp (just in case anyone had it confused)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-N', '10', 'https://vod.afreecatv.com/player/90100147', '-o', '%(upload_date)s-%(uploader)s-%(title)s.%(ext)s']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [afreecatv] Extracting URL: https://vod.afreecatv.com/player/90100147
[afreecatv] 90100147: Downloading webpage
[afreecatv] 90100147: Downloading video info XML
[afreecatv] 90100147: Downloading part 1 m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading multi_video: 다들 너무 감사합니다 ^_^* 고생하셨어요 ♥ 오늘 춤 영상 따지마세요! 
[afreecatv] Playlist 다들 너무 감사합니다 ^_^* 고생하셨어요 ♥ 오늘 춤 영상 따지마세요! : Downloading 1 videos of 1
[debug] The information of all playlist entries will be held in memory
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 20220723_4D451E93_241780835_33: Downloading 1 format(s): hls-original
[debug] Invoking hlsnative downloader on "http://vod-archive-global-cdn-z02.afreecatv.com/v101/hls/vod/20220723/835/241780835/REGL_4D451E93_241780835_33.smil/original/both/playlist.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 9
[download] Destination: 20220723-크레용팝엘린-다들 너무 감사합니다 ^_^_ 고생하셨어요 ♥ 오늘 춤 영상 따지마세요! .mp4
[debug] File locking is not supported. Proceeding without locking
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download] 100% of 24.50MiB in 00:01
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:20220723-크레용팝엘린-다들 너무 감사합니다 ^_^_ 고생하셨어요 ♥ 오늘 춤 영상 따지마세요! .mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "20220723-크레용팝엘린-다들 너무 감사합니다 ^_^_ 고생하셨어요 ♥ 오늘 춤 영상 따지마세요! .mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:20220723-크레용팝엘린-다들 너무 감사합니다 ^_^_ 고생하셨어요 ♥ 오늘 춤 영상 따지마세요! .mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:20220723-크레용팝엘린-다들 너무 감사합니다 ^_^_ 고생하셨어요 ♥ 오늘 춤 영상 따지마세요! .temp.mp4"
[Concat] Moving "K:\youtube-dl\20220723-크레용팝엘린-다들 너무 감사합니다 ^_^_ 고생하셨어요 ♥ 오늘 춤 영상 따지마세요! .mp4" to "NA-크레용팝엘린-다들 너무 감사합니다 ^_^_ 고생하셨어요 ♥ 오늘 춤 영상 따지마세요! .mp4"
[download] Finished downloading playlist: 다들 너무 감사합니다 ^_^* 고생하셨어요 ♥ 오늘 춤 영상 따지마세요!
```

### LINKED ISSUE #8862: No upload date for AfreecaTV videos
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China, Canada

### Provide a description that is worded well enough to be understood

I write "-o "%(upload_date)s %(title)s [%(id)s].%(ext)s"" in config file. 
It fails to get the upload date for AfreecaTV videos whose file names turn out to start with "NA", like "NA 중국 청두 허싱 ❤️ 리액션 공부 or 포즈 [110720091].mp4"
I don't see the "upload_date" in the JSON file. Is it the site problem or the lack of support for the site?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vod.afreecatv.com/player/110720091']
[debug] Home config "yt-dlp.conf": ['-f', 'bv*[protocol!*=dash]+ba/b', '-o', '/home/lochips/videos/bj/%(upload_date)s %(title)s [%(id)s].%(ext)s', '--write-thumbnail', '--convert-thumbnails', 'jpg', '--cookies', 'cookies.txt', '--write-sub', '--sub-langs', 'en,zh-Hans,ja', '--hls-prefer-native', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-167-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-2.3.1, sqlite3-3.31.1, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[afreecatv] Logging in
[afreecatv] Extracting URL: https://vod.afreecatv.com/player/110720091
[afreecatv] 110720091: Downloading JSON metadata
[afreecatv] 110720091: Downloading video info XML
[afreecatv] 110720091: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 110720091: Downloading 1 format(s): hls-original
[info] There are no subtitles for the requested languages
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: /home/lochips/videos/bj/NA 중국 청두 허싱 ❤️ 리액션 공부 or 포즈 [110720091].php
[ThumbnailsConvertor] Converting thumbnail "/home/lochips/videos/bj/NA 중국 청두 허싱 ❤️ 리액션 공부 or 포즈 [110720091].php" to jpg
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:/home/lochips/videos/bj/NA 중국 청두 허싱 ❤️ 리액션 공부 or 포즈 [110720091].php' -update 1 -bsf:v mjpeg2jpeg -movflags +faststart 'file:/home/lochips/videos/bj/NA 중국 청두 허싱 ❤️ 리액션 공부 or 포즈 [110720091].jpg'
Deleting original file /home/lochips/videos/bj/NA 중국 청두 허싱 ❤️ 리액션 공부 or 포즈 [110720091].php (pass -k to keep)
[debug] Invoking hlsnative downloader on "http://vod-normal-global-cdn-z02.afreecatv.com/v101/hls/clip/20231213/709/0418c498-45fc-43c3-a1a5-2c87d7670870/16384709.smil/original/both/playlist.m3u8"
[download] /home/lochips/videos/bj/NA 중국 청두 허싱 ❤️ 리액션 공부 or 포즈 [110720091].mp4 has already been downloaded
[download] 100% of   50.17MiB
```

### LINKED ISSUE #9544: Afreecatv Failed to parse XML
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

The afreecatv website has just stopped working since six hours ago. There is the prompt:

yt-dlp https://vod.afreecatv.com/player/117026071
[afreecatv] Extracting URL: https://vod.afreecatv.com/player/117026071
[afreecatv] 117026071: Downloading JSON metadata
Extracting cookies from firefox
Extracted 1509 cookies from firefox
[afreecatv] 117026071: Downloading video info XML
ERROR: [afreecatv] 117026071: 117026071: Failed to parse XML (caused by ParseError('no element found: line 1, column 0')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vod.afreecatv.com/player/117026071']
[debug] Portable config "C:\Users\syazyz\scoop\apps\yt-dlp\current\yt-dlp.conf": []
[debug] Home config "yt-dlp.conf": ['--proxy', 'socks5://127.0.0.1:7888', '--merge-output-format', 'mkv', '--continue', '-o', '%(uploader)s\\%(upload_date)s - %(title)s.%(ext)s', '--no-check-certificate', '--prefer-insecure', '--user-agent', 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)', '--concurrent-fragments', '3', '--cookies-from-browser', 'firefox:C:/GreenSoft/System/Profiles/FFP', '--downloader-args', 'ffmpeg_i:-hwaccel cuda -c:v vp9_cuvid']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.03.22.222728 from yt-dlp/yt-dlp-master-builds [e5d4f1110] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-03-20-git-e04c638f5f-full_build-www.gyan.dev (setts), ffprobe 2024-03-20-git-e04c638f5f-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {'all': 'socks5://127.0.0.1:7888'}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\GreenSoft\System\Profiles\FFP\cookies.sqlite"
Extracted 1514 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1807 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.03.22.222728 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.03.22.222728 from yt-dlp/yt-dlp-master-builds)
[afreecatv] Extracting URL: https://vod.afreecatv.com/player/117026071
[afreecatv] 117026071: Downloading JSON metadata
[afreecatv] 117026071: Downloading video info XML
ERROR: [afreecatv] 117026071: 117026071: Failed to parse XML (caused by ParseError('no element found: line 1, column 0')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\afreecatv.py", line 202, in _real_extract
  File "yt_dlp\extractor\common.py", line 1086, in download_content
  File "yt_dlp\extractor\common.py", line 1056, in download_handle
  File "yt_dlp\extractor\common.py", line 1046, in parse
  File "yt_dlp\extractor\common.py", line 1026, in _parse_xml
  File "yt_dlp\extractor\common.py", line 1016, in __print_error

  File "yt_dlp\extractor\common.py", line 1024, in _parse_xml
  File "yt_dlp\compat\__init__.py", line 24, in compat_etree_fromstring
  File "xml\etree\ElementTree.py", line 1321, in XML
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

### PR DESCRIPTION
**Pull request by Tomoka1**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

As in a somewhat reversal of #6283 this uses fully JSON again as some necessary information are not provided in XML any more.
This code will **not** keep XML part for backward compatibility. 
The code is tested with login and without, on adult and regular.

Closes #4592, Closes #8862, Closes #9544 

<details open>
<summary>Template</summary>

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by zyz-1998** [comment]
still is problem : ERROR: [afreecatv] 109615861: 109615861: Failed to parse XML (caused by ParseError

**Comment by Tomoka1** [comment]
> still is problem : ERROR: [afreecatv] 109615861: 109615861: Failed to parse XML (caused by ParseError

Are you sure you used the suggested changes? There shouldn't be anything to parse XML left. 
Your example 109615861 works fine for me.

**Comment by zyz-1998** [comment]
I deployed yt_dlp using
C:\Users\ZYZ\.conda\envs\python3.8\python.exe -m pip install --force-reinstall "yt-dlp[default] @ https://github.com/yt-dlp/yt- dlp/archive/master.tar.gz"

Is it because the latest package was not downloaded? Thank you.

**Comment by HobbyistDev** [comment]
> I deployed yt_dlp using
> C:\Users\ZYZ.conda\envs\python3.8\python.exe -m pip install --force-reinstall "yt-dlp[default] @ https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz"

Is it because the latest package was not downloaded? Thank you.
I think you should get yt-dlp from Tomoka1's branch first (because it's not in main branch yet)

---
While the aim of the PR is not to extract XML file, i think it nice if we could extract the `upload_date` (and perhaps other key) like #8862

**Comment by zyz-1998** [comment]
What should be done, thank you

**Comment by zyz-1998** [comment]
new probelm ERROR: [afreecatv] 109615861: 109615861: HTTP Error 502: Bad Gateway (caused by <HTTPError 502: Bad Gateway>)

**Comment by Tomoka1** [comment]
> While the aim of the PR is not to extract XML file, i think it nice if we could extract the `upload_date` (and perhaps other key) like #8862

I am not sure what you're referring to. 
`upload_date` is retrieved from `file_info_key` as it was done before in similar fashion. 
Using `write_tm` or `broad_start` wouldn't be an issue, if that's preferred.

```sh
[~]$ python -m yt_dlp https://vod.afreecatv.com/player/109615861 --print "%(upload_date)s %(title)s" 
20231116 [클립]생)사랑스런 민영이 오늘은 시스루~ 검스 ㅎ ㅏㅏㅏ ㅀ
```

> new probelm ERROR: [afreecatv] 109615861: 109615861: HTTP Error 502: Bad Gateway (caused by <HTTPError 502: Bad Gateway>)
Not replicable on my side. I assume you're sitting in some geolocked region.
Try `curl https://api.m.afreecatv.com/station/video/a/view` and if it's negative please open another issue.

**Comment by zyz-1998** [comment]
#  C:\Users\ZYZ\.conda\envs\python3.8\python.exe -m  pip install --force-reinstall "yt-dlp[default] @ https://github.com/Tomoka1/yt-dlp/archive/afreecatv-from_xml_to_json.tar.gz"
# python -m yt_dlp https://vod.afreecatv.com/player/109615861 --print "%(upload_date)s %(title)s" 
ERROR: [afreecatv] 109615861: 109615861: Failed to parse XML (caused by ParseError('no element found: line 1, column 0')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Review by bashonly — CHANGES_REQUESTED** [review]
Partial review

We don't need the `for _ in range(2):` loop at all anymore, right? IIRC it was used to re-fetch adult content by updating the query for the XML request. But we don't do that anymore.

Can you also update the tests and add an adult content test, since the current one is dead?

**Comment by bashonly** [comment]
I removed all the dead code and simplified/modernized what was left. Please test my changes and let me know what you think.

My previous review is no longer applicable except for this part:

> Can you also update the tests and add an adult content test, since the current one is dead?

**Comment by Tomoka1** [comment]
@bashonly Oh, i just wrote up-to-date tests myself before seeing the merge. Sorry i didn't have too much time this week. Thanks for your hard work!

**Pull request merged**
