### PR TITLE
catch BlockingIOError and report why ID was skipped

### PR DESCRIPTION
**Pull request by jakeogh**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

With the addition of advisory locking in #1066 this change is necessary to gracefully download the next video when a yt-dlp process hits an advisory lock `BlockingIOError`. Without this patch, when two yt-dlp processes are launched with either the same playlist or different playlists that happen to have at least one same ID, if one of the yt-dlp processes encounters a `BlockingIOError` the process exits. With this patch, the process that would have exited instead continues on to the next video, and the first process (this is also the case without this patch) finishes it's current ID download and produces the expected merged output file.

Videos with fragments also work as expected.

Implementation note: It is important that the yt-dlp process that encountered the `BlockingIOError` move on to the next video, rather than attempt to download the "next unlocked" part of the ID (such as the audio track) because that situation results in a corner case where the first yt-dlp process also hits a `BlockingIOError` when it finishes the part it was downloading and attempts to download the (perhaps still advisory locked) audio track. This corner case results in both processes not producing a merged output file. This corner case does not exist with or without this patch.

### CODE REVIEW

**Comment by pukkandan** [comment]
> Without this patch, when two yt-dlp processes are launched with either the same playlist or different playlists that happen to have at least one same ID, if one of the yt-dlp processes encounters a BlockingIOError the process exits. With this patch, the process that would have exited instead continues on to the next video, and the first process (this is also the case without this patch) finishes it's current ID download and produces the expected merged output file.

No, the current behavior is correct

```shell
❯ yt-dlp test:youtube test:reddit --force-over -v
[debug] Command-line config: ['test:youtube', 'test:reddit', '--force-over', '-v']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, err utf-8, pref cp65001
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: b6cff15b9
[debug] Python version 3.10.2 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg N-105465-gbedb4bac1c-20220206 (setts,fdk), ffprobe N-105465-gbedb4bac1c-20220206, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [TestURL] Extracting URL: test:youtube
[TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BaW_jenozKc: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr3---sn-gwpa-jjwe.googlevideo.com/videoplayback?expire=1646335831&ei=98IgYvTjAu-K1d8PrZmRwAE&ip=2405%3A201%3Af003%3Abaf6%3Ac89%3Aa1d9%3Aa2b1%3Afb83&id=o-ACROHmqF17I4yGXVPWDFd2cBqu4bss67pnM_GznoDIiY&itag=248&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-gwpa-jjwe%2Csn-gwpa-h55z&ms=au%2Crdu&mv=m&mvi=3&pl=48&initcwndbps=312500&vprv=1&mime=video%2Fwebm&gir=yes&clen=988479&dur=9.833&lmt=1544741703689523&mt=1646312703&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgJwJd1qBnWT63WyixftXGHSWrpR8yAkN-GD8cpuOmNOwCIQDqpUqwqcwBqyMDfPD-edYdyXkBPhuu8wOWPxGmY9MAQg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOtSA5DWjCp1Tp3JkbZYh4bdL1amykR0UNb_N40rQiAgAiBQ0-chDTNyHt22Aj79cpUVRV0MzgGVZUVlAiIW0qkqAg%3D%3D"
ERROR: unable to open for writing: Locking file failed: 'The process cannot access the file because another process has locked a portion of the file.'
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\downloader\http.py", line 277, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\downloader\common.py", line 218, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\utils.py", line 671, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).open()
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\utils.py", line 2212, in open
    return self.__enter__()
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\utils.py", line 2187, in __enter__
    _lock_file(self.f, exclusive, self.block)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\utils.py", line 2135, in _lock_file
    raise BlockingIOError('Locking file failed: %r' % ctypes.FormatError())
BlockingIOError: Locking file failed: 'The process cannot access the file because another process has locked a portion of the file.'


[debug] Invoking downloader on "https://rr3---sn-gwpa-jjwe.googlevideo.com/videoplayback?expire=1646335831&ei=98IgYvTjAu-K1d8PrZmRwAE&ip=2405%3A201%3Af003%3Abaf6%3Ac89%3Aa1d9%3Aa2b1%3Afb83&id=o-ACROHmqF17I4yGXVPWDFd2cBqu4bss67pnM_GznoDIiY&itag=251&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-gwpa-jjwe%2Csn-gwpa-h55z&ms=au%2Crdu&mv=m&mvi=3&pl=48&initcwndbps=312500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=142292&dur=9.841&lmt=1506055557712479&mt=1646312703&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJ5stFXtkm0VKNhPBNsvK1qA68nkO54xAJXeOP7w-Ft7AiBLKNA9XqvypprAuYhgD_3PXmcLg7DHTWooJPTT3fwRbA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOtSA5DWjCp1Tp3JkbZYh4bdL1amykR0UNb_N40rQiAgAiBQ0-chDTNyHt22Aj79cpUVRV0MzgGVZUVlAiIW0qkqAg%3D%3D"
[download] Destination: youtube-dl test video ''_ä↭𝕐  [BaW_jenozKc].f251.webm
[download] 100% of 138.96KiB in 00:00
[debug] [TestURL] Extracting URL: test:reddit
[TestURL] Test URL: https://www.reddit.com/r/videos/comments/6rrwyj/that_small_heart_attack/
[debug] [Reddit] Extracting URL: https://www.reddit.com/r/videos/comments/6rrwyj/that_small_heart_attack/
[Reddit] 6rrwyj: Downloading JSON metadata
[Reddit] 6rrwyj: Downloading m3u8 information
[Reddit] 6rrwyj: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] zv89llsvexdz: Downloading 1 format(s): hls-1875+dash-AUDIO-1
Deleting existing file That small heart attack. [zv89llsvexdz].mp4
[debug] Invoking downloader on "https://v.redd.it/zv89llsvexdz/HLS_1_5_M_v4.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 5
[download] Destination: That small heart attack. [zv89llsvexdz].fhls-1875.mp4
[download] 100% of 2.23MiB in 00:00
[debug] Invoking downloader on "https://v.redd.it/zv89llsvexdz/audio"
[download] Destination: That small heart attack. [zv89llsvexdz].fdash-AUDIO-1.m4a
[download] 100% of 189.47KiB in 00:00
[Merger] Merging formats into "That small heart attack. [zv89llsvexdz].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:That small heart attack. [zv89llsvexdz].fhls-1875.mp4" -i "file:That small heart attack. [zv89llsvexdz].fdash-AUDIO-1.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:That small heart attack. [zv89llsvexdz].temp.mp4"
Deleting original file That small heart attack. [zv89llsvexdz].fhls-1875.mp4 (pass -k to keep)
Deleting original file That small heart attack. [zv89llsvexdz].fdash-AUDIO-1.m4a (pass -k to keep)
```

> Implementation note: It is important that the yt-dlp process that encountered the BlockingIOError move on to the next video, rather than attempt to download the "next unlocked" part of the ID (such as the audio track)

https://github.com/yt-dlp/yt-dlp/pull/1066#issuecomment-1019456386

> because that situation results in a corner case where the first yt-dlp process also hits a BlockingIOError when it finishes the part it was downloading and attempts to download the (perhaps still advisory locked) audio track. This corner case results in both processes not producing a merged output file. This corner case does not exist with or without this patch.

https://github.com/yt-dlp/yt-dlp/pull/1066#issuecomment-925655474

As I said before, the intention of merging #1066 was not to encourage running multiple yt-dlp instances. Instead, locking ensures that yt-dlp "plays nice" with any other program that may be locking the file. 

Do not assume that the file is being locked by another yt-dlp process. If a lock cannot be acquired, yt-dlp should move on to the next file and assume the file for which the lock wasn't acquired failed to download. ie, PPs should fail and the download should exit with an error code.

If you have any idea for implementing some way to verify that the file was in fact downloaded (instead of assuming lock means it's being downloaded by another yt-dlp instance), then we can consider gracefully exiting/running PPs

**Comment by jakeogh** [comment]
Thanks for all your work on this. I have attempted to be as precise as possible in my reply.
 
I am not suggesting acquiring an advisory lock on any file handle not being currently written to. I only mentioned it once in #1066 as an option, but we didn't do that, and this PR does not do that.

My intention of employing advisory locking is to prevent a race condition which causes data corruption (fixed by #1066) that has existed since the beginning of youtube-dl. I first attempted to get it fixed upstream in https://github.com/ytdl-org/youtube-dl/pull/18690 (earlier mentions of the issue can be fount at the top of the 2018 PR).

Running multiple yt-dlp processes is a common¹ use case, a user may run yt-dlp to download playlist A for example, and then perhaps some time later, while playlist A is downloading, decide to launch yt-dlp to download playlist B.

If playlist A and B contain at least one same ID, it's possible that one yt-dlp processes will encounter that ID while the other process is already writing to the video or audio file. Before #1066 was merged, this situation would result in the silent² corruption of the video and/or audio file and therefore corruption of the final merged output file.

Without this current PR, a user encountering the common use case above, will have one process `exit 1` and not³ complete downloading the playlist. I don't see any reason to exclude yt-dlp from the list of processes that yt-dlp should play nice with.

With this PR, both playlist A and B download completely, independent of the number of ID's that the playlists share. Importantly, as far as I know, this has no corner cases.

My implementation note above is not specifically related to this PR, but I felt it was important to include it because I am eager to prevent the corner case race condition which it outlines from appearing in a future commit. This race condition does not exist with or without the current PR. 

To encounter this race (which can result in no merged output file), the current behavior would need to be changed from:
`NoRace: process encountering the BlockingIOError exits 1 without attempting any more operations for the ID in question`
to:
`Race: process encountering the BlockingIOError attempts to download the next resource (usually the the audio track) for the ID in question`

What this PR does is change the current NoRace condition to process the next ID if there is one instead of exiting 1. I can not think of any situation where this does not result in a better outcome than the current NoRace condition. User's cant know ahead of time if playlist A and B share an ID.

In the special case where the process encountering the BlockingIOError has no additional ID's to process, this PR could be modified to exit 1, but that would introduce an inconsistency, where the exit behavior is dependent on playlist order.

¹: A similar use case is downloading two different search url's.
²: In some cases ffmpeg errors out on the merge, but the result is (almost) just as bad, leaving 2 unmerged files with data corruption in one or both.
³: Technically, there is a "good" corner case right now, where both A and B download completely, but that is only when the process encountering BlockingIOError happens to be on it's last ID.

**Comment by pukkandan** [comment]
Along with replying to your post, I did address my actual issue with your PR. For clarification, here is the part that is directly relevant:

> No, the current behavior is correct
> [log demonstrating current/expected behavior]

> Do not assume that the file is being locked by another yt-dlp process. If a lock cannot be acquired, yt-dlp should move on to the next file and assume the file for which the lock wasn't acquired failed to download. ie, PPs should fail and the download should exit with an error code.

---

> Without this current PR, a user encountering the common use case above, will have one process exit 1 and not³ complete downloading the playlist.

It does complete the playlist, as shown with log in my earlier comment. The only difference is that (without the PR) it exits with an error code **which is the expected behavior** since yt-dlp has no way of confirming the locked video was in fact downloaded. As far as that yt-dlp instance is concerned, a video failed to download and this is reflected in the error code.

**Comment by jakeogh** [comment]
Your earlier comment isn't covering the case I outlined. A and B are different playlists. One of them is not downloaded completely.

**Comment by pukkandan** [comment]
Maybe I am misunderstanding, but I believe it is covered. Please show example logs to the contrary.

PS: You can add a breakpoint right after file locking (or just add an `input('locked...')`) to reliable reproduce blocking behavior

**Comment by pukkandan** [comment]
@jakeogh

**Comment by jakeogh** [comment]
@pukkandan this discussion would be easier if #2994 lands first, but is independent from it, #2994 is critical, I discovered it checking my assumptions while reviewing this bug. Sorry about the lag, was traveling.

**Comment by pukkandan** [comment]
> Maybe I am misunderstanding, but I believe it is covered. Please show example logs to the contrary.

Can be re-opened if this is answered and we find this PR is necessary

**Pull request closed without merging**
