### PR TITLE
[Hanimetv] Add extractor

### PR DESCRIPTION
**Pull request by Quist0n**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This pull request adds support for the website hanime.tv. This extractor supports downloading single videos as well as playlists.

### CODE REVIEW

**Comment by pukkandan** [comment]
We dont support illegal sites

**Comment by Quist0n** [comment]
> We dont support illegal sites

Hanime.tv isn't an illegal site though. Can you tell me what about it is illegal ?

**Comment by pukkandan** [comment]
They do not have license to distribute many of the shows they do

**Comment by pukkandan** [comment]
[Their TOS](https://hanime.tv/terms-of-use) does claim to respond to copyright claims
> Claims of Copyright Infringement. If you believe your work has been reproduced or distributed in a way that constitutes a copyright infringement or are aware of any infringing material available through the hanime.tv service, please notify us by completing the Copyright Infringement Claims Form.

However, the [link provided](https://docs.google.com/forms/d/1tzF8ny2x3PJzpozG96M4nBxDx58ymiekc3X3oftsQKI) is invalid

Also, the first entry in their home page currently is [Interspecies Reviewers](https://en.wikipedia.org/wiki/Interspecies_Reviewers#Anime), which they do not appear to have license for. So any claims of being a legal streaming site is unconvincing.

**Comment by Quist0n** [comment]
> [Their TOS](https://hanime.tv/terms-of-use) does claim to respond to copyright claims
> 
> > Claims of Copyright Infringement. If you believe your work has been reproduced or distributed in a way that constitutes a copyright infringement or are aware of any infringing material available through the hanime.tv service, please notify us by completing the Copyright Infringement Claims Form.
> 
> However, the [link provided](https://docs.google.com/forms/d/1tzF8ny2x3PJzpozG96M4nBxDx58ymiekc3X3oftsQKI) is invalid
> 
> Also, the first entry in their home page currently is [Interspecies Reviewers](https://en.wikipedia.org/wiki/Interspecies_Reviewers#Anime), which they do not appear to have license for. So any claims of being a legal streaming site is unconvincing.

Ah, I see. I thought they had the rights based on when certain things would be released and just the general flow of the site. More organized, no dupes, that kind of thing. It seems I was mistaken, sorry about that.

**Pull request closed without merging**
