### PR TITLE
[crunchyroll:beta] extract timestamp

### LINKED ISSUE #4533: CrunchyRoll Beta does not appears to pay attention to  --dateafter "today- and possibly --playlist-reverse
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I have recently had my account forced to use CrunchyRoll Beta and my current scripts have stopped working

I have slowly being trying to diagnose parts of it and slowly re-building the query so it works like it previously did

I have noticed a few commands that do not seem to function as expected when using the -a to pull back some playlists and process them.

It also appears that I can no longer filter on the languages like I did with --extractor-args "crunchyroll:[language=enUS,en-US]" 
 it may be possibly doing the playlist in reverse but is pulling back a language I do not need. 

Does anyone have any have a way I can filter to only ja-JP and en-US as a workaround for now? It does appear now if I use the --no-overwrites it skips the file if already downloaded if the date can not be filtered at this time. I assume this may be the fact its not being exposed from the beta URLs

The good news is it does appear to have fixed some of my naming issues with the seasons coming through as 0 if it's a first season. 

Any help would be much apricated. If I point this at a direct URL for an episode it Downloads as I expect 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
.\yt-dlp --embed-subs --write-subs --sub-lang en,en_Uncut,en_Uncut_CC,en-US,enUS --parse-metadata "%(series)s - %(title)s S%(season_number)02dE%(episode_number)02d:%(title)s"  -o "%(series)s/Season %(season_number)02d/S%(season_number)02dEP%(episode_number)02d-%(language)s - %(series)s- %(episode)s.%(ext)s" -v --extractor-args "crunchyrollbeta:language=enUS,jaJP" --cookies .\crunchyroll.com_cookies.txt --trim-filenames 110 --dateafter "today-19day" --playlist-reverse --no-overwrites -a .\series.txt
[debug] Command-line config: ['--embed-subs', '--write-subs', '--sub-lang', 'en,en_Uncut,en_Uncut_CC,en-US,enUS', '--parse-metadata', '%(series)s - %(title)s S%(season_number)02dE%(episode_number)02d:%(title)s', '-o', '%(series)s/Season %(season_number)02d/S%(season_number)02dEP%(episode_number)02d-%(language)s - %(series)s- %(episode)s.%(ext)s', '-v', '--extractor-args', 'crunchyrollbeta:language=enUS,jaJP', '--cookies', '.\\crunchyroll.com_cookies.txt', '--trim-filenames', '110', '--dateafter', 'today-19day', '--playlist-reverse', '--no-overwrites', '-a', '.\\series.txt']
[debug] Batch file urls: ['https://www.crunchyroll.com/shikimoris-not-just-a-cutie', 'https://www.crunchyroll.com/rent-a-girlfriend', 'https://www.crunchyroll.com/kaguya-sama-love-is-war']
'\\MyServer\'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0-essentials_build-www.gyan.dev (setts), ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [crunchyroll:playlist] Extracting URL: https://www.crunchyroll.com/shikimoris-not-just-a-cutie
[crunchyroll:playlist] shikimoris-not-just-a-cutie: Downloading webpage
[crunchyroll:playlist] shikimoris-not-just-a-cutie: Redirected to beta site - https://beta.crunchyroll.com/series/GNVHKN7M4/shikimoris-not-just-a-cutie
[debug] [crunchyroll:playlist:beta] Extracting URL: https://beta.crunchyroll.com/series/GNVHKN7M4/shikimoris-not-just-a-cutie
[crunchyroll:playlist:beta] Retrieving main page
[crunchyroll:playlist:beta] Authenticating with cookie
[crunchyroll:playlist:beta] Retrieving signed policy
[crunchyroll:playlist:beta] shikimoris-not-just-a-cutie: Retrieving series metadata
[crunchyroll:playlist:beta] shikimoris-not-just-a-cutie: Retrieving season list
[download] Downloading playlist: Shikimori's Not Just a Cutie
[crunchyroll:playlist:beta] shikimoris-not-just-a-cutie: Retrieving episode list for shikimoris-not-just-a-cutie
[crunchyroll:playlist:beta] shikimoris-not-just-a-cutie: Retrieving episode list for shikimoris-not-just-a-cutie-german-dub
[crunchyroll:playlist:beta] shikimoris-not-just-a-cutie: Retrieving episode list for shikimoris-not-just-a-cutie-english-dub
[crunchyroll:playlist:beta] shikimoris-not-just-a-cutie: Retrieving episode list for shikimoris-not-just-a-cutie-portuguese-dub
[crunchyroll:playlist:beta] shikimoris-not-just-a-cutie: Retrieving episode list for shikimoris-not-just-a-cutie-spanish-dub
[crunchyroll:playlist:beta] shikimoris-not-just-a-cutie: Retrieving episode list for shikimoris-not-just-a-cutie-russian-dub
[crunchyroll:playlist:beta] Playlist Shikimori's Not Just a Cutie: Downloading 74 videos of 74
[download] Downloading video 1 of 74
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/G14U403J2/better-than-a-dream
[crunchyroll:beta] better-than-a-dream: Retrieving episode metadata
[crunchyroll:beta] better-than-a-dream: Retrieving stream info
[crunchyroll:beta] better-than-a-dream: Downloading adaptive_hls information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Searching for '(?P<title>.+)' in '%(series)s - %(title)s S%(season_number)02dE%(episode_number)02d'
[MetadataParser] Parsed title from '%(series)s - %(title)s S%(season_number)02dE%(episode_number)02d': "Shikimori's Not Just a Cutie - Shikimori's Not Just a Cutie (Russian Dub) Episode 12 – Better Than a Dream S01E12"
[debug] Default format spec: bestvideo*+bestaudio/best
[info] G14U403J2: Downloading 1 format(s): adaptive_hls-8126
[debug] Invoking hlsnative downloader on "https://pl.crunchyroll.com/evs3/daaae10e5f6c9a639e7bb5ac81b39b32/assets/5258d7d633679f220a4bbcfb860c4b8b_4606448.mp4/index-v1-a1.m3u8?Expires=1659621801&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy9kYWFhZTEwZTVmNmM5YTYzOWU3YmI1YWM4MWIzOWIzMi9hc3NldHMvNTI1OGQ3ZDYzMzY3OWYyMjBhNGJiY2ZiODYwYzRiOGJfNDYwNjQ0OC5tcDQvaW5kZXgtdjEtYTEubTN1OCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY1OTYyMTgwMX19fV19&Signature=StRr92bfO8K~3BO3fl39gx9iALZBNBFSHxUe8LQM0RqVQLyv7pdRSWqnsJQxw-LlTAc1VcAHbYKcaifJ9EsysT1I5XMFMdLQ4H-3D1u1Dak1HP8sRsOC9U4r0ZNaPbS7tzI-K8SDs0~z8vjH0l5a9OHscTylb6CmxAQn~oCqDf9vcMoeei5J8YITDAqU6odwYGvETHdICrMUXrpB-FyRnF-KaQDkg9A0kGBq8iGa9FeaUAAtgHY306H39pMlHG8rZKytCXVEUWsncBUCQZku8HdW4IaGmeyVS-R526Cxi4DlBK2Df1SmBCtMS0CvNBpIqB71kBSrbb5AQBhfSrdxiQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 351
[download] Destination: Shikimori's Not Just a Cutie\Season 01\S01EP12-ru-RU - Shikimori's Not Just a Cutie- Better Than a Dream.mp4
[debug] File locking is not supported. Proceeding without locking
[download]  11.1% of ~1.57GiB at    3.67MiB/s ETA 03:56 (frag 39/351)
ERROR: Interrupted by user
```

### PR DESCRIPTION
**Pull request by tejing1**
### Description of your *pull request* and other information

Adds `timestamp` output to `CrunchyrollBetaIE`, enabling `--dateafter`, among other things.

Fixes #4533

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
Make sure you've run the tests

**Comment by tejing1** [comment]
Looks like some of the test videos have been removed from the site. Should I look for another example of what those videos were supposed to test?

**Comment by pukkandan** [comment]
Are all happy code paths are covered by current tests?

**Comment by pukkandan** [comment]
skimming through the code, it seems so. In that case, no new tests are needed

**Comment by tejing1** [comment]
Given that the beta site is still login-only, the tests are really only testing the redirect functionality, anyway.

**Comment by pukkandan** [comment]
hm.. what? You should run the test after adding your credentials to local_parameters. The other extractor has it's own tests

**Comment by pukkandan** [comment]
Have you been doing the tests wrong all this time? https://github.com/yt-dlp/yt-dlp/blob/7356a44443995d83c59b915186b6a719769eab60/CONTRIBUTING.md?plain=1#L237-L243

**Comment by tejing1** [comment]
:facepalm: I completely failed to take in that part of the contributing instructions. Yeah, I've been doing it wrong the whole time >.<.

Should I change the tests to match the logged in results? If I do, they'll fail without a login, because the redirect makes it come out differently.

**Comment by pukkandan** [comment]
yes

> they'll fail without a login, because the redirect makes it come out differently.
that is fine

**Comment by tejing1** [comment]
Sorry for the long wait. Ran into crunchyroll login endpoint rate-limits and had to wait it out.

**Pull request merged**
