### PR TITLE
[lbry/odysee] change host for api to fix "HTTPError 405: 'Method Not …

### PR DESCRIPTION
**Pull request by PSlava**
…Allowed'"

Signed-off-by: Slava <slash@i-slash.com>

**IMPORTANT**: PRs without the template will be CLOSED

Odysee is not working at all. Getting 'HTTPError 405: 'Method Not Allowed''

</details>

changed host for API from api.lbry.tv to api.na-backend.odysee.com

browsers use this host

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by Nex4rius** [comment]
It worked for me :)

**Comment by atom-smasher** [comment]
Just confirming both (1) the bug as reported and (2) the fix as desired.

yt-dlp version 2022.11.11 [8b644025b]

Thank you :)

**Comment by flashdagger** [comment]
will fix #5573

**Comment by pukkandan** [comment]
Implement fallback to the original. You could also add an extractor-arg for user to set the domain

**Comment by Ulmo** [comment]
This hard coded address works in North America.  Thanks for this simple fix.

Is there a dynamic way to handle this?  E.g., look up what Odysee wants to use and cache that, fail on failure, relookup and recache, and if lookup or cached results fail, fallback to the historical good ones?  (Typical server upgrade following pathway; I'm sure someone made a code piece for this general function someplace.)

**Comment by dirkf** [comment]
1. Get the `embedURL` from the ld+json or elsewhere in the page.
2. Fetch the page at that URL
3. Find the JS statement `var r = {...};` where ... includes the word `LBRY_WEB_API`
4. Extract and parse the braced JS object into a dict
5. The item with key `LBRY_WEB_API` has the value scheme://host for the API (other items may also be useful)
6. Or use "https://api.na-backend.odysee.com"

**Comment by dirkf** [comment]
Also, the JS statement is in the JS linked in an element like this
```
<script src="/public/ui-202211241558.d7bd8cc389.js" async></script>
```
in video pages **and** in the home page https://odysee.com/.

**Comment by Grub4K** [comment]
Resolved on the sites end

**Pull request closed without merging**
