### PR TITLE
[fragment] Generalize download code

### PR DESCRIPTION
**Pull request by pukkandan**
A lot of the code in `hls` and `dash` are identical. This PR attempts to merge the common parts of the code from both into the `fragment` base class.

Any small bug in this code could have serious consequences. So a lot of testing is required. Also, if someone could review the changes, it would be appreciated

### CODE REVIEW

**Comment by Jules-A** [comment]
Maybe request a review from @shirt-dev since it was mostly (if not all) of his code?

**Comment by Jules-A** [comment]
I tested this branch a little bit and it's bugged for me.
> [TubiTv] 577958: Downloading JSON metadata
[TubiTv] 577958: Downloading m3u8 information
[MetadataFromField] parsed myindex from "webpage_url": 1
WARNING: Could not interpret video %(series)s - S%(season_number)sE%(episode_number)s as "^(?P<title>.+ - S\d+E\d+)$"
[info] 577958: Downloading 1 format(s): 1358
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 427
[download] Destination: D:\Temp\TubiTv\S01 -E01 - DOME (Dub) - 1.mp4
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100.0% of ~230.27MiB at  3.13MiB/s ETA 00:00     ERROR: unable to download video data: [Errno 2] No such file or directory: 'D:\\Temp\\TubiTv\\S01 -E01 - DOME (Dub) - 1.mp4.part-Frag30'

It starts building the part file but looks like it's failing to download some fragments (I'm not sure if it's missing at download or during merging into part file).

**Comment by pukkandan** [comment]
@Jules-A Looks similar to #373. Did you pull the changes that I made today?

**Comment by Jules-A** [comment]
> 
> 
> @Jules-A Looks similar to #373. Did you pull the changes that I made today?

I downloaded from this branch as of https://github.com/pukkandan/yt-dlp-dev/commit/e9d5be237aa9c641e3361bb0bfdce033dae8b66c so it's currently missing 3 unrelated commits.

**Comment by pukkandan** [comment]
Please give the URL so that I can test. Btw, always post the whole log. The verbose header shows the passed options, git HEAD etc so that I dont need to ask for each thing one by one

**Comment by Jules-A** [comment]
> 
> 
> Please give the URL so that I can test. Btw, always post the whole log. The verbose header shows the passed options, git HEAD etc so that I dont need to ask for each thing one by one

https://tubitv.com/tv-shows/577958/s01-e01-dome-dub?start=true

[log.txt](https://github.com/yt-dlp/yt-dlp/files/6644575/log.txt)

**Comment by pukkandan** [comment]
I can reproduce the issue, but cant seem to figure out why it is happening. I'll have another look tomorrow

**Comment by pukkandan** [comment]
> https://tubitv.com/tv-shows/577958/s01-e01-dome-dub?start=true
> 
> [log.txt](https://github.com/yt-dlp/yt-dlp/files/6644575/log.txt)

There was a race condition where multiple threads where trying to modify `ctx` at the same time causing some filenames to get become associated with the wrong fragment. This has now been fixed

While fixing this, I also figured out how to append fragments as they download. So this PR now closes #359

**Pull request merged**
