### PR TITLE
Adding album name to metadata

### PR DESCRIPTION
**Pull request by Arifbrat**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADD DESCRIPTION HERE

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by garret1317** [comment]
could you fill in the template please

**Comment by Arifbrat** [comment]
> could you fill in the template please

Okey

**Comment by Arifbrat** [comment]
> could you fill in the template please

I mentioned.

**Comment by bashonly** [comment]
The album name was already being added to embedded metadata; the value was being drawn from the `album` field in the info dict.

The PR's change will instead ignore the info dict's `album` field, and instead try to draw the value from the info dict's `track` field, and then fall back to the `title` field. I don't see why this would be desired. Can you explain the intent here?

**Comment by Arifbrat** [comment]
> The album name was already being added to embedded metadata; the value was being drawn from the `album` field in the info dict.
> 
> The PR's change will instead ignore the info dict's `album` field, and try to draw the value from the info dict's `track` field, and then fall back to the `title` field. I don't see why this would be desired. Can you explain the intent here?

Thumbnail photo does not appear if album name is not written to music

**Comment by Arifbrat** [comment]
> The album name was already being added to embedded metadata; the value was being drawn from the `album` field in the info dict.
> 
> The PR's change will instead ignore the info dict's `album` field, and try to draw the value from the info dict's `track` field, and then fall back to the `title` field. I don't see why this would be desired. Can you explain the intent here?

The album is not assigned a value so I added a value to get that value from the "info dict".

**Comment by bashonly** [comment]
> The album is not assigned a value so I added a value to get that value from the "info dict".

This is something you could handle on a case-by-case basis with the `--parse-metadata` option. The default should not be changed

**Pull request closed without merging**
