### PR TITLE
[youtube:comments] Detect comment section loop

### PR DESCRIPTION
**Pull request by coletdjnz**
Fixes https://github.com/yt-dlp/yt-dlp/issues/6290

Authored by: coletdjnz

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADD DESCRIPTION HERE

Fixes https://github.com/yt-dlp/yt-dlp/issues/6290

The above case has the entire comment section looping. This stops the comment extraction if it detects that.

Note that this will not stop any other kind of looping e.g. a single page repeating.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [X] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by pukkandan** [comment]
Wouldn't it be more robust to store all detected comment ids? This can detect similar loops in reply threads, for example

**Comment by pukkandan** [comment]
If that's not something you want to do, you can merge this

**Comment by coletdjnz** [comment]
> Wouldn't it be more robust to store all detected comment ids in a set? This can detect similar loops in reply threads, for example

Yeah that's another thing I was considering, but it may have more of a memory impact.

**Comment by pukkandan** [comment]
Not really:
```py
In [18]: import string, random, sys

In [19]: x = { ''.join(random.choices(string.ascii_letters + string.digits, k=50)) for _ in range(1000000) }

In [20]: sys.getsizeof(x)/(2**20)
Out[20]: 32.000205993652344
```

**Comment by JustAnotherArchivist** [comment]
@pukkandan That's only the size of the set object itself and does not include the size of the strings within. Each of those is 75 bytes per my testing (which seems right; the empty string object is 49 byte, plus 26 bytes), so that adds another 75 MB per million comments. Might still be fine of course depending on who you ask.

**Comment by ivan** [comment]
I confirmed that this PR fixed the problem with https://www.youtube.com/watch?v=kOHXmlRaTqU

```
[youtube] Downloading comment API JSON page 7 (173/420)
WARNING: [youtube] Detected comment section loop from YouTube. Stopping comment extraction.
[youtube] Extracted 173 comments
```

**Comment by pukkandan** [comment]
> That's only the size of the set object itself and does not include the size of the strings within. Each of those is 75 bytes per my testing (which seems right; the empty string object is 49 byte, plus 26 bytes), so that adds another 75 MB per million comments. Might still be fine of course depending on who you ask.

The strings are already in memory inside the whole comment json. Afaik, Python doesn't copy them it

**Comment by coletdjnz** [comment]
If memory isn't an issue, would the process of checking if we already have the comment *for every comment* for millions of comments any concern?

Either way we can add support if we want this to be very robust.

**Comment by pukkandan** [comment]
> If memory isn't an issue, would the process of checking if we already have the comment _for every comment_ for millions of comments any concern?

Compared to the time we spend downloading comment webpages, it's negligible

```py
In [19]: %%time
    ...: comments = set()
    ...: for _ in range(1000_000):
    ...:   current = ''.join(random.choices(string.ascii_letters + string.digits, k=26))
    ...:   if current not in comments:
    ...:     comments.add(current)
    ...:
CPU times: total: 10.7 s
Wall time: 10.8 s
```

**Comment by ivan** [comment]
With this PR as it is now, I still observe looping on some videos (https://www.youtube.com/watch?v=GuGYYdwcPYw and https://www.youtube.com/watch?v=Tr8AS-a4AOc):

### `GuGYYdwcPYw`

```
[youtube] Downloading comment API JSON page 34083 (677547/144045)
[youtube]     Downloading comment API JSON reply thread 1 (677550/144045)
[youtube]     Downloading comment API JSON reply thread 2 (677553/144045)
[youtube]     Downloading comment API JSON reply thread 3 (677570/144045)
[youtube] Downloading comment API JSON page 34084 (677573/144045)
[youtube] Downloading comment API JSON page 34085 (677593/144045)
[youtube]     Downloading comment API JSON reply thread 1 (677596/144045)
[youtube] Downloading comment API JSON page 34086 (677617/144045)
[youtube] Downloading comment API JSON page 34087 (677637/144045)
```

### `Tr8AS-a4AOc`

```
[youtube] Downloading comment API JSON page 178299 (3155716/75172)
[youtube]     Downloading comment API JSON reply thread 1 (3155718/75172)
[youtube]     Downloading comment API JSON reply thread 2 (3155734/75172)
[youtube] Downloading comment API JSON page 178300 (3155736/75172)
[youtube] Downloading comment API JSON page 178301 (3155754/75172)
```

**Comment by coletdjnz** [comment]
> With this PR as it is now, I still observe looping on some videos (https://www.youtube.com/watch?v=GuGYYdwcPYw and https://www.youtube.com/watch?v=Tr8AS-a4AOc):
> ### `GuGYYdwcPYw`
> 
> ```
> [youtube] Downloading comment API JSON page 34083 (677547/144045)
> [youtube]     Downloading comment API JSON reply thread 1 (677550/144045)
> [youtube]     Downloading comment API JSON reply thread 2 (677553/144045)
> [youtube]     Downloading comment API JSON reply thread 3 (677570/144045)
> [youtube] Downloading comment API JSON page 34084 (677573/144045)
> [youtube] Downloading comment API JSON page 34085 (677593/144045)
> [youtube]     Downloading comment API JSON reply thread 1 (677596/144045)
> [youtube] Downloading comment API JSON page 34086 (677617/144045)
> [youtube] Downloading comment API JSON page 34087 (677637/144045)
> ```
> 
> ### `Tr8AS-a4AOc`
> 
> ```
> [youtube] Downloading comment API JSON page 178299 (3155716/75172)
> [youtube]     Downloading comment API JSON reply thread 1 (3155718/75172)
> [youtube]     Downloading comment API JSON reply thread 2 (3155734/75172)
> [youtube] Downloading comment API JSON page 178300 (3155736/75172)
> [youtube] Downloading comment API JSON page 178301 (3155754/75172)
> ```

can you check if it works for you now?

**Comment by ivan** [comment]
Thanks a lot, that does fix the loop, but it might be stopping too early? (assuming the other comments can be downloaded)

### `Tr8AS-a4AOc`

```
[youtube] Downloading comment API JSON page 35 (1136/75500)
[youtube]     Downloading comment API JSON reply thread 1 (1150/75500)
[youtube] Downloading comment API JSON page 36 (1156/75500)
[youtube] Downloading comment API JSON page 37 (1176/75500)
[youtube]     Downloading comment API JSON reply thread 1 (1184/75500)
[youtube] Downloading comment API JSON page 38 (1195/75500)
[youtube] Downloading comment API JSON page 39 (1205/75500)
[youtube] Downloading comment API JSON page 40 (1205/75500)
WARNING: [youtube] Detected comment loop from YouTube. Stopping comment extraction.
[youtube] Extracted 1205 comments
```

### `GuGYYdwcPYw`

```
[youtube] Downloading comment API JSON page 105 (2725/145550)
[youtube]     Downloading comment API JSON reply thread 1 (2734/145550)
[youtube] Downloading comment API JSON page 106 (2747/145550)
[youtube]     Downloading comment API JSON reply thread 1 (2752/145550)
[youtube]     Downloading comment API JSON reply thread 2 (2764/145550)
[youtube]     Downloading comment API JSON reply thread 3 (2768/145550)
[youtube] Downloading comment API JSON page 107 (2771/145550)
[youtube] Downloading comment API JSON page 108 (2776/145550)
[youtube] Downloading comment API JSON page 109 (2776/145550)
WARNING: [youtube] Detected comment loop from YouTube. Stopping comment extraction.
[youtube] Extracted 2778 comments
```

**Comment by coletdjnz** [comment]
> Thanks a lot, that does fix the loop, but it might be stopping too early? (assuming the other comments can be downloaded)
> 
> ### `Tr8AS-a4AOc`
> 
> ```
> [youtube] Downloading comment API JSON page 35 (1136/75500)
> [youtube]     Downloading comment API JSON reply thread 1 (1150/75500)
> [youtube] Downloading comment API JSON page 36 (1156/75500)
> [youtube] Downloading comment API JSON page 37 (1176/75500)
> [youtube]     Downloading comment API JSON reply thread 1 (1184/75500)
> [youtube] Downloading comment API JSON page 38 (1195/75500)
> [youtube] Downloading comment API JSON page 39 (1205/75500)
> [youtube] Downloading comment API JSON page 40 (1205/75500)
> WARNING: [youtube] Detected comment loop from YouTube. Stopping comment extraction.
> [youtube] Extracted 1205 comments
> ```
> 
> ### `GuGYYdwcPYw`
> 
> ```
> [youtube] Downloading comment API JSON page 105 (2725/145550)
> [youtube]     Downloading comment API JSON reply thread 1 (2734/145550)
> [youtube] Downloading comment API JSON page 106 (2747/145550)
> [youtube]     Downloading comment API JSON reply thread 1 (2752/145550)
> [youtube]     Downloading comment API JSON reply thread 2 (2764/145550)
> [youtube]     Downloading comment API JSON reply thread 3 (2768/145550)
> [youtube] Downloading comment API JSON page 107 (2771/145550)
> [youtube] Downloading comment API JSON page 108 (2776/145550)
> [youtube] Downloading comment API JSON page 109 (2776/145550)
> WARNING: [youtube] Detected comment loop from YouTube. Stopping comment extraction.
> [youtube] Extracted 2778 comments
> ```

 That would be the point where it starts looping

**Pull request merged**
