### PR TITLE
[ie/Qub] Fix extractor

### PR DESCRIPTION
**Pull request by alexhuot1**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Fixes the 404 error on tva/qub website. Used the fix proposed in the youtube-dl issue: https://github.com/ytdl-org/youtube-dl/issues/31240 

Fixes #
#4989

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [X] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/)
Took the code from this repo: https://github.com/dirkf/youtube-dl
This file exactly: https://github.com/dirkf/youtube-dl/blob/df-tva-extractor-ovrhaul/youtube_dl/extractor/tva.py

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by pukkandan** [comment]
The code is not following our style requirements, but youtube-dl's. Either wait for it to be merged upstream and I will pull it. Or, rewrite according to our conventions.

**Comment by dnlldl** [comment]
> The code is not following our style requirements, but youtube-dl's. Either wait for it to be merged upstream and I will pull it. Or, rewrite according to our conventions.

Any update? It still doesn't work.

**Review by bashonly — CHANGES_REQUESTED** [review]

**Comment by alexhuot1** [comment]
I've adjusted the PR to be more precise. Thanks ;)

**Comment by alexhuot1** [comment]
Nobody seams to review sin

**Review by bashonly — APPROVED** [review]
please update the test

**Comment by dnlldl** [comment]
Is this working? I'm getting a 404 when trying some such as https://www.qub.ca/tvaplus/tva/fugueuse/saison-2/episode-11-1000091058

**Comment by bashonly** [comment]
@dnlldl that link works for me. Make sure you are on the latest nightly release. If it still doesn't work, then open a new issue with a complete verbose log please

**Comment by dnlldl** [comment]
> @dnlldl that link works for me. Make sure you are on the latest nightly release. If it still doesn't work, then open a new issue with a complete verbose log please

Ah that must be why, I'm on stable. Using Unraid at the moment with https://github.com/alexta69/metube, doesn't seem to support release tags. I will wait for it to be in the stable branch, maybe in a few weeks?

**Comment by bashonly** [comment]
@dnlldl This patch is already in the stable branch. But when opening a new issue the instructions ask you to provide a log from the latest nightly/master.

**Pull request merged**
