### PR TITLE
Use `os.setxattr` if available

### LINKED ISSUE #8193: use Python's native XATTR support rather than xattr/pyxattr
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hey.

AFAICS from current `master`:
https://github.com/yt-dlp/yt-dlp/blob/c54ddfba0f7d68034339426223d75373c5fc86df/yt_dlp/dependencies/__init__.py#L63
yt-dlp would always use the `xattr`-module (by one of the two implementations) fr XATTR support.

However, since version 3.3, Python itself has XATTR support:
https://docs.python.org/3/library/os.html#linux-extended-attributes

I think it would be nice if those function would be used and the dependencies could be dropped.

Cheers,
Chris.

PS: I guess the stuff from the issue template that I didn't check or fill out is not really relevant for this issue.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

_No response_

### PR DESCRIPTION
**Pull request by bashonly**
Use stdlib xattr support if available

Closes #8193

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🗑️🐧🏷️

Simplify and improve xattr metadata writing on Linux. Remove xattr and pyxattr dependencies and use `os.setxattr` instead. Update `README.md` and docstrings accordingly.

> _No more xattr, no more pyxattr_
> _We don't need them to write our metadata_
> _We use `os.setxattr` to set our flags_
> _We are the masters of the extended attributes_

### Walkthrough
*  Simplify and improve the writing of xattr metadata on Linux by using the built-in `os.setxattr` function ([link](https://github.com/yt-dlp/yt-dlp/pull/8205/files?diff=unified&w=0#diff-feda8f56946dc048e754111850baaef0eec4b9f8bbc2d3f04b1a785626ea5c0eL4444-R4447), [link](https://github.com/yt-dlp/yt-dlp/pull/8205/files?diff=unified&w=0#diff-feda8f56946dc048e754111850baaef0eec4b9f8bbc2d3f04b1a785626ea5c0eL57-R57), [link](https://github.com/yt-dlp/yt-dlp/pull/8205/files?diff=unified&w=0#diff-de7a33dfc7bfbde1984024aefea7058b51f5de324d4460efdee999bf798ebd01L62-L70))
* Update the docstring of the `XAttrMetadataPP` class to reflect the new assumption of xattr support on Linux ([link](https://github.com/yt-dlp/yt-dlp/pull/8205/files?diff=unified&w=0#diff-671f23d83ae21e81d1bcf8852cd9394c9571c80d0d6fe2adf082b372729798d2L15-R15))
* Remove the mention of xattr, pyxattr and setfattr from the `README.md` file, as they are no longer required dependencies ([link](https://github.com/yt-dlp/yt-dlp/pull/8205/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L283))

</details>

### CODE REVIEW

**Review by Grub4K — APPROVED** [review]

**Comment by coletdjnz** [comment]
I would add a test if feasible

**Comment by dirkf** [comment]
Especially for Darwin, BSD: https://github.com/yt-dlp/yt-dlp/issues/8193#issuecomment-1734589913

**Comment by Grub4K** [comment]
Honestly not sure how we can test this effectively. If you have ideas feel free to suggest

**Comment by coletdjnz** [comment]
Hmm, was having a think about tests. One could possibly do some unit tests on `write_xattr`. However I ran into a problem where I wanted to create a tempfile to write the xattrs to but the temp file fs doesn't support xattrs.

```py
    @unittest.skipUnless(callable(getattr(os, 'setxattr', None)), 'setxattr not available')
    def test_write_xattr_os_xattr(self):
        with mock.patch('os.setxattr', wraps=os.setxattr) as mock_setxattr:
            with tempfile.NamedTemporaryFile(delete=False) as temp_file:
                attr_name = 'user.dublincore.title'
                attr_value = b'testvalue'

                try:
                    write_xattr(temp_file.name, attr_name, attr_value)
                    mock_setxattr.assert_called_once()
                    retrieved_value = os.getxattr(temp_file.name, attr_name)
                    self.assertEqual(retrieved_value, attr_value)
                finally:
                    os.remove(temp_file.name)
```

**Review by coletdjnz — APPROVED** [review]
seems to work and looks fine to me

**Pull request merged**
