### PR TITLE
[extractor/qdance] Add extractor

### LINKED ISSUE #7385: Q-Dance Network
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Australia

### Example URLs

- Single stream: https://www.q-dance.com/network/live/149170193

### Provide a description that is worded well enough to be understood

Website streams the liveset of music festivals such as Defqon.1 & Qlimax. The stream can be downloaded via m3u8 using extensions that target and download m3u8 files.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'brave', '-vU', 'https://www.q-dance.com/network/live/149170193']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.21 [42f2d40b4] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from brave
[debug] Extracting cookies from: "C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Profile 5\Network\Cookies"
[debug] Found local state file at "C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Local State"
[Cookies] Extracted 95 cookies from brave
[debug] cookie version breakdown: {'v10': 95, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1848 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.21
Current Build Hash: 0e00f0a64217f271301625b09ae9ed05fe430e5a42391389504ddc01b2e42380
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Updating to stable@2023.06.22 ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/latest/download/SHA2-256SUMS
Updated yt-dlp to stable@2023.06.22
[debug] Restarting: yt-dlp --cookies-from-browser brave -vU "https://www.q-dance.com/network/live/149170193"
[debug] Command-line config: ['--cookies-from-browser', 'brave', '-vU', 'https://www.q-dance.com/network/live/149170193']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from brave
[debug] Extracting cookies from: "C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Profile 5\Network\Cookies"
[debug] Found local state file at "C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Local State"
[Cookies] Extracted 95 cookies from brave
[debug] cookie version breakdown: {'v10': 95, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 37e7ffe204309357cfd1388b0e2c782a30e293ddd0f2761a9a8f6afa185b3566
yt-dlp is up to date (stable@2023.06.22)
[generic] Extracting URL: https://www.q-dance.com/network/live/149170193
[generic] 149170193: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 149170193: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.q-dance.com/network/live/149170193
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1555, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1631, in __extract_info
  File "yt_dlp\extractor\common.py", line 708, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.q-dance.com/network/live/149170193
```

### PR DESCRIPTION
**Pull request by bashonly**
q-dance.com serves livestreams and VODs of music festival sets. All content is authwalled. Extractor supports login and cookies.

Closes #7385

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🎵🕺🌐

Add support for Q-Dance website. Import QDanceIE class from `qdance.py` in `_extractors.py`. Implement QDanceIE class in `qdance.py` to extract video information and formats from Q-Dance API and website.

> _`QDanceIE` class_
> _Extracts hardstyle videos_
> _Winter nights are warm_

### Walkthrough
*  Add support for Q-Dance website ([link](https://github.com/yt-dlp/yt-dlp/pull/7420/files?diff=unified&w=0#diff-780b22dc7eb280f5a7b2bbf79aff17826de88ddcbf2fc1116ba19901827aa4e3R1534), [link](https://github.com/yt-dlp/yt-dlp/pull/7420/files?diff=unified&w=0#diff-490c41733598cb78f532ebb9566e0c6b401fc8b2b811da91c1c588f717c494f6R1-R149))
   * Import QDanceIE class from `qdance.py` module in `_extractors.py` ([link](https://github.com/yt-dlp/yt-dlp/pull/7420/files?diff=unified&w=0#diff-780b22dc7eb280f5a7b2bbf79aff17826de88ddcbf2fc1116ba19901827aa4e3R1534))
   * Define QDanceIE class in `qdance.py` module that inherits from InfoExtractor ([link](https://github.com/yt-dlp/yt-dlp/pull/7420/files?diff=unified&w=0#diff-490c41733598cb78f532ebb9566e0c6b401fc8b2b811da91c1c588f717c494f6R1-R149))

</details>

### CODE REVIEW

**Comment by revunix** [comment]
Q-dance started using a new ID format for videos, instead of numbers like 184575047, they now use a random alphanumeric ID like WhDleSIWSfeT3Q9ObBKBeA.

Please update 🫣

**Comment by bashonly** [comment]
@revunix I could fix it if you are willing to share account creds and an actual example URL

**Comment by revunix** [comment]
@bashonly how can i give you my account? But the request url is the same. there just changed the link ID. ¯\_(ツ)_/¯

**Comment by bashonly** [comment]
@revunix
you can email me, bashonly ( a t ) protonmail ( d o t ) com
or join the [yt-dlp discord server](https://discord.gg/H5MNcFW63r) and DM me on there (same username)

please also just share an actual full example URL w/the new format so I don't have to mess around with constructing my own URL or digging around on the site for an example

**Pull request merged**
