### PR TITLE
[extractor/instagram] Fix post extraction error with non logged in users

### LINKED ISSUE #4532: Instagram: Unable to extract additional data, username, & video URL.
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

U.S.

### Provide a description that is worded well enough to be understood

Downloading from Instagram used to work properly about 99% of the time - but as of a little more than a week ago, it entirely stopped working.  I uninstalled the repo version, then downloaded & installed the up to date version from Github.  It worked for one day, but I've hit the same wall again.

-------------------------------

This is the verbose output of a failed download:

```
$ yt-dlp --verbose https://www.instagram.com/p/Cfo4kgugFV4/
[debug] Command-line config: ['--verbose', 'https://www.instagram.com/p/Cfo4kgugFV4/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.57-antix.1-amd64-smp-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/Cfo4kgugFV4/
[Instagram] Cfo4kgugFV4: Downloading JSON metadata
WARNING: [Instagram] Cfo4kgugFV4: General metadata extraction failed
[Instagram] Cfo4kgugFV4: Downloading video info
[Instagram] Cfo4kgugFV4: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cfo4kgugFV4: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/instagram.py", line 433, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1335, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1230, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1194, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```
-------------------------

---------------------------
This is the output using the -vu flag:

```
$ yt-dlp -vu https://www.instagram.com/p/Cfo4kgugFV4/
[debug] Command-line config: ['-vu', 'https://www.instagram.com/p/Cfo4kgugFV4/']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.57-antix.1-amd64-smp-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```
-------------------------

As you can see, I DID provide a URL.  But -vu couldn't recognize it.
NOTE:  -vu requests the user to type in the account password.  That's quite vague.  I tried my desktop user password, and my Instagram account password.  Neither worked.

The URL I was trying to download from was
https://www.instagram.com/p/Cfo4kgugFV4/

---------------------------

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp --verbose https://www.instagram.com/p/Cfo4kgugFV4/
[debug] Command-line config: ['--verbose', 'https://www.instagram.com/p/Cfo4kgugFV4/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.57-antix.1-amd64-smp-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/Cfo4kgugFV4/
[Instagram] Cfo4kgugFV4: Downloading JSON metadata
WARNING: [Instagram] Cfo4kgugFV4: General metadata extraction failed
[Instagram] Cfo4kgugFV4: Downloading video info
[Instagram] Cfo4kgugFV4: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cfo4kgugFV4: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/instagram.py", line 433, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1335, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1230, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1194, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

### PR DESCRIPTION
**Pull request by pritam20ps05**
### Description of *pull request* and other information

Fixes the current issue faced by non logged in users with post extractor by adding main webpage extraction. Current extraction order: GraphQL (mandatory) -> web API (for logged in users) -> webpage (for non logged in users) -> embed page (for non logged in users)

Fixes #4532

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pritam20ps05** [comment]
Why do not merge? it fixes the problem with error notes when the extraction fails

**Comment by pukkandan** [comment]
Because the new error message is wrong. The videos open in browser without login. So raising a login_required is incorrect

**Comment by pritam20ps05** [comment]
No this error is general purpose error and would be shown if anyhow extraction fails. Otherwise the ugly error comes with almost no clarity.

**Comment by pukkandan** [comment]
You think "login required" is a general purpose error and shouldn't just be used when *login is required*??

**Comment by pritam20ps05** [comment]
So what we tell the user if the extraction fails or we just show them the traceback caused due to unwanted code execution?

**Comment by pukkandan** [comment]
Raise login_reqiored only when it's actually login issue. There is no need to "fix" the current error message, because the **extraction is broken**. But, if you think you can provide a better error message, raise an ExtractorError. You can hint the user that login can workaround the issue, but not that lack of login **is** the issue

**Comment by pukkandan** [comment]
Also, the PR title/desc no longer reflects what it does?

**Pull request closed without merging**
