### PR TITLE
--download-sections "*from_urls" extracting sections from embedded YT URLS 

### PR DESCRIPTION
**Pull request by TheSQLWhisperer**
A new option was added to --download-sections  - *from_urls - to generate sections automatically from the URL itself.

When --download-sections "*from_urls" is specified, for any URLS of the form https://www.youtube.com/embed/VIDEOID?start=6&end=10

The start and end values are parsed and an additional download section is generated. The default value for start is 0, the default value for end is inf (end of video). If neither start nor end is present in the URL the old behavior remains unchanged, even if *from_urls is specified.

Multiple start and end values are supported per URL, these are paired and multiple sections are generated.
If multiple --download-sections are specified they are combined with the newly generated sections, for each video.

When the *from_urls option is specified the default output template is changed to "%(title)s-%(id)s-%(section_start)s-%(section_end)s.%(ext)s". This is done in order to produce different files when there are multiple sections from the same video are specified or different sections are already present in the directory, otherwise the default behavior is to skip the download.

Updated documentation for --download-sections "*from_url", added explanation and URL example.

Execution example: 

py -bb -Werror -Xdev ".\yt_dlp\__main__.py" "https://www.youtube.com/embed/djzX3fXnIFs?start=6&end=10"  --download-sections "*from_urls"  -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
  
<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [x] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
📝🎞️🔗

This pull request adds a new feature to yt-dlp that allows downloading sections of videos based on the URL. It modifies `yt_dlp/__init__.py`, `yt_dlp/utils/_utils.py`, and `README.md` to implement and document the `--download-sections` option and the `*from_url` value. It also changes the default output template to include the section start and end times in the file name.

> _If you want to download a section_
> _Of a video without much inspection_
> _Use `--download-sections`_
> _With `*from_url` selections_
> _And enjoy the automatic detection_

### Walkthrough
*  Add a new feature to download sections of videos based on the URL parameters ([link](https://github.com/yt-dlp/yt-dlp/pull/7248/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L619-R626), [link](https://github.com/yt-dlp/yt-dlp/pull/7248/files?diff=unified&w=0#diff-368601fd75cc1f1f9a4427938fe6381ffbab2ed89434cabb25d9346b43f037b0L326-R341), [link](https://github.com/yt-dlp/yt-dlp/pull/7248/files?diff=unified&w=0#diff-368601fd75cc1f1f9a4427938fe6381ffbab2ed89434cabb25d9346b43f037b0L339-R361), [link](https://github.com/yt-dlp/yt-dlp/pull/7248/files?diff=unified&w=0#diff-feda8f56946dc048e754111850baaef0eec4b9f8bbc2d3f04b1a785626ea5c0eL3751-R3772), [link](https://github.com/yt-dlp/yt-dlp/pull/7248/files?diff=unified&w=0#diff-feda8f56946dc048e754111850baaef0eec4b9f8bbc2d3f04b1a785626ea5c0eL3768-R3817))
  * Update the documentation of the `--download-sections` option in `README.md` to explain the new value `*from_url` and the default output template ([link](https://github.com/yt-dlp/yt-dlp/pull/7248/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L619-R626))
  * Modify the `parse_chapters` function in `yt_dlp/__init__.py` to accept a flag parameter that indicates whether to extract ranges from the URL or not, and return the flag along with the chapters and ranges ([link](https://github.com/yt-dlp/yt-dlp/pull/7248/files?diff=unified&w=0#diff-368601fd75cc1f1f9a4427938fe6381ffbab2ed89434cabb25d9346b43f037b0L326-R341))
  * Modify the `validate_options` function in `yt_dlp/__init__.py` to pass the flag to the `download_range_func` constructor, and update the default output template if the flag is set ([link](https://github.com/yt-dlp/yt-dlp/pull/7248/files?diff=unified&w=0#diff-368601fd75cc1f1f9a4427938fe6381ffbab2ed89434cabb25d9346b43f037b0L339-R361))
  * Modify the `download_range_func` class in `yt_dlp/utils/_utils.py` to store the flag as an attribute, and add a static method to extract ranges from the URL ([link](https://github.com/yt-dlp/yt-dlp/pull/7248/files?diff=unified&w=0#diff-feda8f56946dc048e754111850baaef0eec4b9f8bbc2d3f04b1a785626ea5c0eL3751-R3772))
  * Modify the `__call__` method of the `download_range_func` class in `yt_dlp/utils/_utils.py` to combine the ranges from the URL with the existing ranges, and yield from the combined list ([link](https://github.com/yt-dlp/yt-dlp/pull/7248/files?diff=unified&w=0#diff-feda8f56946dc048e754111850baaef0eec4b9f8bbc2d3f04b1a785626ea5c0eL3768-R3817))

</details>

### CODE REVIEW

**Comment by pukkandan** [comment]
> does using 'download-sections: "*from_urls" option downloads all the video before slicing for the desired fragments?

No

**Comment by pukkandan** [comment]
You maybe encountering https://github.com/yt-dlp/yt-dlp/issues/4478. Try avoiding dash formats.

**Comment by TheSQLWhisperer** [comment]
> You maybe encountering #4478. Try avoiding dash formats.

no idea, still this is a regression.
My examples works properly in 2023.03.04 and doesn't work in the current release.
I don't currently have the ability to diagnose the root cause.

**Comment by bashonly** [comment]
> no idea, still this is a regression.
> My example works properly in 2023.03.04 and doesn't work in the current release.

See https://github.com/yt-dlp/yt-dlp/issues/7703#issuecomment-1654206693 (also where this issue can be tracked going forward)

In your logs, version 2023.03.04 is downloading formats `136+140` while current release is downloading `609+140`. If you run current release with `-f 136+140` it will work fine (or at least it does for me). IMO not a regression, just a problem inherent in the iOS vp9 HLS formats

**Pull request closed without merging**
