### PR TITLE
[ie/crunchyroll] Remove initial state scrape

### LINKED ISSUE #7624: Crunchyroll ERROR: Unable to extract initial state
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

U.S.

### Provide a description that is worded well enough to be understood

Episodes I was able to get yesterday, also do not work today. I even logged out, closed Firefox and logging back in to no avail. All episodes do play in the browser.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
F:\_CR>yt-dlp.exe -vU "https://www.crunchyroll.com/watch/G2XU0D7Z0/they-show-up-when-you-least-expect-it" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0" --cookies-from-browser firefox -F
[debug] Command-line config: ['-vU', 'https://www.crunchyroll.com/watch/G2XU0D7Z0/they-show-up-when-you-least-expect-it', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0', '--cookies-from-browser', 'firefox', '-F']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-107013-g93b31dae1d-20220527 (setts), ffprobe N-107013-g93b31dae1d-20220527
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\David\AppData\Roaming\Mozilla\Firefox\Profiles\w22netn6.default-release\cookies.sqlite"
[Cookies] Extracted 2872 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/G2XU0D7Z0/they-show-up-when-you-least-expect-it
[crunchyroll] Retrieving main page (lang=None)
ERROR: [crunchyroll] G2XU0D7Z0: Unable to extract initial state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\crunchyroll.py", line 320, in _real_extract
  File "yt_dlp\extractor\crunchyroll.py", line 114, in _call_api
  File "yt_dlp\extractor\crunchyroll.py", line 99, in _call_base_api
  File "yt_dlp\extractor\crunchyroll.py", line 72, in _update_query
  File "yt_dlp\extractor\common.py", line 1272, in _search_json
  File "yt_dlp\extractor\common.py", line 1258, in _search_regex

F:\_CR>pause
Press any key to continue . . .
```

### PR DESCRIPTION
**Pull request by Grub4K**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

This PR removes the initial state scraping, saving one request. The initial state payload was removed from the webpage, and so we hardcode these values instead.

It also tries to adds a more helpful message for 403 workaround (#7442).

Fixes #7624

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details><details><summary>Copilot Summary</summary>  

### Summary
🛠️🌐✅

Improve Crunchyroll extraction by using better API parameters, handling errors, and fixing a bug.

> _`Crunchyroll` extracts_
> _With client IDs, locale_
> _Cloudflare cut off_

### Walkthrough
* Add and use class attributes for client IDs and locale codes ([link](https://github.com/yt-dlp/yt-dlp/pull/7632/files?diff=unified&w=0#diff-e2aa04216cc9a5b0a2e020fa6201e0403ed0a820ba38d084b4da5dac2c10d7f2L30-R47), [link](https://github.com/yt-dlp/yt-dlp/pull/7632/files?diff=unified&w=0#diff-e2aa04216cc9a5b0a2e020fa6201e0403ed0a820ba38d084b4da5dac2c10d7f2L65-R107), [link](https://github.com/yt-dlp/yt-dlp/pull/7632/files?diff=unified&w=0#diff-e2aa04216cc9a5b0a2e020fa6201e0403ed0a820ba38d084b4da5dac2c10d7f2L105-R120))
* Refactor and improve base extractor methods ([link](https://github.com/yt-dlp/yt-dlp/pull/7632/files?diff=unified&w=0#diff-e2aa04216cc9a5b0a2e020fa6201e0403ed0a820ba38d084b4da5dac2c10d7f2L65-R107), [link](https://github.com/yt-dlp/yt-dlp/pull/7632/files?diff=unified&w=0#diff-e2aa04216cc9a5b0a2e020fa6201e0403ed0a820ba38d084b4da5dac2c10d7f2L105-R120))
* Fix minor bug in beta extractor URL regex ([link](https://github.com/yt-dlp/yt-dlp/pull/7632/files?diff=unified&w=0#diff-e2aa04216cc9a5b0a2e020fa6201e0403ed0a820ba38d084b4da5dac2c10d7f2L209-R222))
* Add test case for beta extractor with German language URL ([link](https://github.com/yt-dlp/yt-dlp/pull/7632/files?diff=unified&w=0#diff-e2aa04216cc9a5b0a2e020fa6201e0403ed0a820ba38d084b4da5dac2c10d7f2L307-R320))

</details>

### CODE REVIEW

**Comment by ProDev2** [comment]
Works perfectly for me! Thank you. Also I checked the code and it shouldn't cause any merge conflicts with my PR (#7009) after you merge it to master.

**Comment by Grub4K** [comment]
This PR and build aim to fix both the 403 and the `initial state` error.
If working correctly, the 403 should no longer be present.
If it still is, please let me know the specific region and OS that failed in a comment with a verbose (`-v`) log.

If it fails, there is still a way to do the workaround as discussed [here](https://github.com/yt-dlp/yt-dlp/issues/7442#issuecomment-1610223778):
- Extract your *current* User-Agent from the browser
    - This can be done using google/duckduckgo/... by searching for "my user-agent"
- Open a crunchyroll.com page in the browser
- Load cookies from the browser into `yt-dlp`
    - Use either `--cookies-from-browser` or `--cookies`
- Pass the previously extracted User-Agent to yt-dlp
    - Use `--user-agent <your_user_agent>`
- Additionally, pass the flag to disable the automatic workaround
    - `--extractor-arg crunchyrollbeta:ua_workaround`

To test, first get the build in one of the following ways:
- update diretly from a regular builds: `yt-dlp --update-to Grub4K/yt-dlp@2023.07.18.215323`
- download it from the [pr-branch pre-release](https://github.com/Grub4K/yt-dlp/releases/tag/2023.07.18.215323)
- run from source: `git checkout git@github.com:Grub4K/yt-dlp.git`,
    then `git switch fix/crunchy-initial-state`
- install using pip: `python3 -m pip install -U pip setuptools wheel`, then `python3 -m pip install --force-reinstall https://github.com/Grub4K/yt-dlp/archive/fix/crunchy-initial-state.tar.gz`

Afterwards, try and run through the above steps, letting me know of any further errors.

**Comment by hajimekun** [comment]
Seems that now get only 350 segmets from manifest so the 351 is lost and the file will be truncated, donno for sure if the problem is related but it happens only in some episodes

**Comment by bashonly** [comment]
@hajimekun Doesn't sound like it would be related. You can open a new issue if you think it should be looked into

**Pull request merged**
