### PR TITLE
[extractor/TRUTV+TURNER] Fix Extractors

### LINKED ISSUE #3400: TruTV URL extraction broken (maybe other problems)
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Description

It looks like TruTV may have changed their URL structure. There is an open pull request over at [Youtube-DL](https://github.com/ytdl-org/youtube-dl/pull/24466) that I haven't tested yet. The new URL structure is like: https://www.trutv.com/shows/impractical-jokers/season-9/episode-18/eric-andre (should be available for free in the US)

### Verbose log

```shell
yt-dlp -vU https://www.trutv.com/shows/impractical-jokers/season-9/episode-18/eric-andre
[debug] Command-line config: ['-vU', 'https://www.trutv.com/shows/impractical-jokers/season-9/episode-18/eric-andre']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.7.3 (CPython 64bit) - Linux-5.10.28-Unraid-x86_64-with-debian-10.10
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://www.trutv.com/shows/impractical-jokers/season-9/episode-18/eric-andre
[generic] eric-andre: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] eric-andre: Downloading webpage
[generic] eric-andre: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.trutv.com/shows/impractical-jokers/season-9/episode-18/eric-andre
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.trutv.com/shows/impractical-jokers/season-9/episode-18/eric-andre
```

### PR DESCRIPTION
**Pull request by ohmybahgosh**
<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### Description of your *pull request* and other information

</details>

### Fixes Turner & TRUTV extractors to handle new URL format

Apply patches created by https://github.com/ThatNerdyPikachu via https://github.com/ytdl-org/youtube-dl/pull/24466/files that fix Turner & TRUTV extractors.

Fixes #3400

### CODE REVIEW

**Comment by pukkandan** [comment]
When porting PR's you need to make necessary changes according to our coding conventions

**Comment by ohmybahgosh** [comment]
> When porting PR's you need to make necessary changes according to our coding conventions. Or, you can wait for the upstream PR to get merged and I will port the changes myself

Apologies, but python is not my strong suit lol.  I just randomly stumbled upon #3400 and saw that a PR had been pening over on youtube-dl...tried the patch in yt-dlp and it fixed trutv, so I figured I could at least get the ball rolling on this by submitting the patched youtube-dl PR :)

**Comment by ohmybahgosh** [comment]
Just realized the repo attached to the patch PR was taken down by a DMC@ ...so not sure if they will get pulled in to youtube-dl lol


image

**Comment by pukkandan** [comment]
> I just randomly stumbled upon https://github.com/yt-dlp/yt-dlp/issues/3400 and saw that a PR had been pending over on youtube-dl...tried the patch in yt-dlp and it fixed trutv, so I figured I could at least get the ball rolling on this by submitting the patched youtube-dl PR :)

This is effectively the same as opening an issue and mentioning the upstream PR. And since there is already an issue open, you could just have comment that there is a patch available

**Pull request closed without merging**
