### PR TITLE
[extractor/viu] Added support for second subtitle and updated testing url

### PR DESCRIPTION
**Pull request by tkgmomosheep**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Some shows will contain more than one subtitle as shown below, this commit added support for extracting it.
Testing URLs are also not available anymore, they were updated accordingly.

URL: `https://www.viu.com/ott/hk/zh-hk/vod/430078/%E7%AC%AC%E5%85%AD%E6%84%9F-3`
```
      {
         "is_default":1,
         "name":"繁體中文",
         "url":"https://d2anahhhmp1ffz.cloudfront.net/4279146490/799524ec920a46b1960dc18729d2a98261bcb8e3",
         "subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/4279146490/799524ec920a46b1960dc18729d2a98261bcb8e3",
         "product_subtitle_id":"240856",
         "product_subtitle_language_id":"1",
         "second_subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/2156290699/c04164fcd48fc654733a877382f018f1cb381d89",
         "second_subtitle_position":1,
         "code":"zh-Hant"
      }
```

URL: `https://www.viu.com/ott/hk/zh-hk/vod/444666/%E6%88%91%E7%9A%84%E5%AE%A4%E5%8F%8B%E6%98%AF%E4%B9%9D%E5%B0%BE%E7%8B%90`
```
      {
         "is_default":1,
         "name":"繁體中文",
         "url":"https://d2anahhhmp1ffz.cloudfront.net/3058849036/65e41c405b9405739271c1badaa303868602ed3a",
         "subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/3058849036/65e41c405b9405739271c1badaa303868602ed3a",
         "product_subtitle_id":"253068",
         "product_subtitle_language_id":"1",
         "second_subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/674676911/744f1fed7f536677b76e7e695f7ff03a7c7ad330",
         "second_subtitle_position":0,
         "code":"zh-Hant"
      },
```

Command running on latest version
Command: `./yt-dlp -vU --list-subs --no-playlist https://www.viu.com/ott/hk/zh-hk/vod/430078/%E7%AC%AC%E5%85%AD%E6%84%9F-3`

```
[debug] Command-line config: ['-vU', '--list-subs', '--no-playlist', 'https://www.viu.com/ott/hk/zh-hk/vod/430078/%E7%AC%AC%E5%85%AD%E6%84%9F-3']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22623-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-03-07-git-e645a1ddb9-essentials_build-www.gyan.dev (setts), ffprobe 2022-03-07-git-e645a1ddb9-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [viu:ott] Extracting URL: https://www.viu.com/ott/hk/zh-hk/vod/430078/%E7%AC%AC%E5%85%AD%E6%84%9F-3
[viu:ott] 430078: Downloading video info
[viu:ott] Downloading just the video 430078 because of --no-playlist
[viu:ott] 430078: Getting bearer token
[viu:ott] 430078: Downloading stream info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available subtitles for 430078:
Language Formats
English  srt
Indo     srt
ภาษาไทย  srt
繁體中文     srt
```

Command run on PR version
Command: `python -m yt_dlp -vU --list-subs --no-playlist https://www.viu.com/ott/hk/zh-hk/vod/430078/%E7%AC%AC%E5%85%AD%E6%84%9F-3`

```
[debug] Command-line config: ['-vU', '--list-subs', '--no-playlist', 'https://www.viu.com/ott/hk/zh-hk/vod/430078/%E7%AC%AC%E5%85%AD%E6%84%9F-3']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version 2022.10.04 [4e0511f27] (source) 
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 35b27db60 
[debug] Python 3.9.13 (CPython 64bit) - Windows-10-10.0.22623-SP0  
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs 
[debug] exe versions: ffmpeg 2022-03-07-git-e645a1ddb9-essentials_build-www.gyan.dev (setts), ffprobe 2022-03-07-git-e645a1ddb9-essentials_build-www.gyan.dev
[debug] Optional libraries: certifi-2021.10.08, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1692 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04 
yt-dlp is up to date (2022.10.04)
[debug] [viu:ott] Extracting URL: https://www.viu.com/ott/hk/zh-hk/vod/430078/%E7%AC%AC%E5%85%AD%E6%84%9F-3 
[viu:ott] 430078: Downloading video info
[viu:ott] Downloading just the video 430078 because of --no-playlist 
[viu:ott] 430078: Getting bearer token
[viu:ott] 430078: Downloading stream info 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available subtitles for 430078:
Language   Formats
English    srt
Indo       srt
ภาษาไทย    srt
繁體中文       srt
繁體中文Second srt
```

second_subtitle_url can be seen in the json below under the subtitle section

Raw output of video_data for url `https://www.viu.com/ott/hk/zh-hk/vod/430078/%E7%AC%AC%E5%85%AD%E6%84%9F-3`
```json
{
   "series_id":"22766",
   "product_id":"430078",
   "number":"1",
   "synopsis":"大韓民國的1%",
   "description":"新一季第一集有兩位特別嘉賓—宋恩伊和尹燦榮。恩伊是在錫其中一位好朋友，她和在錫表現出完美的默契；燦榮則展示了他意想不到的魅力。本集，第六感團隊與韓國首1%有關的人見面。",
   "schedule_start_time":"1647532815",
   "schedule_end_time":"1742831955",
   "skip_intro_start_time":0,
   "skip_intro_end_time":15,
   "free_time":1648742415,
   "premium_time":0,
   "is_free_premium_time":0,
   "duration_start":0,
   "cover_image_url":"https://d2anahhhmp1ffz.cloudfront.net/1313295781/d2b14f48d008ef2f3a9200c98d8e9b63967b9cc2",
   "ccs_product_id":"f4976fbfb196d21288ff3db519bab49a",
   "allow_download":"1",
   "share_url":"https://www.viu.com/ott/hk/zh-hk/vod/430078/%E7%AC%AC%E5%85%AD%E6%84%9F-3",
   "subtitle":[
      {
         "is_default":0,
         "name":"English",
         "url":"https://d2anahhhmp1ffz.cloudfront.net/925751760/ba938f69a7b858b8c709d7cc946cfe0084ca675b",
         "subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/925751760/ba938f69a7b858b8c709d7cc946cfe0084ca675b",
         "product_subtitle_id":"240262",
         "product_subtitle_language_id":"3",
         "second_subtitle_url":"",
         "second_subtitle_position":1,
         "code":"en"
      },
      {
         "is_default":0,
         "name":"Indo",
         "url":"https://d2anahhhmp1ffz.cloudfront.net/3255922512/f399e750351924c0aa91557231731e533c302ef8",
         "subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/3255922512/f399e750351924c0aa91557231731e533c302ef8",
         "product_subtitle_id":"240277",
         "product_subtitle_language_id":"7",
         "second_subtitle_url":"",
         "second_subtitle_position":1,
         "code":"id"
      },
      {
         "is_default":0,
         "name":"ภาษาไทย",
         "url":"https://d2anahhhmp1ffz.cloudfront.net/4237993129/b69f134865c5f72aceabe32f47b546f20e2b1d22",
         "subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/4237993129/b69f134865c5f72aceabe32f47b546f20e2b1d22",
         "product_subtitle_id":"240435",
         "product_subtitle_language_id":"8",
         "second_subtitle_url":"",
         "second_subtitle_position":1,
         "code":"th"
      },
      {
         "is_default":1,
         "name":"繁體中文",
         "url":"https://d2anahhhmp1ffz.cloudfront.net/4279146490/799524ec920a46b1960dc18729d2a98261bcb8e3",
         "subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/4279146490/799524ec920a46b1960dc18729d2a98261bcb8e3",
         "product_subtitle_id":"240856",
         "product_subtitle_language_id":"1",
         "second_subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/2156290699/c04164fcd48fc654733a877382f018f1cb381d89",
         "second_subtitle_position":1,
         "code":"zh-Hant"
      }
   ],
   "focus":[
      
   ],
   "ad":[
      {
         "position":0,
         "code_list":[
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007011DP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F430078%2F&cust_params=ott_cate%3Dkoreanvariety%26ott_series_id%3D22766",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            },
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007012DP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F430078%2F&cust_params=ott_cate%3Dkoreanvariety%26ott_series_id%3D22766",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            }
         ],
         "start_time":"0"
      },
      {
         "position":1,
         "code_list":[
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007021DP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F430078%2F&cust_params=ott_cate%3Dkoreanvariety%26ott_series_id%3D22766",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            },
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007021_bDP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F430078%2F&cust_params=ott_cate%3Dkoreanvariety%26ott_series_id%3D22766",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            }
         ],
         "start_time":"2883"
      },
      {
         "position":2,
         "code_list":[
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007022DP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F430078%2F&cust_params=ott_cate%3Dkoreanvariety%26ott_series_id%3D22766",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            },
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007022_bDP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F430078%2F&cust_params=ott_cate%3Dkoreanvariety%26ott_series_id%3D22766",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            }
         ],
         "start_time":"4613"
      },
      {
         "position":3,
         "code_list":[
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007023DP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F430078%2F&cust_params=ott_cate%3Dkoreanvariety%26ott_series_id%3D22766",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            }
         ],
         "start_time":"5934"
      }
   ],
   "is_movie":0,
   "is_parental_lock_limited":"0",
   "allow_play_big_screen":"1",
   "play_big_screen_start_time":"0",
   "play_big_screen_end_time":"0",
   "time_duration":"6614",
   "campaign_name":"",
   "user_level":0,
   "seo_title":"",
   "seo_description":"",
   "has_content_window":"1",
   "classification":"",
   "censorship_ads_mp4_url":"",
   "client_logo":"None",
   "keyword":"Sixth Sense 3, 식스센스 3, 第六感 3, 第六感 第三季, 推理CJ, 最新上架, 韓國綜藝, 劉在錫, Jessi, 吳娜拉, 李美珠, 李相燁, 全昭旻, Yoo Jae Suk, Oh Na Ra, Lee Sang Yeob, Lee Mi Joo",
   "offline_time":"1742831955",
   "poster_logo_url":"",
   "source_flag":"0",
   "allow_tv":"1",
   "released_product_total":14,
   "landscape_episode_image_url":"https://d2anahhhmp1ffz.cloudfront.net/1313295781/d2b14f48d008ef2f3a9200c98d8e9b63967b9cc2",
   "allow_chromecast_play_big_screen":1,
   "allow_airplay_play_big_screen":1,
   "product_tag":[
      
   ]
}
```

Raw output of video_data for url `https://www.viu.com/ott/hk/zh-hk/vod/444666/%E6%88%91%E7%9A%84%E5%AE%A4%E5%8F%8B%E6%98%AF%E4%B9%9D%E5%B0%BE%E7%8B%90`
```json
{
   "series_id":"23807",
   "product_id":"444666",
   "number":"1",
   "synopsis":"同居",
   "description":"申又如，生於高麗顯宗13年，是畢業於成均館的九尾狐男人。李 丹，21世紀女大學生，典型的現代人類。兩個看似完全沒有交集的「種族」，因狐狸內丹而產生糾纏，開始了相差977年的……不，一整個世紀的驚心動魄的同居生活……",
   "schedule_start_time":"1657857624",
   "schedule_end_time":"1752508764",
   "skip_intro_start_time":0,
   "skip_intro_end_time":30,
   "free_time":0,
   "premium_time":0,
   "is_free_premium_time":0,
   "duration_start":0,
   "cover_image_url":"https://d2anahhhmp1ffz.cloudfront.net/2987913268/3d6204b53267f1a17699e131b5e7673e8dfad1ed",
   "ccs_product_id":"3cd4671a4c110ac693f11f933afb1887",
   "allow_download":"1",
   "share_url":"https://www.viu.com/ott/hk/zh-hk/vod/444666/%E6%88%91%E7%9A%84%E5%AE%A4%E5%8F%8B%E6%98%AF%E4%B9%9D%E5%B0%BE%E7%8B%90",
   "subtitle":[
      {
         "is_default":0,
         "name":"English",
         "url":"https://d2anahhhmp1ffz.cloudfront.net/1400088194/8c7dc4228930683b66fda48f7125ad14ad5f6ac3",
         "subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/1400088194/8c7dc4228930683b66fda48f7125ad14ad5f6ac3",
         "product_subtitle_id":"240524",
         "product_subtitle_language_id":"3",
         "second_subtitle_url":"",
         "second_subtitle_position":1,
         "code":"en"
      },
      {
         "is_default":0,
         "name":"ภาษาไทย",
         "url":"https://d2anahhhmp1ffz.cloudfront.net/380887317/6dca5aa82e86d2c16831d1555154894a0d151dcf",
         "subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/380887317/6dca5aa82e86d2c16831d1555154894a0d151dcf",
         "product_subtitle_id":"244020",
         "product_subtitle_language_id":"8",
         "second_subtitle_url":"",
         "second_subtitle_position":1,
         "code":"th"
      },
      {
         "is_default":1,
         "name":"繁體中文",
         "url":"https://d2anahhhmp1ffz.cloudfront.net/3058849036/65e41c405b9405739271c1badaa303868602ed3a",
         "subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/3058849036/65e41c405b9405739271c1badaa303868602ed3a",
         "product_subtitle_id":"253068",
         "product_subtitle_language_id":"1",
         "second_subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/674676911/744f1fed7f536677b76e7e695f7ff03a7c7ad330",
         "second_subtitle_position":0,
         "code":"zh-Hant"
      },
      {
         "is_default":0,
         "name":"Malay",
         "url":"https://d2anahhhmp1ffz.cloudfront.net/1012457802/9dddd0b1aa721c1324a1b9f1262d9b1408c38446",
         "subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/1012457802/9dddd0b1aa721c1324a1b9f1262d9b1408c38446",
         "product_subtitle_id":"255964",
         "product_subtitle_language_id":"6",
         "second_subtitle_url":"",
         "second_subtitle_position":1,
         "code":"ms"
      },
      {
         "is_default":0,
         "name":"မြန်မာဘာသာ",
         "url":"https://d2anahhhmp1ffz.cloudfront.net/4097893180//ff2ba84462eedbae739cc461af0c209deeda221d",
         "subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/4097893180/ff2ba84462eedbae739cc461af0c209deeda221d",
         "product_subtitle_id":"255980",
         "product_subtitle_language_id":"10",
         "second_subtitle_url":"",
         "second_subtitle_position":1,
         "code":"my"
      }
   ],
   "focus":[
      
   ],
   "ad":[
      {
         "position":0,
         "code_list":[
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007011DP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F444666%2F&cust_params=ott_cate%3Dkoreandrama%26ott_series_id%3D23807",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            },
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007012DP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F444666%2F&cust_params=ott_cate%3Dkoreandrama%26ott_series_id%3D23807",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            },
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007013DP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F444666%2F&cust_params=ott_cate%3Dkoreandrama%26ott_series_id%3D23807",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            }
         ],
         "start_time":"0"
      },
      {
         "position":1,
         "code_list":[
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007021DP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F444666%2F&cust_params=ott_cate%3Dkoreandrama%26ott_series_id%3D23807",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            },
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007021_bDP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F444666%2F&cust_params=ott_cate%3Dkoreandrama%26ott_series_id%3D23807",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            }
         ],
         "start_time":"970"
      },
      {
         "position":2,
         "code_list":[
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007022DP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F444666%2F&cust_params=ott_cate%3Dkoreandrama%26ott_series_id%3D23807",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            },
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007022_bDP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F444666%2F&cust_params=ott_cate%3Dkoreandrama%26ott_series_id%3D23807",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            }
         ],
         "start_time":"2051"
      },
      {
         "position":3,
         "code_list":[
            {
               "ad_stuff":"https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720&iu=/94348418/OTTHK100007023DP&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=https%3A%2F%2Fwww.viu.com%2Fott%2Fhk%2Fzh-hk%2Fvod%2F444666%2F&cust_params=ott_cate%3Dkoreandrama%26ott_series_id%3D23807",
               "ad_track":"None",
               "ad_is_user_pay":"0",
               "ima_force":"1"
            }
         ],
         "start_time":"3185"
      }
   ],
   "is_movie":0,
   "is_parental_lock_limited":"0",
   "allow_play_big_screen":"1",
   "play_big_screen_start_time":"0",
   "play_big_screen_end_time":"0",
   "time_duration":"3932",
   "campaign_name":"",
   "user_level":0,
   "seo_title":"",
   "seo_description":"",
   "has_content_window":"1",
   "classification":"",
   "censorship_ads_mp4_url":"",
   "client_logo":"None",
   "keyword":"我的室友是九尾狐, My Roommate is a Gumiho, 간 떨어 지는 동거, 韓劇, 愛情, 喜劇, 奇幻, 愛奇藝, tvn, 南成宇, 崔寶林, 白善宇, 張基龍, 李惠利, 姜漢娜, 金度完, 裴仁爀, Jang Ki Yong, Lee Hye Ri, Kang Han Na, Kim Do Wan, Bae In Hyuk",
   "offline_time":"1752508764",
   "poster_logo_url":"",
   "source_flag":"0",
   "allow_tv":"1",
   "released_product_total":16,
   "landscape_episode_image_url":"https://d2anahhhmp1ffz.cloudfront.net/2987913268/3d6204b53267f1a17699e131b5e7673e8dfad1ed",
   "allow_chromecast_play_big_screen":1,
   "allow_airplay_play_big_screen":1,
   "product_tag":[
      
   ]
}
```

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [X] Fix or improvement to an extractor (Make sure to add/update tests)

### CODE REVIEW

**Comment by pukkandan** [comment]
Could u explain to me how the "second subtitle" different from the normal one?

**Comment by tkgmomosheep** [comment]
> Could u explain to me how the "second subtitle" different from the normal one?

The normal subtitle is for spoken lines, and the "second subtitle" will translate on screen text.

**Comment by pukkandan** [comment]
I pushed some small changes. Test and let me know

**Comment by tkgmomosheep** [comment]
Just tested, seems good! Still produce the same result!
```
[debug] Command-line config: ['-vU', '--list-subs', '--no-playlist', 'https://www.viu.com/ott/hk/zh-hk/vod/430078/%E7%AC%AC%E5%85%AD%E6%84%9F-3']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version 2022.10.04 [4e0511f27] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: ec8653e80
[debug] Python 3.9.13 (CPython 64bit) - Windows-10-10.0.22623-SP0  
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs 
[debug] exe versions: ffmpeg 2022-03-07-git-e645a1ddb9-essentials_build-www.gyan.dev (setts), ffprobe 2022-03-07-git-e645a1ddb9-essentials_build-www.gyan.dev
[debug] Optional libraries: certifi-2021.10.08, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1692 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04 
yt-dlp is up to date (2022.10.04)
[debug] [viu:ott] Extracting URL: https://www.viu.com/ott/hk/zh-hk/vod/430078/%E7%AC%AC%E5%85%AD%E6%84%9F-3 
[viu:ott] 430078: Downloading video info
[viu:ott] Downloading just the video 430078 because of --no-playlist 
[viu:ott] 430078: Getting bearer token
[viu:ott] 430078: Downloading stream info 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available subtitles for 430078:
Language Name                    Formats
English  Spoken text for English srt
Indo     Spoken text for Indo    srt
ภาษาไทย  Spoken text for ภาษาไทย srt
繁體中文     Spoken text for 繁體中文    srt
繁體中文_ost On-screen text for 繁體中文 srt
```

**Pull request merged**
