### PR TITLE
[extractor/stripchat] remove trailing slash from url causing redirect to dummy domain.

### PR DESCRIPTION
**Pull request by dfaker**
### Description of your *pull request* and other information

Stripchat room urls internally append a slash after the room name inside the extractor.

Urls ending in a slash are now redirected to the non-existent stripchat.ssr domain causing getaddrinfo failure, skipping the trailing slash works as normal.

New tests not required as the interface is being passed urls without a trailing slash, purely an internal change to  the class.

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### CODE REVIEW

**Comment by pukkandan** [comment]
Any reason it doesn't just use the `url` variable?

**Comment by dfaker** [comment]
None at all, other than minimizing the scale of the change.

**Comment by pro-ject143** [comment]
I don't understand. Removing trailing slash or leaving it seems to make no difference as unable to download any Stripchat URLs for over a week?

**Comment by dfaker** [comment]
It didn't matter how you supplied the urls to yt-dlp - internally the class was always adding on a slash at the end of everything like `https://stripchat.com/TattooGirlAlia/` which they've got some presumably anti-piracy protection in for that redirect to `https://stripchat.ssr/TattooGirlAlia` - a domain that doesn't exist.

I tried it updated to the most recent release version `2022.09.01` and it works perfectly now.

**Comment by pro-ject143** [comment]
Yes that now works. Thank you.

**Pull request merged**
