### PR TITLE
Added monitoring to ffmpeg download

### LINKED ISSUE #1317: [Feature Request] Improved display of download progress with Dailymotion
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've searched the bugtracker for similar feature requests including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Description

I noticed that when I download a video from Dailymotion the output is different. it looks like yt-dlp is using ffmpeg to extract the videos. So is there any way to fix the problem as I have another program that reads this output to check the download progress and in the case of Dailymotion it sucks. Here is an example:

`yt-dlp https://www.dailymotion.com/video/x84vprc
[dailymotion] Downloading Access Token
[dailymotion] x84vprc: Downloading media JSON metadata
[dailymotion] x84vprc: Downloading metadata JSON
[dailymotion] x84vprc: Downloading m3u8 information
[info] x84vprc: Downloading 1 format(s): hls-720-1
[hlsnative] Downloading m3u8 manifest
WARNING: The stream has AES-128 encryption and pycryptodomex is not available; extraction will be delegated to ffmpeg
[download] Destination: Consommation  - les bureaux de tabac doivent se renouveler pour survivre [x84vprc].mp4
[hls @ 0x7fdbfb000000] Skip ('#EXT-X-VERSION:5')
[hls @ 0x7fdbfb000000] Opening 'https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/p/video/295/729/491927592_mp4_h264_aac_hd.key' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(1)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
Input #0, hls, from 'https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/p/video/295/729/491927592_mp4_h264_aac_hd.m3u8':
  Duration: 00:01:55.40, start: 10.092856, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Consommation  - les bureaux de tabac doivent se renouveler pour survivre [x84vprc].mp4.part':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(2)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(3)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(4)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(5)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(6)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(7)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(8)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(9)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(10)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(11)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(12)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(13)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(14)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(15)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(16)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(17)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(18)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(19)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(20)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(21)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(22)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(23)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(24)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(25)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(26)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(27)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(28)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(29)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(30)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(31)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(32)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(33)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(34)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(35)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(36)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(37)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(38)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
[hls @ 0x7fdbfb000000] Opening 'crypto+https://proxy-022.ix7.dailymotion.com/sec(Y1__c6jS2j6mYXFHdR8-E9lNPZzk-01beGAzVBBx5B8hGAdBDG20svmjeKZrm7PJ6_FLqgDD7NDsCT-hYOF2AXkxYD6LeADJbZXW6Sv5TwE)/frag(39)/p/video/295/729/491927592_mp4_h264_aac_hd.ts' for reading
frame= 2885 fps= 76 q=-1.0 Lsize=   30880kB time=00:01:55.34 bitrate=2193.1kbits/s speed=3.05x    
video:28969kB audio:1836kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.243410%
[ffmpeg] Downloaded 31620707 bytes
[download] 100% of 30.16MiB in 00:40
[FixupM3u8] Fixing malformed AAC bitstream of "Consommation  - les bureaux de tabac doivent se renouveler pour survivre [x84vprc].mp4"`

### LINKED ISSUE #1417: Short-form vs long-form segment download status output
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Sometimes when I download videos,`yt-dlp` / `youtube-dl` "suppresses" the download output so that it constantly updates the output percentage vs outputting and scrolling each downloaded segment to shell stdout.  Other times it does the opposite scrolling each downloaded serialized segment to screen.  I prefer the first output style as it doesn't clutter up my shell output for "eyeballing" successive runs of the command.

To my knowledge, I "think" that the "surpressed" output style seems to happen when I download mp4 containers that contain *both* the audio and video file and the "long-winded verbose segemented" output occurs when i have to specify specific video and audio files that need to be muxed after the fact or mpd/dash streams but that's just a guess.

Since hls / m3u8 and dash / mpd are both segmented streams I can't see one or the other as making a difference to the output though.  

- Is there some reason why the output changes to short-form supressed and or long-form scrolled segment output depending on the way I evoke the command, specify the `format_id` or choose container or separate audio and video files or segment types?  
- Is there a way to change the behavior with a command line option?  (`-q` disables all output and I don't want that)

Thanks if you have the time.

Here's an example of a video that is short-form supressed

```bash
yt-dlp -Uv -f "best[ext=mp4][width<=480]" --write-sub https://www.ardmediathek.de/video/donna-leon/donna-leon-schoener-schein/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2Rvbm5hIGxlb24vMGNkMjFiMDktZjE2MS00ZDg3LWI4OTEtNGMzYTkxOTk4ZDQw/
[debug] Command-line config: ['-Uv', '-f', 'best[ext=mp4][width<=480]', '--write-sub', 'https://www.ardmediathek.de/video/donna-leon/donna-leon-schoener-schein/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2Rvbm5hIGxlb24vMGNkMjFiMDktZjE2MS00ZDg3LWI4OTEtNGMzYTkxOTk4ZDQw/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.22 (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: fccf50211
[debug] Python version 3.9.6 (CPython 64bit) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] Using fake IP 53.9.0.181 (DE) as X-Forwarded-For
[debug] [ARD:mediathek] Extracting URL: https://www.ardmediathek.de/video/donna-leon/donna-leon-schoener-schein/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2Rvbm5hIGxlb24vMGNkMjFiMDktZjE2MS00ZDg3LWI4OTEtNGMzYTkxOTk4ZDQw/
[ARD:mediathek] Y3JpZDovL2Rhc2Vyc3RlLmRlL2Rvbm5hIGxlb24vMGNkMjFiMDktZjE2MS00ZDg3LWI4OTEtNGMzYTkxOTk4ZDQw: Downloading webpage
[ARD:mediathek] 90451812: Downloading media JSON
[ARD:mediathek] 90451812: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: de
[info] 90451812: Downloading 1 format(s): hls-508
[info] Writing video subtitles to: Donna Leon - Schöner Schein [90451812].de.ttml
[debug] Invoking downloader on "https://www.ardmediathek.de/subtitle/520157"
[download] Destination: Donna Leon - Schöner Schein [90451812].de.ttml
[download] 100% of 122.64KiB in 00:00
[debug] Invoking downloader on "https://dasersteuni-vh.akamaihd.net/i/int/2021/06/17/0cd21b09-f161-4d87-b891-4c3a91998d40/,640-1_921535,480-1_921535,960-1_921535,1280-1_921535,1920-1_921535,.mp4.csmil/index_1_av.m3u8?null=0"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1329
[download] Destination: Donna Leon - Schöner Schein [90451812].mp4
[download]   3.4% of ~412.46MiB at  3.13MiB/s ETA 05:15
```

Here's an example of one that is long-form explicit downloaded segment by segment output to shell.  I've edited out all the segment download update lines that normally would follow to keep the output down but it should be obvious what I'm trying to convey.

```bash
yt-dlp -f "bestvideo[ext=mp4][width<=960]+bestaudio[format_id$=Audio_Description]" --write-sub  https://www.france.tv/france-2/candice-renoir/candice-renoir-saison-9/2767859-la-beaute-ne-se-voit-qu-avec-les-yeux-de-l-ame.html
```

### PR DESCRIPTION
**Pull request by Kenshin9977**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [X] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Added support of ffmpeg to _hook_progress in order to monitor the progress of the download when using ffmpeg as the downloader.

Closes #1317, closes #1417

### CODE REVIEW

**Comment by wlritchi** [comment]
Big fan of adding this monitoring! It's worth mentioning that `ffmpeg` supports an option like `-progress foo.txt` to regularly write progress information to a file in an easy-to-parse format, or `-progress pipe:1` to write it to stdout, or even more esoteric options like posting to a socket. It might be worth looking at this option as a more robust option than parsing its human-readable output.

I've so far been using `--downloader-args "ffmpeg:-progress download.progress" --postprocessor-args "ffmpeg:-progress postprocess.progress"` to get access to this while scripting around `yt-dlp`. It would be nice to simplify and only have one place to parse from :)

**Comment by pukkandan** [comment]
Writing to file and reading back is not a good idea. But piping to stdout is worth looking into

**Comment by pukkandan** [comment]
closes #1317

**Comment by pukkandan** [comment]
The implementation needs to be generalized with https://github.com/yt-dlp/yt-dlp/pull/1947

**Comment by pukkandan** [comment]
#1947 is improved version of this

**Pull request closed without merging**
