### PR TITLE
[soundcloud] Add related tracks extractor

### PR DESCRIPTION
**Pull request by Lapin0t**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

## Description

examples:
- https://soundcloud.com/wajang/sexapil-pingers-5/recommended
- https://soundcloud.com/wajang/sexapil-pingers-5/sets
- https://soundcloud.com/wajang/sexapil-pingers-5/albums

This is an initial patch for another soundcloud extractor. I still need to add some test values (only manual probing, i will look at test results tomorrow).

Specifically i'm requesting comments about:

- the regex change at line 75-77 (i don't know what a token is nor tested with one)
- the playlist id i'm giving at line 852 is just the id of the track, not the real id of the playlist, but that is consistent with other uses of `SoundcloudPagedPlaylistBaseIE`. Btw the whole style is imho a bit wrong (inconsistent checking of the `id` field, invented id where it could be gotten from first page response i think), but should be fixed consistently on all usages of this base-class.

Kudos for keeping the beast working.

### CODE REVIEW

**Comment by Lapin0t** [comment]
I just pushed some test cases. Full nosetests seem to mostly work (with a couple unrelated download failures). Yet still there is an 'ERROR' which is triggered by all SC extractors that use the PagedPlaylist thing (cannot mix str and non-str in the query params). Should i fix them in this PR?

**Comment by pukkandan** [comment]
> Yet still there is an 'ERROR' which is triggered by all SC extractors that use the PagedPlaylist thing (cannot mix str and non-str in the query params). I can gladly fix in this PR if it's ok.

I don't understand what you mean. But push the fix anyway coz it's probably easier than trying to explain better

**Comment by Ashish0804** [comment]
@Lapin0t you still working on this?

**Comment by Lapin0t** [comment]
@Ashish0804 Nope, sorry. iirc the error thing i saw wasn't what i thought it was so i left it rot. I'll try looking this week end again. I'll see tomorrow but iirc it's mergeable already since everything seemed to be functional (and the "error"/warning is triggered by this new code path but not originating from it).

**Pull request merged**
