### PR TITLE
fallback to lockf()

### PR DESCRIPTION
**Pull request by jakeogh**
### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

#1066 introduced regression #2670, this _may_ fix, please test.

### CODE REVIEW

**Comment by RedirectCleaner** [comment]
this seems to fix only a part of the problem, it now downloads the file but still throws an error

[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=9s_XAmM_vb4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: a3125791c
[debug] Python version 3.10.2 (CPython 64bit) - Linux-4.14.180-lineageos-g9695abe891c8-aarch64-with-libc
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=9s_XAmM_vb4
[youtube] 9s_XAmM_vb4: Downloading webpage
[youtube] 9s_XAmM_vb4: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 9s_XAmM_vb4: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr3---sn-h0jeenl6.googlevideo.com/videoplayback?expire=1644518137&ei=mQYFYrzyCsuq-gaborPgCQ&ip=62.178.198.204&id=o-AA0Dh52TzcY_x3B2YSQD4WAR3XmO6QUfmkAElLf6pUQ7&itag=248&source=youtube&requiressl=yes&mh=W8&mm=31%2C26&mn=sn-h0jeenl6%2Csn-4g5ednz7&ms=au%2Conr&mv=m&mvi=3&pl=18&initcwndbps=1913750&vprv=1&mime=video%2Fwebm&gir=yes&clen=37572106&dur=160.193&lmt=1640262185659293&mt=1644496181&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgGakCCD9DA6IXV5yYTrc3uw-dKgW6LvjYCD_hjjnYqhECIFt5_SNJG3Uo5ASpXnLm-AhGtptFwEmWq4rqi89o4prG&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKqNULmc4NNcC-9vr3uSI8Bd_JyXh_NZ0Nk2vhDDnhaPAiEA3qKsQqyeAXYQA6wMLGXlkPnug9rmVqc8t9TIEez8L5w%3D"
[download] Resuming download at byte 37572106
[download] dicht & ergreifend – Nix gibt´s [9s_XAmM_vb4].f248.webm has already been downloaded
[download] 100% of 35.83MiB
[debug] Invoking downloader on "https://rr3---sn-h0jeenl6.googlevideo.com/videoplayback?expire=1644518137&ei=mQYFYrzyCsuq-gaborPgCQ&ip=62.178.198.204&id=o-AA0Dh52TzcY_x3B2YSQD4WAR3XmO6QUfmkAElLf6pUQ7&itag=251&source=youtube&requiressl=yes&mh=W8&mm=31%2C26&mn=sn-h0jeenl6%2Csn-4g5ednz7&ms=au%2Conr&mv=m&mvi=3&pl=18&initcwndbps=1913750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=2605622&dur=160.221&lmt=1640260597790651&mt=1644496181&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPsGpH-sEB1m2cocAVFS7wLhl3LS0dvFLjAQfNtJeJpEAiAoKUTRkjhe6Agj9VLxJWevV4DZm3l9PP350VkYcAXnAQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKqNULmc4NNcC-9vr3uSI8Bd_JyXh_NZ0Nk2vhDDnhaPAiEA3qKsQqyeAXYQA6wMLGXlkPnug9rmVqc8t9TIEez8L5w%3D"
[download] Destination: dicht & ergreifend – Nix gibt´s [9s_XAmM_vb4].f251.webm
[download] 100% of 2.48MiB at  3.60MiB/s ETA 00:00ERROR: unable to download video data: [Errno 38] Function not implemented
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/git/yt-dlp/yt_dlp/YoutubeDL.py", line 3068, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/data/data/com.termux/files/home/git/yt-dlp/yt_dlp/YoutubeDL.py", line 2801, in dl
    return fd.download(name, new_info, subtitle)
  File "/data/data/com.termux/files/home/git/yt-dlp/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/data/data/com.termux/files/home/git/yt-dlp/yt_dlp/downloader/http.py", line 372, in real_download
    return download()
  File "/data/data/com.termux/files/home/git/yt-dlp/yt_dlp/downloader/http.py", line 344, in download
    ctx.stream.close()
  File "/data/data/com.termux/files/home/git/yt-dlp/yt_dlp/utils.py", line 2207, in close
    self.__exit__(self, *args, value=False, traceback=False)
  File "/data/data/com.termux/files/home/git/yt-dlp/yt_dlp/utils.py", line 2187, in __exit__
    _unlock_file(self.f)
  File "/data/data/com.termux/files/home/git/yt-dlp/yt_dlp/utils.py", line 2157, in _unlock_file
    fcntl.flock(f, fcntl.LOCK_UN)
OSError: [Errno 38] Function not implemented

**Comment by RedirectCleaner** [comment]
as far as i understand the patch, android implements lockf, so why not use it, when it's available

**Comment by pukkandan** [comment]
I totally forgot https://github.com/yt-dlp/yt-dlp/issues/2080

**Comment by jakeogh** [comment]
@RedirectCleaner excellent, that is the expected result before https://github.com/yt-dlp/yt-dlp/pull/2656 is merged.

Looks good to merge.

**Pull request merged**
