### PR TITLE
Fixed tubitv extractor

### LINKED ISSUE #9937: [TubiTV] Unable to download JSON metadata: HTTP Error 401: Unauthorized
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

[TubiTV.com] When downloading videos from TubiTV.com I am now receiving Unauthorized when the video was previously downloaded without error.  For example: Guest House (2020)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://tubitv.com/movies/659818/guest-house']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-27-git-891ed24f77-essentials_build-www.gyan.dev (setts), ffprobe 2023-02-27-git-891ed24f77-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[debug] Using fake IP 6.197.217.81 (US) as X-Forwarded-For
[TubiTv] Extracting URL: https://tubitv.com/movies/659818/guest-house
[TubiTv] 659818: Downloading JSON metadata
ERROR: [TubiTv] 659818: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>)
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\tubitv.py", line 85, in _real_extract
  File "yt_dlp\extractor\common.py", line 1127, in download_content
  File "yt_dlp\extractor\common.py", line 1087, in download_handle
  File "yt_dlp\extractor\common.py", line 954, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 903, in _request_webpage

  File "yt_dlp\extractor\common.py", line 890, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4131, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 401: Unauthorized
```

### PR DESCRIPTION
**Pull request by chilinux**
**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Fixes the tubitv extractor.  Previously the metadata was provided directly as json at it's own url.  The website has since been revised such that this json data is embedded in the webpage itself.

Fixes #9937

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

### CODE REVIEW

**Comment by chilinux** [comment]
Fixes #9937

**Comment by chilinux** [comment]
This is a patch to existing yt-dlp code.  The majority of the file I don't own.  Of the approx. 20 lines I add, most are largely based lines already there.  I didn't consider anything in the pull request to be deserving of being a new "copyrighted" work that I would own.  The patch is derivative and not deserving of being considered transformative.  I think all the credit still belongs with the author that came before me.

If you need me to claim the code is "my own" then I will.  The only source of inspiration was the code already available to me from the project.  I am fine with releasing all claim that I might have to the code to be consistent with the yt-dlp license.

**Comment by chilinux** [comment]
I authored the derivations of the code to produce the patch.  No one else has a valid calm to authorship of this patch.

**Comment by bashonly** [comment]
Great, please fill out the PR template accordingly -- this is necessary for licensing reasons

**Comment by chilinux** [comment]
PR template is now updated.  Sorry about my confusion regarding my understanding of "original author."

**Review by bashonly — APPROVED** [review]
@Jules-A would you mind testing this?

**Comment by Jules-A** [comment]
> @Jules-A would you mind testing this?

Has major issues: Only finds 20 entries, only got 404s when it tried to download.

The switch away from using the API seems like a weird thing to do, the webpage only loads 20 entries at once.

Idk if it's helpful but this is the userscript I made a while ago to list all the episodes for extraction since there's no TubiTV playlist extractor: https://pastebin.com/raw/qVKtcYNT (very messy since I was too lazy) . Still seems to extract the ids just fine for all seasons.

**Comment by bashonly** [comment]
> The switch away from using the API seems like a weird thing to do, the webpage only loads 20 entries at once.

The series/show extractor was not touched by this PR. It has always extracted from the webpages. I was asking if you could test the video extractor

**Comment by Jules-A** [comment]
> > The switch away from using the API seems like a weird thing to do, the webpage only loads 20 entries at once.
> 
> The series/show extractor was not touched by this PR. It has always extracted from the webpages. I was asking if you could test the video extractor

It removes /oz/ ? Which is the API.

**Comment by bashonly** [comment]
The video extractor removed the API and migrated to web. But the ShowIE has always used the webpage. Look at the code for the series extractor; it is unchanged

**Comment by bashonly** [comment]
The ShowIE is not the subject of this PR and thus will not be fixed in this PR. But I will push something so it at least doesn't give 404s

**Comment by Jules-A** [comment]
> The video extractor removed the API and migrated to web. But the ShowIE has always used the webpage. Look at the code for the series extractor; it is unchanged

Oh whoops, right, my bad. Yeah the playlist extractor never worked anyway and extracting a single show seems to be working fine in some quick tests. Sorry I'm very tired right now.

**Comment by bashonly** [comment]
@Jules-A all good, thank you for testing

**Pull request merged**
